hyperlane-xyz/hyperlane-monorepo

typescript/infra/src/config/agent.ts, typescript/infra/src/core/deploy.ts
Quick fix to return inboxes/outboxes now
=> Fix rust output

.github/workflows/docker.yml
* Added the `GCLOUD_SERVICE_KEY` to workflow secrets so this actually runs :)
* Runs on `main` and any PRs that change the `rust` dir
=> Activate Docker workflow

.github/workflows/rust-skiped.yml
=> Re-add rust-skipped

typescript/sdk/src/gas/calculator.ts
A nit that @mattiecnvr brought up the other day
=> Nit: Promise.all some back to back awaits

solidity/core/test/mailbox.test.ts
Accidentally removed when renaming from `common.test.ts` in #523
=> Re-add mailbox.test.ts

package.json, solidity/app/package.json, solidity/core/package.json, typescript/deploy/package.json, typescript/hardhat/package.json, typescript/infra/package.json, typescript/sdk/package.json, typescript/utils/package.json, yarn.lock
test with `rm yarn.lock` and `yarn` from root or subpackage and eg `yarn prettier`
pin typechain deps due to https://github.com/dethcrypto/TypeChain/issues/721
=> Restore subpackage deps

typescript/deploy/src/deploy.ts, typescript/sdk/src/chains.ts, typescript/sdk/src/provider.ts
Add block explorer links to deployment logs
=> Log explorer links

typescript/deploy/src/router/deploy.ts
Update router SDK with overrides plumbing and logs
=> Pass through overrides to deployRouter (and log)

typescript/infra/config/environments/testnet2/agent.ts
Already deployed, just keeping parity with the repo.
=> Change rate to 1message/15min

.github/dependabot.yml, package.json, yarn.lock
- Add yarn resolution to force security update
- Adjust depandabot config to disable optional PRs
=> Fix dependabot security alerts

typescript/infra/config/environments/mainnet/funding.ts, typescript/infra/config/environments/testnet2/funding.ts, typescript/infra/helm/relayer-funder/templates/cron-job.yaml, typescript/infra/package.json, typescript/infra/scripts/funding/fund-relayers-from-deployer.ts, typescript/infra/src/config/funding.ts, typescript/infra/src/funding/deploy-relayer-funder.ts, yarn.lock
=> Submit relayer funds metric

typescript/infra/config/environments/mainnet/funding.ts, typescript/infra/config/environments/testnet2/funding.ts
=> Fix the push gateway dns addr

typescript/infra/config/environments/mainnet/funding.ts, typescript/infra/config/environments/testnet2/funding.ts
(Already deployed, just updating configs)
=> Deploy relayer funder

solidity/core/contracts/Inbox.sol, solidity/core/test/inbox.test.ts, typescript/infra/hardhat.config.ts, typescript/sdk/src/core/AbacusCore.ts, typescript/sdk/src/core/testAbacusDeploy.hardhat-test.ts
- Add dispatch and process helpers to core
Fixes #590
drive-by:
- move `emit Process` into `_process` such that `TestInbox` also emits
- add test for process event emitted
-
=> Add MVP of e2e message observability

typescript/infra/config/environments/mainnet/agent.ts, typescript/infra/config/environments/testnet2/agent.ts
Deployed and working well so far
=> Deploy change to have arbitrum.* and optimism.* agents use 0 reorg period

typescript/helloworld/src/app/app.ts
=> Apply gas buffer to kathy messages

typescript/infra/config/environments/mainnet/agent.ts, typescript/infra/config/environments/testnet2/agent.ts
Deploys #797 to testnet2 and mainnet, all looking good so far
=> Deploy message indexing fix

rust/config/mainnet/arbitrum_config.json, rust/config/mainnet/bsc_config.json, rust/config/mainnet/celo_config.json, rust/config/mainnet/ethereum_config.json, rust/config/mainnet/optimism_config.json, rust/config/mainnet/polygon_config.json, typescript/infra/config/environments/mainnet/core/rust/arbitrum_config.json, typescript/infra/config/environments/mainnet/core/rust/bsc_config.json, typescript/infra/config/environments/mainnet/core/rust/celo_config.json, typescript/infra/config/environments/mainnet/core/rust/ethereum_config.json, typescript/infra/config/environments/mainnet/core/rust/optimism_config.json, typescript/infra/config/environments/mainnet/core/rust/polygon_config.json, typescript/sdk/src/consts/chainConnectionConfigs.ts, typescript/sdk/src/consts/chainMetadata.ts
Fixes #596
Updates Avalanche Config to reflect #596
=> Increase Avalanche Finality Blocks

typescript/helloworld/src/app/app.ts, typescript/infra/scripts/helloworld/kathy.ts
Temporarily, so that we can push mumbai gas price increases in a PR to follow
=> Remove gas payments from kathy

typescript/infra/config/environments/mainnet/helloworld.ts, typescript/infra/config/environments/testnet2/helloworld.ts, typescript/infra/scripts/helloworld/kathy.ts, typescript/infra/src/config/helloworld.ts, typescript/infra/src/helloworld/kathy.ts
Merging this into the other kathy branch I have then will get that merged with main.
Closes #837
=> Kathy message retrying

typescript/infra/src/config/chain.ts, typescript/sdk/src/providers/RetryProvider.ts, typescript/utils/src/utils.ts
Also updates parameterization to be consistent with the rust RetryingProvider
=> Update RetryProvider to use exponential backoff

typescript/helloworld/src/app/app.ts, typescript/infra/helm/helloworld-kathy/templates/stateful-set.yaml, typescript/infra/helm/helloworld-kathy/values.yaml, typescript/infra/scripts/helloworld/kathy.ts
Couple of quick fixes for the helm config and also fixes a log statement that was doing multiline logging.
=> Kathy fixes

typescript/infra/config/environments/mainnet/helloworld.ts, typescript/infra/config/environments/testnet2/helloworld.ts
This has already been deployed, just updating main.
=> Deploy kathy

typescript/infra/config/environments/mainnet/funding.ts, typescript/infra/config/environments/testnet2/funding.ts, typescript/infra/helm/key-funder/templates/cron-job.yaml
* Deploys the key funder following #876
=> Deploy key funder

typescript/infra/config/environments/mainnet/helloworld.ts, typescript/infra/config/environments/testnet2/helloworld.ts
* Kathy deployment following #891
=> Deploy testnet2 and mainnet to have kathy use its own key

typescript/infra/config/environments/mainnet/helloworld.ts, typescript/infra/config/environments/testnet2/helloworld.ts
Includes #902, finally successfully deploys kathy as a service on mainnet
=> Deploy testnet2 and mainnet kathy as a service

typescript/infra/config/environments/mainnet/chains.ts, typescript/infra/config/environments/testnet2/chains.ts
Seeing some high gas prices on polygon, upping this as a bandaid fix for kathy / key funder
=> Bump polygon maxFeePerGas

typescript/infra/config/environments/mainnet/funding.ts, typescript/infra/config/environments/mainnet/helloworld.ts, typescript/infra/config/environments/testnet2/funding.ts, typescript/infra/config/environments/testnet2/helloworld.ts
We need this change because of a new minimum gas that was set by polygon.
=> Deploy Kathy and Key Funder

solidity/core/contracts/Outbox.sol, typescript/sdk/src/providers/RetryProvider.ts, typescript/utils/src/logging.ts
- Remove uses of console lib
- Fix typo in outbox comment
=> Remove uses of console lib

solidity/app/package.json, solidity/core/package.json, typescript/helloworld/package.json, typescript/infra/package.json, typescript/sdk/package.json, typescript/utils/package.json, yarn.lock
=> v0.4.1 Release

typescript/infra/config/environments/mainnet/helloworld.ts, typescript/infra/config/environments/testnet2/helloworld.ts
=> Update Kathy timeouts

typescript/infra/scripts/helloworld/kathy.ts
This was my bad, wasn't paying enough attention when making suggested changes to the last PR.
=> Fix log on kathy double check

typescript/infra/config/environments/mainnet/helloworld.ts, typescript/infra/config/environments/testnet2/helloworld.ts
* Deploys kathy to include #930
=> Deploy kathy to include log fix

rust/agents/relayer/src/msg/serial_submitter.rs
I intended to push these in #933 but didn't push, oops!
=> Some clarifying comments following the new retry queue heuristic

typescript/infra/scripts/helloworld/kathy.ts
We would just increase the index until it exceeds the pairings object
=> Rotate in kathy correctly

typescript/infra/config/environments/mainnet/helloworld.ts, typescript/infra/config/environments/testnet2/helloworld.ts
=> Deploy kathy to include #960 

rust/Cargo.lock, rust/chains/abacus-ethereum/Cargo.toml, rust/chains/abacus-ethereum/src/retrying.rs, rust/chains/abacus-ethereum/src/trait_builder.rs
Fixes #938 
This PR adds a 60s timeout to all provider requests
=> Add a 60s timeout to http requests

solidity/core/contracts/Inbox.sol, solidity/core/contracts/Outbox.sol, solidity/core/contracts/upgrade/Versioned.sol, solidity/core/contracts/validator-manager/MultisigValidatorManager.sol
- Version validator manager domain hash derivation
- Version MultisigValidatorManager in bytecode const
=> Prevent replayable messages on new inbox versions

solidity/app/hardhat.config.ts, solidity/core/hardhat.config.ts, typescript/helloworld/hardhat.config.ts
- Bump compiler versions
- Bump solc version to 0.8.16
=> fyeo ab 01

solidity/core/contracts/AbacusConnectionManager.sol
=> Clarify default visibility

rust/agents/validator/src/validator.rs
Got broken due to https://github.com/abacus-network/abacus-monorepo/issues/981
=> Fix lint-rs

rust/agents/scraper/migration/bin/init_db.rs, rust/agents/scraper/migration/src/m20220805_000001_create_table_domain.rs, rust/agents/scraper/migration/src/m20220805_000002_create_table_block.rs, rust/agents/scraper/migration/src/m20220805_000003_create_table_checkpoint.rs, rust/agents/scraper/migration/src/m20220805_000003_create_table_cursor.rs, rust/agents/scraper/migration/src/m20220805_000004_create_table_gas_payment.rs, rust/agents/scraper/migration/src/m20220805_000004_create_table_message.rs
Figured out to do this when reading docs.
=> Make domain id the primary key

typescript/infra/scripts/debug-message.ts
Provider does not always throw an error on revert
=> Fix message debugging script

typescript/infra/test/core.test.ts, typescript/sdk/src/deploy/AbacusDeployer.ts, typescript/sdk/src/deploy/core/AbacusCoreDeployer.ts
=> Recover partial contract deployments

typescript/infra/src/agents/aws/validator.ts
Comparing all checkpoints is very slow
=> Only compare latest 20 checkpoints

typescript/infra/config/environments/testnet2/agent.ts
Merge this if you want or append other changes, mostly just making it so you have the right commit sha for what is in rc.
=> Update rc context for new quorum provider testing

typescript/infra/config/environments/mainnet/funding.ts, typescript/infra/config/environments/testnet2/funding.ts
=> Deploy key funder on testnet2 & mainnet

typescript/infra/config/environments/testnet2/agent.ts
=> Test some QuorumProvider changes in testnet2 rc

typescript/infra/config/environments/mainnet/agent.ts, typescript/infra/config/environments/testnet2/agent.ts
* Deploys to include #1081 #1041
=> Deploy to testnet2 and mainnet

.github/pull_request_template.md
Teeny typo oops
n/a
n/a
n/a
n/a
=> Fix PR template typo

typescript/infra/config/environments/mainnet/agent.ts
Deployed to mainnet rc with quorumprovider. Also made a couple additions to the list of providers for some chains (& updated the notion)
none
none
yes
deployed
=> Deploy mainnet rc with QuorumProvider

typescript/infra/config/environments/mainnet/agent.ts, typescript/infra/config/environments/testnet2/agent.ts
Final deploy for the day, includes #1102 for some better debugging tomorrow
none
none
backward compatible
deployed
=> Deploy to testnet2 and mainnet, all contexts

typescript/infra/config/environments/mainnet/agent.ts
Deployed mainnet abacus context with QuorumProvider! woo
none
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/873, but keeping it open because I believe the TS side still needs moving over
All backward compatible
Deployed
=> Deploy mainnet with QuorumProvider

typescript/infra/config/environments/testnet2/create2/addresses.json, typescript/infra/config/environments/testnet2/helloworld/abacus/addresses.json, typescript/infra/config/environments/testnet2/helloworld/rc/addresses.json, typescript/infra/config/environments/testnet2/interchain/abacus/addresses.json, typescript/infra/config/environments/testnet2/interchain/addresses.json, typescript/infra/config/environments/testnet2/testrecipient/addresses.json, typescript/infra/scripts/funding/deploy-key-funder.ts, typescript/infra/scripts/remove-agent-deploys.ts, typescript/infra/src/agents/index.ts, typescript/infra/src/funding/deploy-key-funder.ts, typescript/infra/src/utils/helm.ts, typescript/sdk/src/consts/chainMetadata.ts
This PR contains various adjustments to support chain removal.
Missed the removal from chainMetadata
- Fixes #1129 
Yes
Yes
Manual
=> Changes for chain removal

package.json, typescript/helloworld/package.json, typescript/ica/package.json, typescript/infra/package.json, yarn.lock
- Fix security alert for undici
- Copy resolutions to helloworld package.json for template repo
- Make ICA package private
- Fix version num in infra package
Yes
=> Package.json fixes for security and consistency

package.json, solidity/app/package.json, solidity/core/package.json, typescript/helloworld/package.json, typescript/ica/package.json, typescript/infra/package.json, typescript/sdk/package.json, typescript/utils/package.json, yarn.lock
Bump package version numbers from 0.5.0-beta0 to 0.5.0 for final release
Yes
=> Bump packages to 0.5.0

typescript/infra/config/environments/mainnet/agent.ts, typescript/infra/config/environments/testnet2/agent.ts
It's been a couple weeks since a deploy, so deployed
n/a
n/a
Yes
None
deployed
=> Deploy agents

typescript/helloworld/src/scripts/deploy.ts
Pass through the whole config for the explorer links to work
=> Pass through the whole config

typescript/helloworld/package.json, typescript/sdk/src/core/contracts.ts, typescript/sdk/src/core/message.ts, typescript/sdk/src/deploy/core/HyperlaneCoreDeployer.ts, typescript/sdk/src/deploy/router/HyperlaneRouterChecker.ts, typescript/sdk/src/index.ts, yarn.lock
Remove some straggler references to Network instead of Chain
Remove unneeded utils package ref in helloworld (sdk already has it)
Technically no but I doubt anyone will notice
=> Remove some straggler references to Network instead of Chain

solidity/package.json, typescript/helloworld/package.json, typescript/infra/package.json, typescript/sdk/package.json, typescript/sdk/tsconfig.build.json, typescript/sdk/tsconfig.json, typescript/utils/package.json, yarn.lock
Increment package versions to 0.5.2
Revert tsconfig changes to SDK from #1170
- Fixes #1209
=> 0.5.2 release

typescript/infra/config/environments/testnet2/agent.ts, typescript/sdk/src/deploy/middleware/TokenBridgeRouterDeployer.ts
Deploys the changes for #1195 
Also fixes an annoying import
=> Deploy agents 11-3

typescript/infra/config/environments/testnet2/funding.ts, typescript/infra/scripts/circle-relayer.ts, typescript/sdk/src/deploy/middleware/TokenBridgeApp.ts, typescript/sdk/src/index.ts, typescript/sdk/src/middleware/tokenbridge.hardhat-test.ts
This PR adds a "circle relayer" as an infra script that just loops and polls for events and attestations.
=> Add Circle Relayer MVP

typescript/infra/config/environments/testnet2/index.ts, typescript/infra/config/environments/testnet2/middleware.ts, typescript/infra/helm/liquidity-layer-relayers/Chart.yaml, typescript/infra/helm/liquidity-layer-relayers/templates/_helpers.tpl, typescript/infra/helm/liquidity-layer-relayers/templates/circle-relayer-deployment.yaml, typescript/infra/helm/liquidity-layer-relayers/templates/env-var-external-secret.yaml, typescript/infra/helm/liquidity-layer-relayers/templates/portal-relayer-deployment.yaml, typescript/infra/helm/liquidity-layer-relayers/values.yaml, typescript/infra/src/config/environment.ts, typescript/infra/src/config/middleware.ts, typescript/infra/src/middleware/liquidity-layer-relayer.ts
Helm chart and deploy scripts to run the infra-based relayers
- Fixes #1206
=> Liquidity Layer Relayer Infra

typescript/infra/scripts/verify.ts, typescript/sdk/src/deploy/verify/ContractVerifier.ts
Fixes up minor things about verification
=> Minor changes to verifications

rust/Cargo.lock, rust/abacus-base/Cargo.toml, rust/abacus-base/src/agent.rs, rust/abacus-base/src/contract_sync/cursor.rs, rust/abacus-base/src/contract_sync/interchain_gas.rs, rust/abacus-base/src/contract_sync/mailbox.rs, rust/abacus-base/src/contract_sync/mod.rs, rust/abacus-base/src/lib.rs, rust/abacus-core/src/traits/cursor.rs, rust/abacus-core/src/traits/mod.rs, rust/abacus-test/Cargo.toml, rust/abacus-test/src/mocks/cursor.rs, rust/abacus-test/src/mocks/mod.rs, rust/agents/scraper/src/chain_scraper/mod.rs, rust/agents/scraper/src/chain_scraper/sync.rs, rust/chains/abacus-ethereum/src/retrying.rs, solidity/contracts/middleware/InterchainAccountRouter.sol, solidity/contracts/middleware/InterchainQueryRouter.sol, solidity/contracts/mock/MockInterchainAccountRouter.sol, solidity/interfaces/IInterchainAccountRouter.sol, solidity/interfaces/IInterchainQueryRouter.sol, typescript/infra/scripts/verify.ts, typescript/sdk/src/deploy/verify/ContractVerifier.ts, typescript/sdk/src/gas/token-prices.ts, typescript/sdk/src/middleware/accounts.hardhat-test.ts
This PR pulls in the latest changes from main and should be merged (as opposed to squash merged).
Please review the last two commits only, as the rest have already been reviewed when merged into main.
None
=> Merge main into V2

rust/README.md, rust/agents/scraper/src/settings.rs, rust/hyperlane-base/src/settings/mod.rs, rust/hyperlane-core/src/types/message.rs, solidity/contracts/test/TestHyperlaneConnectionClient.sol, solidity/contracts/test/TestRouter.sol, solidity/update_abis.sh, tools/grafana/validator-dashboard.json, typescript/infra/helm/helloworld-kathy/templates/external-secret.yaml, typescript/infra/helm/key-funder/templates/env-var-external-secret.yaml, typescript/utils/src/types.ts, typescript/utils/src/utils.ts
Some more renaming and fixes that couldn't get into https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1312
Also noticing that the foundry tests aren't being ran and they're currently broken! Will do this in a followup tracked here https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1331
n/a
n/a
Not really - renames!
Yes - some infra changes
Building & running tests
=> More renaming

.github/workflows/e2e.yml, .github/workflows/node.yml, .github/workflows/rust.yml
This PR enables CI to run on pull requests and commits to the `v1` branch.
=> Run CI on v1

typescript/helloworld/src/app/app.ts, typescript/infra/scripts/helloworld/kathy.ts, typescript/sdk/src/core/HyperlaneCore.ts, typescript/utils/src/utils.ts
Same as #1356 , but didn't test it yet live
=> Reduce Kathy Polling in V2

.github/workflows/monorepo-docker.yml, .github/workflows/rust-docker.yml, rust/config/testnet2/alfajores_config.json, rust/config/testnet2/arbitrumgoerli_config.json, rust/config/testnet2/bsctestnet_config.json, rust/config/testnet2/fuji_config.json, rust/config/testnet2/mumbai_config.json, rust/config/testnet2/optimismgoerli_config.json, typescript/infra/config/environments/testnet2/core/rust/alfajores_config.json, typescript/infra/config/environments/testnet2/core/rust/arbitrumrinkeby_config.json, typescript/infra/config/environments/testnet2/core/rust/bsctestnet_config.json, typescript/infra/config/environments/testnet2/core/rust/fuji_config.json, typescript/infra/config/environments/testnet2/core/rust/kovan_config.json, typescript/infra/config/environments/testnet2/core/rust/mumbai_config.json, typescript/infra/config/environments/testnet2/core/rust/optimismkovan_config.json, typescript/sdk/src/consts/chainMetadata.ts
Quick config change to reduce the finality blocks on mumbai, and updates to the CI to build the docker image for the v1 branch.
=> Reduce mumbai finality blocks

typescript/infra/config/environments/testnet2/agent.ts
Let's try this again...
Also nudge for this ticket:
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/532
=> Mumbai reorg period

rust/chains/hyperlane-ethereum/abis/Mailbox.abi.json, rust/chains/hyperlane-ethereum/src/mailbox.rs, solidity/contracts/Mailbox.sol, solidity/test/lib/mailboxes.ts, solidity/test/mailbox.test.ts, solidity/update_abis.sh, typescript/sdk/src/core/HyperlaneCore.ts, typescript/sdk/src/core/TestCoreApp.ts, typescript/sdk/src/core/message.ts
Modifies mailbox logs for more useful indexing
- Fixes #944 
Not with v1
Yes
No
None
Yes
None
=> Modify `Dispatch`, `Process` and add `DispatchId`, `ProcessId`

typescript/infra/config/environments/mainnet/helloworld.ts, typescript/infra/config/environments/testnet2/helloworld.ts
Deployed kathy that uses #1356
=> Polling kathy

typescript/infra/config/environments/testnet2/agent.ts
Moonbasealpha is back up, and so are we :)
None
=> Redeploy agents with moonbasealpha

rust/Cargo.lock, rust/Cargo.toml, rust/agents/relayer/src/main.rs, rust/agents/scraper/src/main.rs, rust/agents/validator/src/main.rs, rust/chains/README.md, rust/chains/hyperlane-ethereum/src/lib.rs, rust/chains/hyperlane-fuel/Cargo.toml, rust/chains/hyperlane-fuel/src/interchain_gas.rs, rust/chains/hyperlane-fuel/src/lib.rs, rust/chains/hyperlane-fuel/src/mailbox.rs, rust/chains/hyperlane-fuel/src/multisig_ism.rs, rust/chains/hyperlane-fuel/src/provider.rs, rust/hyperlane-base/src/lib.rs, rust/hyperlane-base/src/settings/chains.rs, rust/hyperlane-core/src/lib.rs, rust/hyperlane-core/src/traits/mod.rs, rust/hyperlane-test/src/lib.rs
Adds in scaffolding for fuel, this should make it easier to fill in funcunality later.
There was some additional cleanup to other package options and lib.rs files for standardization.
- Depends on #1403
- Depends on #1404
- Fixes https://github.com/hyperlane-xyz/issues/issues/277
- Relates to #1283 
Yes
None
None
=> Fuel scaffolding

README.md
Attempting to prevent people from accidentally looking at the `main` branch when they really want `v1` features
n/a
n/a
Yes
None
None
=> Note on v2 in README

README.md
Attempting to prevent people from accidentally looking at this branch when they really want v2 features
n/a
n/a
Yes
None
None
=> Note on v1/v2 in readme

.github/workflows/e2e.yml, .github/workflows/monorepo-docker.yml, .github/workflows/node.yml, .github/workflows/rust-docker.yml, .github/workflows/rust-skipped.yml, .github/workflows/rust.yml
=> Port update actions

rust/agents/relayer/src/msg/gelato_submitter/mod.rs, rust/agents/relayer/src/msg/mod.rs, rust/agents/relayer/src/msg/processor.rs, rust/agents/relayer/src/msg/serial_submitter.rs
=> Ported reduce message retries

rust/agents/relayer/src/msg/gelato_submitter/mod.rs, rust/agents/relayer/src/msg/mod.rs, rust/agents/relayer/src/msg/processor.rs, rust/agents/relayer/src/msg/serial_submitter.rs, rust/ethers-prometheus/src/middleware/mod.rs, rust/hyperlane-base/src/metrics/core.rs, rust/hyperlane-base/src/metrics/provider.rs, rust/hyperlane-base/src/settings/trace/span_metrics.rs
=> Ported reduce metric cardinality

rust/agents/relayer/src/msg/serial_submitter.rs
Minor change to hopefully keep the e2e tests from failing sporadically.
=> Less relayer backoff

Dockerfile
=> Fix docker build for hyperlane-token

.github/workflows/monorepo-docker.yml, yarn.lock
Fixes docker builds on `main`
Updates submodules to `main`
=> Add submodules to docker build

solidity/contracts/middleware/liquidity-layer/LiquidityLayerRouter.sol, solidity/contracts/middleware/liquidity-layer/adapters/CircleBridgeAdapter.sol, solidity/contracts/middleware/liquidity-layer/interfaces/circle/ITokenMessenger.sol, solidity/contracts/mock/MockCircleBridge.sol, solidity/contracts/mock/MockCircleMessageTransmitter.sol, solidity/contracts/mock/MockCircleTokenMessenger.sol, solidity/test/LiquidityLayerRouter.t.sol, typescript/infra/config/environments/testnet2/liquidityLayer.ts, typescript/infra/config/environments/testnet2/middleware.ts, typescript/infra/config/environments/testnet2/middleware/liquidity-layer/addresses.json, typescript/infra/config/environments/testnet2/middleware/liquidity-layer/verification.json, typescript/sdk/src/deploy/middleware/LiquidityLayerApp.ts, typescript/sdk/src/deploy/middleware/LiquidityLayerRouterDeployer.ts, typescript/sdk/src/deploy/router/HyperlaneRouterDeployer.ts, typescript/sdk/src/middleware/liquidity-layer.hardhat-test.ts
=> Use redeployed CCTP contracts

typescript/infra/config/environments/mainnet/testrecipient/addresses.json, typescript/infra/config/environments/mainnet/testrecipient/verification.json
Deploy TestRecipient on Moonbeam
=> Deploy TestRecipient on Moonbeam

typescript/infra/config/environments/mainnet2/agent.ts, typescript/infra/config/environments/testnet3/agent.ts
Updates mainnet2/testnet3 to the latest agent image
=> Deploy mainnet2/testnet3 with latest agent image

typescript/infra/config/environments/testnet2/agent.ts
Just deploying what's on the abacus context for rc
n/a
n/a
Yes
None
Deployed
=> Deploy v1 RC

typescript/sdk/src/deploy/HyperlaneAppChecker.ts
=> Fix import from src

.github/workflows/node.yml
Doesn't instrument coverage when snapshots haven't been changed
=> Only run coverage when base snapshot has changed

.github/workflows/node.yml
Reverts hyperlane-xyz/hyperlane-monorepo#1568
See https://github.com/dorny/paths-filter/issues/24
=> Revert "Only run coverage when base snapshot has changed"

rust-toolchain, rust/Cargo.lock, rust/Dockerfile, rust/README.md, rust/agents/scraper/src/chain_scraper/mod.rs, rust/agents/scraper/src/db/txn.rs, rust/chains/hyperlane-ethereum/src/tx.rs, rust/hyperlane-core/src/accumulator/incremental.rs, rust/hyperlane-core/src/types/message.rs, rust/hyperlane-core/src/utils.rs, rust/utils/run-locally/src/main.rs
Updated rust and packages. No major updates.
This does pull in a number of security fixes.
Clippy update lead to some additional lints that had to be satisfied.
Yes, but you will need to run `cargo clean`.
None
Manual
Unit Tests
=> Rust Updates

typescript/infra/config/environments/testnet2/agent.ts
_What's included in this PR?_
Yes
No
None
Yes
None
Manual
Unit Tests
=> Block testnet2 TestRecipient relayer

rust/helm/hyperlane-agent/templates/relayer-external-secret.yaml, rust/helm/hyperlane-agent/templates/relayer-statefulset.yaml, typescript/infra/config/environments/mainnet2/agent.ts, typescript/infra/config/environments/testnet3/agent.ts, typescript/infra/src/agents/index.ts
This PR includes the most recent deploy and fixes necessary. It splits the signer configuration on the chain side to only happen for the relayer. I'm personally not sure that the configuration of signers right now is ideal and maybe should be another reason for #1664 or revisited more generally @mattiecnvr @tkporter
=> Deploy Jan 25

rust/config/mainnet2/mainnet2_config.json, rust/config/testnet3/testnet3_config.json, typescript/infra/config/environments/mainnet2/core/verification/verification.json, typescript/infra/config/environments/testnet3/core/verification/verification.json, typescript/sdk/src/consts/environments/mainnet.json, typescript/sdk/src/consts/environments/testnet.json
To pick up https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1674
Contracts not yet verified.
None
=> Re-deploy ValidatorAnnounce contracts

solidity/contracts/middleware/liquidity-layer/LiquidityLayerRouter.sol, solidity/contracts/middleware/liquidity-layer/adapters/CircleBridgeAdapter.sol
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1718
No
Unit Tests
=> Use safeTransfer in liquidity layer

solidity/contracts/OwnableMulticall.sol, solidity/contracts/Router.sol, solidity/contracts/middleware/InterchainQueryRouter.sol, solidity/contracts/middleware/liquidity-layer/LiquidityLayerRouter.sol, solidity/contracts/middleware/liquidity-layer/adapters/CircleBridgeAdapter.sol
=> M04: Triage contracts TODOs in issue tracker

typescript/infra/config/environments/testnet3/agent.ts
See #1690
I needed this commit to fix the whitelist/blacklist config for the rc env.
=> Actually update testnet3 agent image

rust/helm/hyperlane-agent/templates/external-secret.yaml, typescript/infra/config/environments/mainnet2/agent.ts, typescript/infra/config/environments/mainnet2/helloworld.ts, typescript/infra/config/environments/testnet3/agent.ts, typescript/infra/config/environments/testnet3/helloworld.ts, typescript/infra/src/config/agent.ts
Minor change to configs to support http fallback and then tested against testnet3 in rc and deployed.
- Updated hello world rc image for mainnet2 and testnet3
- Fixes #1628
=> Fallback Provider

.github/workflows/monorepo-docker.yml, .github/workflows/rust-docker.yml, typescript/infra/config/environments/testnet3/helloworld.ts
Changes image tags to look like this
`9b61e86-20230202-174933`
Where the first part is the short sha, middle is the year-month-day, and last part is the timestamp (hours mins secs) (to help distinguish which image came first when there are multiple on the same day in use).
=> Better image tags

solidity/contracts/middleware/InterchainAccountRouter.sol
Followup to https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1724
=> External visibility followup

rust/agents/scraper/migration/src/m20221122_000001_create_table_domain.rs
- Updated migration to support `gnosis` and also updated the db (by hand)
None
Yes
None
Manual - Running in mainnet2 now
=> Add gnosis to scraper

rust/agents/relayer/src/relayer.rs
Logs the gas enforcement configuration
n/a
n/a
Yes
None
None
=> Log gas enforcement configuration

typescript/infra/config/environments/mainnet2/helloworld.ts, typescript/infra/config/environments/testnet3/helloworld.ts
Redyces kathy frequency on testnet and mainnet
=> Reduce kathy frequency

rust/chains/hyperlane-ethereum/src/mailbox.rs
Set latest_checkpoint instrumentation to debug level
=> Set latest_checkpoint instrumentation to debug level

typescript/infra/config/environments/mainnet2/helloworld/hyperlane/addresses.json, typescript/infra/config/environments/mainnet2/helloworld/hyperlane/verification.json, typescript/infra/config/environments/mainnet2/helloworld/rc/addresses.json, typescript/infra/config/environments/mainnet2/helloworld/rc/verification.json, typescript/infra/config/environments/testnet3/helloworld/rc/addresses.json, typescript/infra/config/environments/testnet3/helloworld/rc/verification.json
- Picks up https://github.com/hyperlane-xyz/hyperlane-app-template/pull/41
- Redeploys mainnet2/testnet3 rc HelloWorld contracts
- Redeploys mainnet2 Gnosis HelloWorld contract
- Redeployed mainnet2/testnet3 hyperlane/rc agents, and mainnet2 hyperlane kathy
**Does not verify these contracts**
None
=> Update HelloWorld to latest and redeploy

typescript/infra/config/environments/mainnet2/helloworld.ts
=> Deploy mainnet2 kathy

typescript/infra/config/environments/mainnet2/core.ts, typescript/infra/config/environments/mainnet2/validators.ts, typescript/infra/scripts/list-validator-checkpoint-indices.ts, typescript/infra/scripts/verify-validators.ts, typescript/infra/src/agents/aws/validator.ts
Enroll ZKV/Staked to default ism
Fix verify-validators script
=> Enroll ZKV/Staked to default ism

README.md
We've deployed v2! and deprecated v1!
Yes
No
None
Yes
None
Manual
Unit Tests
=> Update readme's note on versioning

typescript/infra/helm/helloworld-kathy/templates/external-secret.yaml, typescript/infra/scripts/helloworld/kathy.ts
Follow up to https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1820
And update Kathy helm charts to support HttpFallback secrets
=> Add HttpFallback as an option to kathy script

.github/workflows/e2e.yml, typescript/infra/config/environments/mainnet/funding.ts, typescript/infra/scripts/funding/fund-keys-from-deployer.ts
Bumps to 1 from 0.1. Ran out of funds on v1 when relaying messages from polygon.
- Fix e2e tests by using node 16
=> Increase key funder celo desired balance to 1

typescript/infra/config/environments/mainnet2/helloworld.ts, typescript/infra/config/environments/testnet3/helloworld.ts
Includes #1922 
none
n/a
Yes
None
Deployed
=> Deploy kathy to use new contracts

.github/workflows/node.yml
Removes PR comments that do not work on external contributions
=> Remove coverage-sol PR comments

typescript/infra/config/environments/mainnet2/agent.ts
Enforce gas amounts on mainnet
none
- Fixes #1610 
Yes
None
Deployed & sent some test messages
=> Deploy on chain fee quoting onto mainnet

typescript/infra/config/environments/mainnet2/agent.ts
=> Deploy polygon hardcode

rust/chains/hyperlane-ethereum/src/interchain_gas.rs
Similar to the change we had to the mailbox to avoid polluting the logs
=> Reduce IGP indexer verbosity

typescript/infra/config/environments/mainnet2/helloworld.ts, typescript/infra/config/environments/testnet3/helloworld.ts
Deploy kathy which includes retrying providers from #1931
=> Deploy retrying kathy

typescript/infra/config/environments/testnet3/funding.ts, typescript/infra/scripts/funding/fund-keys-from-deployer.ts
=> Deploy key-funder with new min balances to testnet3

typescript/infra/scripts/check-rpc-urls.ts
Useful for debugging incidents
=> Add script to check RPC providers

.github/workflows/node.yml
=> Temporarily disable gas ci job in CI

typescript/infra/src/govern/HyperlaneAppGovernor.ts, typescript/infra/src/govern/multisend.ts
Makes some fixes to the safe governor
=> Don't reuse the same nonce and await confirmation

typescript/sdk/src/contracts.ts, typescript/sdk/src/core/HyperlaneCoreDeployer.ts, typescript/sdk/src/deploy/HyperlaneAppChecker.ts, typescript/sdk/src/deploy/HyperlaneDeployer.ts, typescript/sdk/src/gas/HyperlaneIgpDeployer.ts, typescript/sdk/src/index.ts, typescript/sdk/src/router/HyperlaneRouterDeployer.ts
Moves the Deployer classes to detect ownable contracts programmatically when doing ownership transfer
=> Programmatic ownership transfer of ownables in deployer

typescript/sdk/src/providers/MultiProvider.ts
=> Fix address url in contractverifier

rust/agents/relayer/src/relayer.rs, rust/hyperlane-base/src/settings/chains.rs
Removes a vestigial organ from the gelato days. We no longer need a config to denote txsubmission type.
No
- https://discord.com/channels/935678348330434570/1096400530722537513
Yes
None
Unit Tests
=> Remove txsubmission type

typescript/infra/config/environments/mainnet2/agent.ts, typescript/infra/config/environments/testnet3/agent.ts
This PR releases the latest agent image to testnet3 and mainnet2 to pick up general purpose ISM support.
None
=> Release latest agent image

typescript/infra/config/environments/mainnet2/ism/verification.json, typescript/infra/config/environments/testnet3/ism/verification.json, typescript/sdk/src/consts/environments/mainnet.json, typescript/sdk/src/consts/environments/testnet.json
Ran:
```
yarn ts-node scripts/deploy.ts -m ism
```
None
=> Deploy ISM factories to testnet/mainnet

solidity/package.json, typescript/infra/package.json, typescript/sdk/package.json, typescript/utils/package.json, yarn.lock
Publishes 1.3.3, moving the submodules back to their respective mains.
=> Publish 1.3.3

.github/workflows/node.yml, solidity/package.json
To address https://github.com/NomicFoundation/hardhat/issues/3877
Also reverts #2140
=> Use node 16 when compiling contract types

rust/sealevel/Cargo.lock, rust/sealevel/Cargo.toml, rust/sealevel/libraries/interchain-security-module-interface/src/lib.rs, rust/sealevel/libraries/multisig-ism/Cargo.toml, rust/sealevel/libraries/multisig-ism/src/interface.rs, rust/sealevel/libraries/multisig-ism/src/lib.rs, rust/sealevel/libraries/multisig-ism/src/test_data.rs, rust/sealevel/libraries/serializable-account-meta/Cargo.toml, rust/sealevel/libraries/serializable-account-meta/src/lib.rs, rust/sealevel/programs/ism/multisig-ism-message-id/Cargo.toml, rust/sealevel/programs/ism/multisig-ism-message-id/src/processor.rs, rust/sealevel/programs/ism/multisig-ism-message-id/tests/functional.rs, rust/sealevel/programs/ism/rubber-stamp/src/lib.rs
ISM.verify and MultisigIsm.ValidatorSetAndThreshold component of #2254  
n/a
doesn't fix but related to  #2254  
Yes
None
Unit Tests
=> ISM AccountMeta getters

rust/chains/hyperlane-sealevel/src/mailbox.rs, rust/sealevel/client/src/main.rs, rust/sealevel/libraries/hyperlane-sealevel-token/src/processor.rs, rust/sealevel/programs/hyperlane-sealevel-token/tests/functional.rs, rust/sealevel/programs/mailbox/src/accounts.rs, rust/sealevel/programs/mailbox/src/instruction.rs, rust/sealevel/programs/mailbox/src/processor.rs
Fixes #2264 
n/a
- Fixes #2264
Yes
None
Unit Tests, ran end to end
=> Recipient specific process authorities

typescript/infra/fork.sh, typescript/sdk/src/HyperlaneApp.ts, typescript/sdk/src/consts/environments/mainnet.json, typescript/sdk/src/consts/environments/testnet.json, typescript/sdk/src/core/HyperlaneCoreDeployer.ts, typescript/sdk/src/ism/HyperlaneIsmFactory.ts
Fixes env tests failing in CI https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/5081007361/jobs/9128835519. Adds logging to ism factory deployer and ism deployments.
=> Fix env tests for new multisig variants

rust/agents/validator/src/validator.rs
Fixes a bug in which the validator would panic if the mailbox was empty.
None
=> Do not spawn validator backwards pass if count is zero

rust/Cargo.lock, rust/agents/relayer/src/relayer.rs, rust/agents/scraper/src/agent.rs, rust/agents/validator/src/submit.rs, rust/agents/validator/src/validator.rs, rust/chains/hyperlane-ethereum/Cargo.toml, rust/chains/hyperlane-ethereum/src/lib.rs, rust/chains/hyperlane-ethereum/src/singleton_signer.rs, rust/hyperlane-base/src/agent.rs, rust/hyperlane-core/src/traits/signing.rs
I think this will fix it, but either way it should get you closer.
NOTE: This PR merges into the `single-signer` branch intentionally for @yorhodes 's review and learning.
=> Mattie's single signer

rust/sealevel/libraries/hyperlane-sealevel-connection-client/src/router.rs, rust/sealevel/libraries/hyperlane-sealevel-token/src/accounts.rs
Just a driveby
Yes
No
None
Yes
Unit Tests
=> Autoimplement some hyperlane-sealevel-connection-client traits

rust/agents/relayer/src/relayer.rs, rust/agents/scraper/src/agent.rs, rust/agents/scraper/src/chain_scraper/mod.rs, rust/agents/validator/src/submit.rs, rust/agents/validator/src/validator.rs, rust/chains/hyperlane-ethereum/src/lib.rs, rust/chains/hyperlane-ethereum/src/singleton_signer.rs, rust/config/mainnet_config.json, rust/hyperlane-base/src/agent.rs, rust/hyperlane-base/src/contract_sync/mod.rs, rust/hyperlane-base/src/settings/signers.rs, typescript/infra/config/environments/testnet3/funding.ts
Merge main changes
Yes
No
None
Yes
None
Manual
Unit Tests
=> Merge main

typescript/infra/config/environments/mainnet2/agent.ts, typescript/infra/config/environments/testnet3/agent.ts
Updates hyperlane context mainnet2 and testnet3 validator image tags (to whats already deployed)
=> Release new validators internally

typescript/infra/config/environments/mainnet2/validators.ts
Scale down gnosis validators to 1
=> Scale down gnosis validators to 1

typescript/infra/config/environments/mainnet2/agent.ts, typescript/infra/config/environments/testnet3/agent.ts
Updated the scraper to fix a metric issue.
None
Yes
None
Manual
=> Deployed scraper

rust/agents/relayer/src/settings/mod.rs
Missed this by accident from #2249
None
Yes
None
Unit Tests
=> Dedup chain parsing

solidity/package.json, typescript/helloworld/package.json, typescript/infra/package.json, typescript/sdk/package.json, typescript/sdk/src/index.ts, typescript/sdk/src/ism/HyperlaneIsmFactory.ts, typescript/sdk/src/router/HyperlaneRouterDeployer.ts, typescript/token/package.json, typescript/utils/package.json, yarn.lock
- Fix checkConfig in HyperlaneRouterDeployer
- Bump packages to 1.3.7
=> Fix checkConfig in HyperlaneRouterDeployer

rust/agents/validator/src/validator.rs
_What's included in this PR?_
Yes
No
None
Yes
None
Manual
Unit Tests
=> fix(validator): make announce error msg more generic over chains

solidity/contracts/MailboxV3.sol
- Init immutable mailbox v3 and native hooks
- Simplify mailbox and make interfaces payable
- Update version constant
- Keep message ID events
- Kunal/v3 hooks (#2580)
- Add msg.sender to delivery mapping
=> delivery mapping

solidity/test/isms/MultisigIsm.t.sol
- Making forge build work again
- Setting TestMerkleTreeHook as a separate contract for `proof()`
- v3
Yes
Unit tests
=> add merkleTreeHook

solidity/contracts/hooks/AbstractMessageIdAuthHook.sol, solidity/contracts/hooks/DefaultHook.sol, solidity/contracts/hooks/DomainRoutingHook.sol
- Adding default hook using custom config
- `postDispatch` is now public
- v3
Yes
None
=> Adding default hook

rust/hyperlane-base/src/contract_sync/eta_calculator.rs
=> bump eta calculator log prio

solidity/package.json, typescript/helloworld/package.json, typescript/infra/package.json, typescript/sdk/package.json, typescript/token/package.json, typescript/utils/package.json, yarn.lock
https://github.com/hyperlane-xyz/hyperlane-monorepo/releases/tag/v1.5.1
=> Bump versions to 1.5.1

solidity/contracts/Mailbox.sol, solidity/test/Mailbox.t.sol
- Updates mailbox `recipientIsm` to handle more edge cases
> Someone in our Discord ran into this problem ages ago and Dan just did as well. If a recipient contract doesn't specify their own ISM by not having an interchainSecurityModule() fn but they happen to have a fallback function, then the Mailbox's recipientIsm function reverts. The reason is that the Mailbox will attempt to decode empty bytes after calling the recipient's interchainSecurityModule() function into an address.
Fixes https://github.com/hyperlane-xyz/issues/issues/629
Yes
Unit tests
=> Make recipientIsm more robust

typescript/helloworld/src/test/helloworld.test.ts, typescript/sdk/src/test/testUtils.ts
Fixes test-ts CI job on v3 branch broken by https://github.com/hyperlane-xyz/hyperlane-monorepo/commit/af5bd88aa86bb1983a6f169c82755db854e8a1a6
Made CI tests required on v3
Unit tests
=> Fix helloworld unit tests

typescript/infra/config/environments/mainnet2/helloworld.ts, typescript/infra/config/environments/testnet3/helloworld.ts, typescript/infra/scripts/helloworld/kathy.ts, typescript/sdk/src/core/MultiProtocolCore.test.ts
- Triple Kathy wait time to 9 minutes
- Add unit tests for MultiProtocolCore.test.ts
=> Increase Kathy max wait time

rust/Cargo.lock, rust/hyperlane-base/Cargo.toml, rust/hyperlane-core/Cargo.toml, rust/hyperlane-core/src/types/primitive_types.rs, rust/hyperlane-core/src/utils.rs
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2779
see https://docs.rs/getrandom/latest/getrandom/#webassembly-support
Yes
CI
=> Put f64 in hyperlane-core behind float flag

typescript/infra/config/environments/mainnet2/helloworld.ts, typescript/infra/config/environments/testnet3/helloworld.ts, typescript/infra/scripts/helloworld/kathy.ts
Per discussion in standup yesterday
=> Increase Kathy timeout to 12 minutes

typescript/cli/ci-test.sh, typescript/cli/logger.ts, typescript/cli/src/commands/chains.ts, typescript/cli/src/commands/deploy.ts, typescript/cli/src/commands/options.ts, typescript/cli/src/deploy/core.ts, typescript/cli/src/deploy/utils.ts, typescript/cli/src/utils/chains.ts
- Support multiple origins in PI deployments
- Simplify ci test with single core deploy command
- Improve output format of chains list command
Fixes #2813 
Tested locally and with e2e test
=> Support multiple origins in PI deployments

typescript/infra/config/environments/testnet4/agent.ts
Deploy to include #2836
n/a
n/a
yes
deployed
=> Deploy testnet4 agents to include validator signing fix

typescript/sdk/src/token/adapters/CosmWasmTokenAdapter.ts, typescript/utils/src/addresses.ts
=> Check for IBC denom collateral and cosmos addresess

rust/Cargo.lock, rust/Cargo.toml
=> Fix null deser of EventAttribute.value

typescript/infra/src/config/gas-oracle.ts, typescript/utils/.mocharc.json, typescript/utils/index.ts, typescript/utils/package.json, typescript/utils/src/amount.ts, typescript/utils/src/big-numbers.test.ts, typescript/utils/src/big-numbers.ts, typescript/utils/src/multisig.ts, yarn.lock
wip PR for de-dupe BigNumber libraries usage, having some discussion in the issue tab
- Fixes #2751
=> Dedupe BigNum util

typescript/cli/src/send/message.ts
=> log out message instead of ID

rust/utils/run-locally/src/cosmos/mod.rs, rust/utils/run-locally/src/cosmos/utils.rs
=> fix: use metricsport

typescript/cli/src/deploy/warp.ts, typescript/sdk/src/deploy/HyperlaneDeployer.ts
Warp Deploys should not require the specification of an ISM
=> Don't require ISM for warp route deploys

.github/workflows/release.yml, package.json
Fixes yarn command used in release script of changesets action https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/6959943453/job/18938332513
=> Fix publish script on changesets release action

.github/workflows/release.yml
- Give github actions permission to write branches and PRs
=> Adjust release action permissions

.changeset/config.json
@jmrossy requested that we share versions across all the monorepo packages for simplicity of consumption. See https://github.com/changesets/changesets/blob/main/docs/fixed-packages.md
Tested with `yarn changeset version` locally (release action will do this)
=> yarn changeset fixed packages

package.json
https://github.com/yarnpkg/berry/discussions/3486
Hopefully it still works for yarn 4. The command accepts it but we need to test it in CI to know for sure
=> Add --no-immutable flag to version:prepare

.github/workflows/monorepo-docker.yml, .github/workflows/rust-docker.yml, .github/workflows/rust-skipped.yml, .github/workflows/rust.yml
=> Trigger actions on v2

.github/workflows/monorepo-docker.yml, typescript/helloworld/hardhat.config.ts
=> Try to fix monorepo image building

typescript/infra/config/environments/mainnet2/helloworld.ts, typescript/infra/config/environments/testnet3/helloworld.ts
deploy with https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2981
n/a
n/a
ye
deployed
=> Deploy kathy with helloworld Sealevel fix

.changeset/hungry-ducks-greet.md, package.json, typescript/cli/cli.ts, typescript/cli/package.json, typescript/cli/src/version.ts, typescript/sdk/src/consts/chainMetadata.ts
- Fix fatal error in CLI due to version command
- Fix CI test errors due to neutrontestnet metadata
=> Fix CLI error from version command

rust/Cargo.lock, rust/Cargo.toml
Update to latest ethers-rs (forked) version with https://github.com/hyperlane-xyz/ethers-rs/pull/9
n/a
n/a
n/a
Planning to deploy with it, but the ethers-rs version is well tested
=> Update ethers-rs with polygon gas oracle fix

typescript/cli/src/deploy/core.ts
- changing `multisigIsm` to`interchainSecurityModule` for core deployments artifact
=> `multisigIsm` -> `interchainSecurityModule` for core deployments artifact

package.json, typescript/helloworld/src/test/helloworld.test.ts
- Fixes `yarn test`
- Updates helloworld test broken by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2991
CI
=> Previous yarn test --since failed to catch deps

typescript/infra/config/environments/mainnet2/agent.ts, typescript/infra/config/environments/testnet3/agent.ts
Deploys to include https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2974
=> Deploy polygon gas fix to v2

typescript/cli/cli.ts, typescript/cli/package.json, yarn.lock
This reverts commit c606b6a485ce91b04ed096e5c5792a9195ba6f5d.
=> Revert "Add figlet to CLI (#3008)"

solidity/contracts/hooks/libs/StandardHookMetadata.sol
=> StandardHookMetadata.sol small doc fix

.github/workflows/static-analysis.yml
- Fixes slither github action and makes required
=> Fix slither CI action

.changeset/lovely-laws-cover.md, typescript/cli/src/config/artifacts.ts, typescript/cli/src/context.ts, typescript/cli/src/deploy/core.ts, typescript/cli/src/deploy/warp.ts
Consistently respect --yes flag for all user prompts in the core and warp deploy commands
Fixes #3056 
Yes
Locally with CI test alterations
=> Fixes for commands with --yes flag

.github/workflows/node.yml, typescript/infra/config/environments/mainnet2/helloworld.ts, typescript/infra/config/environments/testnet3/helloworld.ts
Reduces the frequency so that a message is send roughly every 5-6 hours
=> Reduce v2 kathy frequency

README.md, rust/README.md
- Explicitly mention Foundry in README and provide instructions to install
- Add Rosetta 2 command to rust setup
=> feat: add foundry and rosetta setup steps

.changeset/fast-pillows-wash.md, typescript/sdk/package.json, typescript/sdk/src/providers/SmartProvider/SmartProvider.test.ts, typescript/utils/index.ts, typescript/utils/src/addresses.ts
Remove hard-coding of min block number and topic1 value.
Add convenience `isAddress` util function
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3148
Yes
=> Fix Smart Provider e2e test

.changeset/thirty-pandas-design.md, .github/workflows/test.yml, package.json, solidity/coverage.sh
- Adds changeset for https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3141
- Runs coverage on all packages after `yarn-test`
Yes
Unit tests
=> Cleanup merge of #3141

typescript/sdk/src/consts/multisigIsm.ts
Adds the validator set to the source of truth in the SDK consts
=> Add Neutron validators

typescript/infra/scripts/announce-validators.ts, typescript/infra/scripts/utils.ts, typescript/infra/src/agents/aws/key.ts, typescript/infra/src/agents/gcp.ts, typescript/infra/src/agents/key-utils.ts, typescript/infra/src/utils/gcloud.ts
improve logging through create-key script and related infra logic
also add `[chainName]` prefix to validator announce logs
drive-by from doing https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3190
=> feat: improve create-key logging 

.changeset/cyan-owls-pull.md, typescript/cli/ci-test.sh, typescript/cli/src/commands/send.ts, typescript/cli/src/send/transfer.ts
- supports synthetic warp routes
- fixes bug in collateral balance checking
- deduces token balance checks from provided router address
- Manual and CLI CI test
=> Improve cli send transfer command

rust/agents/relayer/src/msg/metadata/ccip_read.rs
Fixes the CCIP read json body to use the `sender_as_bytes` variable. This fixes the issue of truncated sender
=> fix: use sender as bytes variables

typescript/infra/config/environments/mainnet3/chains.ts
Add injective to mainnet3 infra config
Env tests
=> Add injective to mainnet config

typescript/cli/cli.ts, typescript/cli/package.json, typescript/cli/src/utils/version-check.ts, yarn.lock
Added version check functionality to CLI
Yes
Manual
=> CLI version check

.github/workflows/test.yml
- Add ethereum to mainnet3 env tests
Env tests
=> Add ethereum to env tests

rust/chains/hyperlane-sealevel/src/interchain_gas.rs, rust/chains/hyperlane-sealevel/src/mailbox.rs, rust/hyperlane-base/src/contract_sync/cursor.rs, typescript/infra/config/environments/mainnet2/agent.ts
=> reduce max sequence range to 5

.github/workflows/cron.yml, .github/workflows/test.yml
- Change `metadata-check` from PR time to a daily cron job
=> Migrate metadata-check to cron workflow

.github/workflows/cron.yml
=> Post to discord #incidents upon cron failure

typescript/sdk/src/hook/HyperlaneHookDeployer.ts, typescript/sdk/src/ism/utils.ts
Copies https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3275 for the core deployer
=> Account for non-evm for domain fetching

rust/config/mainnet3_config.json, rust/config/testnet4_config.json, rust/hyperlane-base/src/settings/parser/mod.rs, rust/hyperlane-core/src/chain.rs, typescript/infra/config/aw-multisig.json, typescript/infra/config/environments/testnet4/agent.ts, typescript/infra/config/kathy.json, typescript/infra/config/relayer.json, typescript/infra/src/agents/key-utils.ts, typescript/sdk/src/consts/chainMetadata.ts, typescript/sdk/src/index.ts, typescript/sdk/src/metadata/chainMetadataTypes.ts
- consistent stringifying of keys
- change plumetestnet reorg period to 0
=> Add technical stack config for Arbitrum Nitro chains

Dockerfile, typescript/infra/src/agents/agent.ts
Fixes Workflow issue due to missing ccip-server package
Yes
=> Update DockerFile to include ccip-server

.github/workflows/test.yml, typescript/infra/config/environments/mainnet3/warp/addresses.json, typescript/infra/scripts/deploy.ts
- Updates inEVM INJ warp route ISM
Yes
- See inEVM fork tests
=> Transfer owner and configure default ISM on inEVM native warp route

.github/workflows/test.yml, typescript/cli/ci-test.sh, typescript/cli/examples/fork/anvil-chains.yaml, typescript/cli/examples/fork/ism.yaml, typescript/cli/examples/fork/warp-tokens.yaml, typescript/helloworld/src/app/app.ts
resolves https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3202
- update ci-test.sh to parameterise the chains, still do anvil<>anvil
- update ci-test.sh to run anvil<>ethereum fork as well
- add some example yamls for the fork test
=> feat: improve cli test coverage for pi<>core interactions

typescript/infra/config/environments/mainnet3/funding.ts, typescript/infra/config/environments/testnet4/funding.ts, typescript/infra/scripts/funding/fund-keys-from-deployer.ts
Reverts hyperlane-xyz/hyperlane-monorepo#3301 
but keeps the value changes
=> Revert "feat: tweak keyfunder params"

solidity/exportBuildArtifact.sh
should fix https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/8257193993/job/22592571029#step:5:25
=> feat: make exportBuildArtifact compliant with sh

.github/workflows/storage-analysis.yml
- Remove github authenticated PR Comment action
=> Remove PR comment from storage layout check

.changeset/proud-cycles-wait.md, typescript/cli/ci-test.sh, typescript/cli/package.json, typescript/cli/src/deploy/warp.ts, typescript/cli/src/tests/deployTestErc20.ts, yarn.lock
- Fix incorrect adapter use in CLI's warp route deployment
- Add a warp collateral deployment to cli e2e test
Fixes https://github.com/hyperlane-xyz/issues/issues/1146
Yes
Tested manually and via new e2e test coverage
=> Fix bug with HypCollateral warp route deployments

rust/chains/hyperlane-ethereum/src/tx.rs, typescript/infra/config/environments/mainnet2/agent.ts
- Fixes #3396 
- Backport of #3462
=> V2: fix BSC gas price logic

typescript/infra/config/aw-multisig.json, typescript/infra/config/environments/mainnet3/validators.ts
=> Only run 1 injective validator

typescript/infra/config/environments/mainnet3/warp/viction-USDT-addresses.json, typescript/infra/config/environments/mainnet3/warp/viction-ethereum-USDT-deployments.yaml, typescript/infra/scripts/warp-routes/helm.ts
Somehow the wrong viction USDT address was in the address artifacts
=> Fix viction USDT address

typescript/sdk/src/core/CoreDeployer.hardhat-test.ts, typescript/sdk/src/core/HyperlaneCoreDeployer.ts, typescript/sdk/src/core/TestRecipientDeployer.ts, typescript/sdk/src/deploy/HyperlaneDeployer.ts, typescript/sdk/src/providers/SmartProvider/SmartProvider.test.ts
Fixes for break introduced in https://github.com/hyperlane-xyz/hyperlane-monorepo/commit/77de7abdd4d8edb86ed922ad7271fac20a0de9da
Skip SmartProvider tests
Yes
=> Fix CLI e2e issue due to TestRecipient ISM

rust/chains/hyperlane-ethereum/src/tx.rs
V3 counterpart of https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3431
=> Half the relayer timeout on v3

.changeset/new-melons-tell.md
forgot to add in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3494
=> fix: add changeset for warp verify fix

solidity/contracts/libs/RateLimited.sol
=> fix: typo in RateLimited.sol

rust/config/mainnet_config.json, typescript/infra/config/environments/mainnet3/chains.ts
=> Set prio fee override for moonbeam

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/src/agents/gcp.ts
See https://discord.com/channels/935678348330434570/1230452070696484956 for context. General idea as a stopgap is to run a relayer concurrent with the Hyperlane one
=> Deploy RC relayer for extra throughput

solidity/coverage.sh
- Fixes coverage job (see codecov output)
=> Fix solidity coverage

.changeset/khaki-days-float.md, typescript/sdk/src/providers/MultiProvider.ts
Small PR to actually allow overrides of gasLimit
=> Allow gasLimit overrides in the SDK/CLI for deploy txs

rust/agents/relayer/src/msg/pending_message.rs, rust/agents/relayer/src/msg/pending_operation.rs, rust/agents/relayer/src/msg/serial_submitter.rs, rust/chains/hyperlane-ethereum/src/contracts/mailbox.rs, rust/hyperlane-core/src/traits/mailbox.rs, rust/hyperlane-core/src/types/transaction.rs
=> [draft] some tweaks to play with batching

typescript/infra/config/environments/mainnet3/owners.ts
=> Ensure owners are configured correctly

rust/agents/relayer/src/msg/serial_submitter.rs
=> fix: sleep after submitting to cosmos chains

rust/config/mainnet_config.json, typescript/infra/config/environments/mainnet3/agent.ts
=> fix: agent config check, run relayer on mantapacific

solidity/contracts/token/extensions/HypFiatTokenCollateral.sol, solidity/contracts/token/extensions/HypXERC20Collateral.sol
* Addresses sol compiler warnings on missing licenses
=> address new license warnings on hyp*coll contracts

.github/workflows/test.yml
- Run tests (except larger-runner jobs) on PRs where base branch is not main
=> Run non larger-runner CI tests on all PRs

solidity/package.json, typescript/ccip-server/package.json, typescript/cli/package.json, typescript/cli/src/version.ts, typescript/helloworld/package.json, typescript/infra/package.json, typescript/sdk/package.json, typescript/utils/package.json, yarn.lock
=> fix: change version to 3.12.2

.github/workflows/lint-pr.yaml
uses this github action: https://github.com/amannn/action-semantic-pull-request
=> chore: enforce conventional commits on PR titles

.changeset/green-ads-live.md, .changeset/lemon-horses-swim.md, .changeset/olive-apricots-develop.md, .changeset/quiet-cheetahs-own.md, .changeset/sixty-avocados-double.md, .changeset/sour-bats-sort.md, .github/workflows/lint-pr.yaml, solidity/CHANGELOG.md, solidity/package.json, typescript/ccip-server/CHANGELOG.md, typescript/ccip-server/package.json, typescript/cli/CHANGELOG.md, typescript/cli/package.json, typescript/cli/src/version.ts, typescript/helloworld/CHANGELOG.md, typescript/helloworld/package.json, typescript/infra/CHANGELOG.md, typescript/infra/package.json, typescript/sdk/CHANGELOG.md, typescript/sdk/package.json, typescript/utils/CHANGELOG.md, typescript/utils/package.json, yarn.lock
=> chore: Merge branch 'main' into noah/cli-2.0

.changeset/selfish-carpets-do.md, typescript/infra/src/govern/HyperlaneAppGovernor.ts, typescript/sdk/src/middleware/account/InterchainAccount.ts, typescript/sdk/src/middleware/account/accounts.hardhat-test.ts, typescript/sdk/src/providers/transactions/schemas.ts, typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5GnosisSafeTxSubmitter.ts, typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5ImpersonatedAccountTxSubmitter.ts, typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5TxSubmitterTypes.ts, typescript/sdk/src/providers/transactions/transformer/ethersV5/EV5InterchainAccountTxTransformer.ts, typescript/sdk/src/providers/transactions/transformer/ethersV5/EV5TxTransformerTypes.ts, typescript/sdk/src/providers/transactions/types.ts
See comments and approvals here: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3792
=> chore(sdk): add zod validation on submitter/transformers popTx + refactor ICA interface

.github/CODEOWNERS
It had to happen #RIP, my getting review requested ended up too noisy to miss actual tags in issues
=> chore: Remove nambrot from codeowners

solidity/.solhint.json, solidity/.solhintignore, solidity/contracts/libs/AnvilRPC.sol
=> Integration test xERC20s

typescript/sdk/src/core/EvmCoreModule.ts
=> fix: typo in core module

typescript/cli/examples/hooks.yaml, typescript/cli/src/send/message.ts, typescript/cli/src/tests/hooks.test.ts
- Fixes CLI e2e
- Use `HyperlaneCore` helpers to simplify CLI
Yes
CLI E2E matrix (now required on `cli-2.0` branch)
=> fix: cli e2e was inadvertently broken

.changeset/spotty-wolves-fail.md, typescript/cli/src/commands/core.ts, typescript/cli/src/commands/options.ts, typescript/cli/src/commands/warp.ts, typescript/sdk/src/index.ts
* adds new `hyperlane warp read` command
- fixes https://github.com/hyperlane-xyz/issues/issues/1189
* yes
=> feat(cli): add 'hyperlane warp read' command

rust/config/testnet_config.json
ran `yarn tsx ./scripts/agents/update-agent-config.ts -e testnet4` and updated testnet4 config
=> fix: testnet4 holesky config

tools/grafana/easy-relayer-dashboard-external.json
Relayer metrics template for monitoring & alerting. Looks like so:
=> feat: relayer dashboard template

typescript/infra/config/environments/testnet4/funding.ts, typescript/infra/config/environments/testnet4/helloworld.ts
Update docker image tag for kathy and key funder
=> chore(infra): Update docker image tag for kathy and key funder

.github/workflows/rust-skipped.yml, .github/workflows/rust.yml, .github/workflows/test.yml
- configure the rust/test workflows to support merge queues into `main`
=> ci: configure merge queue for `main`

funding.json
- Add verification for OP retro funding round 4
=> chore: create `funding.json`

README.md
Add some release/prerelease directions to readme
=> chore: add release steps to readme

rust/config/mainnet_config.json
chore: fix mainnet3 agent config
follow-on from https://github.com/hyperlane-xyz/hyperlane-registry/pull/49
=> chore: fix mainnet3 agent config

solidity/contracts/token/README.md
Pls, review I got that right.
Corrects a **semantic** typo.
relative paths to the libs are corrected
none
Yes
None
=> chore: Update Solidity README.md

.github/workflows/rust-skipped.yml, .github/workflows/test-skipped.yml
fix: test filtering for `*.md` changes
- fix the rust-skipped flow
- add a test-skipped flow to still go green on the required status checks
=> fix: test filtering for `*.md` changes

typescript/sdk/src/ism/metadata/builder.hardhat-test.ts, typescript/sdk/src/middleware/liquidity-layer/liquidity-layer.hardhat-test.ts, typescript/sdk/src/middleware/query/queries.hardhat-test.ts
temporarily skipping this test that occasionally flakes until we can fix it for good
=> ci: temporarily skip a flaky test

.changeset/clean-bees-repeat.md, typescript/cli/src/send/message.ts, typescript/cli/src/send/transfer.ts, typescript/cli/src/status/message.ts, typescript/sdk/src/core/HyperlaneCore.ts, typescript/sdk/src/ism/metadata/builder.hardhat-test.ts, typescript/sdk/src/middleware/liquidity-layer/liquidity-layer.hardhat-test.ts, typescript/sdk/src/middleware/query/queries.hardhat-test.ts
- adds self-relay support to CLI
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3955
- yes
- manual
=> feat(cli): support more ISM types in CLI self-relay

.changeset/sixty-ducks-brush.md, typescript/cli/src/deploy/warp.ts, typescript/sdk/src/providers/SmartProvider/HyperlaneEtherscanProvider.ts, typescript/sdk/src/providers/SmartProvider/HyperlaneJsonRpcProvider.ts, typescript/sdk/src/providers/SmartProvider/ProviderMethods.ts, typescript/sdk/src/providers/SmartProvider/SmartProvider.ts, typescript/sdk/src/token/deploy.ts
`main` equivalent for https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3971 to get it in for the latest warp UI deployment
=> feat: support priorityFee fetching from RPC and some better logging

rust/sealevel/libraries/ecdsa-signature/Cargo.toml, rust/sealevel/libraries/message-recipient-interface/Cargo.toml, rust/sealevel/programs/hyperlane-sealevel-igp/Cargo.toml, rust/sealevel/programs/mailbox/Cargo.toml
changed links pointing to Solana docs due to migration to different repository
=> chore: fix broken links

.changeset/hip-melons-build.md, typescript/cli/src/commands/options.ts, typescript/cli/src/commands/validator.ts, typescript/cli/src/config/agent.ts, typescript/cli/src/validator/preFlightCheck.ts
- Add validator preFlightCheck command that requires a chain name and a comma separated list of validator addresses
- command will check if the validator has announced and log it's storage location and latest signed checkpoint index
example usage:
Happy path
```
$yarn hyperlane validator preflightCheck --chain ethereum --validators 0xCE327111035dd38698c92c3778884dBbB0ca8103,0x5AEd2fD5cC5F9749C455646C86B0Db6126CaFcbB
Hyperlane CLI
Latest check point index of incremental merkle tree: 6279
✅ Validator 0xCE327111035dd38698c92c3778884dBbB0ca8103 announced
storage location: s3://hyperlane-v3-validator-signatures-everstake-ethereum/us-east-2
latest checkpoint index: 6279
✅ Validator is signing the latest available checkpoint
✅ Validator 0x5AEd2fD5cC5F9749C455646C86B0Db6126CaFcbB announced …
```
=> feat(cli): CLI command with pre-flight checks for a validator

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/config/environments/testnet4/agent.ts
=> chore: bump agent docker images

typescript/infra/package.json, typescript/infra/scripts/generate-renzo-warp-route-config.ts, typescript/sdk/src/ism/multisig.ts, yarn.lock
=> feat: Script to generate Renzo Warp Route Configuration

typescript/cli/src/config/chain.ts, typescript/cli/src/deploy/utils.ts
- addresses P1 in https://www.notion.so/hyperlanexyz/CLI-Bug-Bash-5fc0833e51034baeba3beba9319160ff?pvs=4
- NOTE: Mimicking this behaviour: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/cli/src/utils/balances.ts#L23
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4008
- Once merged, this section of the quickstart guide should be removed: https://www.notion.so/hyperlanexyz/Hyperlane-Quickstart-Beta-4d9ff48720ee43fa8456a7d1517098dd?pvs=4#15534475fd8d4b398e51e9e0d527fb48
- cc @avious00
=> fix(cli): make native token required in chain config

rust/config/mainnet_config.json
chore: reconcile mainnet config json with registry
=> chore: reconcile mainnet config json with registry

typescript/infra/src/infrastructure/monitoring/prometheus.ts
See https://discord.com/channels/935678348330434570/935679524534911007/1252943931121864824 - an attempt to fix some intermittent issues we've seen with prometheus
=> fix: set resource requests for prometheus server & node exporter

typescript/infra/config/environments/mainnet3/owners.ts, typescript/infra/scripts/check-deploy.ts, typescript/infra/src/govern/HyperlaneAppGovernor.ts, typescript/sdk/src/core/HyperlaneCoreChecker.ts
Add multisig owners for linea, mode and blast. Expected violations are mailbox,proxyadmin, and ism violations (since the routing ism expected owner is now different)
=> chore: add more multisigs

typescript/infra/scripts/agents/utils.ts
- allow someone to provide a specific set of chains to deploy validators for
deploying validator:
deploying relayer:
=> feat(infra): allow specifying chains to deploy validators for in infra

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: re-enforce a whitelist policy in the RC relayer

typescript/cli/src/config/chain.ts, typescript/cli/src/config/core.ts, typescript/cli/src/config/hooks.ts, typescript/cli/src/config/ism.ts, typescript/cli/src/config/warp.ts, typescript/cli/src/utils/chains.ts, typescript/cli/src/utils/input.ts
- add units and explanation to protocol fee input
- adds `inputWithInfo` to allow optional info developers can request with `i`
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4023
- yes 
- manual
example output:
```
➜  cli git:(cli-2.0) ✗ hl core init --registry $HOME/workplace/Hyperlane/hyperlane-registry --advanced
Hyperlane CLI
Hyperlane Core Configure
------------------------
Creating a new core deployment config...
? Detected owner address as 0x16F4898F47c085C41d7Cc6b1dc72B91EA617dcBb from signer, is this correct? yes
Creating a new advanced ISM config
WARNING: USE AT YOUR RISK.
Advanced ISM configs require knowledge of different ISM types and how they work together topologically. If possible, use the basic ISM configs are recommended.
? Select ISM type …
```
=> fix(cli): add units and explanation to protocol fee input

.changeset/clean-numbers-know.md, typescript/cli/package.json, typescript/helloworld/package.json, typescript/infra/package.json, yarn.lock
To pickup fix in https://github.com/hyperlane-xyz/hyperlane-registry/pull/71
Yes
=> chore: Upgrade registry to 2.1.1

typescript/cli/cli.ts
Forgot to add the new commands to the top-level cli.ts when I added back the commands in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3990
Noticed when trying to test https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4055
Tested with:
```sh
$ yarn workspace @hyperlane-xyz/cli run hyperlane ism read --chain inevm --address 0x79A7c7Fe443971CBc6baD623Fdf8019C379a7178
Hyperlane CLI
{"level":30,"time":1719408936852,"pid":74170,"msg":"Your CLI version: 3.15.0, latest version: 3.16.0"}
Hyperlane ISM Read
------------------
ISM Config at 0x79A7c7Fe443971CBc6baD623Fdf8019C379a7178 on inevm:
address: "0x79A7c7Fe443971CBc6baD623Fdf8019C379a7178"
type: staticAggregationIsm
modules:
- address: "0x718901b7570c59241304758345aF297Ff47D83A1"
type: messageIdMultisigIsm
validators:
- …
```
=> fix(cli): add hook/ism commands

typescript/cli/src/commands/core.ts, typescript/sdk/src/core/EvmCoreReader.ts, typescript/sdk/src/core/HyperlaneCore.ts, typescript/sdk/src/hook/EvmHookModule.ts, typescript/sdk/src/hook/EvmHookReader.test.ts, typescript/sdk/src/hook/EvmHookReader.ts
- gracefully handles RPC failures on hook derivation
- TODO:
- ISM derivation
- none
- P1
- manual
=> fix(cli): gracefully handle RPC failures on hook derivation

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: update deployed relayer image

solidity/contracts/avs/ECDSAServiceManagerBase.sol
Creates a fix for a view function an indexer on the EigenLayer side calls into for UI display
None
N/A
Yes
Regression test added in the Eigenlayer repo
=> fix: index for getOperatorRestakeableStrategies

.changeset/gold-bees-greet.md, typescript/cli/src/commands/core.ts
fix(cli): typo in core read command
=> fix(cli): typo in core read command

rust/hyperlane-core/src/chain.rs
=> chore: Reorder variants of `KnownHyperlaneDomain`

typescript/infra/scripts/warp-routes/helm.ts
Update script to use the latest docker image
=> chore(infra): Update warp monitor docker image

.changeset/lazy-steaks-prove.md, .changeset/light-bulldogs-confess.md, typescript/sdk/src/core/HyperlaneCoreChecker.ts, typescript/sdk/src/hook/EvmHookReader.ts, typescript/sdk/src/ism/EvmIsmReader.ts, typescript/sdk/src/ism/metadata/multisig.ts, typescript/sdk/src/token/deploy.ts, typescript/utils/src/validation.ts
- Set errorMessage argument for assert to required
=> feat(utils): Set errorMessage argument for assert to required

typescript/sdk/src/hook/EvmHookReader.ts
- updates hookType error log level
- none
- yes
- none
=> chore(sdk): update hookType error log level

.changeset/grumpy-ads-pump.md, rust/config/mainnet_config.json, typescript/sdk/src/ism/metadata/aggregation.test.ts, typescript/sdk/src/utils/cosmos.ts
- update cosmos chain schema to match latest spec https://github.com/cosmos/chain-registry/blob/c6cfe11be261b20ce5881ea9ba38d855130c22a5/chain.schema.json#L451-L460
- drive-by fixing of agg test
=> fix(sdk): update cosmos chain schema

typescript/infra/config/environments/mainnet3/warp/EZETH-deployments.yaml
- update ezeth warp monitor config
=> feat(infra): update ezeth warp monitor config

typescript/infra/scripts/warp-routes/helm.ts
- Add new warp monitor image tag
=> feat(infra): Add new warp monitor image tag

typescript/infra/config/environments/mainnet3/agent.ts
updates relayer version, sets gas payment enforcement policy back to normal
=> chore: update neutron relayer

.github/workflows/test.yml
For partners / OSS contributors to have an easier time building and testing the env most relevant to them
=> chore: better agent e2e test naming

typescript/sdk/src/deploy/verify/ContractVerifier.ts
- enhances contract verifier logs
- none
- none
- yes
- manual
=> chore(sdk): enhance contract verifier logs

.changeset/lazy-oranges-sing.md, typescript/sdk/src/deploy/EvmModuleDeployer.ts, typescript/sdk/src/deploy/HyperlaneDeployer.ts, typescript/sdk/src/deploy/verify/ContractVerifier.ts, typescript/sdk/src/deploy/verify/types.ts, typescript/sdk/src/deploy/verify/utils.ts
- removes contract verification check
- adds `expectedimplementation` method params for `verifyproxycontract`
- enhances logging and renames variables for clarity
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4123
- yes
- manual
=> fix(sdk): remove contract verification check; add expectedimplementation; enhance logging

typescript/infra/src/govern/HyperlaneAppGovernor.ts
- This is required as some (Zetachain) safe transaction services are flaky
=> feat(infra): support retrying safe proposal transactions

typescript/sdk/scripts/foundry-test.sh, typescript/sdk/src/providers/SmartProvider/SmartProvider.foundry-test.ts
This Re-adds the unit tests commented out in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4201
=> chore(sdk): Add server error unit tests to SmartProvider 

Dockerfile
Fixes missing docker entry from PR #4139
=> fix: Add widgets ref to dockerfile

.changeset/red-rabbits-dress.md, Dockerfile, typescript/cli/src/commands/core.ts, typescript/cli/src/config/core.ts, typescript/cli/src/deploy/core.ts, typescript/sdk/src/core/AbstractHyperlaneModule.ts, typescript/sdk/src/core/EvmCoreModule.hardhat-test.ts, typescript/sdk/src/core/EvmCoreModule.ts, typescript/sdk/src/index.ts, typescript/sdk/src/token/EvmERC20WarpModule.ts
- Adds `hyperlane core apply` to the CLI
- Adds  mailbox transfer ownership to SDK
- https://github.com/hyperlane-xyz/issues/issues/1328
- https://github.com/hyperlane-xyz/issues/issues/1330
Yes
=> feat(sdk,cli): Add hyperlane core apply with mailbox transfer ownership 

.changeset/twenty-nails-hug.md, typescript/cli/src/config/chain.ts
Prompt for chain testnet/mainnet during chain definition flow
Locally
=> feat(cli): Prompt for isTestnet when defining chain

typescript/widgets/package.json
=> fix: widgets package.json

typescript/sdk/CHANGELOG.md
Fix codespell job on main
https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/10256216777/job/28374837670?pr=4256
=> fix: spelling mistake in sdk CHANGELOG

rust/chains/hyperlane-ethereum/src/mailbox.rs, typescript/infra/config/environments/mainnet2/agent.ts
=> Hacky bsc gas price override on v2

.changeset/dirty-cameras-breathe.md, .registryrc, rust/config/mainnet_config.json, typescript/cli/package.json, typescript/helloworld/package.json, typescript/infra/package.json, typescript/widgets/package.json, yarn.lock
chore: update registry to v2.5.0
=> chore: update registry to v2.5.0

typescript/sdk/src/hook/HyperlaneHookDeployer.ts
fix: short-circuit known configs in legacy hook deployer
given we already do the process of recovering the same hooks for each domain, this short-circuits that even further to avoid the extra time taken to try, recover, move-on for each hook
=> fix: short-circuit known configs in legacy hook deployer

.changeset/gorgeous-pans-look.md, typescript/infra/src/govern/HyperlaneAppGovernor.ts, typescript/infra/src/govern/HyperlaneCoreGovernor.ts, typescript/infra/src/govern/ProxiedRouterGovernor.ts, typescript/sdk/src/deploy/HyperlaneAppChecker.ts, typescript/sdk/src/deploy/types.ts, typescript/sdk/src/index.ts
- Support handling proxyAdmin violation, where the proxyAdmin of a proxy contract is not the expected proxyAdmin, `HyperlaneAppGovernor`
- `HyperlaneCoreGovernor` and `ProxiedRouterGovernor` implementation will use it
Manual
=> feat(governor): Support handling proxyAdmin violation in HyperlaneAppGovernor

.changeset/tough-ties-pump.md, typescript/cli/src/utils/chains.ts
Fixes the new chain message to display the correct command
=> fix(cli): incorrect command for new chains

typescript/infra/scripts/generate-renzo-warp-route-config.ts
As requested by @Mo-Hussain to aid deploy checker
=> fix(infra): Sort Renzo validators 

typescript/infra/config/environments/mainnet3/warp/configGetters/getArbitrumNeutronEclipWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/configGetters/getArbitrumNeutronTiaWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumInevmUSDCWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumInevmUSDTWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionUSDCWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/configGetters/getMantapacificNeutronTiaWarpConfig.ts, typescript/infra/fork.sh
- update the warp configs in infra to reflect expected behavior or change behavior
- allow fork script to support passing warp route id
Manual
=> feat(infra): Update warp configs in infra

.changeset/new-turkeys-end.md, typescript/sdk/src/consts/multisigIsm.ts
feat: add stride validators to default multisig
=> feat: add stride validators to default multisig

typescript/infra/scripts/generate-renzo-warp-route-config.ts
Should match default Ism: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/1abefa60e2a1ded528e852d6fbbf0255c4dfdc42/typescript/sdk/src/consts/multisigIsm.ts#L539-L542
=> fix: Update renzo zircuit validator set

typescript/infra/config/environments/mainnet3/warp/EZETH-deployments.yaml, typescript/infra/scripts/warp-routes/helm.ts
- update infra config to include latest renzo warp router addresses
- update the image tag with new build
=> feat(infra): Update renzo warp config in infra used for monitoring

typescript/helloworld/src/deploy/deploy.ts, typescript/infra/scripts/deploy.ts, typescript/infra/src/deployment/testcontracts/testquerysender.ts, typescript/sdk/src/core/HyperlaneCoreDeployer.ts, typescript/sdk/src/core/TestRecipientDeployer.ts, typescript/sdk/src/deploy/HyperlaneProxyFactoryDeployer.ts, typescript/sdk/src/hook/HyperlaneHookDeployer.ts, typescript/sdk/src/middleware/liquidity-layer/LiquidityLayerRouterDeployer.ts, typescript/sdk/src/middleware/query/InterchainQueryDeployer.ts, typescript/sdk/src/token/deploy.ts
resolves https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4350
=> chore: pass concurrentDeploy to more deployers

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/scripts/agent-utils.ts, typescript/infra/scripts/deploy.ts, typescript/infra/scripts/print-balances.ts, typescript/sdk/src/metadata/ChainMetadataManager.ts
resolves https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4349
- feat: script to print balances of important keys
- super useful as a pre-deploy spot check
e.g. on testnet4
=> feat: script to print balances of important keys

rust/chains/hyperlane-cosmos/src/error.rs, rust/chains/hyperlane-cosmos/src/providers/mod.rs
* Add error handling for getting transaction by hash
* Add error handing for extracting contract address
* Extract a method for 
Yes
Cosmos E2E Testing (without invariant for scraper)
=> feat: add error handling and refactoring

typescript/infra/config/environments/mainnet3/owners.ts
- Successfully executed the multisig transaction to transfer things over to the ICA, woo!
=> chore: set inevm owner to ICA

typescript/infra/config/environments/mainnet3/funding.ts
=> chore: update mainnet3 key funder deployment

.changeset/curvy-ligers-drive.md, typescript/sdk/src/deploy/EvmModuleDeployer.ts
fix: add 10% gas bump to initialize call in EvmModuleDeployer
=> fix: add 10% gas bump to initialize call in EvmModuleDeployer

.gitattributes, .github/workflows/agent-release-artifacts.yml, .github/workflows/rust-docker.yml, .github/workflows/test.yml, .husky/pre-commit, rust/Dockerfile, rust/README.md, rust/main/hyperlane-base/src/settings/loader/mod.rs, rust/main/hyperlane-base/tests/chain_config.rs, rust/main/utils/run-locally/src/cosmos/mod.rs, solidity/update_abis.sh, typescript/infra/scripts/funding/fund-keys-from-deployer.ts, typescript/infra/src/config/agent/agent.ts, typescript/infra/src/config/agent/relayer.ts, typescript/sdk/src/ism/metadata/aggregation.ts
fix: docker agent build
- update image from 1.72.1 -> 1.80.1
drive-by: update more `rust/` --> `rust/main/`
drive-by: consolidate e2e non-cosmwasm cache, multiple cache steps per job can get in the way of each other
=> fix: docker agent build

rust/main/chains/hyperlane-ethereum/src/contracts/mailbox.rs, rust/main/chains/hyperlane-ethereum/src/tx.rs
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4239
- I think ideally we'd maybe cache this, but there isn't a super accessible way of doing this atm and we need this ASAP to accommodate Everclear. So personally am happy to take on the extra RPC per transaction and at some point we'll likely want to revisit our tx submission efficiency, plus we end up needing the latest block for eip 1559 estimation anyways
=> fix: cap agent EVM tx limit to the latest block gas limit

.changeset/flat-seals-prove.md, typescript/infra/scripts/check/check-deploy.ts, typescript/infra/scripts/check/check-utils.ts, typescript/infra/scripts/check/check-warp-deploy.ts, typescript/infra/src/govern/HyperlaneAppGovernor.ts, typescript/infra/src/govern/HyperlaneHaasGovernor.ts, typescript/sdk/src/deploy/HyperlaneAppChecker.ts
feat: check-deploy multiple specified chains
- resolves https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4491
=> feat: check-deploy multiple specified chains

typescript/infra/config/environments/mainnet3/owners.ts, typescript/infra/scripts/check/check-owner-ica.ts, typescript/infra/scripts/check/check-rpc-urls.ts, typescript/infra/scripts/check/check-validator-announce.ts, typescript/infra/scripts/print-mailbox-owner.ts
feat: script to check mailbox ownership
drive-by:
- ICA ownership for everclear+oortmainnet
- move check scripts to check dir
mainnet3:
```sh
┌──────────────┬──────────────────────────────────────────────┬────────┐
│ (index)      │ address                                      │ owner  │
├──────────────┼──────────────────────────────────────────────┼────────┤
│ ancient8     │ '0xD2BFA0F0654E3f2139b8cDC56c32eeC54D32b133' │ 'SAFE' │
│ arbitrum     │ '0x03fD5BE9DF85F0017dC7F4DC3068dDF64fffF25e' │ 'SAFE' │
│ astar        │ '0x6b241544eBa7d89B51b72DF85a0342dAa37371Ca' │ 'ICA'  │
│ astarzkevm   │ '0x526c6DAee1175A1A2337E703B63593acb327Dde4' │ 'ICA'  │
│ avalanche    │ '0x5bE94B17112B8F18eA9Ac8e559377B467556a3c3' │ 'SAFE' │
│ base         │ '0x3949eD0CD036D9FF662d97BD7aC1686051c4aeBF' │ 'SAFE' │ …
```
=> feat: infra script for printing mailbox ownership

.changeset/famous-ants-tan.md
This prevents the version from becoming a major update (v6)
=> fix: Reduce proxy PR to minor

.changeset/loud-elephants-reflect.md, typescript/github-proxy/README.md, typescript/github-proxy/src/index.ts
- Adds `recursive=true` query string to the url in github-proxy
=> fix: Add recursive query string

typescript/infra/src/govern/HyperlaneAppGovernor.ts, typescript/infra/src/govern/HyperlaneCoreGovernor.ts, typescript/infra/src/govern/ProxiedRouterGovernor.ts, typescript/infra/src/govern/multisend.ts, typescript/infra/src/utils/safe.ts
resolves https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4493
feat: improve call logging in check-deploy
- refactors inference of call submission types
- more clearly calls out ICA calls
- using `chalk` in more places for easier reading in terminal
drive-by:
- update logging in multisend + safe utils
updated router enrollment logging:
updated ICA call logging:
=> feat: improve call logging in check-deploy

typescript/cli/package.json, typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumEclipseTETHWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumEclipseUSDCWarpConfig.ts, typescript/infra/config/warp.ts, typescript/infra/package.json, typescript/widgets/package.json, yarn.lock
=> feat: SVM routes tooling

typescript/infra/config/environments/mainnet3/warp/checkWarpDeploy.ts
-  use latest image tag for the check-warp-deploy cron job config
Manual
=> feat(infra): use latest image tag for the check-warp-deploy cron job config

typescript/github-proxy/package.json
chore: make github-proxy private
=> chore: make github-proxy private

typescript/infra/config/environments/mainnet3/warp/configGetters/getRenzoEZETHWarpConifg.ts, typescript/infra/helm/warp-routes/templates/_helpers.tpl, typescript/infra/helm/warp-routes/templates/env-var-external-secret.yaml, typescript/infra/helm/warp-routes/values.yaml, typescript/infra/scripts/warp-routes/deploy-warp-monitor.ts, typescript/infra/scripts/warp-routes/monitor-warp-routes-balances.ts, typescript/infra/src/utils/gcloud.ts, typescript/infra/src/warp/helm.ts
- support private RPCs for warp monitor service
Yes
Manual
=> feat(infra): use private RPCs for warp monitor service

rust/sealevel/client/src/warp_route.rs
=> fix: stop transferring metadata and metadata pointer authorities

typescript/infra/config/environments/mainnet3/funding.ts, typescript/infra/scripts/funding/fund-keys-from-deployer.ts
- Accidentally missed this in #4533
=> chore: add SOL ATA payer on eclipsemainnet to funding monitoring

typescript/infra/scripts/agents/deploy-agents.ts
chore: check if HEAD is behind main before deploying agents
=> chore: check if HEAD is behind main before deploying agents

typescript/infra/config/environments/mainnet3/agent.ts
Seems like they have issues with the chain / RPC
=> chore: disable tangle for now

solidity/package.json
The release job is failing
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/9f19cdf469237773ccd42bcbd6bd3c58c56e644f/.github/workflows/release.yml#L40
https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/11224453679/job/31201246396?pr=4617
None
=> fix: hook into version:update for automated release workflow

typescript/infra/config/environments/mainnet3/agent.ts
Deploy Scraper for Injective, Neutron, Osmosis and Sei chains
1. Enable Scraper role for Injective, Neutron, Osmosis and Sei chains in hyperlane context (production)
2. Upgrade Scraper docker image in hyperlane context.
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3356
Yes
Manual scraping locally
=> feat: Deploy Scraper for Injective, Neutron, Osmosis and Sei chains

rust/sealevel/programs/validator-announce/tests/functional.rs
=> fix: sealevel unit tests flake

.github/workflows/test.yml
=> chore: disable sealevel e2e when possible

.changeset/fluffy-ducks-buy.md, typescript/sdk/src/ism/EvmIsmModule.ts, typescript/sdk/src/router/GasRouterDeployer.ts, typescript/sdk/src/router/ProxiedRouterDeployer.ts
This partially fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4657, specifically made to get warp apply to work on Sei
Yes
Manual - deployed
=> fix: Add override to some transactions

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Scraper so that it gracefully handles blocks and transactions which cannot be fetched or parsed.
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4632
Yes
Local E2E Tests
Local testing of Scraper
Image build after successful CI
=> feat: Upgrade Scraper

.github/workflows/codespell.yml
fix: sort out codespell. Try using the official setup python action
na
na
yes?
ci
=> fix: sort out codespell

rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider.rs
Record transaction with non-native fees. Fees will be recorded as a huge number: max value of unsigned 256-bit long integer. 
Yes
Manual testing of Scraper
=> feat: Record transaction with non-native fees

typescript/infra/config/environments/mainnet3/agent.ts
chore: update agents with reorg remediations
replaces https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4685
na
na
yes
👁️
=> chore: update agents with reorg remediations

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/src/config/agent/relayer.ts
=> chore: extend list of blocked addresses on relayer

.changeset/silver-dancers-rhyme.md, typescript/infra/config/environments/mainnet3/warp/warpIds.ts, typescript/infra/config/warp.ts
Updates the warp Ids for latest renzo deployment to sei and taiko used by the checker
=> chore: Update warp Ids for Renzo

typescript/infra/config/environments/mainnet3/funding.ts
Updates the key funder to include the latest polygon tx overrides added by #4682
=> chore: update key funder image

typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumSeiFastUSDWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/warpIds.ts, typescript/infra/config/warp.ts, typescript/infra/src/config/warp.ts
Adds recent fastUSD deploy to our checking infra
=> feat: add FASTUSD/ethereum-sei to checker

typescript/infra/config/environments/mainnet3/warp/EZETH-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/sei-FASTUSD-deployments.yaml, typescript/infra/scripts/warp-routes/monitor-warp-routes-balances.ts
- Support sei-ethereum-FastUSD warp monitor
- Support xERC20 balance metrics
Manual
=> feat(warpMonitor): Add support for sei-FASTUSD warp monitor

typescript/infra/config/environments/mainnet3/warp/bsc-lumia-LUMIA-deployments.yaml
- Support Lumia bsc-lumia-ethereum warp monitor service
Manual
=> feat(warpMonitor): Support Lumia bsc-lumia-ethereum warp monitor service

rust/main/chains/hyperlane-ethereum/src/config.rs, rust/main/chains/hyperlane-ethereum/src/tx.rs
Fix for leftover [comment](https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4629#discussion_r1811084234) from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4629
=> chore(evm): optimize block number fetching

rust/main/config/mainnet_config.json, rust/main/hyperlane-base/src/contract_sync/mod.rs, rust/main/hyperlane-base/src/settings/parser/mod.rs
=> chore: add sleep log in `fetch_logs_with_cursor`

solidity/contracts/isms/aggregation/AbstractAggregationIsm.sol, solidity/contracts/isms/aggregation/StaticAggregationIsm.sol, solidity/contracts/isms/aggregation/StorageAggregationIsm.sol, solidity/contracts/isms/multisig/StorageMultisigIsm.sol, solidity/test/isms/AggregationIsm.t.sol, typescript/sdk/src/ism/HyperlaneIsmFactory.ts, typescript/sdk/src/ism/metadata/aggregation.ts, typescript/sdk/src/ism/types.ts
=> feat: Implement Storage Aggregation ISM

.changeset/early-chicken-develop.md, typescript/cli/package.json, yarn.lock
fix: update cli dependencies
na
https://discord.com/channels/935678348330434570/961710804011458621/1299011251858440324
y
`npm pack`
`npm install -g hyperlane-cli-local.tgz`
=> fix: update cli dependencies

typescript/infra/config/environments/mainnet3/agent.ts
chore: update agent image
infra
=> chore: update agent image

typescript/infra/config/environments/mainnet3/warp/EZETH-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/ancient8-USDC-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/bsc-lumia-LUMIA-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/eclipse-SOL-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/eclipse-USDC-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/eclipse-WIF-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/eclipse-tETH-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/ethereumUSDC-inevm-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/ethereumUSDT-inevm-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/injective-inevm-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/neutron-mantapacific-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/sei-FASTUSD-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/viction-ethereum-ETH-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/viction-ethereum-USDC-deployments.yaml, typescript/infra/config/environments/mainnet3/warp/viction-ethereum-USDT-deployments.yaml, typescript/infra/package.json, typescript/infra/scripts/warp-routes/monitor-warp-routes-balances.ts, typescript/sdk/src/gas/token-prices.ts, typescript/sdk/src/metadata/warpRouteConfig.ts, yarn.lock
- Support continuous value monitoring by allowing promethues to scrape value metrics for native and collateral tokens
- Uses the `CoinGeckoTokenPriceGetter`
- Added `getTokenPriceByIds` helper method to the `CoinGeckoTokenPriceGetter`, to support fetching prices using the coin gecko id only
- Add a warp_route_id label to metrics
Manual
=> feat(warpMonitor): Support collateral value monitoring

typescript/infra/config/environments/mainnet3/warp/STTIA-eclipsestride-deployments.yaml, typescript/infra/src/warp/helm.ts
=> fix: tokenAddress for native sttia

typescript/infra/config/environments/mainnet3/funding.ts, typescript/infra/scripts/funding/fund-keys-from-deployer.ts
Adds TIA and stTIA ATA payer observability
=> feat: add TIA and stTIA ATA payer observability

typescript/sdk/src/consts/multisigIsm.test.ts
Append more test for `multisigIsm.ts`
Add 2 test cases:
- has a valid number of validators for each threshold
- has valid EVM addresses for each validator
=> test: append-more-multisigmIsm-test

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Scraper so that it stores input data for Ethereum transactions
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4778
Yes
Manual run of Scraper with local database
Manual run of Scraper with db restored from production backup
=> feat: Upgrade Scraper so that it stores input data for Ethereum transactions

.changeset/plenty-pens-peel.md, .changeset/proud-horses-smash.md, typescript/widgets/src/chains/ChainSearchMenu.tsx, typescript/widgets/src/components/SearchMenu.tsx, typescript/widgets/src/components/TextInput.tsx, typescript/widgets/src/stories/ChainSearchMenu.stories.tsx
- Updated ChainSearchMenu with improvements mentioned in #4779 
- Update ChainSearchMenu story with stories related to the new changes
No
Fixes #4779
Yes
Manual testing and visual testing with storybook
=> feat(widgets): ChainSearchMenu improvements

typescript/infra/config/environments/mainnet3/agent.ts
Deployed a new relayer to get access to #4693
=> chore: deploy new relayer

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: update relayer image

typescript/infra/src/warp/helm.ts
- Update warp monitor image tag
=> feat(warpMonitor): Update warp monitor image tag

.changeset/new-olives-applaud.md, typescript/sdk/src/hook/EvmHookReader.ts
Speeds up IGP derivation in TS relayer
Yes
Manual
=> feat: use message context in IGP derivation too

.changeset/slimy-cougars-visit.md, typescript/widgets/.eslintrc, typescript/widgets/package.json, yarn.lock
Add react and react hooks eslint rules for better linting in the widgets project
No
Yes
Manual testing
=> chore(widgets): add react and react hooks eslint config

rust/main/chains/hyperlane-sealevel/src/mailbox.rs, rust/main/chains/hyperlane-sealevel/src/transaction.rs, rust/main/chains/hyperlane-sealevel/src/transaction/tests.rs
Scraper populates delivered messages for Sealevel
- Contributes into  https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4301
Yes
Manual run of Scraper
=> feat: Scraper populates delivered messages for Sealevel

.changeset/odd-frogs-move.md
- Forgot to add a changeset here https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4835 - this is the changeset for that PR
=> docs(changeset): add changeset for SDK in previous PR

typescript/cli/src/consts.ts
=> fix: Update MINIMUM_WARP_DEPLOY_GAS

rust/main/agents/scraper/src/agent.rs, rust/main/agents/scraper/src/db/message.rs, rust/main/agents/scraper/src/main.rs, rust/main/agents/scraper/src/store.rs, rust/main/agents/scraper/src/store/deliveries.rs, rust/main/agents/scraper/src/store/dispatches.rs, rust/main/agents/scraper/src/store/payments.rs, rust/main/agents/scraper/src/store/storage.rs, rust/main/hyperlane-base/src/contract_sync/cursors/rate_limited.rs, rust/main/hyperlane-base/src/contract_sync/cursors/sequence_aware/backward.rs, rust/main/hyperlane-base/src/contract_sync/cursors/sequence_aware/forward.rs, rust/main/hyperlane-base/src/contract_sync/cursors/sequence_aware/mod.rs, rust/main/hyperlane-base/src/contract_sync/mod.rs, rust/main/hyperlane-base/src/settings/base.rs, rust/main/hyperlane-core/src/traits/db.rs
Refactor Hyperlane store for Scraper. Just moved source code into submodules.
Yes
E2E test Ethereum and Sealevel
=> refactor: Refactor Hyperlane store for Scraper

.changeset/fluffy-wombats-teach.md, typescript/widgets/package.json, typescript/widgets/src/chains/ChainAddMenu.tsx, typescript/widgets/src/chains/ChainLogo.tsx, typescript/widgets/src/chains/ChainSearchMenu.tsx, typescript/widgets/src/components/ErrorBoundary.tsx, typescript/widgets/src/components/SearchMenu.tsx, typescript/widgets/src/icons/Web.tsx
The linter wasn't previously running on the .tsx files. This fixes the coverage and the issues
Yes
Tested in Warp UI
=> chore: Lint fixes for widgets lib

typescript/infra/scripts/check/check-validator-version.ts, typescript/sdk/src/aws/validator.ts, typescript/utils/src/index.ts, typescript/utils/src/types.ts
feat: script to check versions of default validators
also prints age of the commit for mismatched validators
update s3 validator to return `metadata_latest.json`
na
ye
manual
=> feat: script to check versions of default validators

typescript/infra/config/environments/mainnet3/agent.ts
Scraper becomes aware of new field `sequence` in `delivered_message` table. 
Yes
Manual
=> feat: Upgrade Scraper to latest

rust/main/agents/scraper/migration/src/m20230309_000004_create_table_gas_payment.rs, rust/main/agents/scraper/src/agent.rs, rust/main/agents/scraper/src/db/generated/gas_payment.rs, rust/main/agents/scraper/src/db/payment.rs, rust/main/agents/scraper/src/store/payments.rs, rust/main/agents/scraper/src/store/storage.rs
Store origin, destination, interchain_gas_paymaster and sequence on gas payment
Yes (after the fields are added to database schema)
E2E Ethereum and Sealevel tests (for no regressions).
=> feat: Store origin, destination, interchain_gas_paymaster and sequence on gas payment

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Scraper: Store origin, destination, interchain_gas_paymaster and sequence
- Contributes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4271
Yes
E2E Ethereum and Sealevel test (no regression)
=> feat: Upgrade Scraper: Store origin, destination, interchain_gas_paymaster and sequence

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: use escalator image

typescript/infra/config/environments/mainnet3/funding.ts, typescript/infra/scripts/funding/fund-keys-from-deployer.ts
chore: add timeouts to keyfunder
little refactoring of ContextFunder for breaking up the funding task + improving error handling
=> feat: add timeouts to keyfunder

rust/main/agents/scraper/src/db/payment.rs, rust/main/agents/scraper/src/store/payments.rs
Add logging to store payments
- Contributes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4271
Yes
Manual
=> fix: Add logging

rust/main/agents/scraper/src/agent.rs
Add logging to figure out Scraper startup time
Yes
Manual
=> fix: Add logging to figure out Scraper startup time

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: bump relayer image

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: request more memory for the relayer pod

rust/main/chains/hyperlane-ethereum/src/tx.rs, typescript/cli/src/commands/core.ts, typescript/cli/src/send/message.ts
Remove redundant words in comment
=> chore: remove redundant words in comment

rust/main/agents/relayer/src/msg/processor.rs
Noticed that the iteration logic doesn't actually prioritize higher nonces. See these example logs https://cloudlogging.app.goo.gl/CAosszzjFzi3uNJM6 when I sent a message right after a relayer restart -- it wouldn't move forward on the high iterator despite there being an unprocessable message on the high iterator, as it was preferring to iterate the low nonce iter through all the processed messages (down to nonce 0). This meant it took a really long time for my message to get relayed!
With this new logic, we should see upon startup we actually do prioritize new messages, not just high nonce messages from before the time of restart.
Would also be open to maybe moving forward the low and high iter at the same time, but that is a bigger change so I'll leave it like this for now
=> fix: prioritize higher nonces in the message processor

typescript/infra/config/environments/mainnet3/warp/warpIds.ts
Add MAGIC/arbitrum-treasure to WarpRouteIds
=> feat(warpRoutes): Add MAGIC/arbitrum-treasure to WarpRouteIds

rust/main/chains/hyperlane-ethereum/src/tx.rs
=> chore: multiply gas price for treasuretopaz too

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/config/environments/testnet4/agent.ts
=> chore: treasure fix relayer images

typescript/sdk/src/router/HyperlaneRouterChecker.ts
Fixes hook checker in Infra
Yes
Manual
=> chore: Fix Checker for hooks

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: bump relayer memory to 20gb

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/config/environments/testnet4/agent.ts
=> chore: zksync fix images

typescript/infra/scripts/warp-routes/monitor/monitor-warp-route-balances.ts
- handle zero balance appropriately in warp monitor 
Manual
=> fix(warpMonitor): Handle zero balance for warp routers

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/config/environments/testnet4/agent.ts
to include the operation status metric fix from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5002
=> chore: update relayer images

typescript/infra/scripts/check/check-validator-version.ts
chore: update Tessellated validator version
=> chore: update Tessellated validator version

typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumSeiFastUSDWarpConfig.ts
- Update FastUSD/ethereum-sei collateral router owner
Manual
=> feat(warpConfig): Update FastUSD/ethereum-sei collateral router owner

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: add undeliverable message to blacklist

rust/main/chains/hyperlane-sealevel/src/rpc/client.rs
=> chore: log simulation result at `error` level if it failed

.github/workflows/test.yml, typescript/cli/src/tests/commands/helpers.ts, typescript/cli/src/tests/commands/warp.ts, typescript/cli/src/tests/warp-init.e2e-test.ts
Adds e2e tests for the `warp init` command
- 
- 
- YES
- E2E
=> test: cli e2e warp init command tests

typescript/infra/config/environments/mainnet3/agent.ts
=> feat: RELAYER UPDATE - update hyperlane,neutron context to tag `234704d-20241226-192528`

typescript/infra/config/environments/mainnet3/funding.ts
- Set Morph desired balance to 0.1
=> chore(funding): Set Morph desired balance to 0.1

rust/main/config/mainnet_config.json, typescript/infra/config/environments/mainnet3/chains.ts
=> feat: remove polygon tx overrides

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: new relayer image

typescript/infra/config/environments/mainnet3/aw-validators/rc.json, typescript/infra/config/environments/mainnet3/validators.ts
Add injective validator to RC
Sorted entries into `rc.json` alphabetically.
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5113
Yes
Tested in RC
=> feat: Add injective validator to RC

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Validators and Scraper to latest version
- Fixes [#[issue number here]](https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5113)
Yes
Change was tested in RC
=> feat: Upgrade Validators and Scraper to latest version

typescript/infra/config/environments/mainnet3/agent.ts
To include the changes from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5100
=> chore: new relayer images

rust/sealevel/environments/mainnet3/warp-routes/ART-artela-base-solana/token-config.json
=> feat: Add Art token-config

rust/main/Cargo.lock, rust/main/agents/relayer/src/main.rs, rust/main/agents/relayer/src/relayer.rs, rust/main/agents/scraper/src/main.rs, rust/main/agents/validator/src/main.rs, rust/main/agents/validator/src/validator.rs, rust/main/hyperlane-base/src/agent.rs, rust/main/hyperlane-base/src/contract_sync/mod.rs
Add logging to agents
* When an agent start
* When cursor indexing task is exiting
* When cursor sync method is exiting
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5098
Yes
E2E tests
=> feat: Add logging to agents

.github/workflows/test.yml, typescript/infra/src/config/chain.ts
- Add private RPCs for Ethereum and Sepolia env-tests
- Support automatic retries for failed env-tests
Manual
=> feat(CI): Use private RPCs for Ethereum and Sepolia env-tests

.changeset/many-llamas-count.md, typescript/infra/config/environments/mainnet3/warp/configGetters/getArbitrumBaseBlastBscEthereumGnosisMantleModeOptimismPolygonScrollZeroNetworkZoraMainnetETHWarpConfig.ts
Updates the zero ETH config getter to reflect updated ownership
- NO
- 
- YES
- Manual
=> fix: update zero eth route config getter

typescript/infra/config/environments/mainnet3/agent.ts
- updated image tag to `62702d3-20250121-002648` to update cursor_max_sequence behavior from #5178 
None
None
Yes
Deployment
=> feat(release): relayer updated to #5065

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade validators to latest version
Yes
Manual
=> feat(release): Upgrade validators to latest version

rust/main/agents/relayer/src/msg/metadata/base.rs, rust/main/agents/relayer/src/msg/metadata/multisig/base.rs, rust/main/hyperlane-base/src/types/multisig.rs
Add logs into relayer so than it logs validator and their store location for checkpoints
Yes
Running locally
=> feat: Add logs for validator checkpoints in relayer

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: blacklist malformed warp recipient msg

solidity/core-utils/zksync/buildArtifact.ts
Reverts hyperlane-xyz/hyperlane-monorepo#5269
=> revert: "fix: zksync default build artifact"

typescript/infra/config/environments/mainnet3/agent.ts
chore: update relayer image + increase memory
=> chore: update relayer image + increase memory

tools/grafana/validator-dashboard-template.json
Update Validator Dashboard (External Sharing Template) dashboard file
Yes
E2E test in CI
=> feat(doc): Update Validator Dashboard (External Sharing Template) dashboard file

rust/sealevel/environments/mainnet3/gas-oracle-configs.json, typescript/infra/config/environments/mainnet3/gasPrices.json, typescript/infra/src/config/gas-oracle.ts
- Base and OP cut in half
- Lower the ethereum gas price
=> feat: lower some IGP quotes

rust/sealevel/environments/mainnet3/gas-oracle-configs.json, typescript/infra/config/environments/mainnet3/gasPrices.json, typescript/infra/scripts/sealevel-helpers/print-gas-oracles.ts, typescript/infra/src/config/gas-oracle.ts
- lower to Solana, lower to Ethereum
- A little bit of wrangling due to #5339 not being merged yet
=> chore: update IGP quotes

typescript/infra/scripts/check/check-warp-deploy.ts
fix: temporarily skip check-deploy for decent route
=> fix: temporarily skip check-deploy for decent route

.gitleaks.toml, .husky/pre-commit, README.md
Add [gitleaks](https://github.com/gitleaks/gitleaks) to pre-commit hook with custom patterns for known RPC providers.
Note, this will require every contributor to have `gitleaks` installed on their machine akin to `yq` or `jq`.
example of success:
```
git commit -m "feat: use gitleaks in pre-commit"
🔍 Checking for potential secrets in staged files...
○
│╲
│ ○
○ ░
░    gitleaks
2:47PM INF 1 commits scanned.
2:47PM INF scanned ~2224 bytes (2.22 KB) in 9.89ms
2:47PM INF no leaks found
✅ No secrets detected
gs→ No staged files match any configured task.
📝 If you haven't yet, please add a changeset for your changes via 'yarn changeset'
[pb/gitleaks 1b06f7376] feat: use gitleaks in pre-commit
2 files changed, 98 insertions(+)
create mode 100644 .gitleaks.toml
```
example of failure if we're …
=> feat: use gitleaks in pre-commit hook

typescript/cli/package.json, typescript/helloworld/package.json, typescript/infra/config/environments/mainnet3/warp/configGetters/getRenzoEZETHSTAGEWarpConfig.ts, typescript/infra/package.json, typescript/widgets/package.json, yarn.lock
This PR updates the Unichain owner to a Safe address for Stage
=> chore: Update EZETHSTAGE uni owner to safe

typescript/infra/config/environments/mainnet3/warp/configGetters/getRenzoPZETHSTAGEWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/configGetters/getRenzoPZETHWarpConfig.ts
This PR adds the PZETHSTAGE getter with respective xERC20 addresses. Most of the other values inherit from PZETH
=> feat: update pzethstage getter

typescript/infra/config/environments/mainnet3/warp/configGetters/getRenzoEZETHSTAGEWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/configGetters/getRenzoEZETHWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/configGetters/getRenzoPZETHSTAGEWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/configGetters/getRenzoPZETHWarpConfig.ts, typescript/infra/config/environments/mainnet3/warp/warpIds.ts, typescript/sdk/src/token/EvmERC20WarpModule.ts
This PR parameterizes the pzeth getter to allow for PZETH Stage
Yes
`yarn tsx ./scripts/warp-routes/export-warp-configs.ts -e mainnet3` with no diffs
=> feat: update pzeth getter to allow for staging

rust/main/config/mainnet_config.json, typescript/infra/config/environments/mainnet3/agent.ts
Deploys all relayers to include #5468
=> feat: deploy relayer with new backoff

rust/main/chains/hyperlane-sealevel/src/mailbox.rs, rust/main/chains/hyperlane-sealevel/src/utils.rs, typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/config/environments/mainnet3/warp/warpIds.ts
Context here: https://github.com/hyperlane-xyz/issues/issues/1423
=> feat: prevent signers in dynamically fetched AccountMetas in the relayer

typescript/sdk/src/ism/EvmIsmReader.ts, typescript/sdk/src/token/checker.ts
Minor fixes to make the infra warp checker work with the xerc20 derivation
=> Minor deploy fixes

typescript/cli/src/deploy/warp.ts, typescript/sdk/src/index.ts
Fix persisting the collateral token when it is an xerc20 token
=> feat: Fix collateral config persistence

typescript/sdk/src/index.ts
=> fix(sdk): fix duplicated import

typescript/infra/config/environments/mainnet3/agent.ts
chore: update hyperlane context relayer
- ensures we have the latest chain deployments running on `hyperlane` context
=> chore: update hyperlane context relayer

typescript/infra/scripts/xerc20/xerc20vs-add-bridge.ts, typescript/infra/scripts/xerc20/xerc20vs-set-limits.ts, typescript/infra/src/xerc20/utils.ts, typescript/sdk/src/index.ts, typescript/sdk/src/token/EvmERC20WarpRouteReader.ts, typescript/sdk/src/token/adapters/EvmTokenAdapter.ts, typescript/sdk/src/token/adapters/ITokenAdapter.ts, typescript/sdk/src/token/types.ts
- Support adding bridges and setting limits for additional limits
Manual
=> feat(limits): Support additionalLockbox limits setting

typescript/infra/src/warp/helm.ts
=> chore(monitor): Update warp monitor image

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Scraper to fix backward cursor metrics. Image: e8851ae-20250227-210423
Yes
None
=> chore: Upgrade Scraper to fix backward cursor metrics

typescript/infra/scripts/funding/calculate-relayer-daily-burn.ts, typescript/infra/scripts/funding/write-alert.ts, typescript/infra/src/config/funding/grafanaAlerts.ts, typescript/infra/src/funding/alerts.ts, typescript/infra/src/infrastructure/monitoring/grafana.ts, typescript/infra/src/infrastructure/monitoring/prometheus.ts
- removes changes that were accidentally pushed to the wrong branch before the PR was merged
- This reverted change was PR'd and put of for review, will put it through a review cycle again
=> fix: revert uninteded commit

typescript/infra/scripts/funding/calculate-relayer-daily-burn.ts, typescript/infra/scripts/funding/write-alert.ts, typescript/infra/src/config/funding/grafanaAlerts.ts, typescript/infra/src/funding/alerts.ts, typescript/infra/src/infrastructure/monitoring/grafana.ts, typescript/infra/src/infrastructure/monitoring/prometheus.ts
- Updates the write alert scripts with helpful prompts and general QoL improvements
- Checks if the proposed change introduces a regression i.e remove a chain from the existing alert, logs an error and aborts
- Read the actual alert threshold via grafana api, compares with proposed thresholds, prompts the user to confirm that they want to introduce these changes
- Check if proposed update will lead to alert firing and prompts the user to confirm with these changes 
Manual
=> feat(balances): Update write alert scripts with helpul prompts

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/config/environments/testnet4/agent.ts
Deploy fixes for how Scraper calculates recipient for complex transactions on Sealevel
- Fixes https://github.com/hyperlane-xyz/issues/issues/1432
Yes
Unit and E2E tests
=> chore: Upgrade Scraper to af7146e-20250314-172005

rust/Dockerfile
=> fix: agent docker build

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: release new relayer image to hyperlane and rc

.husky/pre-commit
Notifies the user that maybe they need to run `yarn install`
yes
=> feat: add message to tell user to yarn install when husky is missing

rust/main/chains/hyperlane-sealevel/src/metric/prometheus_sender.rs
Currently we are using Sealevel RPC client with the default timeout which is 30 seconds. Some of our Sealevel RPC providers take more time to return a response and the client times out. It is especially relevant for historical node on Eclipse mainnet where we see timeouts with an RPC provider.
This change makes the timeout configurable via environment variable SEALEVEL_RPC_CLIENT_ELEVATED_TIMEOUT_SECONDS so that we can change the timeout without rebuilding the binary. The configuration impacts all Sealevel chains.
Timeouts on Eclipse mainnet RPC provider which we use for Scraper and historical data.
Yes.
If the environment variable is not configured, the current default timeout will be used.
Manual
=> fix: Make Sealevel RPC client timeout configurable

rust/sealevel/environments/mainnet3/warp-routes/USDC-arbitrum-base-ethereum-ink-optimism-solanamainnet-superseed/token-config.json, typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumSuperseedUSDCWarpConfig.ts
This PR updates the Superseed USDC owners to Superseed multisigs for both evm and svm
=> chore: transfer ownership superseed USDC

typescript/infra/config/environments/mainnet3/balances/dailyRelayerBurn.json, typescript/infra/config/environments/mainnet3/balances/desiredRelayerBalanceOverrides.json, typescript/infra/config/environments/mainnet3/balances/desiredRelayerBalances.json, typescript/infra/scripts/funding/write-alert.ts
- Support dry run
- Allow writing alerts when we are removing a chain e.g. Astarzkevm
- Show row in diff table when removing chains
- remove references to Astarzkevm in threshold configs
Manual
=> feat: QoL improvements to write alerts script

.changeset/stupid-feet-bathe.md, typescript/widgets/src/index.ts, typescript/widgets/src/logos/Binance.tsx, typescript/widgets/src/walletIntegrations/WalletLogo.tsx
Add BinanceLogo component to the WalletLogo component, for [this](https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/486) 
No
Yes
Local Warp Template UI
=> feat(widgets): add BinanceLogo to WalletLogo component

rust/main/agents/relayer/src/relayer.rs
Add logs to measure init and start time for various entities in relayer. It will be used as a starting point for measurement of improvement we introduce into relayer startup time.
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5748
Yes
Manual
=> fix: Add logs to measure init and start time for various entities in relayer

.changeset/lemon-starfishes-join.md, typescript/widgets/src/starknetkit.d.ts, typescript/widgets/src/walletIntegrations/starknet.ts, typescript/widgets/tsconfig.json
Fix starknetkit compatibility by reverting to default module resolution and introducing module declaration for starknetkit.
- Add proper type declarations via dedicated .d.ts file for starknetkit
None
Yes
Manual
=> fix: Revert bundler module resolution and update starknetkit imports

rust/main/utils/run-locally/src/cosmosnative/cli.rs
=> fix(cosmosnative): try increasing e2e sleep periods

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/config/environments/testnet4/agent.ts
=> chore: deploy relayers with metadata build metrics

solidity/coverage.sh, typescript/infra/config/environments/mainnet3/agent.ts
=> fix: release new relayer

typescript/infra/config/environments/mainnet3/funding.ts, typescript/infra/config/environments/testnet4/funding.ts, typescript/infra/helm/key-funder/templates/cron-job.yaml, typescript/infra/helm/key-funder/values.yaml, typescript/infra/scripts/funding/fund-keys-from-deployer.ts, typescript/infra/src/config/funding.ts, typescript/infra/src/funding/key-funder.ts
feat(keyfunder): allow explicit skipping of chains
- update config with `chainsToSkip`
applied to testnet4 keyfunder to skip hyperevm testnet
=> feat(keyfunder): allow explicit skipping of chains

typescript/infra/scripts/check/check-safe-signers.ts, typescript/infra/scripts/safes/governance/check-safe-signers.ts, typescript/infra/src/utils/safe.ts
- support safe config checking
Manual
=> feat: add safe config checking

rust/main/chains/hyperlane-ethereum/src/tx.rs
=> chore: log eip1559 price estimation error

typescript/infra/config/environments/mainnet3/agent.ts
=> fix: zeronetwork igp check

typescript/infra/src/utils/safe.ts
- support exclusively changing the threshold in `updateSafeOwner`
Manual
=> feat: support changing the threshold

typescript/infra/config/environments/mainnet3/governance/signers/regular.ts
- update the threshold for regular safes
=> feat: update regular safe threshold

rust/main/Cargo.lock, rust/main/Cargo.toml
uses new escalator that checks onchain gas price before escalating
https://github.com/hyperlane-xyz/ethers-rs/pull/37
=> feat: escalator gas syncing

rust/main/agents/relayer/src/msg/op_batch.rs, rust/main/agents/relayer/src/msg/op_submitter.rs, rust/main/agents/relayer/src/msg/processor.rs, rust/main/agents/relayer/src/relayer.rs, rust/main/agents/scraper/src/agent.rs, rust/main/chains/hyperlane-cosmos-native/src/trait_builder.rs, rust/main/chains/hyperlane-cosmos/src/providers/grpc/tests.rs, rust/main/chains/hyperlane-cosmos/src/trait_builder.rs, rust/main/chains/hyperlane-ethereum/src/config.rs, rust/main/chains/hyperlane-ethereum/src/contracts/mailbox.rs, rust/main/chains/hyperlane-ethereum/src/contracts/multicall.rs, rust/main/chains/hyperlane-sealevel/src/trait_builder.rs, rust/main/hyperlane-base/src/settings/chains.rs, rust/main/hyperlane-base/src/settings/parser/connection_parser.rs, rust/main/hyperlane-base/src/settings/parser/mod.rs, rust/main/hyperlane-core/src/config/mod.rs, rust/main/submitter/src/chain_tx_adapter/chains/sealevel/adapter.rs, rust/main/submitter/src/chain_tx_adapter/chains/sealevel/adapter/tests/config.rs
=> feat: chain-specific maxsubmitqueues

typescript/infra/config/environments/mainnet3/warp/warpIds.ts, typescript/infra/src/warp/helm.ts
- add Hyper/stHYPER warp route ids for monitoring, update monitor image
Manual
=> feat: add hyper warp ids and update monitor image

.changeset/config.json
Reverts hyperlane-xyz/hyperlane-monorepo#5827
=> revert: "chore: update cosmos package versions only when there are changes"

typescript/infra/config/environments/mainnet3/warp/warpIds.ts
=> fix: rm old warp route id

rust/main/agents/relayer/src/msg/op_submitter.rs, rust/main/agents/relayer/src/msg/pending_message.rs, rust/main/agents/relayer/src/msg/processor.rs, rust/main/agents/validator/src/submit.rs, rust/main/hyperlane-base/src/db/mod.rs, rust/main/hyperlane-base/src/db/rocks/hyperlane_db.rs, rust/main/hyperlane-core/src/traits/encode.rs, rust/main/hyperlane-core/src/traits/pending_operation.rs
* Store all payload ids for message id
* Store as a vector
* Extend the vector with new payload ids
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5892
Yes
Unit test for encoding/decoding
=> feat: Store all payload ids for message id

typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
=> fix: Refactor startRebalancerAndExpectLog

.gitleaks.toml
Add rule for CryptoCrew
Yes
Manual, locally
=> fix: Add rule for CryptoCrew

rust/main/agents/relayer/src/msg/op_queue.rs, rust/main/agents/relayer/src/msg/op_submitter.rs, rust/main/agents/relayer/src/msg/pending_message.rs, rust/main/chains/hyperlane-cosmos-native/src/mailbox.rs, rust/main/chains/hyperlane-cosmos/src/mailbox/contract.rs, rust/main/chains/hyperlane-ethereum/src/contracts/mailbox.rs, rust/main/chains/hyperlane-ethereum/src/rpc_clients/provider.rs, rust/main/chains/hyperlane-fuel/src/mailbox.rs, rust/main/chains/hyperlane-sealevel/src/mailbox.rs, rust/main/hyperlane-core/src/traits/mailbox.rs, rust/main/hyperlane-core/src/traits/pending_operation.rs, rust/main/hyperlane-core/src/traits/pending_operation/tests.rs, rust/main/hyperlane-test/src/mocks/mailbox.rs, rust/main/submitter/src/chain_tx_adapter/adapter.rs, rust/main/submitter/src/chain_tx_adapter/chains/cosmos.rs, rust/main/submitter/src/chain_tx_adapter/chains/ethereum/adapter.rs, rust/main/submitter/src/chain_tx_adapter/chains/ethereum/payload.rs, rust/main/submitter/src/chain_tx_adapter/chains/ethereum/payload/parse.rs, rust/main/submitter/src/chain_tx_adapter/chains/ethereum/precursor.rs, rust/main/submitter/src/chain_tx_adapter/chains/sealevel/adapter.rs, rust/main/submitter/src/payload/types.rs
- Generate contract calls to check if a particular message was delivered
- Populate payload success criteria with serialized contract calls
- Check if success criteria is met at finality stage of Lander
Yes
None
=> feat(submitter): Report reverted payload with success criteria

.changeset/upset-humans-spend.md, typescript/cli/package.json, typescript/helloworld/package.json, typescript/infra/package.json, typescript/infra/src/warp/helm.ts, typescript/widgets/package.json, yarn.lock
Update registry version to 15.0.0
=> chore: bump registry to 15.0.0 and update monitor image

.gitleaks.toml, typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Relayer and Scraper to latest
- Update leak configuration
Yes
None
=> chore: Upgrade Relayer and Scraper to latest

typescript/sdk/src/core/EvmCoreModule.hardhat-test.ts, typescript/sdk/src/core/EvmCoreModule.ts, typescript/sdk/src/core/EvmIcaModule.hardhat-test.ts, typescript/sdk/src/core/types.ts, typescript/sdk/src/index.ts, typescript/sdk/src/ism/EvmIsmModule.hardhat-test.ts, typescript/sdk/src/ism/EvmIsmReader.ts, typescript/sdk/src/ism/HyperlaneIsmFactory.ts, typescript/sdk/src/ism/metadata/builder.ts, typescript/sdk/src/ism/metadata/routing.ts, typescript/sdk/src/ism/types.ts, typescript/sdk/src/ism/utils.ts, typescript/sdk/src/middleware/account/InterchainAccountChecker.ts, typescript/sdk/src/middleware/account/InterchainAccountDeployer.ts, typescript/sdk/src/middleware/account/contracts.ts
=> fix: SDK for ICA Router deploys without ISMs

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Relayer RC and Neutron to latest
Yes
Sync with Hyperlane context
=> chore: Upgrade Relayer RC and Neutron to latest

rust/main/Cargo.lock, rust/main/chains/hyperlane-ethereum/src/rpc_clients/provider.rs, rust/main/submitter/Cargo.toml, rust/main/submitter/src/chain_tx_adapter/chains/ethereum/adapter.rs, rust/main/submitter/src/chain_tx_adapter/chains/ethereum/adapter/gas_limit_estimator.rs, rust/main/submitter/src/chain_tx_adapter/chains/ethereum/adapter/gas_price_estimator.rs
=> feat: basic evm gas price estimator

rust/main/hyperlane-base/src/settings/loader/mod.rs, rust/main/utils/run-locally/src/main.rs
Retry on getting Relayer balance in E2E since Relayer may not be started yet
Yes
Ethereum E2E locally
=> fix: Retry on getting Relayer balance in E2E since Relayer may not be started yet

rust/sealevel/environments/mainnet3/gas-oracle-configs.json, typescript/infra/scripts/sealevel-helpers/print-gas-oracles.ts
feat: update svm gas oracles
interconnect svmbnb<>soon<>solana<>bsc
=> feat: update svm gas oracles

typescript/cli/src/rebalancer/config/Config.ts, typescript/cli/src/rebalancer/executor/Executor.ts, typescript/cli/src/rebalancer/factories/RebalancerContextFactory.ts, typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/57
=> feat: Min bridge transfer amount threshold

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: resume relayer with reorg failsafe; trial new submitter on linea

typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts, typescript/sdk/src/token/adapters/EvmTokenAdapter.ts
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/54
=> fix: Test e2e with warp bridge

starknet/Dockerfile, starknet/README.md, starknet/compose.yaml
This PR enables the generation of the contract files by building them from source inside a docker container. This speeds up development by allowing the developers to use any starknet contracts release by just specyfing the version.
-
-
Yes
Manual
=> chore: added release generation

typescript/cli/src/rebalancer/config/Config.test.ts, typescript/cli/src/rebalancer/config/Config.ts, typescript/cli/src/rebalancer/executor/WithSemaphore.test.ts, typescript/cli/src/rebalancer/executor/WithSemaphore.ts, typescript/cli/src/rebalancer/factories/RebalancerContextFactory.ts, typescript/cli/src/rebalancer/strategy/StrategyFactory.test.ts, typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/53
=> fix: Semaphore

rust/sealevel/environments/mainnet3/gas-oracle-configs.json, typescript/infra/scripts/sealevel-helpers/print-gas-oracles.ts
Updates the solana igp config to add abstract
no
=> chore: update svm igp config

solidity/contracts/mock/MockValueTransferBridge.sol, typescript/cli/src/rebalancer/config/Config.ts, typescript/cli/src/rebalancer/executor/Executor.ts, typescript/cli/src/rebalancer/factories/RebalancerContextFactory.ts, typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts, typescript/sdk/src/token/adapters/EvmTokenAdapter.ts
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/60
=> fix: Fix quote for rebalance transactions

.changeset/better-carrots-tell.md, typescript/sdk/src/core/CosmosNativeCoreModule.ts, typescript/sdk/src/core/CosmosNativeCoreReader.ts, typescript/sdk/src/index.ts
This PR implements and adds the Cosmos Native Core Reader and Module.
Note that this is the fourth PR of https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/6050 which is being split up in order to make it easier to review
-
-
Yes
Manual Tests
=> chore: add cosmos core module & reader

rust/sealevel/environments/mainnet3/gas-oracle-configs.json, typescript/infra/scripts/sealevel-helpers/print-gas-oracles.ts
feat: add apechain to solana igp
- tidied up ordering of igp connected chains
see the output file
=> feat: add apechain to solana igp

rust/sealevel/environments/mainnet3/warp-routes/MIRAI-abstract-bsc-solanamainnet/program-ids.json, rust/sealevel/environments/mainnet3/warp-routes/MIRAI-abstract-bsc-solanamainnet/token-config.json
Add `MIRAI/abstract-bsc-solanamainnet` token config and program IDs.
N/A
Yes
N/A
=> chore: add `MIRAI/abstract-bsc-solanamainnet`

typescript/cli/src/rebalancer/README.md
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/58
=> fix: Add rebalancer readme

rust/sealevel/environments/mainnet3/warp-routes/USDC-base-ethereum-solana-subtensor/program-ids.json, rust/sealevel/environments/mainnet3/warp-routes/USDC-base-ethereum-solana-subtensor/token-config.json
This PR adds USDC to subtensor
checker
=> feat: subtensor USDC

solidity/contracts/interfaces/ITokenBridge.sol, solidity/contracts/token/HypERC20.sol, solidity/contracts/token/HypERC20Collateral.sol, solidity/contracts/token/HypNative.sol, solidity/contracts/token/TokenBridgeCctp.sol, solidity/contracts/token/extensions/OPL2ToL1TokenBridgeNative.sol, solidity/contracts/token/libs/TokenMessage.sol, solidity/contracts/token/libs/TokenRouter.sol, solidity/test/AmountRouting.t.sol, solidity/test/token/HypERC20MovableCollateral.t.sol, solidity/test/token/OPL2ToL1TokenBridgeNative.t.sol, solidity/test/token/TokenBridgeCctp.t.sol
- TokenRouter implements ITokenBridge
- HypERC20Collateral returns token approval in quote transfer remote
- Fixes Op token bridge inheritance tree
- Fixes broken fuzz test
Yes
Unit Tests
=> feat: implement token bridge for all warp routes

.changeset/fifty-news-taste.md, solidity/contracts/middleware/InterchainAccountRouter.sol, solidity/contracts/middleware/libs/InterchainAccountMessage.sol, solidity/test/InterchainAccountRouter.t.sol
- Adds an event emission with commitment
- Removes redundant call remote event
- Add salt to existing event emission
Unit Tests
=> feat: emit event for ICA commitment

typescript/sdk/src/middleware/account/InterchainAccountDeployer.ts
This is just a provisional fix to fix the build issues on the audit branch
=> fix: build for now

solidity/storage.sh
=> fix: storage diff-check

.github/workflows/test.yml
- Add warp-rebalancer to the e2e matrix
=> fix: Run rebalancer e2e in gh actions

typescript/infra/scripts/funding/calculate-relayer-daily-burn.ts
require ssl for connection
Manual
=> fix: require ssl for connection

rust/main/Cargo.lock, rust/main/Cargo.toml
Applies changes from https://github.com/hyperlane-xyz/ethers-rs/pull/35 - tested on Base and we now pay 80x less
=> fix: priority gas price overpayments

typescript/infra/src/warp/helm.ts
- update monitor image to include new token standard handling
=> chore: update monitor image to include new token standard handling

typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
This is a temp change to debug something on CI
=> fix: Log metrics test

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Scraper to 197fd87-20250521-144619.
Yes
Tested in hyperlane
=> chore: Upgrade Scraper to latest

typescript/cli/src/commands/warp.ts, typescript/cli/src/rebalancer/README.md, typescript/cli/src/rebalancer/config/Config.test.ts, typescript/cli/src/rebalancer/config/Config.ts, typescript/cli/src/rebalancer/executor/Executor.ts, typescript/cli/src/rebalancer/executor/WithSemaphore.test.ts, typescript/cli/src/rebalancer/executor/WithSemaphore.ts, typescript/cli/src/rebalancer/interfaces/IMonitor.ts, typescript/cli/src/rebalancer/interfaces/IStrategy.ts, typescript/cli/src/rebalancer/monitor/Monitor.ts, typescript/cli/src/rebalancer/strategy/BaseStrategy.ts, typescript/cli/src/rebalancer/strategy/MinAmountStrategy.test.ts, typescript/cli/src/rebalancer/strategy/StrategyFactory.test.ts, typescript/cli/src/rebalancer/strategy/StrategyFactory.ts, typescript/cli/src/rebalancer/strategy/WeightedStrategy.test.ts, typescript/cli/src/tests/commands/helpers.ts, typescript/cli/src/tests/commands/warp.ts, typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
=> feat(rebalancer): #6044 feedback - 1st iteration

typescript/cli/src/rebalancer/executor/Executor.ts, typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
Ensures transaction refers to the corresponding route.
Also, udpated messages with route information and amounts expressed in decimal values.
=> fix(Executor): #6044 feedback - transaction/route references

typescript/cli/src/rebalancer/README.md, typescript/cli/src/rebalancer/config/Config.test.ts, typescript/cli/src/rebalancer/config/Config.ts, typescript/cli/src/rebalancer/executor/Executor.ts, typescript/cli/src/rebalancer/strategy/MinAmountStrategy.test.ts, typescript/cli/src/rebalancer/strategy/MinAmountStrategy.ts, typescript/cli/src/rebalancer/strategy/StrategyFactory.test.ts, typescript/cli/src/rebalancer/strategy/StrategyFactory.ts, typescript/cli/src/rebalancer/strategy/WeightedStrategy.test.ts, typescript/cli/src/rebalancer/strategy/WeightedStrategy.ts, typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
=> feat(rebalancer): #6044 feedback - group strategies

typescript/cli/src/rebalancer/README.md, typescript/cli/src/rebalancer/config/Config.test.ts, typescript/cli/src/rebalancer/config/Config.ts, typescript/cli/src/rebalancer/executor/Executor.ts, typescript/cli/src/rebalancer/factories/RebalancerContextFactory.ts, typescript/cli/src/rebalancer/strategy/MinAmountStrategy.test.ts, typescript/cli/src/rebalancer/strategy/MinAmountStrategy.ts, typescript/cli/src/rebalancer/strategy/StrategyFactory.test.ts, typescript/cli/src/rebalancer/strategy/StrategyFactory.ts, typescript/cli/src/rebalancer/strategy/WeightedStrategy.test.ts, typescript/cli/src/rebalancer/strategy/WeightedStrategy.ts, typescript/cli/src/rebalancer/utils/bridgeConfig.test.ts, typescript/cli/src/rebalancer/utils/bridgeConfig.ts, typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
=> feat: #6044 feedback - token uints instead of wei

rust/main/agents/relayer/src/msg/processor.rs, rust/main/submitter/src/payload_dispatcher/db/loader.rs, typescript/sdk/src/ism/EvmIsmModule.hardhat-test.ts
=> chore: fix some comments

typescript/infra/config/environments/mainnet3/gasPrices.json
=> chore: update eth mainnet igp

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: release new agent images

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Relayers and Scraper to latest
Yes
Manual
=> chore: Upgrade Relayers and Scraper to latest

typescript/cli/src/commands/warp.ts, typescript/cli/src/rebalancer/executor/Executor.ts, typescript/cli/src/rebalancer/metrics/Metrics.ts, typescript/cli/src/rebalancer/metrics/utils/metrics.ts, typescript/cli/src/rebalancer/monitor/Monitor.ts, typescript/cli/src/rebalancer/utils/tryFn.ts, typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts, typescript/cli/src/utils/errors.ts
Modifies the `WrappedError` class, as suggested, to include the `cause`
Also, does use the `util.format()` function to better trace errors.
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/73
Yes
Manual/Unit/e2e
=> feat(rebalancer): improve error handling

typescript/sdk/package.json, typescript/sdk/src/token/EvmERC20WarpModule.hardhat-test.ts, typescript/sdk/src/token/EvmERC20WarpModule.ts, typescript/sdk/src/token/EvmERC20WarpRouteReader.ts, typescript/sdk/src/token/types.ts, yarn.lock
=> Use semver compare and dependency version

.changeset/tough-mayflies-laugh.md, typescript/ccip-server/src/services/CCTPService.ts, typescript/ccip-server/src/services/OPStackService.ts, typescript/cli/src/commands/warp.ts, typescript/cli/src/rebalancer/README.md, typescript/cli/src/rebalancer/config/RebalancerConfig.test.ts, typescript/cli/src/rebalancer/config/RebalancerConfig.ts, typescript/cli/src/rebalancer/executor/Executor.ts, typescript/cli/src/rebalancer/factories/RebalancerContextFactory.ts, typescript/cli/src/rebalancer/index.ts, typescript/cli/src/rebalancer/interfaces/IRebalancer.ts, typescript/cli/src/rebalancer/interfaces/IStrategy.ts, typescript/cli/src/rebalancer/metrics/utils/metrics.ts, typescript/cli/src/rebalancer/rebalancer/Rebalancer.ts, typescript/cli/src/rebalancer/rebalancer/WithSemaphore.test.ts, typescript/cli/src/rebalancer/rebalancer/WithSemaphore.ts, typescript/cli/src/rebalancer/strategy/MinAmountStrategy.test.ts, typescript/cli/src/rebalancer/strategy/MinAmountStrategy.ts, typescript/cli/src/rebalancer/strategy/StrategyFactory.test.ts, typescript/cli/src/rebalancer/strategy/StrategyFactory.ts, typescript/cli/src/rebalancer/strategy/WeightedStrategy.ts, typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts, typescript/sdk/src/index.ts, typescript/sdk/src/rebalancer/types.ts
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/70
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/69
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/68
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/67
- Updated README to reflect latest changes
- getInitialTotalCollateral also filters by chains defined in config like the transformer
- Made it so checkFrequency is not required when manual mode is set
- Added lint fixes to ccip server
=> feat: Various fixes

.changeset/slick-cloths-do.md, typescript/sdk/src/warp/WarpCore.ts
Include `getTokenCollateral` to `WarpCore` and re-use in `isDestinationCollateralSufficient`, this will also be re-used in the UI for the upcoming feature of multi-collateral WR
Yes
Unit test
=> chore: add getTokenCollateral to WarpCore

typescript/infra/config/environments/mainnet3/warp/warpIds.ts, typescript/infra/config/warp.ts, typescript/infra/src/warp/helm.ts
This PR updates Renzo EZETH prod and stage warp route id to match registry
Yes
=> chore: Rename renzo ezeth warpId

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Relayer RC Mainnet
Yes
Manual
=> chore: Upgrade Relayer RC Mainnet

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Scraper Mainnet to latest
Yes
Manual
=> chore: Upgrade Scraper Mainnet to latest

typescript/infra/config/environments/mainnet3/rebalancer/USDC/arbitrum-avalanche-base-bsc-ethereum-optimism-unichain-config.yaml, typescript/infra/config/environments/testnet4/rebalancer/USDC/arbitrum-avalanche-base-bsc-ethereum-optimism-unichain-config.yaml, typescript/sdk/src/token/adapters/EvmTokenAdapter.ts
- mainnet USDC test warp route rebalancer config
- TokenAdapter changes to match `MovableCollateralRouter.sol` `allowedDestination` fallback logic 
Manual/e2e
=> feat: rebalancer mainnet test

rust/main/agents/relayer/src/msg/op_submitter.rs, rust/main/agents/relayer/src/msg/pending_message.rs, rust/main/agents/relayer/src/msg/processor.rs, rust/main/agents/validator/src/submit.rs, rust/main/hyperlane-base/src/db/mod.rs, rust/main/hyperlane-base/src/db/rocks/hyperlane_db.rs, rust/main/hyperlane-core/src/traits/pending_operation.rs, rust/main/lander/src/adapter/chains/ethereum/adapter/tx_status_checker.rs, rust/main/lander/src/adapter/chains/ethereum/nonce/db.rs, rust/main/lander/src/adapter/chains/ethereum/nonce/manager.rs, rust/main/lander/src/adapter/chains/ethereum/nonce/state.rs, rust/main/lander/src/adapter/chains/ethereum/nonce/state/tests.rs, rust/main/lander/src/adapter/chains/ethereum/transaction/factory.rs, rust/main/lander/src/adapter/chains/sealevel/adapter.rs, rust/main/lander/src/adapter/chains/sealevel/transaction/factory.rs, rust/main/lander/src/adapter/core.rs, rust/main/lander/src/dispatcher/db/payload/payload_db.rs, rust/main/lander/src/dispatcher/db/transaction/loader.rs, rust/main/lander/src/dispatcher/db/transaction/transaction_db.rs, rust/main/lander/src/dispatcher/entrypoint.rs, rust/main/lander/src/dispatcher/stages/building_stage.rs, rust/main/lander/src/dispatcher/stages/finality_stage.rs, rust/main/lander/src/dispatcher/stages/finality_stage/pool.rs, rust/main/lander/src/dispatcher/stages/inclusion_stage.rs, rust/main/lander/src/dispatcher/stages/state.rs, rust/main/lander/src/dispatcher/test_utils.rs, rust/main/lander/src/dispatcher/tests.rs, rust/main/lander/src/lib.rs, rust/main/lander/src/payload/types.rs, rust/main/lander/src/transaction/types.rs
* Rename PendingInclusion into Pending
* Rename TransactionId into TransactionUuid
* Rename PayloadId into PayloadUuid
Yes
Current tests pass
=> refactor(lander): Rename TransactionId, PayloadId and PendingInclusion

starknet/package.json, typescript/cli/src/context/strategies/signer/MultiProtocolSignerFactory.ts, typescript/sdk/package.json, typescript/utils/package.json, yarn.lock
[draft]: pb/starknet-cli + v3 txs
=> [draft]: pb/starknet-cli + v3 txs

typescript/cli/src/config/warp.ts, typescript/sdk/src/token/EvmERC20WarpRouteReader.ts, typescript/sdk/src/token/StarknetERC20WarpModule.ts, typescript/sdk/src/token/Token.test.ts, typescript/sdk/src/token/TokenStandard.ts, typescript/sdk/src/token/config.ts, typescript/sdk/src/token/contracts.ts, typescript/sdk/src/token/types.ts, typescript/sdk/src/utils/starknet.ts
This PR adds a new TokenStandard `StarknetHypDexCollateral ` and a new TokenType `collateralDex` for the speical Paradex Token: https://github.com/hyperlane-xyz/hyperlane-starknet/pull/13
-
-
-
-
=> chore: add new token standard

typescript/infra/config/environments/mainnet3/agent.ts
=> chore: phase 2 lander on RC

.changeset/fast-emus-sit.md, typescript/cli/package.json, typescript/helloworld/package.json, typescript/infra/package.json, typescript/widgets/package.json, yarn.lock
chore: update registry deps to latest
=> chore: update registry deps to latest

typescript/cli/src/read/warp.ts, typescript/sdk/src/token/StarknetERC20WarpModule.ts
=> chore: small warp deployment fixes

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/config/environments/mainnet3/funding.ts
chore: update relayer, scraper, keyfunder image
want to apply changes from chain deprecations https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/6598
=> chore: update relayer, scraper, keyfunder image

rust/main/chains/hyperlane-starknet/src/ism/interchain_security_module.rs, typescript/infra/config/environments/mainnet3/agent.ts
=> fix(starknet): skip dry_run_verify for now

rust/sealevel/environments/mainnet3/warp-routes/TRUMP-starknet/program-ids.json, rust/sealevel/environments/mainnet3/warp-routes/TRUMP-starknet/token-config.json
chore: add TRUMP starknet token config
=> chore: add `TRUMP` token config

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Relayer RC and Hyperlane in Mainnet
Yes
None
=> chore: Upgrade Relayer RC and Hyperlane in Mainnet

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/config/environments/mainnet3/warp/warpIds.ts
- add cctp token bridges to a metric app context
=> chore: add cctp token bridges to a metric app context

rust/sealevel/environments/mainnet3/warp-routes/Bonk-starknet/token-config.json, rust/sealevel/environments/mainnet3/warp-routes/Fartcoin-starknet/token-config.json, rust/sealevel/environments/mainnet3/warp-routes/JUP-starknet/program-ids.json, rust/sealevel/environments/mainnet3/warp-routes/JUP-starknet/token-config.json, rust/sealevel/environments/mainnet3/warp-routes/SOL-starknet/token-config.json, rust/sealevel/environments/mainnet3/warp-routes/TRUMP-starknet/token-config.json
=> feat: transfer ownership of Solana programs for Starknet warp routes

typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Relayer RC and Hyperlane Mainnet to latest
Yes
None
=> chore: Upgrade Relayer RC and Hyperlane Mainnet to latest

typescript/infra/config/environments/testnet4/agent.ts, typescript/infra/config/environments/testnet4/funding.ts, typescript/infra/config/environments/testnet4/gasPrices.json, typescript/infra/config/environments/testnet4/igp.ts
chore: update testnet igp + keyfunder
- update testnet4 relayers with latest main
=> chore: update testnet igp + keyfunder

typescript/cli/src/rebalancer/runner.ts
- chore: remove argument logging
Manual
=> chore: remove argument logging

rust/sealevel/environments/mainnet3/warp-routes/USDC-paradex/program-ids.json, rust/sealevel/environments/mainnet3/warp-routes/USDC-paradex/token-config.json
- Adds the mainnet Paradex USDC deploy
=> feat: add USDC paradex deploy

typescript/infra/config/environments/mainnet3/agent.ts
Revert back to more recent Relayer images
Yes
None
=> chore: Revert back to more recent Relayer images

typescript/infra/config/environments/mainnet3/agent.ts
Release latest to Relayers in Mainnet
Yes
None
=> chore: Release latest to Relayers in Mainnet

.gitignore
- add yalc files to .gitignore
=> chore: add yalc files to .gitignore

typescript/infra/config/environments/mainnet3/rebalancer/USDC/paradex-config.yaml, typescript/infra/src/rebalancer/helm.ts
=> chore: update rebalancer config

typescript/infra/config/environments/mainnet3/rebalancer/USDC/paradex-config.yaml, typescript/infra/src/rebalancer/helm.ts
- update USDC/paradex rebalancer config
=> chore: update USDC/paradex rebalancer config

typescript/infra/scripts/warp-routes/ousdt/prune-warp-config.ts
chore: update ousdt pruner to easily re-enable chains
- to easily/automatically un-hide ousdt chains https://github.com/hyperlane-xyz/hyperlane-registry/pull/1094
=> chore: update ousdt pruner to easily re-enable chains

rust/Dockerfile
- update rust version to 1.86 in Dockerfile as well
=> feat: fix rust version docker

typescript/sdk/src/consts/multisigIsm.ts
=> chore: add mitosis to radix default ism

typescript/infra/config/environments/mainnet3/warp/configGetters/getoXAUTTokenWarpConfig.ts
This PR updates oXAUT base owner to AW safe
=> chore: Update oXAUT base XERC20 owner to AW safes

.changeset/two-moles-melt.md, typescript/infra/config/environments/mainnet3/warp/configGetters/getoXAUTTokenWarpConfig.ts, typescript/sdk/src/index.ts
This Pr updates the oXAUT already set addition bridge limits for avax, ethereum, worldchain. Also adds the new base chainlink pool
Registry: https://github.com/hyperlane-xyz/hyperlane-registry/pull/1141
- Export type used in Getter
Yes
Manual
=> chore: Update with oXAUT config with bridge limits

rust/sealevel/environments/mainnet3/gas-oracle-configs.json, typescript/infra/scripts/sealevel-helpers/print-gas-oracles.ts
chore: add galactica to solana igp
=> chore: add galactica to solana igp

typescript/infra/config/environments/mainnet3/warp/configGetters/getoUSDTTokenWarpConfig.ts
feat: update ousdt owner on 0g
=> feat: update ousdt owner on 0g

rust/sealevel/environments/mainnet3/gas-oracle-configs.json, typescript/infra/scripts/sealevel-helpers/print-gas-oracles.ts
chore: add radix to solana igp
=> chore: add radix to solana igp

typescript/infra/config/environments/mainnet3/agent.ts
chore: update igp enforcement for stride<>forma
=> chore: update igp enforcement for stride<>forma

typescript/infra/config/environments/mainnet3/agent.ts, typescript/infra/config/environments/testnet4/agent.ts
Upgrade Relayer to latest in Mainnet and Testnet
Yes
Manual
=> chore: Upgrade Relayer to latest in Mainnet and Testnet
