hyperlane-xyz/hyperlane-monorepo

rust/abacus-base/src/metrics.rs
rust/agents/relayer/src/checkpoint_relayer.rs
rust/agents/relayer/src/message_processor.rs
rust/agents/relayer/src/relayer.rs

This PR adds some prometheus gauges to track the various phases of messages and where they are according to agent state (primarily the relayer). The prime metric is `last_known_message_leaf_index` with the following phases:
```
- dispatch: When a message is indexed and stored in the DB
- signed_offchain_checkpoint: When a leaf index is known to be signed by a validator
- inbox_checkpoint: When a leaf index is known to be checkpointed on the inbox
- relayer_processed: When a leaf index was processed with CheckpointRelayer
- processor_loop: The current leaf index in the MessageProcessor loop
- message_processed: When a leaf index was processed as part of the regular MessageProcessor loop
```
Also added a gauge to track the retry queue length

Add gauges to track agents

---

rust/agents/relayer/src/checkpoint_relayer.rs
rust/agents/relayer/src/message_processor.rs
rust/agents/validator/src/submit.rs
rust/tools/abacus-cli/src/subcommands/prove.rs
rust/tools/kms-cli/src/main.rs
typescript/infra/src/agents/index.ts
typescript/sdk/src/core/environments/index.ts

This PR adds the following changes:
- Ignores errors during checkpoint submission in the relayer so it doesn't bring down the whole process
- Pulls out the loops of CheckpointRelayer and MessageProcessor so that tracing spans with the inbox name are actually visible
- Upgrades ethers-rs

Debugging testnet deployment

---

typescript/infra/config/environments/test/index.ts

When running infra scripts, typescript complains that ethers is not defined on hre. That's only try after importing `hardhat-ethers`

Fix import for infra test environment

---

typescript/infra/src/agents/index.ts

When I "fixed" this last time, I mixed up the order .... 
Tested this by giving me the optimismkovan relayer env vars and it ran and succeeded nicely. Which unfortunately doesn't help me understand why the remote agent didnt do it

Fix ENV var for relayer signer aws keys

---

typescript/infra/hardhat.config.ts
typescript/infra/package.json

This PR fixes some minor things from the recent refactor. As `getCoreEnvironmentConfig` is not currently typed, passing the config was wrong and now that the infra hardhat tasks basically assume test environment (since that's how the signer for the multiprovider is deduced),  some args can be dropped

Fix infra test deploy

---

rust/Dockerfile

Was looking to improve caching with the pipeline but discovered that the real issues seems to be that the cache mounts provided by buildkit are just too new to have full support. I ended up doing some general cleanup to the dockerfile in the process so that is what the PR represents.
Closes #358
Later I suspect the docker build-push-action will support the docker cache and this should just start working.
Main improvements:
* Less layers in final image which decreases size
* Sets to locked mode for the cache sharing to prevent weird results from multiple concurrent runs
* Makes build and copy atomic
* Now uses tini for initialization
* Now deletes package registry data after installing needed packages

Improve dockerfile

---

typescript/deploy/src/config.ts
typescript/deploy/src/utils.ts

There is no need to require the overrides key to be set, similar to `IDomainConnection`

Make TransactionConfig.overrides optional

---

typescript/infra/scripts/core.ts
typescript/infra/src/config/agent.ts
typescript/infra/src/core/deploy.ts

Fixes #393 
The agents can be configured to not start from genesis when indexing. This PR tracks the block number at the start of the deployment and then records it in the rust config files

Track starting blocks for Core deployments

---

typescript/sdk/CHANGELOG.md
typescript/sdk/README.md
typescript/sdk/src/core/contracts.ts
typescript/sdk/src/core/index.ts
typescript/sdk/src/core/message.ts
typescript/sdk/src/gas/calculator.ts
typescript/sdk/src/index.ts
typescript/sdk/src/types.ts
typescript/sdk/test/gas/calculator.test.ts
typescript/sdk/test/utils.ts

This PR strongly types InterchainGasCalculator (as well as a dedicated ParsedMessage). This PR also makes InterchainGasCalculator use chain names instead of domain IDs.
I didn't want to override the existing ParsedMessage as that would include having to type AbacusMessage and more and it's not clear to me that we will keep those.
Drive-by changes:
- Removes the sdk's README and points it to the docs
- Adds a changelog file to track breaking changes for the next time sdk gets published
Fixes #407

Strongly type InterchainGasCalculator

---

solidity/core/contracts/Common.sol

Resolves https://github.com/abacus-network/abacus-monorepo/pull/415#discussion_r870229408
Enforces that `Inbox.initialize` and `Outbox.initialize` functions have `initializer` modifiers

Add back initializing guard to Common initializer

---

.husky/pre-commit
package.json
yarn.lock

Runs `yarn prettier` before every `git commit`
`yarn install` will run `postinstall` which tells `husky` to install hooks specified in `.husky` to `.git/hooks`

Add prettier precommit hook

---

rust/config/test/test1_config.json
rust/config/test/test2_config.json
rust/config/test/test3_config.json
typescript/infra/hardhat.config.ts
typescript/infra/src/core/deploy.ts

In a previous PR (https://github.com/abacus-network/abacus-monorepo/pull/343), we changed the semantics of the agent configuration file from `local.json` containing `local`'s inboxes on all the `remote` chains to `remote` inboxes on `local` chain. This PR reverts the original semantics (as well as makes it consistent with the config parsing in the agent code).

Fix agent config generation

---

rust/.vscode/extensions.json

Without this change, vscode emits a warning that maktlad.rust-analyzer
is not in the extensions marketplace.
Since May 16, rust-lang is the new publisher for the
rust-analyzer extension:
https://twitter.com/rust_analyzer/status/1526181089391280128?cxt=HHwWgICwgazniq4qAAAA

Fix for vscode extension recommendation.

---

typescript/deploy/src/router/deploy.ts
typescript/infra/config/environments/dev/controller.ts
typescript/infra/config/environments/test/controller.ts
typescript/infra/config/environments/testnet/controller.ts
typescript/infra/scripts/deploy-controller.ts
typescript/infra/src/config/environment.ts
typescript/infra/src/controller/check.ts
typescript/infra/src/controller/deploy.ts
typescript/infra/src/controller/types.ts
typescript/infra/test/controller.test.ts

This PR extracts `RouterConfig` from the applications config type `Config` in `RouterDeployer`, which allows `Config` to be specifiable without the need to specify abacus-specific configuration such as abacusConnectionManagers. It does bring up the question whether 1) this is actually more confusing or 2) where the owner should go. In a world in which most applications would deploy a separate controller, one would probably not want to add `owner` to `Config` either as it is not static. That being said, it does feel like continuously adding abstractions that don't feel perfect.

Keep RouterConfig outside an applications config

---

.lintstagedrc
.prettierignore

Rust files (+ a few others) should not be processed by prettier or it breaks things

Fix prettier + githook

---

solidity/app/contracts/AbacusConnectionClient.sol
solidity/app/contracts/Router.sol
solidity/app/test/abacusConnectionClient.test.ts
solidity/app/test/router.test.ts
solidity/core/contracts/AbacusConnectionManager.sol
solidity/core/contracts/Mailbox.sol
solidity/core/contracts/validator-manager/MultisigValidatorManager.sol
solidity/core/test/abacusConnectionManager.test.ts
solidity/core/test/mailbox.test.ts
solidity/core/test/validator-manager/multisigValidatorManager.test.ts

This PR standardizes on the following naming scheme:
- If the function updates a single value, the function name should be `setX` and the event name should be `XSet`
- If the function adds a value to a set the function name should be `enrollX` and the event name should be `XEnrolled`
- If the function removes a value from a set the function name should be `unenrollX` and the event name should be `XUnenrolled`
Fixes #560

Standardize event naming across all contracts

---

rust/config/testnet2/alfajores_config.json
rust/config/testnet2/arbitrumrinkeby_config.json
rust/config/testnet2/bsctestnet_config.json
rust/config/testnet2/fuji_config.json
rust/config/testnet2/kovan_config.json
rust/config/testnet2/mumbai_config.json
rust/config/testnet2/optimismkovan_config.json
rust/helm/abacus-agent/templates/checkpointer-external-secret.yaml
rust/helm/abacus-agent/templates/external-secret.yaml
rust/helm/abacus-agent/templates/kathy-external-secret.yaml
rust/helm/abacus-agent/templates/relayer-external-secret.yaml
rust/helm/abacus-agent/templates/validator-external-secret.yaml
typescript/infra/config/environments/testnet2/agent.ts
typescript/infra/config/environments/testnet2/core/rust/alfajores_config.json
typescript/infra/config/environments/testnet2/core/rust/arbitrumrinkeby_config.json
typescript/infra/config/environments/testnet2/core/rust/bsctestnet_config.json
typescript/infra/config/environments/testnet2/core/rust/fuji_config.json
typescript/infra/config/environments/testnet2/core/rust/kovan_config.json
typescript/infra/config/environments/testnet2/core/rust/mumbai_config.json
typescript/infra/config/environments/testnet2/core/rust/optimismkovan_config.json
typescript/infra/src/config/agent.ts
typescript/sdk/src/chain-metadata.ts

* Changes mumbai's blocks till finality to be 32
* Always updates secrets from `external-secrets` upon a fresh agent deploy
* Enables kathy for all envs

More testnet2 tweaks

---

rust/agents/validator/src/submit.rs

This addresses the issue described in #575 wherein
validators crash after new contract deployment due to
failed calls on outbox.latest_checkpoint().
The calls fail due to u256 underflow on count()-1,
since count() is zero on init,
and latest_checkpoint() wants to return an
**index**, which is count() - 1.
This PR adds a retry loop just prior to entering
the existing main validator-submit-loop. I chose
to poll outbox.count() rather than try to decode
the error code or revert reason on failed calls
to latest_checkpoint() so that we avoid tightly
coupling this behavior to particular error codes
or messages, and in fact may want to preserve
exisitng behavior when calls to outbox.latest_checkpoint()
fail for other reasons.
Tested with a modified `rust/run-locally.sh` which
asks Kathy to sleep …

validator: Ensure non-empty outbox on init.

---

rust/abacus-base/src/metrics/core.rs
rust/agents/validator/Cargo.toml
rust/agents/validator/src/submit.rs
rust/agents/validator/src/validator.rs

- Added a metric to track the checkpoint that has been observed and processed
- Now also tracks outbox state in the validator
- Some minor refactoring in the validator
Relates to #421

Validator Metrics

---

rust/abacus-base/src/settings/mod.rs

I couldn't find any comment explaining how the correspondence
between environment variable names and JSON config file
hierarchy works. I think you just have to figure this out by
asking someone or internalizing the decl_settings! implementation.
This is really surprising behavior to me, and people might
benefit from a comment in the settings mod.rs file explaining
what's going on at a high level.

Add a comment explaining an agent config "rune".

---

typescript/infra/scripts/core.ts

Quick fix for the run-locally script.

Don't require partial_core_addresses.json to be present

---

rust/abacus-base/src/settings/mod.rs
rust/agents/kathy/src/kathy.rs
rust/agents/relayer/src/relayer.rs
rust/agents/validator/src/validator.rs

This PR skips the creation of the Inbox contract wrappers in the validator agent. That avoids the need to specify RPC urls for them.

[validator agent] Do not create inbox contracts if validator agent

---

rust-toolchain
rust/Cargo.lock
rust/Dockerfile
rust/README.md
rust/abacus-base/Cargo.toml
rust/abacus-base/src/lib.rs
rust/abacus-base/src/macros.rs
rust/abacus-base/src/settings/mod.rs
rust/abacus-core/Cargo.toml
rust/abacus-test/Cargo.toml
rust/agents/kathy/Cargo.toml
rust/agents/relayer/Cargo.toml
rust/agents/validator/Cargo.toml
rust/chains/abacus-ethereum/Cargo.toml
rust/ethers-prometheus/Cargo.toml
rust/gelato/Cargo.toml

This won't fix all the dependbot warnings because some of them are just for sub-sub dependencies and are not worth trying to patch. But I did take the opportunity to update most of our packages and do some more package cleanup.
- Updates rust to 1.61.0
- Updates lots of packages
- Switches rocksdb to the crates.io version
- Cleaned up the config macro (needed to re-work anyway due to updates in the config package)

Rust updates

---

rust/agents/validator/src/submit.rs

Minor change to be more clear about intent.

Use current index for validator latest processed gauge init

---

typescript/sdk/src/contracts.ts

Like @jmrossy has predicted, our way of recursively serializing and deserializing contracts was brittle. Quickly fixing this to unblock, but we should consider alternative approaches as this is still brittle

Quickly fix recursive contract de/serialization

---

typescript/sdk/src/contracts.ts
typescript/sdk/src/proxy.ts

In #647, The first branch now always takes precedent over the ProxiedAddress detection which should actually come first

Properly de-/serialize proxied contracts

---

rust/chains/abacus-ethereum/abis/Inbox.abi.json
rust/chains/abacus-ethereum/abis/InboxValidatorManager.abi.json
rust/chains/abacus-ethereum/abis/InterchainGasPaymaster.abi.json
rust/chains/abacus-ethereum/abis/Outbox.abi.json
solidity/app/contracts/Router.sol
solidity/core/contracts/InterchainGasPaymaster.sol
solidity/core/contracts/test/TestSendReceiver.sol
solidity/core/interfaces/IInterchainGasPaymaster.sol
solidity/core/test/interchainGasPaymaster.test.ts

* We anticipate future versions of `InterchainGasPaymaster` to conditionally forward payments depending on the destination chain. We expect this to happen if we decide to support a chain that Gelato does not
* Updates ABIs that the agents use. Some changes are from https://github.com/abacus-network/abacus-monorepo/pull/566, which iirc was awkwardly done post-testnet2 but pre-mainnet. Regardless the agents don't depend on these events (and hopefully never will)

Add destination domain to InterchainGasPaymaster.payGasFor

---

typescript/deploy/src/utils.ts
typescript/infra/config/environments/mainnet/funding.ts
typescript/infra/config/environments/mainnet/index.ts
typescript/infra/config/environments/testnet2/funding.ts
typescript/infra/config/environments/testnet2/index.ts
typescript/infra/helm/helloworld-kathy/templates/cron-job.yaml
typescript/infra/helm/relayer-funder/Chart.yaml
typescript/infra/helm/relayer-funder/templates/_helpers.tpl
typescript/infra/helm/relayer-funder/templates/addresses-external-secret.yaml
typescript/infra/helm/relayer-funder/templates/cron-job.yaml
typescript/infra/helm/relayer-funder/templates/env-var-external-secret.yaml
typescript/infra/helm/relayer-funder/templates/external-secret.yaml
typescript/infra/helm/relayer-funder/values.yaml
typescript/infra/scripts/fund-relayers-from-deployer.ts
typescript/infra/scripts/funding/deploy-relayer-funder.ts
typescript/infra/scripts/funding/fund-relayers-from-deployer.ts
typescript/infra/src/agents/agent.ts
typescript/infra/src/config/environment.ts
typescript/infra/src/config/funding.ts
typescript/infra/src/funding/deploy-relayer-funder.ts
typescript/infra/src/utils/utils.ts

* Deploys a k8s cronjob that will occasionally fund the relayer addresses. The relayer addresses are fetched from GCP secret manager using `external-secrets`. In order to do this, the funding script was adapted to allow a file to be passed in that contains a JSON array of `{"identifier": "...", "address": "0x..."}` objects describing each key. Such an array already exists in GCP secret manager and is generated upon creating keys.
* Changes some of the desired balances. Some of theses should ideally be higher-- the numbers chosen are essentially `min(what can currently be afforded, what they probably should be)`.
* Makes the min delta required for a transaction to be relative to the desired balance. Numerator & denominator was chosen because ethers.BigNumber is integer based only
* …

Relayer funding infra

---

rust/agents/validator/src/submit.rs

FIxes #675 
If the reorg-period is 0, we would have still calculated the latest blocknumber and pass that explicitly. Instead, we should revert to the default behavior which is to query for the latest state https://github.com/abacus-network/abacus-monorepo/blob/fbf71303139e11fd28430c4819110dbe898e01a6/rust/chains/abacus-ethereum/src/outbox.rs#L313
This may address issues for some RPC providers that are inconsistent across `eth_getBlockNumber` and `eth_call`

Only pass non-zero reorg periods as lag to latest_checkpoint

---

typescript/infra/helm/relayer-funder/templates/_helpers.tpl

This is already included in https://github.com/abacus-network/abacus-monorepo/pull/683 here https://github.com/abacus-network/abacus-monorepo/pull/683/files#diff-5e9304f4086b7c967a31deba1a9dc305edfc12e886de770dcc04897d379f8b08R40, but as it seems there is likely to be a testnet2 deployment before https://github.com/abacus-network/abacus-monorepo/pull/683 is merged, it'd be nice to have that deployment include this label, which is used by some of the Grafana dashboards. I've already deployed essentially this change on `testnet2` when testing https://github.com/abacus-network/abacus-monorepo/pull/683 and building the dashboards, so a deployment without https://github.com/abacus-network/abacus-monorepo/pull/683 and this PR is a slight regression from the perspective of the Grafana dashboards

Add abacus/context label to abacus agent infra

---

rust/abacus-base/src/metrics/core.rs
rust/agents/relayer/src/msg/serial_submitter.rs
rust/utils/run-locally/src/main.rs

Update two metrics upon successful delivery of message:
*  counter reflecting number of messages successfully delivered during
process lifetime
*  gauge of highest leaf index of any message delivered to this inbox so
far during process lifetime
Also updates run-locally integration test to verify these metric values
upon test termination.

Set message_delivered phase correctly in serial_submitter

---

.github/workflows/e2e.yml
.github/workflows/monorepo-docker.yml
.github/workflows/rust-docker.yml
.github/workflows/rust.yml

Have been noticing that with so many slow workflows it really does not make sense to let them run to completion if we push new commits to a branch. This is a small change based on [this](https://stackoverflow.com/questions/69004608/cancel-previous-pipelines-when-a-new-one-is-triggered-github-actions) which should make them auto-cancel. The benefits are both that it cuts down on CI mins, but also that we are less likely to get throttled and have to wait for things we actually want running to run.

Cancel slow pipelines if new commits are pushed

---

.github/workflows/e2e.yml
.github/workflows/monorepo-docker.yml
.github/workflows/rust-docker.yml
.github/workflows/rust.yml

Whoops, I think the mistake should be obvious from the change, but basically pipelines were cancelling because groups were wrong and causing conflicts. This creates unique group names per workflow.

Workflow cancelling 2

---

rust/agents/relayer/src/msg/serial_submitter.rs

Restores functionality accidentally lost in #637 wherein we proactively check inbox message_status() call before attempting delivery of a message.

Check delivery status on inbox before attempting delivery

---

rust/helm/abacus-agent/templates/_helpers.tpl

* Looks like #691 was accidentally removed at some point, probably when doing some merging. This just adds it back.

Re-add abacus/context label to agent infra

---

rust/abacus-base/src/contract_sync/interchain_gas.rs
rust/abacus-base/src/contract_sync/outbox.rs

Noticing a lot of these log messages and the fact we almost always want to filter them out.

reduce "indexed block heights" log level

---

typescript/infra/scripts/funding/fund-relayers-from-deployer.ts

* Format logs as JSON one-liners
* Catch errors so that any funding attempts after the error are still attempted, while still exiting with a non-zero exit code.
* Drive-by to change the Pushgateway to use `async/await` rather than `.then` for promises just to be more consistent with the rest of the codebase
This doesn't:
* Include the deployment to have this be used on testnet2/mainnet
* Change the cron schedule or desired relayer balances - this is mostly just bc I'm not confident the relayer funder has enough funds if we were to like 6x the desired relayer balances, and I figured we should get this fix out asap. We can do the cron schedule / desired relayer balance changes later-- I created https://github.com/abacus-network/abacus-monorepo/issues/742 to track this
Closes #732

Small fixes for relayer funder script

---

solidity/core/contracts/Inbox.sol
solidity/core/test/inbox.test.ts

This check prevents a byzantine validator set from spoofing messages from a different origin domain.
Fixes #736

Add origin domain check to Inbox.process()

---

rust/agents/validator/src/validator.rs

Fixes a small typo in the user-facing documentation

docs: Fix typo in validator.rs

---

rust/abacus-core/src/lib.rs
rust/abacus-test/src/lib.rs

Lingering in just a couple of comments.

cleanup: Drop vestigial references to the optics project.

---

rust/utils/run-locally/src/main.rs

At @webbhorn's suggestion, I was able to repo locally by setting a very short timeout, so using a much longer one should help here.
Closes #801

Make timeout longer for contract deploy

---

rust/Cargo.lock
rust/abacus-base/Cargo.toml
rust/abacus-base/src/contract_sync/outbox.rs
rust/abacus-test/Cargo.toml
rust/abacus-test/src/test_utils.rs

Before this PR, the test will panic due to outbox syncer running in a concurrent
tokio task after the test completes and invoking mocked functions without expectations set.
The panic is also swallowed by a separate bug and is only visible if tests are run under
`cargo test -- --show-output`.
After this PR, we no longer see a backtrace / panic when running with `cargo test -- --show-output`.
We also correctly mark the test as failed in `cargo test` if we introduce a new panic in the test or DB harness code.
Some additional changes to try and improve things adjacent to this test:
*  use tmpfs instead of disk + panic-unwind-detection for the RocksDB contents to avoid the panic detection complexity
*  avoid the current correctness dependency on sleep(from_secs(5)) in the test. This is …

Fix broken test `contract_sync::outbox::test::handles_missing_rpc_messages`.

---

rust/Cargo.lock
rust/abacus-core/Cargo.toml
rust/abacus-core/src/chain.rs

Fixes #786 
Adds arbitrum, bsc, and optimism and their domains to the `domain_and_chain!` macro, which will enable portions of our monitoring to properly identify traffic relating to this chains instead of filling with "unknown" today.
Also introduces a unit test that searches for any json config files it can find, tries to parse them all, takes the union of all chain names and domain mappings it can see, and ensures certain internal consistency properties hold and that the `domain_and_chain!` macro is aware of them.
It's possible that this could be eventually adapated for json configs living in `typescript/infra` instead of `rust` if we go that direction. My hope was just to avoid a situation where we forget to keep things synchronized again.

Bring `domain_and_chain!` macro up to date, and add test coverage to keep it there

---

typescript/sdk/src/gas/calculator.ts

Not caught by tests as this function is stubbed out

Fix minor bug in InterchainGasCalculator

---

typescript/infra/config/environments/testnet2/chains.ts

We've been defaulting to 1.5gwei for maxFeePerGas which is underpriced, preventing us from submitting txs to mumbai.

Update mumbai gas prices

---

typescript/helloworld/src/app/app.ts
typescript/infra/config/environments/mainnet/funding.ts

This PR makes two small changes to address alerts that have fired in the last day.
First, it adjusts Kathy gas estimation to increase the multiplier from 1.1 times the estimate to 1.2. We had a Kathy tx last night that ran out of gas.
Second, it adjusts the relayer funder to run every hour at the 45 minute mark, rather than every 10 minutes, so as not to conflict with Kathy, per https://github.com/abacus-network/abacus-monorepo/issues/780

Increase kathy gas, adjust relayer funder cadence

---

typescript/sdk/src/consts/chainConnectionConfigs.ts

Ethers will interptet 0 confirmations as an excuse to treat a null confirmation as valid https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/base-provider.ts#L1286
This PR thus treats instant finality as 1 confirmation, not 0 confirmations

set instant finality to 1 confirmation

---

typescript/infra/scripts/funding/fund-relayers-from-deployer.ts
typescript/infra/src/agents/agent.ts
typescript/infra/test/agents.test.ts

* Logs errors correctly in the relayer funder
* Fixes the broken key identifier parsing in ReadOnlyAgentKey, along with tests so this doesn't happen again

Fix relayer funder - fix identifier parsing & error logging

---

typescript/infra/src/config/chain.ts

> [9:39 AM] tkporter: My theory is we:
> 1. signed a tx using the NonceManager, which locally increments the nonce N to N+1 that it'll use for the next tx signing
> 2. had a provider issue like the rlp one that caused the previously signed tx to never be mined
> 3. kathy just continues on to the next message to do
> 4. when we eventually want to send a message from arbitrumrinkeby again, we sign the tx with the nonce N+1, leaving a gap
> [9:41 AM] tkporter: all the nonce too high logs have the tx nonce incrementing so this is probably it

Bypass `NonceManager` in `getMultiProviderFromGCP`

---

typescript/infra/config/environments/mainnet/funding.ts
typescript/infra/config/environments/testnet2/funding.ts
typescript/infra/config/environments/testnet2/helloworld.ts

* Deploys testnet2 kathy, and testnet2 & mainnet key funder to include #888
* Not deploying kathy on mainnet yet as we've not transitioned mainnet kathy to being a service yet

Deploy kathy / key funder without nonce manager

---

typescript/infra/config/environments/mainnet/funding.ts
typescript/infra/config/environments/mainnet/helloworld.ts
typescript/infra/config/environments/testnet2/funding.ts
typescript/infra/config/environments/testnet2/helloworld.ts
typescript/infra/helm/helloworld-kathy/templates/stateful-set.yaml
typescript/infra/helm/key-funder/templates/cron-job.yaml
typescript/infra/helm/key-funder/values.yaml
typescript/infra/scripts/helloworld/kathy.ts
typescript/infra/src/agents/aws/key.ts
typescript/sdk/src/gas/calculator.test.ts
typescript/sdk/src/gas/calculator.ts

* Deploys key funder on testnet2 and mainnet to fund Kathy keys
* Upon trying to deploy #889, I came across some issues that my local testing unfortunately didn't catch:
1. There's a bug in the current InterchainGasCalculator that causes an error to be thrown when the exchange rate isn't an integer! If you try to create an `ethers.BigNumber` from a non-integer `number`, it'll throw with something like: `underflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-underflow ] (fault="underflow", operation="BigNumber.from", value=605.000605000605, code=NUMERIC_FAULT, version=bignumber/5.6.2)`. The fix here was to just round to the nearest integer, which is acceptable because we're using the PRECISION multiplier. I ran into this for the first time when deploying Kathy to mainnet. We …

Fund kathy keys in testnet2 & mainnet, fix some issues with Kathy infra and InterchainGasCalculator

---

typescript/infra/scripts/helloworld/kathy.ts
typescript/sdk/src/consts/chainMetadata.ts
typescript/sdk/src/gas/token-prices.test.ts
typescript/sdk/src/gas/token-prices.ts
typescript/sdk/src/test/testUtils.ts

* Gas is paid for on Optimism and Arbitrum in ETH, which the current code did not accommodate
* Noticing that the Kathy balance isn't high enough on some cheap chains (like Opt/Arb) to cover the whole cost of an expensive chain like Ethereum. For now, I'm having kathy still do the IGC calculation, but only pay 1 wei as gas payment. I've created #901 to undo this change once we have a high enough balance and are claiming IGP payments regularly

Fix IGC price fetching for optimism/arb, for now don't pay correct interchain gas in Kathy

---

typescript/infra/scripts/helloworld/kathy.ts

Fixes #922 
This PR tries to assert message processing via the stats stored on the HelloWorld contract

Try to assert the message was processed via contract state

---

typescript/sdk/src/consts/chainConnectionConfigs.ts

Noticed the existing one just doesn't work

Update default eth provider url

---

rust/agents/relayer/src/msg/serial_submitter.rs

This allows GCP to correctly filter for it in stackdriver logging

Add leaf index as a key on the log line

---

rust/abacus-base/src/contract_sync/interchain_gas.rs
rust/abacus-base/src/contract_sync/outbox.rs

Partially fixes #796 
This PR causes contract sync indexers to use the full chunk size. Before, it would always strictly use the successor of the end of the last block range it searched. In situations where the node may be unreliable at serving events close to the tip, this would mean we would only ever search a block in a range once. This the cost of an RPC request is basically indpendent of the size of the range, we may as well use the full range to give ourselves several attempts at getting events. Processing of the events already is idempotent anyways.

Always use the full chunk size

---

typescript/infra/scripts/funding/reclaim-from-igp.ts
typescript/sdk/src/consts/chainConnectionConfigs.ts

This PR adds a script to reclaim funds from the IGP to the deployer key. 
Fixes #892 
Drive-by:
- Have all block explorer URLs end without a trailing slash

Reclaim IGP funds to deployer key

---

rust/abacus-core/src/db/abacus_db.rs

* After #935, we'll definitely attempt to index gas payment events that have already been indexed. We shouldn't use `warn` logs, so I lowered it to `trace`

Lower log to `trace` level that's printed for already seen gas payments

---

rust/agents/relayer/src/msg/serial_submitter.rs

* Rather than sorting the run queue by the # of retries, this will instead push new messages from the wait queue into the front of the run queue, but will push any messages that are reverting to the back of the run queue, which is now ordered in a FIFO manner. See #919 for context.
* Note just pushing to the back of the queue for all kinds of processing errors can have some consequences because it's possible for message processing to fail for reasons other than the message reverting. For example, sometimes we can get into a situation where a transaction doesn't get mined within 5 mins and times out, and ideally we should just retry the same message. Because we expect the run queue to stay small and for these timeouts to occur very infrequently, this is probably not an issue, but we should …

Push failing messages to the back of the run queue

---

typescript/infra/src/config/chain.ts

The `RetryJsonRpcProvider` is incompatible with `StaticCeloJsonRpcProvider` for Celo chains. For now, just not retrying for Celo chains.
This was the error for anyone curious. Tested to ensure this was the issue.
```
{"error":"Error: invalid BigNumber value (argument=\"value\", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.6.2)\n    at Logger.makeError (/abacus-monorepo/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)\n    at Logger.throwError (/abacus-monorepo/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)\n    at Logger.throwArgumentError (/abacus-monorepo/node_modules/@ethersproject/logger/src.ts/index.ts:277:21)\n    at Function.BigNumber.from (/abacus-monorepo/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:289:23)\n    at …
```

Don't use retrying provider when using Celo

---

typescript/infra/scripts/debug-message.ts
typescript/sdk/src/core/AbacusCore.ts
typescript/sdk/src/index.ts

Adds a basic script to help debug messages not being received.
This will:
1. Print the whole parsed message and helpful info about the message
2. Ensure the destination domain id is a valid one for the environment
3. Check if the message has been processed yet
4. Get the recipient EVM address and make an `eth_getCode` RPC to ensure there’s code at the address, identifying most bytes32 encoding issues
5. Make a direct handle call to the recipient with the correct params with the from address set to the inbox address, reporting if it reverts and what the revert msg is
I'd love to see this be used for a super basic website so that it can be self-service for ppl.
Other features I think would be nice but aren't included in here:
* If a message has been processed already, look at old `Process` …

Message debug script

---

rust/abacus-base/src/contract_sync/interchain_gas.rs
rust/abacus-base/src/contract_sync/outbox.rs

Noticed the `from` in the GasPayments log message wasn't the `full_chunk_from`. Instead, just removing any variables from the message so it's easier to search for logs based off the message

Change indexing log messages

---

typescript/sdk/src/test/envSubsetDeployer/utils.ts
typescript/utils/src/logging.ts
typescript/utils/src/utils.ts

When running the SDK in non-node.js environment we would get a reference error
Fixes #959

Safely access process.env

---

solidity/core/contracts/AbacusConnectionManager.sol
solidity/core/contracts/Inbox.sol
solidity/core/contracts/Outbox.sol
solidity/core/contracts/upgrade/Versioned.sol
solidity/core/contracts/validator-manager/MultisigValidatorManager.sol
solidity/core/interfaces/IMailbox.sol
solidity/core/interfaces/IMultisigValidatorManager.sol
solidity/core/test/abacusConnectionManager.test.ts

In favor of https://github.com/abacus-network/abacus-monorepo/pull/964
- Version validator manager domain hash derivation
- Version MultisigValidatorManager in bytecode const
- Add backwards compatibility comments
- Prevent reuse of domain hashes in ACM
- Add enrollInbox helper to ACM
- Add pragma to new interface
- Avoid namespace collision on helper

Prevent replayable messages on new `Inbox` versions (as enrolled on `AbacusConnectionManager`)

---

rust/Cargo.lock
rust/abacus-base/Cargo.toml
rust/abacus-core/Cargo.toml
rust/abacus-test/Cargo.toml
rust/agents/relayer/Cargo.toml
rust/agents/validator/Cargo.toml
rust/chains/abacus-ethereum/Cargo.toml
rust/ethers-prometheus/Cargo.toml
rust/gelato/Cargo.toml
rust/utils/abigen/Cargo.toml

* Upgrades ethers-rs to include https://github.com/abacus-network/ethers-rs/pull/2
Tested locally by running a relayer using RC env vars

Upgrade ethers-rs to fix Optimsim gas estimation

---

typescript/infra/test/core.test.ts

Fixes bug in partial deployment tests which caused `test3` to exist as a key with undefined value

Use sinon restore and check test3 contracts

---

typescript/infra/config/environments/testnet2/agent.ts

* Deploy RC to include #967 
* I don't think we should move to other contexts yet - I want to wait for the new API because right now we're hardcoding the max gas value as 5M gas. Their new API will handle gas estimation for us

Deploy testnet2 rc to use Gelato

---

typescript/sdk/src/deploy/AbacusDeployer.ts
typescript/sdk/src/deploy/core/AbacusCoreDeployer.ts

- Adds waiting for tx confirmation of function calls
- Correctly passes through the implementation address to `deployProxy`

Further core deploy fixes

---

Dockerfile

Fixes [docker build failures](https://github.com/abacus-network/abacus-monorepo/actions/runs/3048745571/jobs/4914133249) introduced by https://github.com/abacus-network/abacus-monorepo/pull/1057

Copy ICA pjson when building docker image

---

typescript/infra/config/environments/testnet2/funding.ts

Key funder should now fund on Goerli - before it was being skipped

Deploy testnet2 key funder

---

rust/agents/relayer/src/msg/processor.rs
rust/agents/relayer/src/relayer.rs
rust/agents/validator/src/submit.rs

This changes a couple things:
* I noticed in the relayers that we have a metrics loop that was spawned for each inbox that only calls Outbox.state() every once in a while. Because there's only 1 outbox this is unnecessary, so this changes it to only spawn one loop
* I also think the once per minute is pretty frequent - maybe when we implement watchtowers it'll make sense to have a more accurate outlook as to whether the Outbox has been failed, but even then I expect the watchtowers will be the ones with the more intense monitoring around the failure of outboxes

Decrease frequency of Outbox.state() RPCs

---

typescript/infra/config/environments/mainnet/agent.ts
typescript/infra/config/environments/testnet2/agent.ts

* Deploy mostly to include #1087 and #1083
* Uses Gelato for alfajores, mumbai, and goerli on all testnet2 contexts

Deploy testnet2 and mainnet agents, use Gelato where we can for all testnet2 contexts

---

rust/abacus-base/src/types/checkpoint_syncer.rs
rust/abacus-base/src/types/s3_storage.rs
typescript/infra/scripts/verify-validator.ts

We've been unable to read from public S3 buckets that are outside our AWS account. While the S3 buckets are public, AWS didn't seem to accept credentials from an AWS account other than the S3 bucket's account.
The workaround is to use "anonymous" credentials (i.e. no credentials) for these requests.
I spent a tiny bit of time to try to understand why we're able to do this in Typescript but didn't want to spend too much time there because it was clear the solution is to just not use credentials. Fwiw it seems like in Typescript there are credentials in the HTTP header and we don't see any issues! My best guess is the headers / credentials are handled slightly differently and it has a meaningful impact.
* Clippy complained that the difference in the variant sizes of  the `CheckpointSyncers` …

Use anonymous S3 client for reading in S3 checkpoint syncer

---

rust/chains/abacus-ethereum/src/retrying.rs
rust/chains/abacus-ethereum/src/trait_builder.rs
typescript/infra/config/environments/testnet2/agent.ts

The QuorumProvider somewhat exacerbated the age old issue of us first doing an `eth_blockNumber` RPC to get the block height and then a performing a subsequent RPC (like an `eth_call`) at that block height, but the servicing node isn't aware of that block height yet, so it returns an error.
This is for a few reasons - the first is that the QuorumProvider will almost always do that get-block-number-then-do-rpc-at-that-block-number because it needs to ensure that all inner providers are performing the RPC at the same block height. Before QuorumProvider, for chains with instant finality, we were able to get around requesting specific block number and instead would default to the `"latest"` block tag for RPCs.
The other reason is that we were wrapping the QuorumProvider with RetryingProvider, …

Wrap inner providers with RetryingProvider when using QuorumProvider, not the QuorumProvider itself

---

typescript/infra/config/environments/mainnet/agent.ts
typescript/infra/config/environments/testnet2/agent.ts

Mostly includes https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1099. This PR deployed to testnet2 with quorumprovider from a commit on that branch, this PR deploys from a commit from main
n/a
n/a
Fully backward compatible
deployed

Deploy testnet2 & mainnet - all testnet2 contexts using QuorumProvider

---

typescript/infra/scripts/debug-message.ts

On the suggestion of @jmrossy , changed this to the estimateGas which should properly throw an exception in all reversion cases.
- Fixes https://github.com/hyperlane-xyz/issues/issues/201
Yes
Tried with `yarn ts-node scripts/debug-message.ts --tx-hash 0x17d6cb51afa2c2ab10be0ce78496c9ffc0899dc25f2943dc332f4b1bcdee856c --origin-chain fuji -e testnet2`

Use estimateGas in msg debugger

---

typescript/infra/config/environments/mainnet/funding.ts
typescript/infra/config/environments/mainnet/helloworld.ts
typescript/infra/config/environments/mainnet/index.ts
typescript/infra/config/environments/testnet2/funding.ts
typescript/infra/config/environments/testnet2/helloworld.ts
typescript/infra/config/environments/testnet2/index.ts
typescript/infra/helm/helloworld-kathy/templates/_helpers.tpl
typescript/infra/helm/helloworld-kathy/templates/external-secret.yaml
typescript/infra/helm/key-funder/templates/cron-job.yaml
typescript/infra/helm/key-funder/templates/env-var-external-secret.yaml
typescript/infra/scripts/funding/fund-keys-from-deployer.ts
typescript/infra/scripts/helloworld/kathy.ts
typescript/infra/scripts/helloworld/utils.ts
typescript/infra/scripts/utils.ts
typescript/infra/src/config/chain.ts
typescript/infra/src/config/environment.ts
typescript/infra/src/config/funding.ts
typescript/infra/src/config/helloworld.ts
typescript/infra/src/funding/deploy-key-funder.ts
typescript/infra/src/helloworld/kathy.ts

* Allows the key funder and kathy scripts to be configured to use a QuorumProvider (really in ethers-js jargon this is a FallbackProvider)
* Deployed this to testnet2 for the key funder & kathy - upon this merging I'll deploy to testnet2 again from a `main` commit and do the same for mainnet
Not really
https://github.com/abacus-network/abacus-monorepo/issues/872 and https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/873 are related, though not closing them out yet
This is actually backward compatible - yargs doesn't complain if there is a flag provided that it isn't aware of, so we can still deploy old versions of kathy/key funder using the new infra
Deployed to testnet2

Support QuorumProvider (i.e. FallbackProvider) in kathy and key funder

---

typescript/infra/config/environments/mainnet/validators.ts

Fixes the ZKV polygon relayer config which accidentally had avalanche content 
None
None
Yes
None

Fix ZKV polygon relayer config

---

typescript/infra/config/environments/mainnet/funding.ts
typescript/infra/config/environments/mainnet/helloworld.ts
typescript/infra/config/environments/testnet2/funding.ts
typescript/infra/config/environments/testnet2/helloworld.ts

* Deploys to include #1111
* Uses quorum provider in kathy and key funder in mainnet
none
- Fixes #872 
- Fixes #873 
Yes
None
deployed

Deploy key funder and kathy

---

rust/abacus-base/src/contract_sync/interchain_gas.rs
rust/abacus-base/src/types/s3_storage.rs
rust/abacus-core/src/db/abacus_db.rs
rust/agents/relayer/src/msg/gas_payment/policies/meets_estimated_cost.rs
rust/agents/relayer/src/msg/gelato_submitter/mod.rs
rust/chains/abacus-ethereum/src/trait_builder.rs

* Noticed an issue with the Fuji relayer, a Fuji validator, and a Mumbai validator over the weekend that I think could be related to a lack of timeouts in places where we do HTTP requests. I think the original PR to add timeouts to the Http connection type happened at the same time as the initial HttpQuorum PR so this wasn't added at the time, so I added a timeout to HttpQuorum inner providers. While I was at it, added timeouts in other places where we do HTTP requests
* Noticed that the prometheus counter tracking the # of total gas payment events processed was huge, turns out we were counting events we'd already processed
none
n/a
Yes
_Are there any infrastructure implications, e.g. changes that would prohibit deploying older commits using this …

Add timeout to inner HttpQuorum providers & all API requests, correctly record # of gas payment events processed

---

.github/pull_request_template.md
rust/agents/validator/src/submit.rs

Following some feedback, it's not super clear if a validator is working correctly because we don't log much
Minor log changes
n/a
Yes
None
None

Info log in validator when polling checkpoints

---

typescript/infra/config/environments/mainnet/agent.ts
typescript/infra/config/environments/testnet2/agent.ts

Deploys to testnet2 and mainnet mostly to include #1116
none
n/a
Sorta - see #1116 for the real breaking change
See #1116
Deployed

Deploy agents

---

typescript/infra/config/environments/testnet2/helloworld.ts

This PR stops sending to and from the deprecated networks in kathy. This should first trigger alerts in grafana for no messages sent. Eventually we'll remove them from the SDK and agent artifacts as well.

Skip deprecated networks in kathy

---

typescript/sdk/src/consts/environments/index.ts
typescript/sdk/src/index.ts

This PR gives a simple mapping for developers who just want to access the core addresses. This avoids the need to select the environment first and then understand the address structure, while not needing to construct an `AbacusCore` object (for which you would need a MultiProvider)

Export developer-relevant addresses as hyperlaneCoreAddresses

---

typescript/infra/config/environments/mainnet/agent.ts

Moonbeam relayer is having issues with delivering and we can't see the response, so disabling for now

Disable gelato for  now

---

rust/Cargo.lock
rust/abacus-base/Cargo.toml
rust/abacus-core/Cargo.toml
rust/abacus-test/Cargo.toml
rust/agents/relayer/Cargo.toml
rust/agents/scraper/Cargo.toml
rust/agents/validator/Cargo.toml
rust/chains/abacus-ethereum/Cargo.toml
rust/ethers-prometheus/Cargo.toml
rust/gelato/Cargo.toml
rust/utils/abigen/Cargo.toml

Updates the ethers-rs to include https://github.com/hyperlane-xyz/ethers-rs/pull/5
none
- Related #1160 
Yes
None
Deployed to testnet2 rc with a similar version using the new ethers-rs version

Update ethers-rs to include QuorumProvider fix

---

rust/config/testnet2/alfajores_config.json
rust/config/testnet2/arbitrumgoerli_config.json
rust/config/testnet2/bsctestnet_config.json
rust/config/testnet2/fuji_config.json
rust/config/testnet2/goerli_config.json
rust/config/testnet2/moonbasealpha_config.json
rust/config/testnet2/mumbai_config.json
rust/config/testnet2/optimismgoerli_config.json
rust/config/testnet2/scraper_config.json
typescript/sdk/src/consts/chainMetadata.ts

This PR adjusts the safe finality period of Goerli from 7 to 2. Now that the merge is complete, Goerli is much less likely to significantly reorg, and the responsiveness of the relayer and scraper (who wait for finality) is worth the very minor risk of reorgs.
- Fixes #1195

Adjust Goerli finality from 7 to 2

---

solidity/contracts/middleware/InterchainAccountRouter.sol

_What's included in this PR?_
This change causes InterchainAccountRouter.dispatch(...) to return the message leaf index of the dispatched message.
No
- Fixes #1233 
No
Potentially
None

Adding message leaf index to InterchainAccountRouter

---

rust/abacus-base/src/contract_sync/interchain_gas.rs
rust/abacus-base/src/contract_sync/outbox.rs
rust/abacus-base/src/settings/chains.rs
rust/agents/scraper/src/scraper/mod.rs

* Adds a sleep to the indexing loops to reduce RPC calls
* Significantly increases the sleep duration when caught up
None
Yes
None
Manual
E2E Test

Add sleeps to indexing loops

---

typescript/infra/config/environments/mainnet/agent.ts
typescript/infra/config/environments/mainnet/funding.ts
typescript/infra/config/environments/mainnet/helloworld.ts
typescript/infra/config/environments/testnet2/agent.ts
typescript/infra/config/environments/testnet2/funding.ts
typescript/infra/config/environments/testnet2/helloworld.ts

* Deployed agents to include #1254 
* Deployed kathy to include #1226 
* Deployed key funder because might as well
none
n/a
Yes
None
Deployed

Deploy agents / kathy / key funder

---

typescript/infra/config/environments/mainnet/helloworld.ts
typescript/infra/helm/key-funder/templates/cron-job.yaml
typescript/infra/scripts/funding/fund-keys-from-deployer.ts
typescript/infra/scripts/helloworld/kathy.ts
typescript/infra/src/config/funding.ts
typescript/infra/src/config/helloworld.ts
typescript/infra/src/funding/deploy-key-funder.ts

* Key funder now only tops up when the balance of a key is at 50% of what it should be (previously was 10%)
* Kathy now has `--cycles-between-ethereum-messages`. If it's 1, then every other full cycle messages to/from Ethereum are skipped. For mainnet, it's configured to 3, so at a pace of 1 cycle every 6 hours, this results in 1 cycle per day that sends messages to/from Ethereum
A bit clunky, but I figure Kathy is already a bit clunky 😄 
None
- Fixes #1245
Yes
No - but to use `--cycles-between-ethereum-messages` the infra in this commit is needed
None (👀)

Changes to kathy and key funder to spend less on eth

---

solidity/contracts/Call.sol
solidity/contracts/OwnableMulticall.sol
solidity/contracts/middleware/InterchainQueryRouter.sol
solidity/contracts/mock/MockHyperlaneEnvironment.sol
solidity/contracts/mock/MockInterchainAccountRouter.sol
solidity/interfaces/IInterchainAccountRouter.sol
solidity/interfaces/IInterchainQueryRouter.sol
solidity/test/MockInterchainAccount.t.sol
solidity/test/TestQuerySender.t.sol
solidity/test/TokenBridgeRouter.t.sol
typescript/sdk/src/consts/environments/index.ts
typescript/sdk/src/domains.ts
typescript/sdk/src/types.ts

- Have InterchainAccountRouter and MockInterchainAccountRouter conform to IInterchainAccountRouter
- Have InterchainQueryRouter conform to IInterchainQueryRouter
- Made `ChainNameToDomainId` more forgiving type wise
- Loosen type of hyperlaneCoreAddresses
- Fixes #1163 
No, new middleware routers will have to be deployed
Yes, deploys from this commit won't yield the same bytecode and thus same contract addresses for middleware contracts
Unit Tests

Quickstart fixes

---

typescript/sdk/src/deploy/router/HyperlaneRouterChecker.ts

Adds a check for the ACM address in the HyperlaneRouterChecker. Noticed a discrepancy in ACM addresses
n/a
n/a
Yes
None
Manual - tried running it and it worked correctly

Check ACM address in HyperlaneRouterChecker

---

typescript/sdk/src/gas/token-prices.ts

When we have a fresh cache entry for every chain we want prices for we shouldn't make a query with no token IDs.

Do not make empty queries to coingecko

---

rust/Cargo.lock
rust/abacus-base/Cargo.toml
rust/abacus-base/src/agent.rs
rust/abacus-base/src/contract_sync/cursor.rs
rust/abacus-base/src/contract_sync/interchain_gas.rs
rust/abacus-base/src/contract_sync/mod.rs
rust/abacus-base/src/contract_sync/outbox.rs
rust/abacus-base/src/lib.rs
rust/abacus-core/src/traits/cursor.rs
rust/abacus-core/src/traits/mod.rs
rust/abacus-test/Cargo.toml
rust/abacus-test/src/mocks/cursor.rs
rust/abacus-test/src/mocks/mod.rs
rust/agents/scraper/src/chain_scraper/mod.rs
rust/agents/scraper/src/chain_scraper/sync.rs

Two main things I wanted to do in this PR
1) End some of the duplication between the indexers
2) Implement a more robust RPC rate limiter
No
- Fixes #1255 
Yes
None
Manual
Unit Tests

Proper RPC Useage fix

---

solidity/contracts/middleware/InterchainAccountRouter.sol
solidity/contracts/middleware/InterchainQueryRouter.sol
solidity/contracts/mock/MockInterchainAccountRouter.sol
solidity/interfaces/IInterchainAccountRouter.sol
solidity/interfaces/IInterchainQueryRouter.sol
typescript/sdk/src/middleware/accounts.hardhat-test.ts

Support ICA/IQS functions without Call struct function signatures which may be more intuitive to some
- Fixes #1242 and fixes #1243
Yes
No
None
Yes
None
Manual
Unit Tests

Support ICA/IQS functions without Call struct

---

rust/agents/scraper/src/chain_scraper/sync.rs

Noticed this when poking through some logs
n/a
n/a
Yes
None
None

Correct span field "chunk_size" for scraper

---

solidity/contracts/Router.sol
solidity/test/router.test.ts

Adds a batch function for enrolling multiple remote routers. Added no consumption code yet until it is propagated through.
No
Yes - Once consuming code uses the batch function, it obviously doesn't work against older deployments
Unit Tests

Add Router#enrollRemoteRouters

---

typescript/utils/src/validator.ts

The utils package depends on itself which caused some problems when building for me when switching between main and v2. The fix was to just rely on the local files
none
none
Yes
None
`yarn build`

Fix utils build

---

rust/chains/hyperlane-ethereum/src/multisig_ism.rs
rust/hyperlane-core/src/types/checkpoint.rs

Sorts validator signatures by the order that the MultisigIsm contract expects.
Honestly the implementation feels a little heavyweight to me - wondering if there's an easier way of doing this that I didn't think of?
I considered caching the `ordering_map` alongside the validators, wondering if y'all feel I should do that
n/a
n/a
Yes
no
Ran a relayer locally and it worked

Order signatures correctly

---

typescript/helloworld/src/app/app.ts
typescript/infra/scripts/helloworld/kathy.ts
typescript/sdk/src/core/HyperlaneCore.ts
typescript/sdk/src/core/message.ts
typescript/utils/src/utils.ts

Instead of searching for events, this will make Kathy just poll for the delivery status on the inbox directly. This avoids costly RPC calls.

Reduce Kathy polling

---

typescript/infra/config/environments/testnet2/agent.ts

Moonbasealpha is down, and causing issues for relayers. Will re-enable when back up.
None.

Temporarily disable moonbasealpha for testnet2

---

rust/agents/scraper/src/agent.rs
rust/chains/hyperlane-ethereum/src/interchain_gas.rs
rust/chains/hyperlane-ethereum/src/mailbox.rs
rust/chains/hyperlane-ethereum/src/multisig_ism.rs
rust/chains/hyperlane-ethereum/src/provider.rs
rust/chains/hyperlane-ethereum/src/trait_builder.rs
rust/hyperlane-base/src/agent.rs
rust/hyperlane-base/src/settings/chains.rs
rust/hyperlane-base/src/settings/mod.rs

Pulled in some minor refactors form my rabbit hole earlier into dynamic providers
- Renamed `MakeableWithProvider` to `BuildableWithProvider` to better represent how it is used
- Renamed all `try_into_` functions in this chain to `build_` since it did not actually convert `self` and was therefore a misnomer
- Cut back on code duplication with a delegation macro
- Refactored how chains is structured to prepare for new chains
- Relates to https://github.com/hyperlane-xyz/issues/issues/277
- Relates to https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1362
Yes
None …

Provider config and build path

---

rust/agents/scraper/migration/src/m20221122_000001_create_table_domain.rs

Minor fix to domain id for ethereum.
No
Yes
None

Fix the ethereum domain id in the database for scraper

---

rust/agents/relayer/src/msg/gelato_submitter/mod.rs
rust/agents/relayer/src/msg/mod.rs
rust/agents/relayer/src/msg/processor.rs
rust/agents/relayer/src/msg/serial_submitter.rs
typescript/infra/config/environments/mainnet/agent.ts
typescript/infra/config/environments/testnet2/agent.ts

Quick fix to make it so that messages are not constituently being retired if they fail to be sent. This does not evict messages, but it does provide a bandaid for now to reduce the RPC calls we are making. It also hard-codes in the waits for now so that if someone is testing with a message thy won't have to possible wait for days after they fix the issue that was preventing a message from being sent.
We should also be able to port this change to v2 pretty easily.
Minor cleanup to imports.
- #1405
Yes
None
Manual (e2e)

Reduce message retries

---

rust/abacus-base/src/metrics/core.rs
rust/abacus-base/src/metrics/provider.rs
rust/abacus-base/src/settings/trace/span_metrics.rs
rust/agents/relayer/src/msg/gelato_submitter/mod.rs
rust/agents/relayer/src/msg/mod.rs
rust/agents/relayer/src/msg/processor.rs
rust/agents/relayer/src/msg/serial_submitter.rs
rust/ethers-prometheus/src/middleware/mod.rs
typescript/infra/config/environments/mainnet/agent.ts
typescript/infra/config/environments/testnet2/agent.ts

* Replaced histograms with counter + duration sums (we were not using the histogram buckets anyway)
* Removed submission time histogram for submitters
None
Yes
Yes - slight change to metrics dashboards might be required
Manual
Unit Tests

Reduce metric cardinality

---

solidity/package.json
typescript/helloworld/package.json
typescript/infra/package.json
typescript/sdk/package.json
typescript/sdk/src/consts/chainConnectionConfigs.ts
typescript/utils/package.json
yarn.lock

Rotates out ankr which seems to have problems and deployed 0.5.6 for that

Replace default goerli rpc provider

---

rust/abacus-base/src/metrics/json_rpc_client.rs
rust/abacus-base/src/settings/chains.rs
rust/chains/abacus-ethereum/src/retrying.rs
rust/chains/abacus-ethereum/src/trait_builder.rs
rust/ethers-prometheus/src/json_rpc_client.rs

Noticed the metrics we are collecting for provider requests is actually not the number of requests we send to the underlying provider which means our error tracking is very wrong. The success count should be the same though. 
Also made a change to how we count errors to be more in-line with best practice and make it a little easier to see what is going on.
None
Yes
Minor - does change the meaning/accuracy of the metric and changes how failures are reported.
Manual

Fix provider wrapping order

---

rust/hyperlane-core/src/types/checkpoint.rs

To test some behavior of the Fuel/Sway contracts against the existing logic in the agent codebase, we need access to the hashed Checkpoint that validators sign. This makes the relevant functions public, and renames them to be a little more clear
Minor rename
n/a
Yes
None
CI tests

Make some Checkpoint hash fns public and rename them too

---

.github/workflows/node.yml
typescript/token/.eslintignore
typescript/token/.eslintrc
typescript/token/.gitignore
typescript/token/.prettierignore
typescript/token/.prettierrc
typescript/token/.solcover.js
typescript/token/.solhint.json
typescript/token/contracts/HypERC20.sol
typescript/token/contracts/HypERC20Collateral.sol
typescript/token/contracts/HypERC721.sol
typescript/token/contracts/HypERC721Collateral.sol
typescript/token/contracts/extensions/HypERC721URICollateral.sol
typescript/token/contracts/extensions/HypERC721URIStorage.sol
typescript/token/contracts/libs/Message.sol
typescript/token/contracts/libs/TokenRouter.sol
typescript/token/contracts/test/ERC20Test.sol
typescript/token/contracts/test/ERC721Test.sol
typescript/token/hardhat.config.ts
typescript/token/package.json
typescript/token/scripts/deploy.ts
typescript/token/src/app.ts
typescript/token/src/config.ts
typescript/token/src/contracts.ts
typescript/token/src/deploy.ts
typescript/token/test/erc20.test.ts
typescript/token/test/erc721.test.ts
typescript/token/tsconfig.json
yarn.lock

This PR moves back the token-repo to allow for changes to be made atomically across packages and expects the https://github.com/hyperlane-xyz/hyperlane-token to be occasionally synced like helloworld does.
Yes
None
Unit Tests

Add token package back into the monorepo for now

---

solidity/contracts/Router.sol
solidity/contracts/middleware/V2CompatibilityRouter.sol
solidity/test/V2CompatabilityMiddlewareRouter.t.sol
typescript/infra/config/environments/mainnet/middleware/v2compatibility/addresses.json
typescript/infra/config/environments/mainnet/middleware/v2compatibility/verification.json
typescript/infra/config/environments/testnet2/middleware/v2compatibility/addresses.json
typescript/infra/config/environments/testnet2/middleware/v2compatibility/verification.json
typescript/infra/scripts/middleware/deploy-v2compatibility.ts
typescript/sdk/src/deploy/middleware/V2CompatibilityMiddlewareDeployer.ts
typescript/sdk/src/deploy/router/HyperlaneRouterDeployer.ts
typescript/sdk/src/index.ts
typescript/sdk/src/middleware.ts

Adds V2Compatbility middleware that allows users to use the `V2CompatibilityRouter` in place of v2 mailboxes

Add V2Compatibility middleware

---

typescript/infra/scripts/middleware/portal-relayer.ts

When doing the DX games, I tried to transfer a token that hasn't had its wrapped representation created yet. The portal relayer we operate doesn't know how to create the new wrapped representation, so it just continually will try to process the transfer which reverts each time. When it reverts, the process throws. As a temporary fix, this doesn't throw on errors when processing transfers. This way we'll process future Portal transfers instead of erroring out before reaching them
Context:
https://www.notion.so/Trevor-Notes-eff6851b9d11475bb75e69b8b7e62e63
https://www.notion.so/DX-Games-4-Tickets-8ac7d78387fa4dc0bd87b9b6c9c9b06c
none
n/a
Yes
_Are there any infrastructure implications, e.g. changes that would prohibit deploying older commits using …

Portal relayer: don't throw if there's an error

---

.github/workflows/e2e.yml

Reduces the number of kathy rounds that are run in the CI which will reduce how long it takes to run and should fix the flakiness since we are not reducing the timeout.
None
Yes
None
Unit Tests

Reduce rounds for e2e CI

---

solidity/contracts/Mailbox.sol
solidity/contracts/test/TestRecipient.sol
solidity/interfaces/IMailbox.sol
solidity/test/mailbox.test.ts

This PR exposes `Mailbox.recipientIsm()` as a public function.
This makes for a quality-of-life improvement for relayers. Rather than having to duplicate the logic in `Mailbox` to determine what ISM a `Mailbox` will use for message verification, relayers can call this view function directly.
None
None
Yes
Unit Tests

Expose Mailbox.recipientIsm() as a public function

---

typescript/sdk/src/consts/chains.ts

Fixing small oversight from #1449

Fix alphabetical ordering of mainnet chains

---

.github/workflows/node.yml

Use bug fix from https://github.com/osmind-development-org/lcov-reporter-action/pull/1

Use patched version of github action

---

rust/agents/relayer/src/msg/processor.rs

Fixes a bug introduced when I updated the processor, where the latest nonce gauge will not update until the relayer sees a new message that hasn't been delivered.
This means the gauge hangs out at 0 for a while after the relayer restarts.
Fixed by updating the gauge first-thing in the processor loop.
- Minor refactor of message processor `tick()`

Update message processor gauge first

---

typescript/infra/src/utils/utils.ts

Sick of having this show up in the diff, best practice is to have a new line at the end.

writeJSON with new line at the end

---

typescript/infra/scripts/deploy-infra-external-secrets.ts
typescript/infra/scripts/deploy-infra-monitoring.ts

Assert right kube context in more infra deploys to avoid the external secrets situation

Assert right kube context in more infra deploys

---

typescript/infra/scripts/deploy-infra-external-secrets.ts
typescript/infra/scripts/deploy-infra-monitoring.ts

Assert right kube-context when deploying infra
v1 version of #1567

Assert right kube-context when deploying infra

---

typescript/sdk/src/consts/chainMetadata.ts

Default public ankr goerli node is unreliable, same as #1431

Add new default goerli rpc

---

rust/hyperlane-base/src/macros.rs
rust/hyperlane-base/src/settings/loader.rs

This PR implements a `CONFIG_FILES` env var which allows operators of the agents to specify a comma separated list of paths from which the agent should load (partial) config files. This should superseed the current method of specifying `RUN_ENV` and `BASE_CONFIG` (which is still supported).
- Fixes #1576 
Yes
None, since it is backwards compatible
Manual

Allow loading config files from the CONFIG_FILES env var

---

typescript/infra/config/environments/testnet3/middleware.ts
typescript/infra/config/environments/testnet3/middleware/liquidity-layer/addresses.json
typescript/infra/config/environments/testnet3/middleware/liquidity-layer/verification.json
typescript/infra/helm/liquidity-layer-relayers/templates/env-var-external-secret.yaml
typescript/sdk/src/deploy/verify/ContractVerifier.ts
typescript/sdk/src/providers/ChainConnection.ts

This PR deploys the liqudity layer to testnet3. Also fixes the retrieval of explorerApiUrls and a minor abacus artifact from the helm chart.
- Fixes #1539 
Yes
None
Manual

Deploy liquidity layer to testnet3

---

rust/hyperlane-core/src/traits/signing.rs

Quick fix to add a couple aliases to support the old format.
None.
- https://discord.com/channels/935678348330434570/1065751999313891458
- https://discord.com/channels/935678348330434570/1067180600886300724
Yes
None
Manual
Unit Tests

Fix SignedType backwards compatibility on deserialization

---

rust/agents/relayer/src/msg/processor.rs
rust/agents/relayer/src/msg/serial_submitter.rs

- Decreases the timeout for serial submitter to 200ms
- Updates the processor getting of unprocessed messages to loop until it hits the end or finds a message to send
None
- https://discord.com/channels/935678348330434570/1067584368639492237
Yes
None
None

Fixes for run queue init delay

---

typescript/sdk/src/utils/MultiGeneric.ts

Allow MultiGenerics to access chains not in the AllChains list. Allows the HyperlaneDeployer to be used for unknown chains, needed for warp route deployment.
None

Support unknown chains in MultiGenerics

---

.github/workflows/e2e.yml
.github/workflows/node.yml
rust/agents/relayer/src/msg/serial_submitter.rs
solidity/contracts/test/TestSendReceiver.sol
solidity/test/testSendReceiver.test.ts
yarn.lock

Speeds up CI by:
- fixing node_modules caching
- sending fewer messages in the e2e test
- failing less frequently in the e2e test
- removing yarn build cache from e2e test which always misses 
- Update hyperlane/token to latest main
- Fix coverage-sol to read proper files
- Never cancel in-progress e2e tests on main

Speed up CI

---

rust/Cargo.lock
rust/abacus-base/Cargo.toml
rust/abacus-core/Cargo.toml
rust/abacus-test/Cargo.toml
rust/agents/relayer/Cargo.toml
rust/agents/relayer/src/msg/gas_payment/policies/meets_estimated_cost.rs
rust/agents/scraper/Cargo.toml
rust/agents/scraper/migration/src/m20220805_000001_create_table_domain.rs
rust/agents/scraper/src/date_time.rs
rust/agents/validator/Cargo.toml
rust/chains/abacus-ethereum/Cargo.toml
rust/chains/abacus-ethereum/src/fallback.rs
rust/chains/abacus-ethereum/src/lib.rs
rust/chains/abacus-ethereum/src/trait_builder.rs
rust/ethers-prometheus/Cargo.toml
rust/gelato/Cargo.toml
rust/utils/abigen/Cargo.toml
rust/utils/run-locally/src/main.rs

Ported #1571 to v1
- Had to run some updates since it would not work otherwise
- First step to #1626
Yes
None
Manual
Unit Tests

Port FallbackProvider to v1

---

solidity/contracts/Mailbox.sol
solidity/contracts/isms/MultisigIsm.sol
solidity/contracts/middleware/InterchainAccountRouter.sol
solidity/contracts/middleware/InterchainQueryRouter.sol
solidity/contracts/middleware/liquidity-layer/LiquidityLayerRouter.sol
solidity/contracts/middleware/liquidity-layer/adapters/CircleBridgeAdapter.sol

> public functions that are never called by the contract should be
declared external to save gas.
> Path: monorepo/solidity/contracts/Mailbox.sol : latestCheckpoint()
> monorepo/solidity/contracts/isms/MultisigIsm.sol : verify()
> monorepo/solidity/contracts/middleware/InterchainAccountRouter.sol :
initialize(), getInterchainAccount()
> monorepo/solidity/contracts/middleware/InterchainQueryRouter.sol :
initialize()
> monorepo/solidity/contracts/middleware/liquidity-layer/LiquidityLayer
Router.sol : initialize()
> monorepo/solidity/contracts/middleware/liquidity-layer/adapters/Circl
eBridgeAdapter.sol : initialize()
No
Unit Tests

Use external function visibility where possible

---

solidity/contracts/Create2Factory.sol

> The Create2Factory contract implements custom errors, a solidity
functionality introduced on version 0.8.4.
> The pragma version defined in the contract is ^0.8.0, making it
possible to raise compilation errors.
None

H07: Add pragma to Create2Factory for custom errors

---

solidity/contracts/middleware/liquidity-layer/adapters/CircleBridgeAdapter.sol
solidity/test/LiquidityLayerRouter.t.sol

> hyperlaneDomainToCircleDomain mapping can be ambiguous, as in Circle
domain the Ethereum chain is encoded as ‘0’.
> This issue have been already identified by the developers and
highlighted in a TODO comment on line 25.
No
Unit Tests

Require remote routers in CircleBridgeAdapter

---

solidity/contracts/OwnableMulticall.sol
solidity/contracts/Router.sol
solidity/contracts/isms/MultisigIsm.sol

> Length computation for arrays is often included in the for loops
condition instead of being catched in a local variable.
> In these cases, the Solidity compiler will always read the length of
the array during each iteration.
> Instead, creating a new variable uint256 _length and iterating for
(uint256 i = 0; i < _length; ++i) will be much cheaper in terms of
Gas.
> This is most impactful for storage variable read operations, but it
is advised as a best practice in any case.
No
Unit Tests

Cache for loop array lengths

---

solidity/contracts/Call.sol
solidity/contracts/OwnableMulticall.sol
solidity/contracts/middleware/InterchainQueryRouter.sol

> InterchainQueryRouter is the Router contract used to poll view
functions on a remote chain. By design, the InterchainQueryRouter on
the remote chain will perform a callback on the origin chain to
communicate the results of the calls. The calls on the remote chain
are performed through the function OwnableMulticall._call(), called
by InterchainQueryRouter._handle().
> In case of a failed call, OwnableMulticall._call() will revert, so
the flow of InterchainQueryRouter._handle() will stop before calling
_dispatch() which would take care of sending the callback to the
origin chain.
> In this case, the origin chain will receive no callbacks, and will
not be informed of the failed call on the remote chain. Even if the
call failed and there is no value to communicate to the origin chain,
a …

Handle reverting queries

---

rust/helm/abacus-agent/templates/external-secret.yaml
rust/helm/scraper/templates/configmap.yaml
rust/helm/scraper/templates/external-secret.yaml
typescript/infra/config/environments/mainnet/agent.ts
typescript/infra/config/environments/testnet2/agent.ts
typescript/infra/src/config/agent.ts

Changes v1 deployments to use the FallbackProvider for all operations.
- Updated helm
- Updated config
- Updated shas to the new commits that have been deployed
None
- Fixes #1626 
- Fixes #1627 
Yes
Yes - fallback provider has to be disabled for older commits
Manual

Deploy Fallback Provider to V1

---

typescript/sdk/src/consts/environments/mainnet.json

Seems these must've been accidentally removed :/
no
n/a
Yes
None
None

Add mainnet moonbeam IQS & ICA addresses to SDK

---

rust/agents/relayer/src/msg/metadata_builder.rs
rust/chains/hyperlane-ethereum/src/interchain_gas.rs
rust/chains/hyperlane-ethereum/src/mailbox.rs
rust/chains/hyperlane-ethereum/src/multisig_ism.rs
rust/chains/hyperlane-ethereum/src/provider.rs
rust/chains/hyperlane-fuel/src/interchain_gas.rs
rust/chains/hyperlane-fuel/src/mailbox.rs
rust/chains/hyperlane-fuel/src/multisig_ism.rs
rust/chains/hyperlane-fuel/src/provider.rs
rust/hyperlane-base/src/mailbox.rs
rust/hyperlane-core/src/traits/deployed.rs
rust/hyperlane-core/src/traits/provider.rs
rust/hyperlane-test/src/mocks/mailbox.rs

Had a few relayer operators run into this today:
If a recipient doesn't have any code at the destination, the call to [Mailbox.recipientIsm](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/solidity/contracts/Mailbox.sol#L265) will revert. The try/catch already in there unfortunately isn't sufficient to prevent this (see here https://ethereum.stackexchange.com/questions/129150/solidity-try-catch-call-to-external-non-existent-address-method)
This conflicts with our use of the RetryingProvider, which pretty much assumes we never will intentionally make an `eth_call` that reverts. We end up retrying the eth_call a bunch of times, holding up progress in the serial submitter and providing a bunch of scary logs
This PR:
* Adds a `provider` fn to the `HyperlaneChain` trait, so that …

Prevent calls to `Mailbox.recipientIsm` when the recipient of a message isn't a contract

---

rust/hyperlane-base/src/metrics/core.rs

Removed a deprecated phase from the metric docs. I had gotten confused why the metric was not working so this helps clear that up.
None
Yes
None
None

Remove deprecated phase from metric

---

typescript/infra/config/environments/mainnet2/helloworld.ts

Previous deploy (#1787 ) was with a non-existent tag.
None

Fix mainnet2 kathy image tag

---

typescript/infra/config/environments/mainnet2/helloworld.ts
typescript/infra/config/environments/testnet3/helloworld.ts
typescript/infra/src/config/chain.ts
typescript/infra/src/config/helloworld.ts

This PR updates the hyperlane context Kathys to use HttpFallback providers.
- Add back support for HttpQuorum providers in TS
- Fixes kathy reliability (hopefully)
Yes
None
None

Use fallback provider in Hyperlane context kathys

---

rust/agents/relayer/src/msg/processor.rs
rust/hyperlane-base/src/metrics/core.rs

Adds a domain-independent last known message nonce gauge to relayer
None
- Fixes #1688 
Yes
None
None

Add max message nonce gauge to relayer

---

rust/agents/relayer/src/msg/gas_payment/policies/meets_estimated_cost.rs
rust/agents/relayer/src/msg/gelato_submitter/sponsored_call_op.rs
rust/agents/relayer/src/msg/processor.rs
rust/agents/relayer/src/msg/serial_submitter.rs
rust/chains/hyperlane-ethereum/src/mailbox.rs
rust/chains/hyperlane-fuel/src/mailbox.rs
rust/hyperlane-core/src/db/hyperlane_db.rs

A recent PR (#1797) had switched from logging `HyperlaneMessages` as `msg` to `message` which collides with the default JSON format for the actual log text. Oops. This had not shown up in manual testing as I was using the pretty format instead of the JSON format.
This changes us to consistently using `msg`.
None
- https://discord.com/channels/935678348330434570/935678739663192184/1075503502245249197
Yes
None
Manual

Fix message log collision

---

typescript/infra/config/environments/mainnet/agent.ts
typescript/infra/config/environments/mainnet/helloworld.ts
typescript/infra/config/environments/testnet2/agent.ts
typescript/infra/config/environments/testnet2/helloworld.ts

- Skip all chains other than Polygon and Celo in abacus context kathys
- Whitelist Polygon<->Celo and Alfajores<->Mumbai HelloWorld messages in abacus context relayer
- Make Toucan relayer whitelist more specific
- 
- Fixes https://github.com/hyperlane-xyz/issues/issues/383
- 
Yes
None
None

Spin kathy back up for polygon/celo only

---

typescript/infra/src/config/chain.ts

By default, ethers-js's FallbackProvider will assign each inner provider the same priority and then shuffle the providers for each request.
We want just basic falling back from first -> last. This makes use of the `priority` config to have consistent ordering. See https://docs.ethers.org/v5/api/providers/other/#FallbackProvider:
We noticed this when a URL that wasn't configured as the first one was getting consistently hit
n/a
n/a
Yes
No, but will want to upgrade any monorepo images for things like kathy
None

Add priority to FallbackProviderConfig when building an ethers-js FallbackProvider

---

typescript/sdk/src/core/HyperlaneCore.ts
typescript/sdk/src/deploy/router/HyperlaneRouterDeployer.ts
typescript/sdk/src/middleware/accounts.hardhat-test.ts

Ensures that the ISM in router deployment config is set once deployment is completed (irrespective of initializer/custom deployer)
None
Yes
SDK unit tests (hijacked accounts router)

Add ISM to RouterDeployer.initConnectionClient

---

typescript/infra/config/environments/mainnet/helloworld.ts
typescript/infra/config/environments/testnet2/agent.ts

- Swap domain IDs in toucan whitelist
- Bump mainnet kathy frequency to one message per hr alternating between celo and polygon
- 
None

Fix toucan testnet2 whitelist and increase mainnet kathy frequency

---

.github/workflows/e2e.yml
rust/agents/relayer/src/msg/metadata_builder.rs
rust/hyperlane-base/src/types/checkpoint_syncer.rs
typescript/infra/config/environments/mainnet2/agent.ts
typescript/infra/config/environments/testnet3/agent.ts
yarn.lock

Improves parsing/santization of announced validator locations
- Use node v16.x in CI e2e tests
- Fixes [#[issue number here]](https://github.com/hyperlane-xyz/issues/issues/390)
Yes
None
None

Better sanitization of announced validator locations

---

rust/hyperlane-core/src/traits/signing.rs
rust/hyperlane-core/src/types/checkpoint.rs

This PR modifies the serialization of signed types (i.e. announcements and checkpoints) to include the concatenated signature (i.e. the `serialized_signature` field).
Example:
```
{
"value": {
"validator": "0x70997970c51812dc3a010c7d01b50e0d17dc79c8",
"mailbox_address": "0x000000000000000000000000610178da211fef7d417bc0e6fed39f05609ad788",
"mailbox_domain": 13371,
"storage_location": "file:///var/folders/np/338cspjd73j9p52y9d_34r9w0000gn/T/.tmpaWomYN"
},
"signature": {
"r": "0x8960ff5557b283d9799ddbdb3a24d454dee0fab534effc40f411fdc20ed9cef7",
"s": "0x4ed1d8c1b2198b7a26b1a06c9b494e80c81aae54d2918494861fc7e52d3c8d21",
"v": 27
},
"serialized_signature": "0x8960ff5557b283d9799ddbdb3a24d454dee0fab534effc40f411fdc20ed9cef74ed1d8c1b2198b7a26b1a06c9b494e80c81aae54d2918494861fc7e52d3c8d211b"
}
``` …

Serialize concatenated signature

---

rust/agents/relayer/src/relayer.rs
rust/agents/relayer/src/settings/mod.rs
rust/helm/hyperlane-agent/templates/relayer-statefulset.yaml
rust/hyperlane-base/src/settings/loader.rs

The relayer now requires a list of destination chains that it will operate on. This also updates the helm chart to maintain current funcunality.
No
- Fixes #1687
Yes
Yes
Manual - Verified with a dry-run that it is correctly generating the list of destination chains

Make relayer require destination chains

---

rust/agents/relayer/src/settings/matching_list.rs
rust/agents/scraper/src/agent.rs
rust/agents/validator/src/settings.rs
rust/agents/validator/src/validator.rs
rust/config/mainnet2/mainnet2_config.json
rust/config/test/test_config.json
rust/config/testnet3/testnet3_config.json
rust/hyperlane-base/src/contract_sync/mailbox.rs
rust/hyperlane-base/src/settings/chains.rs
rust/hyperlane-core/src/chain.rs
rust/hyperlane-core/src/utils.rs
typescript/infra/config/environments/mainnet2/agent.ts
typescript/infra/config/environments/testnet3/agent.ts
typescript/infra/src/config/agent.ts
typescript/infra/src/core/deploy.ts

This ports the `StrOrInt` type that was used in the matching list to be used more generally in the config anywhere that an integer is expected. This also updates typescript to use the number versions since it is a little more straightforward and prevents some confusion around chain name support.
This was not extended to cases where we expect very large integers with the thought that it might lead to weird errors because of limitations on the intermediary types.
None
- Relates to #1850 
Yes
None
Manual
Unit Tests

Allow configs to use number or strings for numerics

---

rust/Dockerfile
rust/agents/relayer/Cargo.toml
rust/agents/scraper/Cargo.toml
rust/agents/validator/Cargo.toml
rust/helm/hyperlane-agent/templates/configmap.yaml
rust/hyperlane-base/Cargo.toml
rust/hyperlane-base/src/agent.rs
rust/hyperlane-base/src/settings/loader.rs

Switches us to using color-eyre by default for stack traces. To use oneline error you now must both have the `oneline-errors` feature enabled (which happens by default) and set the `ONELINE_BACKTRACES` env var to `true` which is not default.
This way even when someone is running the docker image they will still get better backtraces by default.
Updated the debug config print to also use oneline backtraces to decide whether to compress it all onto one line or not.
- Relates to #1850
Yes
None
Manual

Better default stack traces

---

rust/helm/hyperlane-agent/templates/configmap.yaml
typescript/infra/config/environments/mainnet2/agent.ts
typescript/infra/config/environments/testnet3/agent.ts
typescript/infra/src/agents/index.ts
typescript/infra/src/config/agent.ts

Now that we pay for gas on testnet, no need to blacklist. Mainnet will follow soon
Some fixes to the deploy tooling:
* BigInt isn't able to be used with JSON.stringify out of the box (https://github.com/GoogleChromeLabs/jsbi/issues/30). Instead moved to the ethers BigNumberish
* Configmaps don't like unquoted bools - they want strings and otherwise complain
n/a
Yes
None
Deployed testnet3

Remove testnet3 relayer blacklist

---

typescript/infra/scripts/funding/fund-keys-from-deployer.ts
typescript/infra/scripts/utils.ts
typescript/sdk/src/consts/chains.ts

* On mainnets, funds the kathy key with much more than other keys, shooting for > $100 of value such that accurate gas payments can be made
* Adds IGP claiming to the key funder if the balance of the IGP exceeds a threshold
* Some minor drive-bys following the SDK refactor -- one of which was that the infra multiprovider wasn't correctly setting the signer
Small changes in the wake of the SDK refactor
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/901
Yes
Sorta - the mainnet key funder doesn't have enough funds atm to cover some of these amounts (e.g. CELO, xDAI, MATIC). So we shouldn't deploy this onto …

Fund kathy more on mainnet, add IGP claiming to key funder

---

solidity/test/GasRouter.t.sol

I *believe* this is the fix for the flaky fuzz tests we've been experiencing.
My theory is that the IGP's balance was overflowing by there being 2 subsequent `payForGas` calls with each payment being > `type(uint256).max / 2`.
I found that this test was the culprit by running specific fuzz tests we have. Then made the fix and ran it multiple times and never saw an overflow again
n/a
n/a
Yes
None
Unit Tests

Fix flaky fuzz test

---

typescript/infra/config/environments/mainnet2/funding.ts
typescript/infra/config/environments/testnet3/funding.ts

Deploys key funder on testnet3 and mainnet2 to include https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1883
none
n/a
Yes
None
Deployed

Deploy key funder with IGP claiming & higher kathy balances

---

typescript/infra/config/environments/mainnet2/agent.ts
typescript/infra/config/environments/testnet3/agent.ts
typescript/infra/src/config/agent.ts

* Routine agent deploy to all envs / contexts
* Fixed a JSON deserialization issue where a U256 must be a string and not a number
* Added the on chain fee quoting gas enforcement policy to infra
* Deployed to testnet3 rc with on chain fee quoting gas enforcement policy
n/a
n/a
Yes
not really - but bc this includes an infra fix, you should deploy using this commit or later
Deployed

Deploy agents, deploy on chain fee quoting to testnet3 rc

---

typescript/infra/scripts/announce-validators.ts
typescript/infra/scripts/funding/fund-keys-from-deployer.ts
typescript/infra/src/agents/aws/s3.ts
typescript/infra/src/agents/aws/validator.ts

Noticed that if an IGP claim fails, it's not gracefully handled
none
n/a
Yes
None
Ran locally

Graceful handling of errors with key funder's IGP claim or L2 bridging

---

typescript/infra/scripts/funding/fund-keys-from-deployer.ts

For some extra context: #1934 and #1933 
Calling IGP.claim() was not using the Polygon tx defaults. Therefore we'd use a priority fee < 30 gwei and have txs be rejected :|
none
n/a
Yes
None
Ran locally

Use Polygon overrides when IGP claiming in key funder

---

rust/agents/relayer/src/msg/gas_payment/mod.rs
rust/chains/hyperlane-ethereum/src/mailbox.rs

* Moves to `estimateRetryableTicket` to get Arbitrum L2 gas
none
- Fixes #1728
Yes
None
Unit tests - haven't deployed yet tho

Move to estimateRetryableTicket to get L2 gas for arbitrum chains

---

typescript/infra/config/environments/testnet3/agent.ts

Start enforcing arbitrum gas amounts after #1949 
none
related: #1610 
Yes
None
Deployed and sent some messages

Deploy to testnet3 with arbitrum enforcement

---

rust/config/mainnet_config.json
typescript/infra/config/environments/mainnet2/core.ts

See https://github.com/hyperlane-xyz/issues/issues/415 for context
Essentially all validators are on 20 block finality but we changed the relayer to 14 [recently](https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1675/files#diff-67e27b51135e9801b172be277ee0f667ed7b5ea5cb600f987bceb03b75eb3d65R33). It results in a weird scenario where the relayer will retry a message a few times before there's a quorum from validators. Moving back to 20 in the relayer
* Added names to validator addresses which I found useful to know at a glance
- Fixes https://github.com/hyperlane-xyz/issues/issues/415
yes
Sorta. We should re-deploy …

Change ethereum finality in config 14 -> 20

---

typescript/sdk/src/providers/MultiProvider.ts

Currently, if the MP doesn't have a signer, the function will always return null

Fix explorerAddressURL when no signer

---

typescript/infra/config/environments/mainnet2/agent.ts
typescript/infra/config/environments/testnet3/agent.ts

Deploys to include #1959 
Note I did deploy testnet3 using the blacklist included in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1957, I'm just not including it in this PR
no
- Fixes https://github.com/hyperlane-xyz/issues/issues/415
Yes
None
Deployed

Deploy agents to include 20 block Eth finality

---

rust/agents/relayer/src/msg/processor.rs

The metric sets it for the origin label of `any` which is not as useful as setting to the actual origin

Set origin of metric

---

solidity/contracts/middleware/liquidity-layer/adapters/CircleBridgeAdapter.sol

> H02. Upgradeability Errors
> CircleBridgeAdapter.sol is inheriting Router, but is not initializing it. Issue M09 is related to this situation.
> OwnableMulticall.sol is inheriting OwnableUpgradable, but is not initializing it.
> Path: monorepo/solidity/contracts/middleware/CircleBridgeAdapter.sol: initialize()
> Recommendation: Initialize the inherited upgradable contracts.
Yes (deployment only)
Unit tests

Init OwnableUpgradeable in CircleBridgeAdapter

---

rust/Cargo.toml

Was accidentally removed in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1975/files#diff-7bdd9f71c229927ffff28bd337aa4ab3ab960426cd17fe857afe922014dfe791L13
Using the legacy feature allows us to opt into EIP 1559 txs. We should clean this up at some point, this is so fragile
Decided to put the legacy feature at the workspace lvl because we'll probably not want to miss this again by accident
n/a
n/a
Yes
None
None

Use legacy feature for ethers-contract

---

typescript/infra/scripts/funding/fund-keys-from-deployer.ts

With the goerli gas spike message 0x7052dc74be0f6a81007e2b10e11c11a70948b200c7c5a12fa80eab527ec641e0 requires 0.08 arb-eth to deliver and the relayer has 0.06, and we don't fund b/c 0.06 is > half of our desired of 0.1
Bumping to 0.5 for testnet L2s
We will probably need more goerli ETH
Once approved will deploy

Bump L2 desired balances

---

solidity/contracts/OwnableMulticall.sol

- Use `Ownable_init` instead of `transferOwnership`
Unit Tests

H02: OwnableMulticall followup

---

typescript/infra/scripts/deploy.ts
typescript/infra/src/core/deploy.ts
typescript/infra/src/deploy.ts

This PR fixes the broken E2E tests by writing agent config after core *or* IGP deploys.
Rather than reading contract addresses from the deployed contracts, agent configs are built from the cached contract addresses in the SDK. Therefore, we must write (but not read) contract addresses when deploying to the test environment.

Write agent config for core and IGP deploys

---

typescript/sdk/src/deploy/HyperlaneAppChecker.ts
typescript/sdk/src/gas/HyperlaneIgpChecker.ts

We recently started checking the owner for every ownable contract.
This broke CI since StorageGasOracle's owner is not expected to match the configured config owner.
None

Do not check StorageGasOracle's owner

---

.github/workflows/node.yml
typescript/infra/scripts/deploy.ts
typescript/sdk/src/utils/objects.ts

Follow-up to #2062, fixes an issue where `pick` inserts a key into an object that wasn't originally present. 
This was causing HyperlaneApps to be instantiated with undefined addresses, which caused the fork tests to fail.
Also skips fork testing ICAs/IQS due to the IGP mismatch error

Fix fork tests 2, fixier

---

typescript/sdk/src/contracts.ts
typescript/sdk/src/index.ts

attachContractsMap should filter out chains for which a complete set of addresses is not present
None

Fix SDK attachContractsMap bug

---

typescript/utils/src/utils.ts

Fixes a bug in which processes (e.g. e2e test) would hang until the timeout completed

Clear timeout in runWithTimeout

---

rust/agents/relayer/src/settings/mod.rs

Fixes a bug where we were first parsing the matching list as a string and then trying to convert it which was impacting the expected config type.
None
- https://discord.com/channels/935678348330434570/1096400530722537513
Yes
None
Unit Tests

Fix payment enforcement config parsing bug

---

rust/hyperlane-core/tests/chain_config.rs

Forgot this in the other PR, just adds a link to the reference when there is a parsing error.
None
- From #2070 
Yes
None
None

Add link to reference

---

rust/hyperlane-base/src/settings/loader.rs
rust/hyperlane-core/tests/chain_config.rs

Minor fix to docs URL linked to by configuration errors.
None
- https://discord.com/channels/935678348330434570/1096400530722537513
Yes
None
None

Fix docs link

---

typescript/sdk/src/contracts.ts

Currently we say that filterAddressesMap must take a AddressesMap<F> but it really takes AddressesMap<any> and outputs AddressesMap<F>
None

filterAddressesMap takes arbitrary addresses map

---

solidity/tsconfig.json

Fixes `yarn build` failing on `main`
https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/4765379482/jobs/8471042324

Try adjusting core tsconfig

---

typescript/infra/scripts/funding/fund-keys-from-deployer.ts

We increased the desired balances for relayers on L2s significantly to 0.5. The target key funder balance for L2s was previously 10x the relayer target balance - we probably shouldn't be bridging over 5 ETH. This lowers the multiplier to 5, so that we shoot for a 2.5 ETH key funder balance on L2s
none
n/a
Yes
None
None

Lower L2 funding multiplier from 10 to 5

---

solidity/test/isms/DomainRoutingIsm.t.sol

Fixes a bug in the DomainRoutingIsm tests that curiously only started showing in CI a few days ago.
None

Fix DomainRoutingIsm tests

---

rust/sealevel/Cargo.lock
rust/sealevel/libraries/multisig-ism/Cargo.toml
rust/sealevel/libraries/multisig-ism/src/interface.rs
rust/sealevel/libraries/multisig-ism/src/lib.rs
rust/sealevel/programs/ism/multisig-ism-message-id/src/instruction.rs
rust/sealevel/programs/ism/multisig-ism-message-id/src/processor.rs
rust/sealevel/programs/ism/multisig-ism-message-id/tests/functional.rs

* #2253 for the Multisig ISM's validators and threshold instruction
None
- Fixes #2253 - final PR for that transition
Yes
None
Unit Tests

Multisig ISM discriminator instructions

---

rust/Cargo.lock
rust/hyperlane-base/Cargo.toml
rust/hyperlane-base/src/settings/aws_credentials.rs
rust/hyperlane-base/src/settings/mod.rs
rust/hyperlane-base/src/settings/signers.rs
rust/hyperlane-base/src/types/s3_storage.rs

Support of web identity AWS credentials: https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2168
`WebIdentityProvider` resides in `rusoto_sts`, I had to add a dependency on `rusoto_sts = "*"`.
Yes. The newly added `AwsChainCredentialsProvider` preserves 100% compatibility with clients using `EnvironmentProvider`. We tested the following scenarios:
1) Run agent with `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY` / `AWS_SESSION_TOKEN` credentials — the current default behavior  — works as before.
2) Without envs from p.1 but with `AWS_WEB_IDENTITY_TOKEN_FILE` / `AWS_ROLE_ARN` / `AWS_ROLE_SESSION_NAME` injected by AWS EKS pod identity [webhook](https://github.com/aws/amazon-eks-pod-identity-webhook) — works well. We ran the agents for 24+ hours …

feat: support WebIdentityProvider for AWS credentials [#2168].

---

rust/sealevel/libraries/message-recipient-interface/src/lib.rs
rust/sealevel/programs/hyperlane-sealevel-token/src/processor.rs
rust/sealevel/programs/recipient/echo/src/lib.rs

Final component of #2254 
Still need to actually move warp routes over, but going to do that as a part of the effort in #2219 
no
- Fixes #2254
Yes
None
Unit Tests

Message recipient `handle` account meta getter instructions

---

rust/helm/agent-common/templates/_helpers.tpl
rust/helm/hyperlane-agent/templates/external-secret.yaml
rust/helm/hyperlane-agent/templates/relayer-external-secret.yaml
rust/helm/hyperlane-agent/templates/scraper-external-secret.yaml
rust/helm/hyperlane-agent/templates/validator-external-secret.yaml
rust/helm/hyperlane-agent/values.yaml

This PR makes the SecretStore type as configurable for all external secrets instead of using fixed `ClusterSecretStore` type.
No
`externalSecrets.clusterSecretStore` should be replaced with `externalSecrets.StoreName` in the values.
None
Manual

feat(helm): Support configurable SecretStore type

---

rust/chains/hyperlane-sealevel/src/mailbox.rs
rust/sealevel/Cargo.lock
rust/sealevel/libraries/message-recipient-interface/src/lib.rs
rust/sealevel/programs/hyperlane-sealevel-token-native/src/processor.rs
rust/sealevel/programs/hyperlane-sealevel-token/src/processor.rs
rust/sealevel/programs/mailbox/Cargo.toml
rust/sealevel/programs/mailbox/src/accounts.rs
rust/sealevel/programs/mailbox/src/instruction.rs
rust/sealevel/programs/mailbox/src/lib.rs
rust/sealevel/programs/mailbox/src/pda_seeds.rs
rust/sealevel/programs/mailbox/src/processor.rs
rust/sealevel/programs/recipient/echo/src/lib.rs

* Fixes #2209 
* The relayer doesn't yet get the list of account metas that the ISM.verify instruction uses - this is coming next!
* Removes the ism / ism_accounts from the Inbox data & replaces with just "default_ism"
no
- Fixes #2209
Yes
None
Unit Tests & ran end to end locally 😎

Relayer and Mailbox program supports fetching of recipient isms

---

rust/chains/hyperlane-sealevel/src/mailbox.rs
rust/sealevel/Cargo.lock
rust/sealevel/Cargo.toml
rust/sealevel/libraries/access-control/Cargo.toml
rust/sealevel/libraries/access-control/src/lib.rs
rust/sealevel/programs/ism/multisig-ism-message-id/Cargo.toml
rust/sealevel/programs/ism/multisig-ism-message-id/src/accounts.rs
rust/sealevel/programs/ism/multisig-ism-message-id/src/instruction.rs
rust/sealevel/programs/ism/multisig-ism-message-id/src/processor.rs
rust/sealevel/programs/ism/multisig-ism-message-id/tests/functional.rs
rust/sealevel/programs/mailbox/Cargo.toml
rust/sealevel/programs/mailbox/src/accounts.rs
rust/sealevel/programs/mailbox/src/instruction.rs
rust/sealevel/programs/mailbox/src/processor.rs

* Adds an `AccessControl` trait in a new `access-control` library
* Makes the Mailbox support ownership, and requires default ISM setting to be done by the owner
* Moves the multisig ism to using the AccessControl library
no
- Sets the scene for #2218
Yes
None
Unit Tests & ran end to end

Add access control library, make Mailbox default ISM setting only owner

---

rust/hyperlane-base/src/contract_sync/cursor.rs
rust/utils/run-locally/src/main.rs

This PR fixes a bug in the MessageSyncCursor rewind logic that causes the cursor to get stuck.
The cursor would look for the message with nonce `n`, find it, and move its `next_block` to the block `b_n` at which `n` was dispatched.
It would then index starting at `b_n`, find `n` again, interpret that as a "discontinuity", and rewind back to `b_n`, getting itself stuck permanently.
We *should* be moving to `b_n` and not e.g. `b_n + 1` because we have no guarantee that `n+1` was not also present in `b_n` but just dropped by a flaky `eth_getLogs` implementation.
The fix is to only consider messages with nonce > `n` when looking for discontinuities when our target nonce is `n + 1`.
- Modifies the E2E tests to use a chunk size of 1, allowing us to reproduce this failure mode without the …

Fix bug in MessageSyncCursor rewind logic

---

rust/chains/hyperlane-sealevel/src/mailbox.rs
rust/sealevel/client/src/main.rs
rust/sealevel/libraries/access-control/src/lib.rs
rust/sealevel/programs/mailbox/src/accounts.rs
rust/sealevel/programs/mailbox/src/pda_seeds.rs
rust/sealevel/programs/mailbox/src/processor.rs
rust/utils/sealevel-test.bash

* When a message is processed, a PDA based off its message ID is created
* I decided to put the actual message ID in the contents of the account to make indexing possible, and added a sequence number in there based off the # of processed messages so that indexing is easier
* Removed the `delivered` hashmap
n/a
- Fixes #2208 
Yes
None
Unit Tests, works end to end

Mailbox PDA for each message that is processed

---

rust/agents/relayer/src/msg/processor.rs

Ensures the relayer never attempts to process a message destined for it's own origin domain.
- Fixes https://github.com/hyperlane-xyz/issues/issues/464
Yes
E2E tests

Add origin filter to relayer msg processor

---

rust/hyperlane-base/src/contract_sync/cursor.rs

RPC providers can be inconsistent. When a message has just been inserted into the mailbox, it's possible that one Mailbox.count() query returns N and a subsequent query returns N-1.
None

Gracefully handle inconsistent RPC providers in ForwardMessageSyncCursor

---

rust/chains/hyperlane-sealevel/src/mailbox.rs
rust/sealevel/client/src/main.rs
rust/sealevel/libraries/hyperlane-sealevel-token/src/accounts.rs
rust/sealevel/libraries/hyperlane-sealevel-token/src/instruction.rs
rust/sealevel/libraries/hyperlane-sealevel-token/src/processor.rs
rust/sealevel/programs/hyperlane-sealevel-token/tests/functional.rs
rust/sealevel/programs/mailbox/src/instruction.rs
rust/sealevel/programs/mailbox/src/pda_seeds.rs
rust/sealevel/programs/mailbox/src/processor.rs

Before this PR, the Mailbox supported multiple different local domains. This moves to a single canonical local domain for the program's deployment
n/a
- Fixes #2204 
Yes
None
Unit Tests & ran end to end

Enforce a single local domain in the Mailbox

---

rust/agents/scraper/src/db/message.rs
rust/hyperlane-base/src/contract_sync/cursor.rs

Goerli had a message dispatched (nonce=1964) with a destination domain that failed to be converted from i32 to u32 when being retrieved from the database. This fixes these bugs for domain ids and nonce and improves logs for this type of failure.
Scraper needs to be redeployed
Ran scraper locally against read replica of explorer DB

Fix bug in postgres message coercion

---

rust/Cargo.lock
rust/Cargo.toml
rust/chains/hyperlane-ethereum/src/signers.rs
rust/ethers-prometheus/Cargo.toml
rust/hyperlane-base/src/settings/mod.rs
rust/hyperlane-base/src/settings/signers.rs

- Update ethers-rs fork
- Create new KMS client instead of using OnceCell
Yes
No
Running validator locally with replica of validator DB

Fix AWS KMS Signer connection issues

---

rust/README.md

Update rust README with instructions for running agents locally against cloud resources.

Add instructions for running agents locally against cloud resources to `rust/README`

---

rust/chains/hyperlane-ethereum/src/mailbox.rs
rust/chains/hyperlane-sealevel/src/interchain_security_module.rs
rust/chains/hyperlane-sealevel/src/mailbox.rs
rust/hyperlane-base/src/db/rocks/hyperlane_db.rs
rust/hyperlane-base/src/settings/signers.rs
rust/hyperlane-base/src/settings/trace/mod.rs
rust/sealevel/libraries/hyperlane-sealevel-token/src/accounts.rs
rust/sealevel/libraries/hyperlane-sealevel-token/src/instruction.rs
rust/sealevel/libraries/hyperlane-sealevel-token/src/message.rs
rust/sealevel/libraries/interchain-security-module-interface/src/lib.rs
rust/sealevel/libraries/message-recipient-interface/src/lib.rs
rust/sealevel/libraries/multisig-ism/src/interface.rs
rust/sealevel/libraries/serializable-account-meta/src/lib.rs
rust/sealevel/programs/hyperlane-sealevel-token-collateral/src/plugin.rs
rust/sealevel/programs/hyperlane-sealevel-token/src/plugin.rs
rust/sealevel/programs/ism/multisig-ism-message-id/src/error.rs
rust/sealevel/programs/ism/multisig-ism-message-id/src/processor.rs
rust/sealevel/programs/mailbox/src/accounts.rs
rust/sealevel/programs/mailbox/src/processor.rs

Finally caved and ran `cargo clippy` in `rust/` and `rust/sealevel`, this includes the fixes
Removed console logging from the TracingConfig which was added earlier & doesn't seem to be needed
n/a
Yes
None
Clippy is satisfied so I am too

Sealevel - make clippy happy

---

rust/chains/hyperlane-ethereum/src/rpc_clients/mod.rs

Adds a fix for this error message I noticed in the logs:
```
(code: 3, message: execution reverted: INSUFFICIENT_BALANCE, ...)
```
None
Yes
None
None

Handle additional error case in retrying provider

---

rust/chains/hyperlane-ethereum/src/interchain_security_module.rs
rust/chains/hyperlane-ethereum/src/mailbox.rs
rust/chains/hyperlane-ethereum/src/multisig_ism.rs
rust/chains/hyperlane-ethereum/src/routing_ism.rs

Seeing a ton of errors for process estimate costs even though they are fully being handled elsewhere and are also not really an error in the first place. This makes it harder as an operator to spot real errors so I think we should eliminate this error log. (We also already log this error elsewhere so it does not add any new information).
This also targets the `ret` logs produced by tracing since many of them are unhelpful and most of the cases where we actually need a log we already have one.
None
Yes
None
None

Reduce log noise

---

rust/chains/hyperlane-sealevel/src/mailbox.rs
rust/sealevel/Cargo.lock
rust/sealevel/client/Cargo.toml
rust/sealevel/client/src/main.rs
rust/utils/sealevel-test.bash

Starts using the multisig-ism-message-id ISM in the end to end tests
- Fixes #2317 
- Fixes #2348
Yes
None
Ran end to end

Use multisig ism message ID in end to end setup

---

rust/chains/hyperlane-ethereum/src/singleton_signer.rs
rust/hyperlane-base/src/settings/signers.rs

- configures hyper http client to close connections after 20s
- makes singleton signer retry (5) times before bubbling error up
Yes
Local binary testing against cloud resources

Reduce hyper client pool idle timeout to 20s

---

rust/agents/validator/src/submit.rs

Observed in validator
```
Request ID: Some("c0cc123e-da52-47f4-a2d3-aeddd034a2f5") Body: {"__type":"ThrottlingException","message":"You have exceeded the rate at which you may call KMS. Reduce the frequency of your calls."}
```
- Add sleep and checkpoint sync cache for rate limit
- Skip tree in checkpoint submitter span
Yes
Local testing

Prevent AWS KMS throttling in validator

---

rust/chains/hyperlane-sealevel/src/mailbox.rs
rust/hyperlane-base/src/settings/chains.rs
rust/sealevel/README.md
rust/sealevel/client/src/main.rs

* moved to using little endian encoding of some variables in the `DispatchedMessage` struct in the agents to match what's done on-chain
* Noticed an inaccurate config error message
* the `token enroll-remote-router` command now accepts H256 hex strings and pubkeys
no
none
Yes
None
e2e test

Accurately use little endian encoding of nonce / slot in DispatchedMessage, small fixes

---

typescript/sdk/src/ism/HyperlaneIsmFactory.ts
typescript/sdk/src/middleware/liquidity-layer/LiquidityLayerRouterDeployer.ts
typescript/sdk/src/router/GasRouterDeployer.ts
typescript/sdk/src/router/HyperlaneRouterChecker.ts
typescript/sdk/src/router/HyperlaneRouterDeployer.ts
typescript/sdk/src/router/types.ts

To accommodate warp routes that exist on EVM chains *and* other execution environments, we need the ability to enroll remote routers on EVM-based routers that weren't deployed by the router deployer. This adds a new optional `foreignDeployment` property to the `RouterConfig`, which means that deployment will not be attempted to this chain, but it will be enrolled as a remote router on any contracts that are deployed to. The general flow looks something like:
* Deploy the warp route contracts on all EVM chains, enrolling each other as routers
* Deploy the warp route contracts on the alt execution environment chains, also configuring the existing EVM contract deployments as `foreignDeployment`s so that they are enrolled as routers on the alt execution environment contracts
* Now equipped …

Existing deployment support in Router tooling, small ISM factory fixes

---

rust/agents/relayer/src/msg/pending_message.rs

Closes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2090
Recent improvements from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2195 already catch the error in that user report. This PR just adds a hint as to why fetching may have failed; in that report, the user's `fallback` function was returning an empty value which caused casting to an `address` to fail and revert, so the error occurs because the returned value is malformed.
Thanks to @tkporter for walking me through the contracts to better understand the scope of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2090.

chore(relayer): improve ISM address error message

---

rust/hyperlane-base/src/settings/chains.rs

If you don't specify a connection config, atm the error message says you're missing the `domain`. I ran into this previously and found it hard to debug; a validator operator in discord also ran into this
n/a
n/a
Yes
None
None

Fix misleading config error to do with connection configs

---

typescript/token/src/config.ts
typescript/token/src/deploy.ts

Just copying the changes from https://github.com/hyperlane-xyz/hyperlane-token/pull/73, which I unfortunately didn't get in before the absorption
In the name of #2366 
Yes
None
Unit Tests, used it in hyperlane-deploy when deploying synthetic tokens relating to a collateral warp route that lives on Solana

Use configured collateral token metadata

---

rust/hyperlane-base/src/contract_sync/eta_calculator.rs

It was observed that this function can be called with a `last_block` that is greater than the `currenct_block`, which results in an underflow. Use saturating math to prevent this.
Yes
None
None

fix(contract_sync): saturating math in eta calculator

---

rust/agents/validator/src/validator.rs
rust/chains/hyperlane-ethereum/src/validator_announce.rs
rust/hyperlane-core/src/traits/validator_announce.rs
rust/hyperlane-test/src/mocks/validator_announce.rs

It has been reported that `contract_call.tx.max_cost()` can fail / not exist on some networks. When that's the case, default to assuming no additional validator gas is required and just send the tx. If the tx fails, report the failure and suggest that gas may be insufficient in the logged error.
None
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2426
Yes
None
None

fix(validator): announce directly if no gas estimate

---

rust/sealevel/client/src/cmd_utils.rs
rust/sealevel/client/src/core.rs
rust/sealevel/client/src/warp_route.rs

Using the current stable Solana version, the usage of --upgrade-authority changed
(new version after running `sh -c "$(curl -sSfL https://release.solana.com/stable/install)"`
```
$ solana --version
solana-cli 1.14.20 (src:87ce9bb7; feat:1879391783)
```
n/a
n/a
Yes
None
Unit Tests, e2e tests

Fix client's usage of `--upgrade-authority` with stable version of solana-cli

---

typescript/sdk/src/index.ts
typescript/sdk/src/metadata/agentConfig.test.ts
typescript/sdk/src/metadata/agentConfig.ts

- Change buildAgentConfig to create a combined new + old config schema
- Add unit tests for buildAgentConfig utils
Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2524

Update buildAgentConfig for backwards compat

---

typescript/infra/config/environments/testnet3/core.ts
typescript/sdk/src/deploy/HyperlaneDeployer.ts

- Deployed the AggregationISM configured with default multisig validators on Testnet
- Fixed edge case of handling zero address for `connectionClient.interchainSecurityModule`
- Fixes #2477
Yes
Manual

Deploy AggregationISM to testnet3 core

---

typescript/infra/config/environments/mainnet2/agent.ts
typescript/infra/config/environments/testnet3/agent.ts

- Updating both rc and hyperlane testnet3 and mainnet2 versions for relayers and validators to `ed7569d-20230725-171222` image which has the necessary changes for `AggregationISM` and `NullMetadataISM`
None
- Release: https://github.com/hyperlane-xyz/hyperlane-monorepo/releases/tag/agents-2023-07-25
Yes
Manual

Updating the relayer and validator images to 2023-07-25 version

---

rust/utils/run-locally/src/ethereum.rs

Fixes a minor bug when testing locally where sometimes a failure in the e2e test will not correctly clean up anvil. This just runs `pkill -SIGKILL anvil` to clean it up if it was running.
None
Yes
Manual

E2E test `pkill` anvil

---

.husky/pre-commit
rust/hyperlane-core/src/accumulator/incremental.rs

Tired of the workflow telling you to run `cargo fmt`? Worry no more, now on commit all your rust code will get checked so you don't have to wait for the pipeline to fail.
None
Yes
manual

Run rust fmt on pre-commit

---

rust/agents/validator/src/settings.rs
rust/agents/validator/src/validator.rs

This handles a bug where we did not default the chain signer to the validator signature for EVM chains and also handles the case where we might try to announce without setting a chain signer for other chains.
Not really a change but I looked into #2457 and I noticed the validators already check that signers are set for all destination chains so I think the error was just for validators which this PR fixes.
- Fixes #2458
- Fixes  #2457
Yes
Unit Tests

Validator announce signers

---

rust/agents/relayer/src/relayer.rs
rust/agents/scraper/src/agent.rs
rust/agents/validator/src/validator.rs
rust/chains/hyperlane-ethereum/src/interchain_gas.rs
rust/chains/hyperlane-ethereum/src/mailbox.rs
rust/chains/hyperlane-fuel/src/interchain_gas.rs
rust/chains/hyperlane-fuel/src/mailbox.rs
rust/chains/hyperlane-sealevel/src/interchain_gas.rs
rust/chains/hyperlane-sealevel/src/mailbox.rs
rust/hyperlane-base/src/contract_sync/cursor.rs
rust/hyperlane-base/src/contract_sync/mod.rs
rust/hyperlane-base/src/settings/chains.rs
rust/hyperlane-core/src/chain.rs
rust/hyperlane-core/src/traits/cursor.rs
rust/hyperlane-core/src/traits/indexer.rs

This reverts commit 127294decc4077982c82044847ab6165c74c2ba0, to include a cursor bugfix in main and remove an IGP indexing bug added by that PR.

Revert "refactor(IndexMode): remove `IndexRange`… (#2562)"

---

rust/sealevel/libraries/hyperlane-sealevel-token/src/instruction.rs
rust/sealevel/libraries/hyperlane-sealevel-token/src/processor.rs
rust/sealevel/programs/hyperlane-sealevel-token-collateral/src/processor.rs
rust/sealevel/programs/hyperlane-sealevel-token-collateral/tests/functional.rs
rust/sealevel/programs/hyperlane-sealevel-token-native/src/processor.rs
rust/sealevel/programs/hyperlane-sealevel-token-native/tests/functional.rs
rust/sealevel/programs/hyperlane-sealevel-token/src/processor.rs
rust/sealevel/programs/hyperlane-sealevel-token/tests/functional.rs

Sadly I missed adding an instruction to allow a warp route owner to set the IGP. This adds that. We're deploying a warp route without an IGP for now because the UI hasn't been updated to work with IGP payments yet (which is required as the UI needs to handcraft specific accounts that are passed in). We'll probably wanna flip the switch to charging gas at some point, so want to make sure we're able to do that
The way the tests are set up involves a lot of code duplications - sorry 🙈 - we should revisit at some point as now isn't the time
n/a
Related #2613 
Fully backward compatible
Unit / functional tests

Add SetInterchainGasPaymaster instruction to warp route programs

---

typescript/infra/config/aggregationIsm.ts
typescript/infra/config/environments/mainnet2/agent.ts
typescript/infra/config/environments/mainnet2/chains.ts
typescript/infra/config/environments/mainnet2/gas-oracle.ts
typescript/infra/config/environments/mainnet2/igp.ts
typescript/infra/config/environments/test/agent.ts
typescript/infra/config/environments/test/chains.ts
typescript/infra/config/environments/testnet3/agent.ts
typescript/infra/config/environments/testnet3/chains.ts
typescript/infra/config/environments/testnet3/gas-oracle.ts
typescript/infra/config/environments/testnet3/igp.ts
typescript/infra/config/environments/testnet3/owners.ts
typescript/infra/scripts/agents/utils.ts
typescript/infra/scripts/funding/fund-keys-from-deployer.ts
typescript/infra/src/agents/index.ts
typescript/infra/src/agents/key-utils.ts
typescript/infra/src/config/agent/agent.ts
typescript/infra/src/config/agent/relayer.ts
typescript/infra/src/roles.ts
typescript/sdk/src/consts/chains.ts

In addition to the context, also configure the **chains** that an agent is deployable to.
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2664
Dry-ran the script for the three agents. Output for the validator looks wrong though:
```
% npx ts-node typescript/infra/scripts/agents/deploy-agents.ts -e mainnet2 -r validator --dry-run
undefined
```

Specify per-agent chains to deploy to in deploy-agents

---

typescript/infra/config/environments/mainnet2/validators.ts
typescript/infra/config/environments/testnet3/validators.ts

Adds addresses of the rc validator keys for solana, nautilus and their testnet counterparts

Solana and Nautilus RC validators

---

rust/Dockerfile

Process user used in Dockerfile can now read and write to any volume mounted under the `/data/` directory.
N/A
Fixes: 2691
Yes
Manual
I've built the image locally and tested that we can mount any kind of docker volume under the `/data/` directory

fix: Add data directory owned by user 1000

---

typescript/infra/src/deployment/deploy.ts

- Currently if you do keyboard interrupt while running the deploy script, none of the already deployed addresses get written to the artifacts.
- Register a SIGINT handler in the `deployWithArtifacts` script
None
None
Yes
Manual

Handling Ctrl+C while deploying 

---

rust/agents/relayer/src/settings/matching_list.rs
typescript/sdk/src/metadata/customZodTypes.ts

Fixes a current deployment issue due to some changes in the infra deployment.
Also caught an error in the schema for the matching list type and updated it.

Support base58 in matching list

---

rust/chains/hyperlane-sealevel/src/interchain_gas.rs
rust/hyperlane-base/src/contract_sync/eta_calculator.rs

Removes some unnecessary logs from the sealevel igp indexing fn. Also instruments the eta calculator in response to https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2723

chore(sealevel igp indexing): reduce log verbosity

---

rust/hyperlane-base/src/contract_sync/eta_calculator.rs

the `debug!` logs either are not occurring very often, or are not displayed at all in the gcp logs

use `warn` logging level for eta errors

---

solidity/contracts/hooks/MerkleTreeHook.sol
solidity/test/MerkleTreeHook.t.sol
solidity/test/merkle.test.ts

- Adding "InsertedIntoEvent" for standalone indexing of events by the agents
None
#2313 
Yes
Unit tests

add InsertedIntoTree event

---

typescript/infra/config/environments/mainnet2/agent.ts
typescript/infra/config/environments/testnet3/agent.ts

New relayer gas payment policies for testnet3 and mainnet2, based on these rules:
- ~~leave `PJH5QAbxAqrrnSXfH3GHR8icua8CDFZmo97z91xmpvx` in the `GasPaymentEnforcementPolicyType.None` matching list until we move its ownership~~
- don't enforce gas payments:
- from the helloworld router on solanadevnet
- from solana devnet and mainnet warp routes to anything
- with the exception of `EJqwFjvVJSAxH8Ur2PYuMfdvoJeutjmH6GkoEFQ4MdSa`, which now has an igp configured (`HksFWQM1EXJJ5mxo2uZoMfmksXHaNhCunh71NqcQQHZ8`)
- from the bsc/bsctestnet routers of all the warp routes
- for interchain queries on both testnet3 and mainnet2
- Fixes https://github.com/hyperlane-xyz/issues/issues/570
Yes
None

chore: new relayer gas policies

---

rust/chains/hyperlane-sealevel/src/interchain_gas.rs
rust/sealevel/client/src/main.rs
rust/utils/run-locally/src/solana.rs
typescript/infra/config/environments/mainnet2/agent.ts

- Some small changes to help with debugging sealevel IGP
- Turns out the GasPaymentAccount data format onchain is different from the one in `main`. This causes IGP indexing to not work in the wild, but it works in e2e. Because we were planning to change the IGP anyways as we transfer ownership to Zebec, this isn't so bad - so temporarily just not enforcing ZBC warp route Solana -> Nautilus gas payments. In practice, we're still effectively enforcing gas payments because the warp route will pay for gas
- Also added the new BSC POSE addy
n/a
yes
Deployed, poked around, used cmds

Sealevel IGP debugging, temporarily change Sealevel gas payment policy

---

solidity/contracts/client/Router.sol
solidity/contracts/isms/routing/DefaultFallbackRoutingIsm.sol
solidity/contracts/isms/routing/DomainRoutingIsm.sol
solidity/hardhat.config.ts
solidity/test/isms/DomainRoutingIsm.t.sol
solidity/test/router.test.ts
typescript/sdk/src/ism/HyperlaneIsmFactory.ts

Introduces explicit removal to Routers and Routing ISMs
- Fixes https://github.com/hyperlane-xyz/issues/issues/630
Yes
Unit tests

Add unenroll to Router

---

typescript/token/src/adapters/SealevelTokenAdapter.ts

Because incremental merkle tree insertion complexity can change depending on what the index in the merkle tree is, we ran into a situation where the 200k default compute limit wasn't enough when trying to perform a transfer remote on sealevel.
Normal cost for index 257, about 158k units:
https://explorer.solana.com/tx/4oB9b6PaaKvGMhrQS7XGmi7zBpX3GUW99sbVrSjFwm5AVT96emKF4NH6gn2y9cLMLep8wQJ9LqwJifG5QMpr4BAs
Index 255, about 245k units!: https://explorer.solana.com/tx/3v6SbrT58smwnLdnrEFaMXowaEDmo6EpPmKFTUMe9aESo5FTExmJdr2uMH5QJW9hnZTqrB1mfFZe4Vmu75CCAyPs
The fix is to simply request more units. Solana tx fees don't actually charge you more if you use more units. Txs have a global cap of 1.4M units -- I'm just requesting 1M here as a balance between having lots of units & not bricking …

Request 1M compute units in transfer remote

---

rust/helm/hyperlane-agent/templates/external-secret.yaml
typescript/infra/config/environments/testnet4/infrastructure.ts

- a single external-secrets instance lives on the cluster, and we are running testnet3 and testnet4 on the same cluster
- json parsing errors were silently swallowed, moved to `mustFromJson` to prevent this
n/a

still allow getting testnet3 secrets via externalsecrets, use `mustFromJson` in helm templates

---

typescript/infra/config/environments/testnet3/agent.ts
typescript/infra/config/environments/testnet3/chains.ts

- Rpc urls are super flaky, stopping the validators and relayer support
- Keeping proteustestnet artifacts / chain metadata for now

Stop running proteustestnet agents

---

rust/helm/hyperlane-agent/templates/_helpers.tpl
rust/helm/hyperlane-agent/templates/validator-configmap.yaml
rust/helm/hyperlane-agent/templates/validator-external-secret.yaml
rust/helm/hyperlane-agent/templates/validator-statefulset.yaml

* polygonzkevmtestnet's validator name was too long because of the `controller-revision-hash` label, see https://github.com/kubernetes/kubernetes/issues/64023
* Seeks to preserve the `-validator` suffix in the name, but truncates the earlier bit - in practice this results in validator pods like `polygonzkevmtestnet-validator-hyperlane-ag-validator-0`. This felt like the most backward compatible change -- of course we could consider trying to get a name like `polygonzkevmtestnet-hyperlane-agent-validator-0` but this would break backward compatibility more dramatically because we'd need to change all the other validator pods. Imo we should just really avoid long chain names or consider a more breaking change to our infra
n/a
n/a
Mostly
Deployed

Fix long validator name for polygonzkevmtestnet

---

rust/agents/relayer/src/msg/processor.rs
rust/agents/validator/src/submit.rs
rust/agents/validator/src/validator.rs
rust/chains/hyperlane-ethereum/src/interchain_gas.rs
rust/chains/hyperlane-ethereum/src/mailbox.rs
rust/chains/hyperlane-ethereum/src/merkle_tree_hook.rs
rust/hyperlane-base/src/db/rocks/hyperlane_db.rs
rust/hyperlane-base/src/settings/chains.rs
rust/hyperlane-base/src/settings/parser/mod.rs

* https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/532 wasn't actually fully closed out - finality_blocks was used still for indexing. Sadly testnet4 infra wasn't configuring finality blocks anymore, so we weren't indexing only finalized blocks. Moved fully to reorg_period
* Refactored `checkpoint_submitter` in light of races revealed by the above ^ problem. It used to assume that message indexing and the `latest_checkpoint()` call would align with one another, and wasn't resilient to the tree already being past the correctness checkpoint. A couple situations were possible before that aren't now:
a. Indexing is ahead of the latest_checkpoint() call, which will result in tree ingesting the new indexed messages and the tree being ahead of the correctness checkpoint :(
b. It's …

Rm finality blocks and refactor checkpoint_submitter to be resilient to edge cases

---

rust/agents/validator/src/submit.rs
rust/hyperlane-base/src/settings/trace/mod.rs

Hides some cosmos logs from debug level
Only shows submission logs if there is queue in the checkpoint submitter

Less noisy logs

---

rust/config/mainnet3_config.json

Adds a key in there that if it has funds, can be used the announce. Otherwise the operator has to specify their own key or somebody else has to announce

Add announcement key in config

---

rust/Cargo.lock
rust/chains/hyperlane-cosmos/src/interchain_gas.rs
rust/chains/hyperlane-cosmos/src/mailbox.rs
rust/chains/hyperlane-cosmos/src/merkle_tree_hook.rs
rust/chains/hyperlane-cosmos/src/providers/rpc.rs
rust/hyperlane-core/Cargo.toml
rust/hyperlane-core/src/error.rs
rust/hyperlane-core/src/types/mod.rs
rust/hyperlane-core/src/types/primitive_types.rs

fix: progress on removing unwraps

---

rust/chains/hyperlane-cosmos/src/aggregation_ism.rs
rust/chains/hyperlane-cosmos/src/error.rs
rust/chains/hyperlane-cosmos/src/lib.rs
rust/chains/hyperlane-cosmos/src/libs/verify.rs
rust/chains/hyperlane-cosmos/src/mailbox.rs
rust/chains/hyperlane-cosmos/src/merkle_tree_hook.rs
rust/chains/hyperlane-cosmos/src/multisig_ism.rs
rust/chains/hyperlane-cosmos/src/providers/grpc.rs
rust/chains/hyperlane-cosmos/src/providers/rpc.rs
rust/chains/hyperlane-cosmos/src/routing_ism.rs
rust/chains/hyperlane-cosmos/src/signers.rs
rust/chains/hyperlane-cosmos/src/validator_announce.rs
rust/hyperlane-base/src/settings/signers.rs
rust/hyperlane-core/src/error.rs

- Removes unwraps and expects from everywhere but `run-locally`
- Precomputes the `address` in `Signer` at construction time, to propagate the error early and keep signatures ergonomic by not requiring a `Result`. Couldn't also precompile `SigningKey` (the privkey type) because it's not `Sync` 😢
- Defines a `hyperlane-cosmos`-specific error enum (`HyperlaneCosmosError`), which can be converted to `ChainCommunicationError` with the `?` operator. This is a pattern we'd like to refactor towards in the future, to remove dependencies from `hyperlane-core` as much as possible
- One inconvenience is that you need to `.map_err()` to `HyperlaneCosmosError` first, to use `?`. I wish `?` had deref coercion semantics where it'd keep covnerting until an error matches, but I assume this isn't possible …

refactor: finish removing unwraps

---

rust/chains/hyperlane-cosmos/src/interchain_gas.rs
rust/chains/hyperlane-cosmos/src/mailbox.rs
rust/chains/hyperlane-cosmos/src/merkle_tree_hook.rs
rust/chains/hyperlane-cosmos/src/providers/rpc.rs
rust/config/mainnet3_config.json
rust/config/testnet4_config.json
rust/hyperlane-base/src/settings/chains.rs

Hopeful quick fix to indexing issues we're seeing. Leading theory is that the tx_search is asking for a block range that the servicing RPC node doesn't actually have state for.
Curious if @nambrot you feel we should go with a more conservative reorg period, maybe 2 blocks?
My personal theory is that this isn't just bad RPC load balancing, but that the tip that's returned is simply committed to but the state transition hasn't yet been executed, see https://github.com/CosmWasm/cosmwasm/blob/main/SEMANTICS.md#sdk-context
> First, the Tendermint engine will seek 2/3+ consensus on a list of transactions to be included in the next block. This is done without executing them. They are simply subjected to a minimal pre-filter by the Cosmos SDK module, to ensure they are validly formatted …

Correctly consider reorg period when indexing, set reorg period to 1 on Neutron

---

typescript/sdk/package.json
typescript/sdk/src/ism/HyperlaneIsmFactory.ts
yarn.lock

- Removes FS introduced by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2826
- No, breaks Op Ism recovery
- Opens https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2898
None

Remove FS dep from sdk

---

.github/workflows/agent-release-artifacts.yml
.github/workflows/e2e.yml
.github/workflows/mergify.yml.bak
.github/workflows/monorepo-docker.yml
.github/workflows/node.yml
.github/workflows/rust-docker.yml
.github/workflows/rust-skipped.yml
.github/workflows/rust.yml
rust/utils/run-locally/src/cosmos/mod.rs
rust/utils/run-locally/src/cosmos/utils.rs

Size of rust build exceeds the storage space in the `ubuntu-latest` runner. `larger-runner` has more storage, but let's see if it also has all the system dependencies required to build

chore: use larger runner for github actions

---

rust/chains/hyperlane-cosmos/src/mailbox.rs
rust/utils/run-locally/src/cosmos/mod.rs

Adds "gas payment count" and "confirmed submitted messages" as termination invariants to the cw run-locally, to get the test to actually fail if messages are not delivered

Add cw run-locally invariants

---

typescript/cli/ci-test.sh
typescript/cli/src/consts.ts
typescript/cli/src/deploy/core.ts
typescript/cli/src/deploy/utils.ts
typescript/cli/src/deploy/warp.ts
typescript/cli/src/send/message.ts
typescript/cli/src/send/transfer.ts
typescript/cli/src/utils/balances.ts

- Check min gas on each chain in preflight

cli gas preflight

---

rust/config/mainnet3_config.json

RPC URLs on scroll max out at 1k

1k block chunk for scroll indexing

---

typescript/infra/config/environments/mainnet3/agent.ts
typescript/infra/config/environments/testnet4/agent.ts

Image from the latest PR to trevor/new-featv3-cosmos-oct-28, which is https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2912
This includes a fix to merkle tree indexing so it indexes it in the same way as messages

Deploy testnet4 & mainnet3 agents with image that includes merkle tree indexing fix

---

rust/chains/hyperlane-ethereum/src/mailbox.rs
rust/chains/hyperlane-ethereum/src/trait_builder.rs
rust/chains/hyperlane-ethereum/src/tx.rs
rust/chains/hyperlane-ethereum/src/validator_announce.rs

After investigating #2959, I found the following
this is a known problem with Polygon, explanation here https://github.com/ethers-io/ethers.js/issues/2828#issuecomment-1283014250
Fun fact Asa looked into this once https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/771
Here's a discussion it in Foundry, which I found hoping that ethers-rs folks had ran into this before
https://github.com/foundry-rs/foundry/issues/1703
Foundry fixed this by using the Polygon gas station oracle which seems to be recommended path https://github.com/foundry-rs/foundry/pull/3368/files#diff-c89a4bbf7a90da118dcf00c5fe70eba78f8e5d95662bb5f039a353113e95042bR205
There's actually a polygon ethers middleware for this https://docs.rs/ethers/latest/ethers/middleware/gas_oracle/polygon/struct.Polygon.html
So I …

Use Polygon gas oracle

---

typescript/helloworld/src/multiProtocolApp/sealevelAdapter.ts

We need to request a higher compute limit for certain message indexes that result in a higher # of internal nodes being hashed when inserting into the merkle tree. Similar issue as #2771
n/a
n/a
yes
none 😛

Use higher compute budget for helloworld sealevel

---

rust/Cargo.lock
rust/Cargo.toml

Cherry-picked the commit from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2903, which is now out of date
n/a
n/a
yes
we're running the relayer with an image off of https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2903

Update ethers-rs to use lower max priority fee

---

typescript/infra/config/environments/mainnet3/agent.ts
typescript/infra/config/environments/mainnet3/chains.ts
typescript/infra/config/environments/testnet4/agent.ts

Deploys w/ https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2998
- Had to remove mantapacific from the list of scraper chains because it's not present in the DB domain table atm
n/a
n/a
Deployed

Deploy new agents w/ Polygon gas fix

---

rust/Cargo.lock
rust/Cargo.toml

Uses a version of our ethers fork with https://github.com/hyperlane-xyz/ethers-rs/pull/10, which adds back a change that I had reverted from https://github.com/hyperlane-xyz/ethers-rs/pull/8
This is required to fix bsc / bsctestnet txs, where the base fee is 0 and we want to estimate the priority fee
n/a
n/a
ye
deployed and saw successful bsc / bsctestnet msgs

Use new ethers-rs version that should work with BSC

---

typescript/infra/config/environments/mainnet3/helloworld.ts
typescript/infra/config/environments/testnet4/helloworld.ts
typescript/infra/src/helloworld/kathy.ts

Deploy Kathy with #3001 
Small fix to deploy kathy successfully - because the relayer chains doesn't include neutron and kathy will try to create a multiprovider for all chains the env, we need to use the environment chain names as the helm `hyperlane.chains` value

Deploy kathy w/ PolygonZkEvm fix

---

.changeset/ninety-seas-chew.md
typescript/cli/src/config/ism.ts
typescript/cli/src/config/multisig.ts
typescript/cli/src/deploy/agent.ts
typescript/cli/src/deploy/core.ts
typescript/cli/src/utils/chains.ts

- don't restrict user to having two chains for ism config
- if the user accidentally picks two chains, we prompt them again to confirm if they don't want to use the hyperlane validators for their multisigconfig
None
- fixes https://github.com/hyperlane-xyz/issues/issues/811
Yes
Manual between arbitrumgoerli and anvil1

fix:don't prompt user for multisig config if chain is core

---

rust/chains/hyperlane-sealevel/src/error.rs
rust/chains/hyperlane-sealevel/src/interchain_gas.rs
rust/chains/hyperlane-sealevel/src/interchain_security_module.rs
rust/chains/hyperlane-sealevel/src/lib.rs
rust/chains/hyperlane-sealevel/src/mailbox.rs
rust/chains/hyperlane-sealevel/src/merkle_tree_hook.rs
rust/chains/hyperlane-sealevel/src/multisig_ism.rs
rust/chains/hyperlane-sealevel/src/provider.rs
rust/chains/hyperlane-sealevel/src/validator_announce.rs

Publishes sealevel balance as a relayer metric
**Drive-by Changes**
- Creates `HyperlaneSealevelError`, a `hyperlane-sealevel` specific type to avoid including sealevel errors in `hyperlane-core`'s `ChainCommunicationError`. It's pretty empty now, but we have a starting point now. This follows the approach used in `hyperlane-cosmos` too.
- Includes an rpc provider instance in `SealevelProvider`, and uses it to add `get_balance` on `SealevelProvider`.
**Testing**
None, as sealevel e2e is currently disabled

Sealevel balance metrics

---

rust/agents/relayer/src/merkle_tree/processor.rs

There are way too many `No message found in DB for leaf index` logs to have them at debug level. Also the wording makes it seem like an error when it's not.

chore: reduce agents log verbosity, reword

---

typescript/infra/config/environments/mainnet3/funding.ts
typescript/infra/config/environments/testnet4/funding.ts
typescript/infra/scripts/funding/fund-keys-from-deployer.ts
typescript/infra/src/agents/key-utils.ts
typescript/infra/src/funding/key-funder.ts

- Noticed an issue with #3023 where mainnet3 helloworld addresses were always used. This uses the correct environment and context
- Also noticed errors with key funder infra because the neutron rpc url wasn't present - fixed the previous hack to accommodate this
- Filter out non evm or blessed chains from key funder as well
n/a
related to #3024 
yes
ran locally

Kathy keys using correct env/context helloworld chains, small fixes

---

rust/chains/hyperlane-cosmos/src/providers/grpc.rs

@tkporter reported that cosmos balance strings were being interpreted as hex when parsed, causing them to appear much larger. This fixes by parsing as decimal.
Tested manually by checking the metrics endpoint.

fix: cosmos balance parsing

---

typescript/infra/src/infrastructure/external-secrets/helm/README.md
typescript/infra/src/utils/gcloud.ts
typescript/infra/src/utils/utils.ts
typescript/sdk/src/ism/types.ts

Hey I found a few typo. One is plain text (README.md file), rests are comments. This is a minor change that doesn't require testing. Have a nice day.

chore(typescript): typo fix

---

rust/agents/relayer/src/settings/mod.rs

Cherry-picks #2921 which got merged into the wrong branch

Actually default to none policy (#2921)

---

typescript/infra/config/environments/mainnet3/funding.ts
typescript/infra/config/environments/testnet4/funding.ts
typescript/infra/scripts/funding/fund-keys-from-deployer.ts

Avalanche is like 5x more expensive now, see relayer txs https://snowtrace.io/address/0x74Cae0ECC47B02Ed9B9D32E000Fd70B9417970C5. A single funding of 0.3 is only enough to cover like 2 messages

Bump desired AVAX balance

---

rust/config/testnet4_config.json
typescript/infra/config/environments/testnet4/agent.ts
typescript/infra/config/environments/testnet4/chains.ts
typescript/infra/config/environments/testnet4/gas-oracle.ts
typescript/infra/config/environments/testnet4/infrastructure.ts
typescript/sdk/src/consts/chains.ts
typescript/sdk/src/consts/multisigIsm.ts

Removes most occurences of lines that contain the `neutron` string from the testnet4 context. Where validators are set (e.g. [here](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/3e685f9fb04fd1dd10b05250ade5b65150b75086/typescript/infra/config/environments/testnet4/validators.ts#L29)), the neutron context is required for type safety but can stay empty

chore: remove neutron-related deployments from testnet4 context

---

.changeset/five-spoons-complain.md
typescript/infra/config/environments/mainnet3/ism/verification.json
typescript/infra/config/environments/mainnet3/owners.ts
typescript/infra/config/environments/testnet4/ism/verification.json
typescript/sdk/src/consts/environments/mainnet.json
typescript/sdk/src/consts/environments/testnet.json

Redeploys Routing ISM factories with new bytecode
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3009 changed the routing ISM factory interface without redeploying
No
None

Redeploy routing ISM factories

---

rust/config/mainnet3_config.json
typescript/infra/config/environments/mainnet3/agent.ts

Updates the neutron gas price to be slightly above the min that was recently updated :| https://github.com/cosmos/chain-registry/blob/master/neutron/chain.json#L20
Deployed the Neutron relayer to include our recent changes that allow for the gas price to be easily configured

Bump neutron gas price

---

typescript/sdk/src/core/HyperlaneCoreDeployer.ts

I had an issue with the `hyperlane deploy core` script and it was caused by trying to initialize the existing mailbox contract. The deploy script already has an error handling for that specific reason, but it doesn't work if the call fails during the dry run when estimating gas.  In that case, the returned error looks like this:
```json
{
"reason": "cannot estimate gas; transaction may fail or may require manual gas limit",
"code": "UNPREDICTABLE_GAS_LIMIT",
"error": {
"reason": "execution reverted: Initializable: contract is already initialized",
"code": "UNPREDICTABLE_GAS_LIMIT",
"method": "estimateGas",
"transaction": {
"from": "0xD4643110b33D92783A5bF29D41b2d14a2Db69016",
"gasPrice": {
"type": "BigNumber",
"hex": "0x0b165100c3"
},
"to": "0xD4C4582cB9B0e63B180fEFefAE78dB486B736299", …
```

Fix initializing existing mailbox with failing gas estimation

---

rust/chains/hyperlane-ethereum/src/interchain_gas.rs
rust/chains/hyperlane-ethereum/src/mailbox.rs
rust/chains/hyperlane-ethereum/src/merkle_tree_hook.rs
rust/hyperlane-base/src/contract_sync/mod.rs
rust/hyperlane-core/src/types/log_metadata.rs
rust/hyperlane-core/src/types/merkle_tree.rs
rust/hyperlane-core/src/types/message.rs
rust/hyperlane-core/src/types/mod.rs

Deduplicates ethereum logs by collecting them into a HashSet before returning a Vec. I couldn't find a way to deduplicate using an ethers config, but since `fetch_logs` is only called once in hyperlane-base, I'm doing the deduplication there "globally". I also noted in doc comments that duplicates may be returned.
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3070
Yes
Will rely on e2e passing but haven't added unit tests for this scenario

fix: dedup eth logs

---

rust/config/mainnet3_config.json
typescript/infra/config/environments/mainnet3/agent.ts
typescript/infra/config/environments/testnet4/agent.ts
typescript/infra/scripts/announce-validators.ts

- viction RPC URL maxes out at 1K blocks for eth_getLogs
- restored the index params for scroll that were accidentally changed in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3067/files#diff-edae1a4e631a67121d92119998e37740c0190bec5060e3c842cc86e4d3d26a4dL701
- deploys the agents
- fixes announce-validators.ts if there are non-evm chains in the env

Ancient8 & viction agent deploy

---

rust/Cargo.lock
rust/chains/hyperlane-cosmos/Cargo.toml

Supporting TLS gRPC endpoints is as simple as enabling the `tonic` crate features in this PR. However to maintain compatiblity with the plaintext endpoints, we need to always use `http` instead of `https`, otherwise `tonic` will try to establish a TLS connection to them and fail. 
- Fixes https://github.com/hyperlane-xyz/issues/issues/893
No, in the sense that all prior plaintext urls need to be changed from `https` to `http`
Manual

fix: support TLS gRPC endpoints

---

.changeset/old-lizards-melt.md
typescript/sdk/src/ism/HyperlaneIsmFactory.hardhat-test.ts
typescript/sdk/src/ism/HyperlaneIsmFactory.ts
typescript/sdk/src/ism/types.ts

HyperlaneIsmFactory is now wary of (try)getDomainId or (try)getChainName calls which may fail and handles them appropriately.
- switched from chainName to domain in `routingModuleDelta`
- replace `getDomainId` with `tryGetDomainId` and `getChainName` with `tryGetChainName` wherever necessary.
None
None
Yes
Hardhat unit tests

fix:`HyperlaneIsmFactory` doesn't fail with missing chainMetadata errors

---

.github/workflows/test.yml
package.json
solidity/foundry.toml
solidity/package.json
solidity/test/isms/OPStackIsm.t.sol
typescript/cli/package.json
typescript/helloworld/package.json
typescript/infra/package.json
typescript/sdk/package.json
typescript/sdk/src/providers/SmartProvider/SmartProvider.test.ts
typescript/utils/package.json

- Problem: OpStackIsm.t.sol was failing because of very stale block number for fork
Fix: Excluding foundry fork testing  from CI and updating block number
- Problem: SmartProvider getLogs tests failing because the the results end up being an empty list and getConfirmations results a smaller number of confirmations than expected (712 vs 1705184)
fix: excluded from ci
None
None
Yes
Manual

fix: failing ci tests for `SmartProvider` and `OpStackIsm.t.sol`

---

rust/agents/relayer/src/settings/matching_list.rs

Upon trying to use a blacklist with an array of H256s as the `recipientAddress`, was getting a panic:
```
running 1 test
parse_value: Array [Object {"destinationdomain": Number(11155111), "origindomain": Number(1399811151), "recipientaddress": Array [String("0x6AD4DEBA8A147d000C09de6465267a9047d1c217"), String("0x6AD4DEBA8A147d000C09de6465267a9047d1c218")], "senderaddress": Array [String("0x6AD4DEBA8A147d000C09de6465267a9047d1c217"), String("0x6AD4DEBA8A147d000C09de6465267a9047d1c218")]}] "Expected matching list"
thread 'settings::matching_list::test::supports_sequence_h256s' panicked at 'called `Result::unwrap()` on an `Err` value: ConfigParsingError([(ConfigPath([]), Expected matching list
Caused by:
invalid type: string "0x6AD4DEBA8A147d000C09de6465267a9047d1c217", expected a borrowed …
```

Fix parsing sequences of H256s in a matchinglist via agent settings

---

typescript/infra/config/environments/testnet4/agent.ts

Blacklists a griefer that sent a bunch of messages before we had IGPs properly configured on testnet4

Blacklist (optimism)goerli griefer, deploy w/ new image on testnet4

---

rust/hyperlane-base/src/contract_sync/mod.rs
rust/hyperlane-core/src/types/log_metadata.rs
rust/hyperlane-core/src/types/message.rs
rust/hyperlane-core/src/types/mod.rs

Backports https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3191 to V2
Adds some trait impls to fix compilation
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2586

V2 rate-limiting fix

---

rust/Cargo.lock
rust/chains/hyperlane-sealevel/Cargo.toml
rust/chains/hyperlane-sealevel/src/mailbox.rs
rust/chains/hyperlane-sealevel/src/utils.rs

context: https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3167
This is just a temporary measure and not intended to be anything permanent

short term kludge: sleep 5s after getting blockhash on solana

---

.github/workflows/agent-release-artifacts.yml
.github/workflows/monorepo-docker.yml
.github/workflows/rust-docker.yml
.github/workflows/rust.yml
.github/workflows/static-analysis.yml
.github/workflows/storage-analysis.yml
.github/workflows/test.yml

With our current repo settings for PRs, github checks out the merge commit with main instead of the actual HEAD of the PR. It feels counter-intuitive for CI to build the merge commit each time rather than the commit one has pushed, considering we require branches to be up to date with main before merging anyway.
This can also cause problems when deploying RCs, because your RC monorepo builds (e.g. for keyfunder, kathy) would unintentionally include changes that are not in your RC branch. Experienced first hand as part of https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3190.
This change ensures that when running in a PR context it uses the intended HEAD of the PR, rather than the unintended merge commit with main.

feat: build head of PRs instead of merge commit

---

.changeset/friendly-peas-roll.md
typescript/cli/src/config/hooks.ts
typescript/cli/src/deploy/core.ts

- To simplify the PI deployment, I've removed the igp from preset hook config which PI deployers use if they don't provide a hook config via the CLI.
- This means we don't need to deploy IGP or storage gas oracles and the PI deployer can spin up relayer with gas enforcement policy set to false.
None
None
Yes
Manual

feat:removing igp from preset hook config

---

rust/config/mainnet3_config.json

Looks like https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3179/files#diff-edae1a4e631a67121d92119998e37740c0190bec5060e3c842cc86e4d3d26a4dL417 removed Neutron from mainnet3_config.json :(
Seems like the Typescript tooling may have overridden it accidentally? Will need to figure out what to do there

Add Neutron back to mainnet3_config.json

---

typescript/cli/src/deploy/core.ts

resolves https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3189
- only build agent config for chains deployed to
- drive-by retrieve HyperlaneCore outside of the loop
TODO:

fix: agent config artifact includes only chains user deployed to

---

rust/Cargo.lock
rust/Cargo.toml
rust/chains/hyperlane-cosmos/Cargo.toml
rust/chains/hyperlane-cosmos/src/interchain_security_module.rs
rust/chains/hyperlane-cosmos/src/payloads/ism_routes.rs
rust/chains/hyperlane-cosmos/src/types.rs
rust/sealevel/environments/local-e2e/warp-routes/testwarproute/program-ids.json
rust/utils/run-locally/Cargo.toml
rust/utils/run-locally/src/cosmos/crypto.rs
rust/utils/run-locally/src/cosmos/deploy.rs
rust/utils/run-locally/src/cosmos/link.rs
rust/utils/run-locally/src/cosmos/mod.rs
rust/utils/run-locally/src/cosmos/types.rs

Replaces usage of `hpl-interface` with `hyperlane-cosmwasm-interface` and updates imports

republish  as hpl-interface as hyperlane-cosmwasm-interface

---

typescript/sdk/src/consts/chainMetadata.ts

- existing viction and sepolia RPC urls were failing on eth_getCode
- CI fork tests

Rotate chain metadata RPC urls

---

typescript/cli/src/deploy/agent.ts

Users can run into an issue where the URL to deploy to kurtosis does not display correctly for unsupported terminals. I have ran into this myself with my mac setup.
It manifests as:
- "click here" text, no URL
- unformatted text with URL containing "no-width space" characters
Related issue: https://github.com/sindresorhus/terminal-link/issues/18#issuecomment-1068020361
As suggested by a comment on the above issue, we can add a fallback to the `terminalLink` call to simply print the URL as a backup.

fix: add fallback to kurtosis terminal link

---

.changeset/curvy-geese-beam.md
rust/config/mainnet3_config.json
typescript/sdk/src/consts/chainMetadata.ts

Seeing some issues possibly related to querying for logs in a range that an RPC server doesn't know about yet. Increasing the reorg period from 1 to 10 to be extra conservative
rm'd the unused finalityBlocks from mainnet3_config.json

Increase injective reorg period

---

rust/agents/relayer/src/msg/metadata/ccip_read.rs
rust/chains/hyperlane-cosmos/src/mailbox.rs
rust/chains/hyperlane-ethereum/src/mailbox.rs
rust/chains/hyperlane-ethereum/src/tx.rs
rust/chains/hyperlane-fuel/src/mailbox.rs
rust/hyperlane-core/src/traits/signing.rs
rust/hyperlane-core/src/utils.rs

`H160`'s `ToString` implementation adds ellipsis points instead of outputting the full hex string, for some reason (e.g. `0xc66a…7b6f`). This will result in an error when `Mailbox.process` is called on the CCIP Read ISM.

CCIP Read metadata builder fix

---

rust/agents/scraper/src/agent.rs

Allow unknown domains in the scraper

---

typescript/cli/src/commands/chains.ts

* Added environment specification to the `hyperlane chains list` CLI command
* Provides CLI-users with the option to specify `--testnet` | `-t` or `--mainnet` | `-m` to only display chains for that environment
* None
* None
* Yes
* Manual
* `yarn hyperlane chains list --help`
```
Options:
--help     Show help                                             [boolean]
-m, --mainnet  Only list mainnet chains
-t, --testnet  Only list testnet chains
```
* `yarn hyperlane chains list -m`
```
Hyperlane core mainnet chains:
------------------------------
...
```
* `yarn hyperlane chains list -t`
```
Hyperlane core testnet chains:
------------------------------
...
```
* `yarn hyperlane chains list -m -t`
```
Error: Arguments mainnet and testnet are mutually exclusive
hyperlane chains list
List all …
```

Add env spec to chains list CLI command

---

.github/workflows/test.yml

- parallelise cosmwasm and non-cosmwasm e2e tests
- no need to have an explicit agent build step
- cc @daniel-savu 
- `e2e` status should still pass as it collates result from the matrix 
before: 26-30m
after: 15-20m
there's likely further optimisation that can be done by caching the agent build artifacts? but I think this should be good enough for now

feat: parallelise e2e test workflow

---

rust/Dockerfile
rust/helm/hyperlane-agent/templates/relayer-statefulset.yaml
typescript/infra/config/environments/mainnet2/agent.ts
typescript/infra/src/agents/index.ts
typescript/infra/src/config/agent/relayer.ts

Will restart the pod if:
- the relayer serial submitter's latest nonce is lower than that of the validators
- the relayer serial submitter's latest nonce hasn't increased in the last 10 mins (to avoid a case where the relayer has just spun up and is trying to catch up to the validators)
Fixes https://github.com/hyperlane-xyz/issues/issues/1102

v2 liveness probe to cover Solana indexing flakiness

---

typescript/sdk/src/deploy/verify/ContractVerifier.ts

skip verification if rpc url is localhost

fix: skip verification for local endpoints

---

rust/chains/hyperlane-cosmos/src/providers/rpc.rs
rust/hyperlane-base/src/settings/trace/mod.rs

Our logging prio order was off, double checked with [this crate](https://docs.rs/log/latest/log/enum.Level.html). Debug logs would be visible at `Info` level according to the previous rules.
Removed the debug formatting of a cosmsos log field, so it's no longer surrounded in quotes (bc we'd get `cursor_label: ""InterchainGasPaymentCursor""`)

fix: log level order, cosmos logging nit

---

typescript/infra/config/environments/mainnet3/agent.ts
typescript/infra/config/environments/testnet4/agent.ts

Updates the docker images and removes docker overrides

chore: deploy block-by-block cosmos indexing everywhere

---

solidity/test/test/TestSendReceiver.t.sol
typescript/infra/config/environments/mainnet3/agent.ts

- Stops enforcing gas payments on the inEVM / Injective warp route
- Looks like we've been running the RC validator without a whitelist - this ensures it only tries to relay between the helloworld RC

Temporary inEVM gas payment enforcement, add back whitelist to RC config

---

rust/chains/hyperlane-sealevel/src/mailbox.rs
typescript/infra/config/environments/mainnet2/agent.ts

Basically https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3407

Higher SOL fees

---

.changeset/loud-falcons-hang.md
typescript/sdk/src/warp/WarpCore.test.ts
typescript/sdk/src/warp/WarpCore.ts
typescript/utils/src/addresses.test.ts
typescript/utils/src/addresses.ts

- Prevent warp transfers to zero-ish addresses
- Increase address utility test coverage
Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3421
Yes
Tested in warp UI and added unit tests

Prevent warp transfers to zero-ish addresses

---

Dockerfile
typescript/infra/config/environments/mainnet2/funding.ts
typescript/infra/scripts/funding/fund-keys-from-deployer.ts

- See https://github.com/hyperlane-xyz/issues/issues/1047
- Intentionally going with a "hacky" short term approach because we consistently hit this, we're unlikely to prioritize a better solution for v3, and this change is only for v2 which we are in maintenance-only mode, so it's ok to hardcode these accounts
- New monorepo base image to fix building, which requires node 18 apparently

Hacky solana balance monitoring

---

typescript/infra/config/environments/mainnet3/agent.ts

Follow-up to https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3415#issue-2183782377, to actually deploy with the labels

chore: release relayers with op-queue labels

---

typescript/infra/config/environments/mainnet3/agent.ts

The prepare queue alert will automatically pick up viction if warp route labels are set.

chore: add viction warp route labels to mainnet relayer

---

typescript/infra/config/environments/mainnet3/agent.ts
typescript/infra/config/environments/mainnet3/warp/inevm-USDC-addresses.json
typescript/infra/config/environments/mainnet3/warp/inevm-USDT-addresses.json
typescript/infra/src/config/agent/relayer.ts

Generalizes `routerMatchingList` to `matchingList` for use with asymmetric app artifacts
- migrate to `matchingList` for some app context agent config
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3441
- Yes
Unit tests

Generalize matching list agent config fn

---

solidity/contracts/middleware/InterchainAccountRouter.sol
solidity/test/InterchainAccountRouter.t.sol

- added accountOwner mapping to the ICA router for easier tracking of remote owners for the transaction type inference by the AppGovernor
none
none
yes
unit

feat: add account -> owner mapping in ICA router

---

rust/chains/hyperlane-ethereum/src/tx.rs
typescript/infra/config/environments/mainnet3/agent.ts

- Fixes #3396 
- See v2 backport here #3463 
So turns out this is because:
- BSC nodes tend to enforce a minimum gas price of 3 gwei when you submit a tx
- it's possible for validators to include privileged txs at a lower gas price, so in practice (probably some mev stuff ?) there are a bunch of txs in blocks with transactions lower than 3 gwei
- BSC's 1559 situation is they have a base fee of zero, so it's basically like they just use legacy txs
- when we try to figure out what to pay in prio fees, we are suggested a 1 gwei priority fee:
```
$ cast rpc eth_feeHistory 10 latest "[5.0]" --rpc-url https://rpc.ankr.com/bsc
{"oldestBlock":"0x23706f7","reward":[["0x3b9aca00"]],"baseFeePerGas":["0x0","0x0"],"gasUsedRatio":[0.1149265]}
$ cast td 0x3b9aca00
1000000000
```
So options are:
1. tx …

Fix BSC gas price issues by treating chains with a base fee of 0 as non-1559

---

solidity/test/InterchainAccountRouter.t.sol

make sure we assume `value <= balance - gasQuote`
none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3468
fuzz

fix: send_value fuzz test for ICA

---

typescript/infra/config/environments/mainnet2/funding.ts
typescript/infra/src/utils/metrics.ts

- v2 backport of https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3491

By default, don't overwrite pushgateway metrics

---

rust/chains/hyperlane-ethereum/src/tx.rs

On nautilus, we are having trouble getting txs confirmed, but we are waiting for 5 minutes before attempting. This reduces it to half that

Half the relayer timeout on v2

---

.changeset/cuddly-ravens-run.md
typescript/cli/src/commands/chains.ts

resolves https://github.com/hyperlane-xyz/issues/issues/1066
- uses the list of deployed addresses from SDK to determine core mainnet/testnet chains
- tidy up `hyperlane chains list` command to accept `env` (either `mainnet` or `testnet`)
will do docs update to reflect updated chains list command
before:
after:

feat: CLI chain list derived from SDK contract addresses artifact

---

typescript/infra/config/environments/testnet4/helloworld.ts

- Adds `mumbai` to `chainsToSkip` as a preliminary step for deprecating Polygon Mumbai testnet
- Unblocks #3521 
- Fixes #1181

add 'mumbai' to chainsToSkip

---

typescript/infra/scripts/deploy.ts
typescript/sdk/src/deploy/HyperlaneDeployer.ts

- For https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3483, I was passing in ica artifacts through the cachedAddressesMap function which in turn writes these addresses to the deploy addresses.json file and this causes chain not found error in the subsequent module deployments.
Fix
- Read from options.icaApp for the router address (extra step added to the runbook)
None
- https://discord.com/channels/935678348330434570/1225043256782622730
Yes
local manual

fix:deploy-core ci writing unnecessary cache fix

---

.github/workflows/test.yml

Currently there's no way to know exactly where a panic occurred in rust e2e. This adds full backtraces to show where the task `.join` that caused the panic was. For example, this line isn't visible in the regular backtrace and it shows that the panic happened when spawning the anvil task (if you check out commit `0cc48e164379d08a8f4c3703eaab79bb86e271d6`):
```
at [...]/hyperlane-monorepo/rust/utils/run-locally/src/main.rs:321:22
```

chore: rust ci tests with full backtraces enabled

---

rust/helm/hyperlane-agent/templates/relayer-statefulset.yaml

5 mins isn't enough to spin up a relayer and have it indicate healthy metrics anymore. This moves it to 30 mins. Initially I went with a more complicated approach to use restart metrics to prevent reporting a relayer as unhealthy if it has restarted in the last 30 mins, but this is basically the same thing as this

Increase liveness probe initialDelaySeconds to 30 mins

---

typescript/sdk/src/token/deploy.ts

Returns the deployedContracts object in token deployer
- Fixes #3585 
None

Return entire deployedContracts object

---

typescript/sdk/src/test/multiProviderStubs.ts
typescript/sdk/src/test/testUtils.ts
typescript/sdk/src/token/Token.test.ts

testUtils gets used by TestCoreDeployer which gets exported from the SDK, so we can't import sinon there. We should reorganize these test utils

Avoid sinon import in exported lib files

---

typescript/sdk/package.json

* do not exit if `@safe-global/protocol-kit/**/Multi_send.ts` dne
* This fixes an issue where successfully building the sdk 2+ times exits out, when instead `tsc` should always be executed
* n/a
* n/a
* yes
* manual

do not exit if @safe-global/protocol-kit/**/Multi_send.ts dne

---

.changeset/wet-ghosts-turn.md
typescript/cli/src/commands/options.ts

* Adds defaultDescription to yargs --key option to avoid printing sensitive data
* None
* None
* Yes
* Manual

add defaultDescription to yargs --key option

---

.changeset/tricky-walls-care.md
typescript/infra/scripts/safe-delegate.ts
typescript/infra/src/govern/HyperlaneAppGovernor.ts
typescript/infra/src/govern/multisend.ts
typescript/sdk/package.json
typescript/sdk/src/hook/read.ts
typescript/sdk/src/index.ts
typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5GnosisSafeTxSubmitter.ts
typescript/sdk/src/providers/transactions/transformer/ethersV5/EV5InterchainAccountTxTransformer.ts
typescript/sdk/src/utils/gnosisSafe.js
typescript/sdk/tsconfig.json

Replace SDK's `gnosisSafe.ts` utils file with a pure JS version to avoid TS checks on Safe lib which has an incorrectly placed TS file in it's lib dist folder:
Fix assert import
https://github.com/safe-global/safe-core-sdk/issues/805

Workaround TS bug in Safe protocol-lib

---

solidity/foundry.toml
solidity/hardhat.config.cts
solidity/package.json
yarn.lock

does what the title says, making use of https://www.npmjs.com/package/hardhat-ignore-warnings

fix: ignore warnings from fx-portal lib

---

README.md

Add section to the readme on using nvm to manage node versions

chore: add section to readme on nvm

---

typescript/infra/config/environments/mainnet3/funding.ts
typescript/infra/config/environments/mainnet3/infrastructure.ts
typescript/infra/config/environments/mainnet3/liquidityLayer.ts
typescript/infra/config/environments/testnet4/funding.ts
typescript/infra/config/environments/testnet4/infrastructure.ts
typescript/infra/config/environments/testnet4/middleware.ts

GKE was complaining that the kube-state-metrics version we were running with was hitting deprecated APIs, I expect this to fix it.
Some minor changes to the infra setup meant that now the push gateway has a different service name, kinda annoyingly with a double `prometheus` in the name. I updated key funder to push to the new gateway
We no longer use GKE autopilot, so started using the node exporter too

chore: update clusters to use new prometheus version

---

rust/Cargo.toml

Found the reason why we never had `trace` level logs in release builds - the `tracing` crate had a feature flag enabled that would wipe out all trace calls at compile time :(
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3823

fix: allow all log levels in release build

---

.github/workflows/test.yml

As part of #3788, we moved to using the registry's `main` branch in CI. I accidentally didn't include this for other non-required tests that I didn't realize were failing, and then automerge merged that PR. This ensures the registry is usable by these other tests

fix: fix CI tests to correctly use registry from `main`

---

.github/workflows/monorepo-docker.yml
Dockerfile

Infra services require the presence of a registry. This is expected to be found at the env var REGISTRY_URI. This PR fetches the latest registry from `main` and uses that as the registry in the monorepo image for infra services / scripts to make use of. To prevent caching of this git clone, we use a build-time arg such that if the arg changes, any later layers in the image will be ran. See https://stackoverflow.com/a/73501716
- Partially fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3827 - we'll need a deploy to fully close it out

fix: fetch the registry's `main` branch in the monorepo Docker image

---

typescript/infra/config/environments/mainnet2/funding.ts
typescript/infra/config/environments/mainnet2/liquidityLayer.ts
typescript/infra/config/environments/testnet3/funding.ts
typescript/infra/config/environments/testnet3/middleware.ts

Updates the pushgateway URL following https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3772

chore: update pushgateway URL

---

.changeset/hip-squids-lay.md
.eslintrc
typescript/cli/cli.ts
typescript/cli/src/avs/stakeRegistry.ts
typescript/cli/src/commands/config.ts
typescript/cli/src/commands/core.ts
typescript/cli/src/config/hooks.ts
typescript/cli/src/config/ism.ts
typescript/cli/src/utils/keys.ts
typescript/cli/src/validator/address.ts
typescript/sdk/src/core/CoreDeployer.hardhat-test.ts
typescript/sdk/src/hook/EvmHookModule.ts
typescript/sdk/src/ism/EvmIsmModule.ts

* adds new `hyperlane core config` command
* this combines previous `hl config create ism` & `hl config create hook` control flows
* adds default ISM behaviour to aggregate `IsmType.TRUSTED_RELAYER` and the previous default fallback, `IsmType.MESSAGE_ID_MULTISIG`
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3688
* yes

feat(cli): add 'hyperlane core config' command

---

.changeset/great-cycles-tickle.md
typescript/cli/cli.ts
typescript/cli/src/commands/config.ts
typescript/cli/src/commands/warp.ts
typescript/cli/src/config/ism.ts
typescript/cli/src/config/warp.ts

* adds new `hyperlane warp config` command
* this replaces previous `hl config create warp` control flow
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3537
* yes

feat(cli): add 'hyperlane warp config' command

---

.changeset/bright-islands-shake.md
typescript/cli/src/commands/core.ts
typescript/cli/src/commands/deploy.ts
typescript/cli/src/commands/options.ts
typescript/cli/src/config/hooks.ts
typescript/cli/src/config/ism.ts
typescript/cli/src/config/warp.ts
typescript/sdk/src/deploy/HyperlaneDeployer.ts

- Updates `hl core config` to output a single `CoreConfig` file
- Makes `CoreConfig` single chain ie. remove ChainMap
- Removes `nativeTokenAndDecimals()` for fee calculation
- Add description as a prameter for `outputFileCommandOption()`
- Fixes #3877
No, Outputs CoreConfig as a single file and no longer expecting 2 individual files
Manual

feat: implement hyperlane core config to return CoreConfig

---

typescript/cli/src/commands/core.ts
typescript/cli/src/config/ism.ts

- Updates `hl core read` to output a single `CoreConfig` file
- Fixes #3880
Yes
Manual

feat: implement hyperlane core read to return CoreConfig 

---

rust/hyperlane-base/src/settings/signers.rs
rust/hyperlane-base/src/types/mod.rs
rust/hyperlane-base/src/types/s3_storage.rs
rust/hyperlane-base/src/types/utils.rs
typescript/infra/config/environments/mainnet2/agent.ts

Backport of https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3283
Applies the fix in
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/2384 everywhere an `HttpClient` is constructed via rusoto.
It lowers the S3 timeout to 15s based on tips in [this thread](https://github.com/hyperium/hyper/issues/2136#issuecomment-589488526), to avoid `Error during dispatch: connection closed before message completed` errors. Note that we'll probably still run into these issues, but less frequently
([source](https://github.com/rusoto/rusoto/issues/1766#issuecomment-639299961)).

fix: backport rusoto timeout change to v2

---

.changeset/spotty-days-worry.md
typescript/cli/ci-test.sh
typescript/cli/src/commands/send.ts
typescript/cli/src/commands/warp.ts

- adds `hl warp send` command in favor of `hl send transfer`
* none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3691
- yes
- ci-test: includes call to `hl warp send`
- manual: `hl warp send`

feat(cli): add 'hyperlane warp send' command

---

typescript/infra/config/environments/mainnet3/funding.ts
typescript/infra/config/environments/mainnet3/helloworld.ts
typescript/infra/config/environments/mainnet3/index.ts
typescript/infra/config/environments/mainnet3/liquidityLayer.ts
typescript/infra/config/environments/testnet4/funding.ts
typescript/infra/config/environments/testnet4/helloworld.ts
typescript/infra/config/environments/testnet4/index.ts
typescript/infra/config/environments/testnet4/middleware.ts
typescript/infra/helm/helloworld-kathy/templates/_helpers.tpl
typescript/infra/helm/key-funder/templates/cron-job.yaml
typescript/infra/helm/liquidity-layer-relayers/templates/circle-relayer-deployment.yaml
typescript/infra/helm/liquidity-layer-relayers/templates/portal-relayer-deployment.yaml
typescript/infra/scripts/agent-utils.ts
typescript/infra/scripts/agents/update-agent-config.ts
typescript/infra/scripts/funding/fund-keys-from-deployer.ts
typescript/infra/scripts/helloworld/kathy.ts
typescript/infra/scripts/helloworld/utils.ts
typescript/infra/src/config/chain.ts
typescript/infra/src/config/environment.ts
typescript/infra/src/config/funding.ts
typescript/infra/src/config/helloworld/types.ts
typescript/infra/src/config/middleware.ts
typescript/infra/src/funding/key-funder.ts
typescript/infra/src/helloworld/kathy.ts
typescript/infra/src/middleware/liquidity-layer-relayer.ts

Removed references to RpcConsensusType where TS-based providers are used in infra

chore(infra): Remove RpcConsensusType usage in infra now that SmartProvider is used instead

---

typescript/cli/src/config/hooks.ts

* removes domainRoutingHook & interchainGasPaymaster(Hook) from hyperlane * configure list
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3896
- yes
- ci-test

fix(cli): remove domainRoutingHook & interchainGasPaymaster(Hook) from hyperlane * configure list

---

rust/chains/hyperlane-ethereum/src/mailbox.rs
typescript/infra/config/environments/mainnet2/agent.ts

feat: set nautilus gas price via env var

---

typescript/cli/src/commands/core.ts
typescript/cli/src/config/chain.ts
typescript/cli/src/config/ism.ts
typescript/cli/src/config/warp.ts
typescript/cli/src/utils/chains.ts

- adds `source` field to detect and confirm prompt so users know where defaults are coming from
- none
- none
- yes
- manual

feat(cli): add 'source' to detectAndConfirmOrPrompt

---

rust/hyperlane-base/src/contract_sync/cursors/sequence_aware/backward.rs

chore: restrict for how long the backward syncer can block

---

typescript/cli/src/config/ism.ts

- removes `opStackIsm` & `pausableIsm` from `hyperlane core configure`
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3907
- yes
- ci-test
- manual

fix(cli): remove opStackIsm & pausableIsm from hyperlane core configure

---

typescript/infra/helm/helloworld-kathy/templates/external-secret.yaml
typescript/infra/helm/key-funder/templates/env-var-external-secret.yaml
typescript/infra/helm/liquidity-layer-relayers/templates/env-var-external-secret.yaml
typescript/infra/scripts/agent-utils.ts
typescript/infra/scripts/check-rpc-urls.ts
typescript/infra/scripts/deploy.ts
typescript/infra/scripts/secret-rpc-urls/get-rpc-urls.ts
typescript/infra/scripts/secret-rpc-urls/set-rpc-urls.ts
typescript/infra/scripts/verify.ts
typescript/infra/src/agents/index.ts
typescript/infra/src/config/chain.ts
typescript/infra/src/utils/gcloud.ts

- clean up references to the single rpc secrets which are redundant as the multi rpc secret includes the single one
- add get-rpc-urls script to get secret rpc urls for a given environment and chain
- add set-rpc-urls script to: 1) create the secret if it does not exist and add the first secret version or 2) add new secret version to an existing secret and disable the previous version of the secret. The script with test all rpc urls to ensure that they are valid 
example usage:
get-rpc-urls 
`yarn tsx scripts/secret-rpc-urls/get-rpc-urls.ts -e testnet2 -c fuji`
set-rpc-urls
`yarn tsx scripts/secret-rpc-urls/set-rpc-urls.ts -e testnet2 -c fuji -r https://api.avax-test.network/ext/bc/C/rpc,https://rpc.ankr.com/avalanche_fuji`
- replace `withNetwork` util with `withChain` as we rarely use …

feat(infra): Command to create endpoint secrets; cleaning up endpoints

---

typescript/cli/src/commands/core.ts
typescript/cli/src/commands/warp.ts
typescript/cli/src/config/core.ts
typescript/cli/src/config/hooks.ts
typescript/cli/src/config/ism.ts
typescript/cli/src/config/utils.ts
typescript/cli/src/config/warp.ts
typescript/cli/src/utils/chains.ts
typescript/cli/src/utils/files.ts
yarn.lock

* removes prompt on default hooks in `hyperlane core configure`
* required hook now defaults to protocol and default hook defaults to merkle
- reshuffling `hyperlane warp configure` to accommodate the change as well (and maintain symmetry)
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3895
- yes
- manual
- ci-test

fix(cli): no prompt on default hooks in hyperlane core configure

---

typescript/cli/src/config/ism.ts

- sets default fallback owner to empty instead of prompting for warp config
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3903
- yes
- ci-test
- manual

fix(cli): set default fallback owner to empty instead of prompting for warp config

---

.changeset/bright-emus-double.md
typescript/cli/src/config/chain.ts
typescript/sdk/src/index.ts

- simply prompts if not a lowercase one-word chain name, instead of sometimes returning incorrect chain name
- none
- none
- yes
- manual w/ caldera: https://early-rabbits-throw.hub.caldera.xyz/

fix(cli): remove default for chain name

---

.github/workflows/rust-skipped.yml
.github/workflows/rust.yml
.github/workflows/test.yml

- skips unnecessary tests for PRs on just markdown changes e.g. README

ci: ignore `*.md` changes when triggering rust/test workflows

---

.changeset/sharp-geckos-wash.md
typescript/cli/src/config/warp.ts

- Fixes `hyperlane warp configure` ism selection looping by configuring a default Aggregation ISM with trusted relayer and fallback routing
- Fixes #3924 
Yes
Manual

fix: warp configure infinite loop

---

.changeset/late-rings-attack.md
typescript/cli/src/deploy/dry-run.ts
typescript/cli/src/deploy/warp.ts
typescript/sdk/src/index.ts
typescript/sdk/src/ism/EvmIsmModule.ts
typescript/sdk/src/token/EvmERC20WarpModule.hardhat-test.ts
typescript/sdk/src/token/deploy.ts

Adds deployment support for IsmConfig within a WarpRouteConfig
- Update dry-run confirmation to 1
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3933
Yes
Manual

feat: add deploy support for IsmConfig in WarpConfig

---

.changeset/strong-colts-hide.md
solidity/script/avs/eigenlayer_addresses.json
typescript/cli/src/avs/config.ts
typescript/cli/src/avs/stakeRegistry.ts
typescript/cli/src/commands/avs.ts

- Added all the strategies used by EigenDA on mainnet here:https://github.com/Layr-Labs/eigenlayer-contracts?tab=readme-ov-file#deployments
- Deployed AVS contracts to mainnet 
- Added contract address to CLI 
(reminder: strategies are just LST tokens supported for restaking. These are not relevant for us but brings us to parity with most other AVSs).
- `avsSigningKey` renamed to `avsSigningKeyAddress` as `avsSigningKey` may imply the private key and confuse operators.

feat: AVS mainnet deployment

---

rust/hyperlane-core/src/chain.rs

So validators can be run with `--originChainName <chainname>`, like in the docs [here](https://docs.hyperlane.xyz/docs/operate/validators/run-validators#running-the-binary)

chore: add all new chains to `KnownHyperlaneDomain` struct

---

.changeset/new-timers-applaud.md
typescript/cli/src/config/chain.ts

- Add logic to `hyperlane config create chain` to prompt for `displayName`
Yes
Manual

feat: `hyperlane config create chain` prompts for `displayName`

---

solidity/contracts/token/extensions/HypXERC20.sol
solidity/contracts/token/extensions/HypXERC20Lockbox.sol

- Follow OZ best practice from https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#initializing_the_implementation_contract
Yes
Unit tests

fix: disable initializers in xERC20 adapters

---

.changeset/olive-geckos-behave.md
typescript/cli/src/deploy/warp.ts
typescript/sdk/src/token/TokenStandard.ts
typescript/sdk/src/warp/WarpCore.ts

Amending https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3973 to ensure output of the CLI doesn't incorrectly add `collateralAddressOrDenom` to xERC20 configs.

fix: Do not consider xERC20 a collateral standard 2

---

typescript/infra/scripts/agent-utils.ts
typescript/infra/src/deployment/deploy.ts
typescript/infra/src/utils/utils.ts

- filters out remote domain metadata from configs written to disk
```
"ancient8": {
// this gets removed
"arbitrum": {
"aggregationHook": "0xblahblahblah",
"interchainSecurityModule": "0xblahblah"
...etc
},
// keep the usual entries like this
"aggregationHook": "0x1EF4ED658d542524d1D547ba2F94d3B038a55b8f",
"batchContractAddress": "0x4C97D35c668EE5194a13c8DE8Afc18cce40C9F28",
"blockExplorers": [
...etc
```
- no longer include secret overrides in the configs written to disk
- i.e. use public registry RPCs and chain metadata (want our output to be like that of update-agent-config, but with updated contract addresses only)

feat: reduce extraneous entries in generated registry/agent artifacts

---

.changeset/new-taxis-fry.md
.github/workflows/test.yml
rust/config/mainnet_config.json
typescript/cli/src/avs/stakeRegistry.ts
typescript/cli/src/commands/core.ts
typescript/cli/src/commands/hook.ts
typescript/cli/src/commands/ism.ts
typescript/cli/src/validator/address.ts
typescript/sdk/src/ism/metadata/multisig.ts
typescript/sdk/src/providers/SmartProvider/SmartProvider.ts
typescript/sdk/src/token/adapters/EvmTokenAdapter.ts
typescript/sdk/src/token/config.ts

the original functionality of these commands got lost across a couple of refactors
1. `ism read`/`hook read` was merged to become `core read`, which still had the purpose of "gimme config at this address"
2. then with a recent change, `core read` became "gimme the ism/hook configs relating to this mailbox address"
This PR adds the original functionality back of returning the ISM/Hook configs for *any* ISM/Hook address (on EVM)
drive-by:
- update mainnet config
- fix typescript linting errors/warnings

feat: reintroduce `ism read` and `hook read` commands

---

.changeset/shy-countries-heal.md
.github/workflows/test.yml
typescript/cli/src/avs/stakeRegistry.ts
typescript/cli/src/deploy/warp.ts
typescript/cli/src/validator/address.ts
typescript/sdk/src/deploy/EvmModuleDeployer.ts
typescript/sdk/src/deploy/HyperlaneDeployer.ts
typescript/sdk/src/hook/EvmHookModule.hardhat-test.ts
typescript/sdk/src/hook/EvmHookModule.ts
typescript/sdk/src/ism/EvmIsmModule.hardhat-test.ts
typescript/sdk/src/ism/EvmIsmModule.ts
typescript/sdk/src/ism/metadata/multisig.ts
typescript/sdk/src/providers/SmartProvider/SmartProvider.ts
typescript/sdk/src/token/adapters/EvmTokenAdapter.ts
typescript/sdk/src/token/config.ts
typescript/utils/src/objects.ts

resolves https://github.com/hyperlane-xyz/issues/issues/1153
- enables creation of new Hooks through the EvmHookModule
- introduce `EvmModuleDeployer`
- separate from `HyperlaneDeployer`
- contains some basic methods to deploy a contract/proxy
- reduces module necessity HyperlaneDeployer
IN PROGRESS:

feat: implement `create()` for `EvmHookModule`

---

typescript/.changeset/tall-radios-grin.md
typescript/sdk/src/deploy/HyperlaneDeployer.ts
typescript/sdk/src/deploy/verify/utils.test.ts
typescript/sdk/src/deploy/verify/utils.ts

**Overview**:
The `addVerificationArtifacts` method in the `HyperlaneDeployer` class previously added verification artifacts without checking for duplicates, potentially leading to redundant data that could affect performance and reliability. This PR introduces a mechanism to prevent such duplication by implementing a shallow comparison check before adding new artifacts.
**Changes**:
- Modified the `addVerificationArtifacts` method to include a shallow comparison against existing artifacts.
- Used direct property comparisons to efficiently prevent the addition of duplicate entries.
- Ensured that the comparison handles large ABI-encoded strings efficiently by comparing string references.
**Benefits:**
- Efficiency: Reduces unnecessary processing and storage by avoiding duplicate entries. …

fix: prevent duplication in verification artifacts array

---

.changeset/mean-books-clean.md
typescript/cli/package.json
typescript/cli/src/commands/options.ts
typescript/cli/src/commands/warp.ts
typescript/cli/src/config/warp.ts
typescript/cli/src/send/transfer.ts
typescript/cli/src/utils/tokens.ts
typescript/helloworld/package.json
typescript/infra/package.json
yarn.lock

- This allows users to interact read warp routes from the registry with symbol identifier rather than chain/address
Rename `wei` to `amount`
No, outputs chain map
- Manual
(single)
```sh
$ yarn hyperlane warp read --symbol EZETH
$ yarn hyperlane warp send --symbol EZETH
```
(multiple)
```sh
$ yarn hyperlane warp read --symbol USDC
$ yarn hyperlane warp send --symbol USDC
```

feat(cli): add `warp --symbol` flag

---

.changeset/wise-cobras-juggle.md
typescript/cli/src/utils/chains.ts
typescript/cli/src/utils/cli-options.ts

- Add process.stdout.rows to pageSize adjustment for chain selection
- Defaults to 15 if process.stdout.rows < 0
Yes
Manual

feat: add stdout.rows to pagesize calculation with DEFAULT_PAGE_SIZE

---

.changeset/sour-squids-buy.md
.github/workflows/test-skipped.yml
.github/workflows/test.yml
typescript/cli/ci-advanced-test.sh

- updates `ci-test.sh` name to `ci-advanced-test.sh`
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3995
- yes
- implicit

chore(cli): update ci-test to ci-advanced-test

---

.changeset/bright-horses-give.md
typescript/sdk/src/token/deploy.ts

Token deployer should always derive token metadata's total supply to 0, otherwise the collateral token's total supply will be minted initially on the synthetic, creating 2x the desired total supply.
- Regression introduced by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3820
- opens https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4013
Yes
Unit Tests

fix: derived token supply to 0

---

rust/utils/run-locally/src/invariants.rs

Context is explained in the comment, copying it here:
```
// TODO: Sometimes we find more logs than expected. This may either mean that gas is deducted twice for the same message due to a bug,
// or that submitting the message transaction fails for some messages. Figure out which is the case and convert this check to
// strict equality.
// EDIT: Having had a quick look, it seems like there are some legitimate reverts happening in the confirm step
// (`Transaction attempting to process message either reverted or was reorged`)
// in which case more gas expenditure logs than messages are expected.
```

fix: e2e invariant flake

---

typescript/infra/scripts/check-deploy.ts
typescript/infra/src/govern/HyperlaneAppGovernor.ts
typescript/sdk/src/core/HyperlaneCoreChecker.ts

THIS PR SHOULD NOT BE MERGED.
This is some temp changes to test that the governor can resolve the violations to transferOwnership to a multisig.
Changed that the prompting indeed is disabled during fork testing (probably should go in another PR)
No
Ran `./fork.sh mainnet3 core mode` and noted that the violations are resolved

feat: allow fork-testing of transfer ownership

---

rust/agents/relayer/src/msg/blacklist.rs
rust/agents/relayer/src/msg/mod.rs
rust/agents/relayer/src/msg/processor.rs
rust/agents/relayer/src/relayer.rs
rust/agents/relayer/src/settings/mod.rs
rust/hyperlane-base/src/contract_sync/cursors/sequence_aware/forward.rs
typescript/infra/config/environments/mainnet3/agent.ts
typescript/infra/src/config/agent/relayer.ts
typescript/sdk/src/metadata/agentConfig.ts

See context here https://discord.com/channels/935678348330434570/1236041564673806427/1252918894755319920 and https://discord.com/channels/935678348330434570/1252953507833708605/1252954456400592997
This is a rudimentary first step toward blacklisting addresses. Future options are outlined in https://discord.com/channels/935678348330434570/1236041564673806427/1252918894755319920. Eventually we can also fetch these addresses directly within the agent from an updated list that we cache and re-fetch occasionally. For now, this just relies on configured addresses.
The approach is:
- Allow hex addresses to be configured. These are intentionally treated as a Vec<u8> instead of an H160 / H256. This is because treating them as H160 is a leak of Ethereum-specific logic into non-chain-specific code …

feat: address blacklisting in the relayer

---

.github/workflows/rust.yml
.github/workflows/test.yml
rust/utils/run-locally/src/invariants.rs
typescript/cli/ci-advanced-test.sh

- brings https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4015 to cli-2.0 branch
- cherry-pick e2e flake fix
- ensure tests run on pushes to `cli-2.0`

feat(ci): rust caching in `test` workflow

---

typescript/infra/config/environments/mainnet3/agent.ts
typescript/infra/config/environments/testnet4/agent.ts
typescript/infra/src/agents/index.ts
typescript/infra/src/config/agent/agent.ts
typescript/infra/src/config/infrastructure.ts

- based off https://abacusworks.grafana.net/d/FSR9YWr7k, updated resource requests for all agents. Because mainnet3 sees so many more messages and more chains, the resource needs there are higher
- allows for resources to be defined in infra - previously we'd just use the default value in the values.yaml of the helm charts. Also makes the resources specific to the type of agent, which is nice because relayers require much higher spec than validators
- I haven't deployed this yet, will do so when I get a review
- Fixes https://github.com/hyperlane-xyz/issues/issues/1288

chore: set agent and environment specific resource requests

---

rust/config/mainnet_config.json
typescript/infra/config/environments/mainnet3/agent.ts

- chore: enable `osmosis` on relayer
- drive-by add default chain signer/key/type to agent config
- `signer.key` is copied from `neutron`

chore: enable `osmosis` on relayer

---

.changeset/shiny-cups-help.md
typescript/cli/src/deploy/warp.ts
typescript/sdk/src/hook/EvmHookModule.hardhat-test.ts
typescript/sdk/src/providers/SmartProvider/SmartProvider.ts
typescript/sdk/src/token/EvmERC20WarpRouteReader.ts

- Add logic to enable setting of log levels to the SmartProvider. 
- Add logic to set log level to `silent` in the beginning of `deriveTokenType()`, and then resetting it after.
- Fixes #4006 
Yes
Manual

feat: Add smart provider log setter

---

typescript/cli/src/deploy/core.ts
typescript/cli/src/deploy/warp.ts

- displays core artifacts to stdout after core deploy
- none
- P1
- y
- manual
example output:
```
⛽️ Gas Usage Statistics
- Gas required for core deploy on brown: 0.000020444175441289 ETH
Now updating chain brown at filesystem registry at /Users/nbayindirli/workplace/Hyperlane/hyperlane-registry
Done updating chain brown at filesystem registry
Now updating chain brown at filesystem registry at /Users/nbayindirli/.hyperlane
Done updating chain brown at filesystem registry
✅ Core contract deployments complete
staticMerkleRootMultisigIsmFactory: "0x6Df928Ce3A9627eA3D276e8C680b8108040702E3"
staticMessageIdMultisigIsmFactory: "0x35547488D84cd413107b2112726E6711744676db"
staticAggregationIsmFactory: "0x50B52aAd80195daA77F7AacD5ea612d07aFa17Ea"
staticAggregationHookFactory: …
```

chore(cli): display core artifacts after core deploy

---

typescript/cli/src/config/chain.ts
typescript/cli/src/config/core.ts
typescript/cli/src/config/hooks.ts
typescript/cli/src/config/ism.ts
typescript/cli/src/config/warp.ts
typescript/cli/src/deploy/core.ts
typescript/cli/src/deploy/warp.ts
typescript/cli/src/send/message.ts
typescript/cli/src/utils/chains.ts
typescript/cli/src/utils/input.ts

- formats message stdout during hl send message
- none
- P1
- yes
- manual
example output:
```
➜  cli git:(06-20-fix_cli_add_units_and_explanation_to_protocol_fee_input) ✗ hl send message --relay --registry $HOME/workplace/Hyperlane/hyperlane-registry
Hyperlane CLI
? Select the origin chain fuji
? Select the destination chain brown
Running pre-flight checks for chains...
✅ Chains are valid
✅ Signer is valid
✅ Balances are sufficient
Dispatching message
Pending https://testnet.snowtrace.io/tx/0x5d0793052ad6df340242f332a218b14a8182b083bebbf5666faac83f7c20ed66 (waiting 3 blocks for confirmation)
Sent message from fuji to 0xb2b1125501aA997b912A0fa32f74B3041C0c4FcB on brown.
Message ID: 0x2ba918e23225a7dc67ec803cff998cbe9beefd45c7243422349035dcac5e20d0
Message:
parsed:
version: 3
nonce: 2605 …
```

chore(cli): format message stdout during hl send message

---

typescript/sdk/src/deploy/EvmModuleDeployer.ts
typescript/sdk/src/ism/EvmIsmModule.ts

- in the multiprovider we already do a 10% bump on the estimated gas, as a cover for unpredictable gas estimation
- we recently found that the ism factories do not do this, which caused problems in a recent hyperlane core deployment
- added this into the ism factories on `main`
- so we are ensuring that this change is properly reflected in the new ism module as well

chore: include 10% gas estimate bump in EvmIsmModule

---

typescript/cli/src/config/chain.ts

- displays new chain config after `hl registry init`
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4039
- yes
- manual

chore(cli): display new chain config after registry init

---

solidity/contracts/interfaces/isms/IMultisigIsm.sol
solidity/contracts/isms/multisig/AbstractMultisigIsm.sol

Update `MultisigISM.verify` docs with clarity around signature ordering

docs: add docstrings for multisig signature ordering

---

rust/agents/relayer/src/msg/pending_message.rs

When messages are retried due to the Message Retry API, we bring messages to the front of the queue (by changing their `next_attempt_after`), but also reset their retry count. For messages that are unprocessable due to various reasons (and hence have very high `next_attempt_after`), resetting the retry count will cause the relayer to waste time instead of trying to process newer messages.
This PR makes it such that the retry API will cause messages to be retried immediately once, but won't boost their priority in the queue afterwards (because `num_retries` isn't changed).

chore: don't reset retry count when processing retry API reqs

---

.github/workflows/monorepo-docker.yml
.github/workflows/rust-docker.yml

- use the correct commit hash for the agent and monorepo image tag
- the actual checked out commit was correct, but this now ensures that the TAG_SHA matches the checked out commit hash
- drive-by ensure that workflow gets triggered on changes to itself

fix(ci): use the correct commit sha for agent/monorepo image tags

---

typescript/cli/src/deploy/utils.ts

- Displays formatted deployment plan to confirm core deploy
- none
- Fixes P1
- yes
- Output:
```
➜  cli git:(cli-2.0) ✗ hl core deploy --registry $HOME/workplace/Hyperlane/hyperlane-registry
Hyperlane CLI
Hyperlane permissionless deployment
------------------------------------------------
? Select chain to connect: alpha
Deployment plan
===============
Transaction signer and owner of new contracts: 0x16F4898F47c085C41d7Cc6b1dc72B91EA617dcBb
Deploying core contracts to network: alpha
┌────────────────────────┬──────────────────────────────────────────────┐
│ (index)                │ Values                                       │
├────────────────────────┼──────────────────────────────────────────────┤
│ Name                   │ 'alpha'                                      │
│ Display Name …
```

feat(cli): display formatted deployment plan to confirm core deploy

---

.changeset/calm-eels-care.md
typescript/cli/src/deploy/core.ts
typescript/sdk/src/core/HyperlaneCore.ts
typescript/sdk/src/hook/EvmHookModule.ts
typescript/sdk/src/hook/EvmHookReader.test.ts
typescript/sdk/src/hook/EvmHookReader.ts

This PR fixes RPC errors when trying to send a test message using the CLI for older chains that don't have tokenType (e.g., `hyperlane send message --relay --origin fuji --destination betaop`)
Additional details: https://discord.com/channels/935678348330434570/1254873902480359435/1255215832959811687
Yes
- tested with `hyperlane warp deploy` and then `hyperlane warp send --relay --warp $HOME/.hyperlane/deployments/warp_routes/ETH/alfajores-betaop-config.yaml`
- tested `hyperlane send message --relay --origin fuji --destination betaop`
- tested `hyperlane send message --relay --origin alfrajores --destination betaop`
- tested `hyperlane send message --relay --origin holesky --destination betaop`
- tested `hyperlane core read --mailbox 0xEf9F292fcEBC3848bF4bB92a96a04F9ECBb78E59 --chain …

fix(cli): RPC errors while sending test messages

---

.changeset/brave-penguins-ring.md
solidity/contracts/interfaces/avs/vendored/IDelegationManager.sol
typescript/cli/src/avs/check.ts
typescript/cli/src/avs/config.ts
typescript/cli/src/avs/stakeRegistry.ts
typescript/cli/src/commands/avs.ts
typescript/cli/src/commands/options.ts
typescript/cli/src/logger.ts
typescript/cli/src/utils/files.ts
typescript/cli/src/validator/utils.ts
typescript/sdk/src/aws/s3.ts
typescript/sdk/src/aws/validator.ts

- Command to check all operators on our AVS and show the chains that they are validating on
- Already been reviewed here https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4004, this PR was to merge it main instead of cli-2.0
Example usage:
```
yarn hyperlane avs check --chain ethereum --registry $REGISTRY
Hyperlane CLI
Checking AVS validator status for ethereum, this may take up to a minute to run...
❗️ MerkleTreeHook is not deployed on anvil8545
Operator name: Abacus Works AVS Operator
Operator address: 0xFe114FcC7609578f525219a8eF77e2CCe27C5357
Validator address: 0x03c842db86A6A3E524D4a6615390c1Ea8E2b9541
Validating on...
ethereum
Storage location: s3://hyperlane-mainnet3-ethereum-validator-0/us-east-1
Latest merkle tree checkpoint index: 8219
Latest validator checkpoint index: …
```

feat(cli): Add avs validator status command

---

.github/workflows/test.yml
typescript/infra/scripts/send-test-messages.ts
typescript/sdk/src/consts/testChains.ts

resolves https://github.com/hyperlane-xyz/issues/issues/1291
- remove test4 from kathy test
- drive-by tidy-up of `test4` metadata
- resets e2e test timeout back to original figure
- reuse original e2e rust cache
gonna keep the original commits on here as a trail of thought

fix(e2e): hardcode kathy chains for e2e in send-test-messages.ts

---

.changeset/quiet-ways-pay.md
typescript/cli/src/deploy/warp.ts
typescript/utils/src/validation.ts

Remove extra fields in warp core configs.
Context: https://github.com/hyperlane-xyz/hyperlane-registry/pull/73
Discussion: https://discord.com/channels/935678348330434570/1255901895503908934
Improve type assertion of `assert` util
Yes
Took configs from CLI e2e test artifact and tested it in registry CI.

fix: Remove extra fields in warp core config

---

rust/agents/relayer/src/msg/op_queue.rs

The gcp bill has been shooting up, and it's most likely due to the increased number of undeliverable messages being added to and removed from the queue, causing lots of `debug` level logs on `push` and `pop_many` to be emitted.
This PR changes the verbosity to `trace` - we'll have lower visibility over the lifetime of a message, but there should be sufficient logs remaining to tell us what's going on (such as [operation prepared](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/30630c4fa6010d3b65e7d80fd2ebd87d376224fe/rust/agents/relayer/src/msg/op_submitter.rs#L240), [confirming a pre-submitted one](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/30630c4fa6010d3b65e7d80fd2ebd87d376224fe/rust/agents/relayer/src/msg/op_submitter.rs#L260), [submitting single …

chore: reduce op-queue verbosity

---

.changeset/five-timers-reflect.md
typescript/cli/src/config/chain.ts
typescript/cli/src/utils/files.ts

It includes usage of sortMapEntries option in yamlStringify function called in writeYaml function.
None
- Fixes #4057 
Yes
Because I've converted the argument 2 into the indent option as documented in yaml library.
Manual by trying to reproduce the issue in the same way.

fix: use sortMapEntries in writeYaml

---

typescript/infra/config/environments/mainnet3/funding.ts
typescript/infra/config/environments/mainnet3/igp.ts
typescript/infra/config/environments/mainnet3/supportedChainNames.ts
typescript/infra/config/environments/testnet4/funding.ts
typescript/infra/config/environments/testnet4/index.ts
typescript/infra/config/environments/testnet4/supportedChainNames.ts
typescript/infra/config/registry.ts
typescript/infra/scripts/funding/fund-keys-from-deployer.ts
typescript/infra/scripts/print-token-prices.ts
typescript/infra/src/config/environment.ts
typescript/infra/src/config/funding.ts
typescript/infra/src/funding/key-funder.ts

resolves https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3732
- strongly type the keyfunder config
- new chains added to an environment's supported chains list must be configured
- opens up the path to strongly type more of the env config down the line
missing 1 chain:
missing multiple chains:

feat(infra): strongly type keyfunder config

---

rust/Cargo.lock
rust/Cargo.toml
rust/chains/hyperlane-ethereum/src/rpc_clients/trait_builder.rs
rust/chains/hyperlane-ethereum/src/tx.rs
rust/ethers-prometheus/src/middleware/mod.rs
rust/utils/run-locally/src/invariants.rs

This reverts commit c3c002a8fe4870c7e462cd5073365a7f9a2235bc.
The gas escalator took up to 28gb of memory, and even though it was only ever released on RC, it must have taken up too many cluster resources, ending up starving the `hyperlane` relayer. Reverting for now until we have a better idea

chore: Revert "feat(hyp-ethereum): gas escalator middleware (#3852)"

---

typescript/cli/src/commands/options.ts
typescript/cli/src/commands/registry.ts
typescript/cli/src/config/agent.ts
typescript/cli/src/config/prompts.ts

- Support generating agent config for all supported chains
- Add user prompts: prompt user whether they want to zero the IGP addresses if not provided, prompt user whether they want to generate agent config anyway when schema validation fails
- Support skipping prompts, useful for CI
Example usage:
Specific chains
```
$yarn hyperlane registry agent-config --chains anvil8545
Hyperlane CLI
Creating agent config...
interchainGasPaymaster address is missing for anvil8545
? Would you like to set the interchainGasPaymaster address to 0x0 for anvil8545? yes
Agent config is invalid, this is possibly due to required contracts not being deployed. See details below:
Validation error: Required at "chains.anvil8545.merkleTreeHook"
? Would you like to continue anyway? yes
Writing agent config to file …
```

feat(cli): Support agent config generation for all chains

---

.changeset/proud-days-flash.md
typescript/cli/src/commands/options.ts
typescript/cli/src/commands/warp.ts
typescript/cli/src/deploy/warp.ts
typescript/sdk/src/deploy/schemas.ts
typescript/sdk/src/index.ts
typescript/sdk/src/ism/EvmIsmModule.hardhat-test.ts
typescript/sdk/src/ism/EvmIsmModule.ts
typescript/sdk/src/token/EvmERC20WarpModule.hardhat-test.ts
typescript/sdk/src/token/EvmERC20WarpModule.ts

- Adds `hyperlane warp apply`
- Fixes https://github.com/hyperlane-xyz/issues/issues/1190
Yes
Manual
To test: `yarn hyperlane warp apply --warp`

feat(cli): Add hyperlane warp apply

---

.changeset/tiny-lions-kiss.md
typescript/sdk/src/aws/validator.ts

- Set the folder in the `S3Config` to include any subdirectories and not just the first folder
- This brings the SDK inline with current behavior in the agents
- Fixes #4100 
Yes
Manual

feat(sdk): Handle subdirectories for the folder in S3Validator

---

solidity/contracts/test/ERC20Test.sol
solidity/contracts/token/interfaces/IXERC20.sol
typescript/infra/config/environments/mainnet3/warp/EZETH-deployments.yaml
typescript/infra/scripts/warp-routes/monitor-warp-routes-balances.ts

- Add support for pushing limits metrics for xERC20 wrap routes
- For now only push limits metrics for xERC20 wrap routes, not yet supporting warp route balances 
- Fixes #4047 
Manual

feat(infra): Add xERC20 limits monitoring capabilities

---

.changeset/purple-cherries-clean.md
typescript/cli/package.json
typescript/helloworld/package.json
typescript/infra/package.json
yarn.lock

Update to latest registry for faster and more efficient chain metadata/address fetching
https://github.com/hyperlane-xyz/hyperlane-registry/issues/29
Yes
Ran CLI registry commands locally

chore: Bump registry version to 2.3.0

---

.changeset/empty-waves-speak.md
typescript/cli/src/utils/balances.ts

Update text symbol when warning insuficient balance
```diff
- `WARNING: ${address} has low balance on ${chain}. At least ${minBalance} recommended but found ${balance} ${symbol}`
+ `WARNING: ${address} has low balance on ${chain}. At least ${minBalance} ${symbol} recommended but found ${balance} ${symbol}`
```

chore: add symbol text when insuficient balance for pay gas

---

.changeset/wild-fans-repair.md
typescript/cli/.gitignore
typescript/cli/cli.ts
typescript/cli/examples/submit/strategy/gnosis-ica-strategy.yaml
typescript/cli/examples/submit/strategy/gnosis-strategy.yaml
typescript/cli/examples/submit/strategy/impersonated-account-strategy.yaml
typescript/cli/examples/submit/strategy/json-rpc-strategy.yaml
typescript/cli/examples/submit/transactions/alfajores-transactions.json
typescript/cli/examples/submit/transactions/avalanche-transactions.json
typescript/cli/src/commands/options.ts
typescript/cli/src/commands/signCommands.ts
typescript/cli/src/commands/submit.ts
typescript/cli/src/config/submit.ts
typescript/cli/src/context/context.ts
typescript/cli/src/context/types.ts
typescript/cli/src/submit/submit.ts
typescript/cli/src/submit/types.ts
typescript/sdk/src/index.ts
typescript/sdk/src/providers/transactions/schemas.ts
typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5GnosisSafeTxSubmitter.ts
typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5ImpersonatedAccountTxSubmitter.ts
typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5JsonRpcTxSubmitter.ts
typescript/sdk/src/providers/transactions/submitter/schemas.ts
typescript/sdk/src/providers/transactions/transformer/ethersV5/EV5InterchainAccountTxTransformer.ts
typescript/sdk/src/providers/transactions/transformer/schemas.ts
typescript/sdk/src/providers/transactions/types.ts

* adds `hyperlane submit -t ./transactions.json -s ./strategy.json`
* given a set of `transactions` and a submission `strategy`, submit those transactions according to that strategy
* example strategies provided under `/cli/examples/submit/`
* detailed design: https://www.notion.so/hyperlanexyz/CLI-Submitter-Integration-8a14486803ca4ab18f229e8e7f89b57a?pvs=4
* none
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3740
- yes
```
Hyperlane Submit
----------------
Submitting 1 transactions to the jsonRpc submitter...
Sent tx 0x7158756345a913630497dac948a98b1c73921626f9c17cc936994ff22dcd908f
Pending https://alfajores.celoscan.io/tx/0x7158756345a913630497dac948a98b1c73921626f9c17cc936994ff22dcd908f (waiting 1 blocks for confirmation)
✅ Successfully submitted 1 transactions to …
```

feat(cli): add submit command

---

.changeset/nice-planes-kiss.md
typescript/infra/scripts/generate-renzo-warp-route-config.ts
typescript/sdk/src/deploy/HyperlaneDeployer.ts
typescript/sdk/src/deploy/proxy.ts
typescript/sdk/src/ism/HyperlaneIsmFactory.ts

- Initialized check before initializing implementation contract (for contracts that disableInitializers in constructors)
- set gas overrides for renzo warp route deploys
- check that validators are set
- add TODOs for verifying routing ISMs (probably should be removed @ltyu )

fix(sdk): Renzo Fraxtal Deploy Fixes

---

.changeset/four-bottles-hide.md
typescript/cli/src/commands/warp.ts
typescript/cli/src/deploy/warp.ts

- adds formatted deployment plan to confirm warp deploy on `hyperlane warp deploy`
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4129
- yes
- manual
- ci-test
Example display:
```
➜  cli git:(06-25-feat_cli_display_formatted_deployment_plan_to_confirm_warp_deploy) ✗ hl warp deploy --registry /Users/nbayindirli/workplace/Hyperlane/hyperlane-registry --verbosity trace
Hyperlane CLI
Hyperlane Warp Route Deployment
------------------------------------------------
Using warp route deployment config at ./configs/warp-route-deployment.yaml
Warp Route Deployment Plan
==========================
📋 Token Standard: ERC20
📋 Warp Route Config:
┌─────────┬───────┬─────────────┬──────────────────────────────────────────────┬──────────────────────────────────────────────┬─────── …
```

feat(cli): display formatted deployment plan to confirm warp deploy

---

typescript/infra/config/environments/mainnet3/agent.ts
typescript/infra/config/environments/testnet4/agent.ts
typescript/infra/src/config/agent/agent.ts
typescript/infra/test/agent-configs.test.ts

- follow on from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4093
- ts errors in editor if a chain is missing from the config
- makes it easier to update `ValidatorBaseChainConfigMap` in future
one chain missing:
multiple chains missing:

chore(infra): strongly type `AgentChainConfig`

---

.github/workflows/test.yml

- chore: set env-test timeout
- to avoid machines spinning idly for hours/days in jobs like this https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/9872063807/job/27261501530?pr=3888#step:6:44

chore: set env-test timeout

---

typescript/infra/config/environments/mainnet3/helloworld.ts

I didn't deploy kathy following https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3875 and we've hit some RPC issues

chore: deploy kathy

---

typescript/infra/config/environments/mainnet3/agent.ts
typescript/infra/src/infrastructure/monitoring/prometheus.ts

- Starts sending `kube_pod_container_resource_requests` to grafana
- Useful for alerts that depend on the requests for a pod
- Deployed prom servers on testnet4 and mainnet3 with this config change
- Found that the scraper CPU requests are too low - bumped to 2 CPU - seemingly upon startup there's a pretty big CPU spike, so adjusted the requests to be within this spike.
-

feat: start sending resource request metrics to grafana; bump scraper CPU requests

---

typescript/cli/src/config/warp.ts
typescript/sdk/src/deploy/verify/ContractVerifier.ts
typescript/sdk/src/deploy/verify/types.ts

- for certain failures, etherscan may return an html response we cannot parse with JSON.parse(). One such example is when our `sourceCode` is too large, due to including all build artifacts during contract verification.
- while the underlying issue is `Request Entity Too Large` for this failure, our verifier was crashing with:
```
`Error verifying contract: SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON`
```
- this change accounts for unparsable scanner responses during contract verification, and gives our users insight into the underlying failure
- minor log update
- also accounts for bug where we printed "Verification failed" every time we'd check if a contract had been verified or not before verifying
- https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4130 …

fix(sdk): account for unparsable scanner responses during contract verification

---

rust/agents/relayer/src/msg/gas_payment/mod.rs
rust/agents/relayer/src/msg/pending_message.rs
rust/hyperlane-base/src/db/rocks/hyperlane_db.rs
rust/hyperlane-core/src/traits/pending_operation.rs
rust/hyperlane-core/src/types/mod.rs

Adds new status label to relayer opqueue for operations whose gas payments were not found. This now creates a distinction between operations without a payment and those with insufficient payment.
Helps better uncover cases where hook indexing misses events because there is no receipt yet

feat(relayer): new status label for IGP not found

---

.changeset/tame-rocks-talk.md
typescript/sdk/src/deploy/verify/ContractVerifier.ts
typescript/sdk/src/deploy/verify/types.ts

- adjusts timeouts based on explorer family
- collates verif process for maintainability/readability (this also makes timeouts more consistent)
- none
- partially fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4130
- yes
- manual

fix(sdk): adjust timeouts based on explorer family & collate verif process

---

.changeset/soft-tigers-explode.md
typescript/sdk/src/deploy/verify/ContractVerifier.ts
typescript/sdk/src/deploy/verify/types.ts

- used BFS to traverse and prune the dependency graph of any named contract in the buildArtifact input to address 'entity size too large' error thrown from bsc mainnet etherscan explorer
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4164
- yes
- manual (bsc now verifying)

fix(sdk): sourceCode entity too large for contract verification

---

rust/chains/hyperlane-ethereum/src/config.rs
rust/chains/hyperlane-ethereum/src/contracts/mailbox.rs
rust/chains/hyperlane-ethereum/src/contracts/multicall.rs
rust/chains/hyperlane-ethereum/src/tx.rs

Estimating gas isn't very accurate for Multicall txs that allow failures. This PR now estimates gas as: `max(batch_tx_estimate, individual_tx_estimates_sum)`, where `individual_tx_estimates_sum` estimates each individual tx and adds a conservative overhead that `Multicall.aggregate3` adds per subtx.
The aggregate3 overhead is calcualted based on some observed tenderly gas profiling results as follows.
- For [4 txs](https://dashboard.tenderly.co/shared/simulation/63e85ac7-3ea9-475c-8218-a7c1dd508366/gas-usage):
- aggregate3 gas: 805,160
- process costs: 290,091 + 168,711 + 168,711 + 168,711 = 796,224
- overhead: 805,160 - 796,224 = 8,936 => 2,234 per subtx
- For [2 txs](https://dashboard.tenderly.co/tx/arbitrum/0xad644e431dc53c3fc0a074a749d118ff5517346c3f28d8e2513610cc9ab5c91a/gas-usage): …

fix: more conservative batching gas estimates

---

.changeset/tame-snakes-brush.md
solidity/contracts/isms/hook/ArbL2ToL1Ism.sol
solidity/script/DeployArbHook.s.sol
solidity/test/isms/ArbL2ToL1Ism.t.sol

- outbox contract can be derived from arbitrum's bridge contract so it's not useful to pass in
None
None
Yes
Unit

feat: remove outbox param from `ArbL2ToL1Ism`

---

typescript/sdk/src/ism/metadata/builder.hardhat-test.ts

Reenables metadata builder tests with decreased random limits to prevent flakes
Unit Tests

fix: enable metadata builder unit tests

---

.changeset/shaggy-feet-return.md
typescript/sdk/src/ism/metadata/builder.hardhat-test.ts

- updates the deployment of hooks to use EvmHookModule.create()
None
- fixes https://github.com/hyperlane-xyz/issues/issues/1322
Yes
Unit tests

feat: migrate metadata builder test from `HyperlaneHookDeployer` to `EvmHookModule`

---

.changeset/lazy-years-judge.md
typescript/sdk/src/hook/EvmHookReader.ts
typescript/sdk/src/ism/EvmIsmReader.ts
typescript/sdk/src/providers/SmartProvider/SmartProvider.ts
typescript/sdk/src/token/EvmERC20WarpRouteReader.ts
typescript/sdk/src/utils/HyperlaneReader.ts

- silences provider logs in deriveIsmConfig, like deriveHookConfig
- created HyperlaneReader class for readers to extend in order to reuse `setSmartProviderLogLevel`
- none
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4061
- yes
- manual
- ci

fix(sdk): silence provider logs in deriveIsmConfig

---

rust/.gitignore
rust/Cargo.lock
rust/Cargo.toml
rust/agents/relayer/Cargo.toml
rust/agents/relayer/src/main.rs
rust/agents/relayer/src/memory_profiler.rs
rust/agents/relayer/src/server/mod.rs
rust/hyperlane-base/src/contract_sync/cursors/mod.rs
rust/hyperlane-base/src/contract_sync/mod.rs
rust/utils/run-locally/src/cosmos/mod.rs
rust/utils/run-locally/src/main.rs

During the scalability audit we've identified relayer memory usage as a cause of concern. This PR runs the profiler each time e2e is run and outputs a report called `dhat-heap.json` in the current dir. That file can be visualised with a dhat viewer, such as the one hosted by the author [here](https://nnethercote.github.io/dh_view/dh_view.html).
It adds a conditionally compiled heap memory profiler ([dhat-rs](https://docs.rs/dhat/latest/dhat/)), which is only included when both the `memory-profiling` feature is enabled and the `memory-profiling` cargo profile is used.
The report can order the profiling results by total lifetime allocated bytes, peak allocated bytes, total allocation count, etc. Below is the result of sorting by total lifetime allocated bytes, which reveals that the biggest …

feat: Relayer heap profiling

---

rust/chains/hyperlane-ethereum/src/contracts/interchain_gas.rs
rust/chains/hyperlane-ethereum/src/contracts/mailbox.rs
rust/chains/hyperlane-ethereum/src/contracts/merkle_tree_hook.rs
rust/chains/hyperlane-ethereum/src/contracts/validator_announce.rs
rust/chains/hyperlane-ethereum/src/ism/aggregation_ism.rs
rust/chains/hyperlane-ethereum/src/ism/ccip_read_ism.rs
rust/chains/hyperlane-ethereum/src/ism/interchain_security_module.rs
rust/chains/hyperlane-ethereum/src/ism/multisig_ism.rs
rust/chains/hyperlane-ethereum/src/ism/routing_ism.rs
rust/chains/hyperlane-ethereum/src/rpc_clients/provider.rs
rust/chains/hyperlane-ethereum/src/rpc_clients/trait_builder.rs
rust/hyperlane-base/src/settings/chains.rs

Adds an associated const to all ethereum provider builders to specify whether a signer is needed. For an e2e run with 20 messages, we now have 12 providers built with signers at the beginning (3 of which are validator announce), and 708 providers built without a signer. This should hopefully fix the gas escalator memory leak.

fix(evm): only create signer provider when needed

---

.changeset/spotty-ducks-sell.md
typescript/cli/src/commands/core.ts
typescript/cli/src/utils/files.ts

This PR adds a helper function that logs the config terminal "preview", _only_ if the number of lines is < 250 for `hyperlane core read`.
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4191
Yes
Manual
- `yarn build && yarn hyperlane core read --mailbox 0x2f9DB5616fa3fAd1aB06cB2C906830BA63d135e3  --chain fraxtal `
- And tried with a deployed one to test out lines < 250

fix(cli): hide large configs in core read command

---

.changeset/cuddly-fans-chew.md
typescript/ccip-server/package.json
typescript/ccip-server/src/services/HyperlaneService.ts
typescript/ccip-server/src/services/__mocks__/HyperlaneService.ts
typescript/ccip-server/src/services/explorerTypes.ts
typescript/infra/package.json
typescript/sdk/package.json
typescript/sdk/src/token/adapters/CosmosTokenAdapter.ts
typescript/utils/package.json
yarn.lock

- Upgrade CosmJS libs to 0.32.4
- Remove explorer dep from ccip-server
https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/issues/202
No, major version bump required because CosmJS 0.32 is not backwards compatible with 0.31
Tested in Warp UI

chore: Upgrade CosmJS libs to 0.32.4

---

rust/Cargo.lock
rust/Cargo.toml
rust/agents/relayer/src/relayer.rs
rust/agents/scraper/src/agent.rs
rust/chains/hyperlane-ethereum/src/contracts/interchain_gas.rs
rust/chains/hyperlane-ethereum/src/contracts/mailbox.rs
rust/chains/hyperlane-ethereum/src/contracts/merkle_tree_hook.rs
rust/chains/hyperlane-ethereum/src/contracts/validator_announce.rs
rust/chains/hyperlane-ethereum/src/ism/aggregation_ism.rs
rust/chains/hyperlane-ethereum/src/ism/ccip_read_ism.rs
rust/chains/hyperlane-ethereum/src/ism/interchain_security_module.rs
rust/chains/hyperlane-ethereum/src/ism/multisig_ism.rs
rust/chains/hyperlane-ethereum/src/ism/routing_ism.rs
rust/chains/hyperlane-ethereum/src/rpc_clients/provider.rs
rust/chains/hyperlane-ethereum/src/rpc_clients/trait_builder.rs
rust/hyperlane-base/src/contract_sync/broadcast.rs
rust/hyperlane-base/src/contract_sync/cursors/mod.rs
rust/hyperlane-base/src/contract_sync/mod.rs
rust/hyperlane-base/src/settings/chains.rs
rust/utils/run-locally/src/invariants.rs

Follow up to https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4180
Lowers txid broadcast channel capacity from 1M to 30k and refactors it to use a vec of `mpsc` under the hood.
The heap profiler showed that each new chain takes up 100MB of memory because of the txid broadcast channel. In addition to this, the tokio broadcast channel is a ring buffer where new items simply overwrite old items, making it hard to safely lower the capacity. 
As such, to be able to safely lower the capacity of this channel, usage of `tokio`'s `broadcast` channel is replaced with a `Vec` of `mpsc`s, which offer an async `send` interface for backpressure. So instead of overwriting old items, senders will block on sends, which makes sense in our case as we absolutely don't want to miss items. The …

feat: use multiple `mpsc` channels instead of `broadcast` for async interface

---

.changeset/plenty-cameras-hide.md
typescript/cli/src/commands/core.ts

```sh
yarn hyperlane core read --chain etherereum
```
will fetch mailbox address from registry
None
Yes
Manual

feat: default to mailbox address in registry

---

.changeset/fast-teachers-drum.md
typescript/cli/src/send/message.ts
typescript/cli/src/send/transfer.ts
typescript/cli/src/status/message.ts
typescript/cli/src/utils/relay.ts

Circumvents bad hook derivation during self relay
- Fixes https://github.com/hyperlane-xyz/issues/issues/1320
Yes
manual warp send from sepolia origin

fix: use merkle tree hook address from registry for self relay hook derivations

---

typescript/infra/package.json
typescript/infra/scripts/check-deploy.ts
typescript/infra/src/utils/violation.ts
typescript/sdk/src/core/HyperlaneCoreChecker.ts
typescript/sdk/src/router/HyperlaneRouterChecker.ts
yarn.lock

- check-deploy will surface violations when the on-chain ISM state differs from the config for core and warp modules
Example of running check-deploy when the warp config includes a new validator Vs on-chain ISM state
```
┌─────────┬────────────┬────────┬──────────────┬─────────────┬─────────┬──────────────────────────────────────────────┬──────────────────────────────────────────────┐
│ (index) │ chain      │ remote │ name         │ type        │ subType │ actual                                       │ expected                                     │
├─────────┼────────────┼────────┼──────────────┼─────────────┼─────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┤
│ 0       │ 'ethereum' │        │              │ 'ClientIsm' │         │ …
```

feat(infra): ensure check-deploy covers ownable ISMs

---

typescript/sdk/src/ism/metadata/builder.hardhat-test.ts

Reverts hyperlane-xyz/hyperlane-monorepo#4176
Fixes flakey metadata builder test

fix: revert "fix: enable metadata builder unit tests"

---

.changeset/chatty-suns-breathe.md
typescript/sdk/src/providers/transactionFeeEstimators.ts

`tmClient` (i.e. TendermintClient) is now `cometClient`
Related to #4209 but not surfaced because of ts-ignore, which is necessary because the required data isn't surfaced properly by CosmJS
Yes
Tested in Warp UI

fix(sdk): Access correct consensus client when estimating cosmwasm txs

---

.changeset/chilly-cups-tap.md
typescript/cli/src/commands/core.ts

Fixes `hyperlane core apply` to say "Hyperlane Core Apply"
Yes
Manual

fix(cli): hyperlane core apply logging fix

---

.changeset/fast-schools-battle.md
typescript/cli/src/config/hooks.ts
typescript/cli/src/config/ism.ts
typescript/cli/src/config/warp.ts
typescript/cli/src/deploy/agent.ts
typescript/cli/src/utils/chains.ts

Block on user selecting multiple chains in `hyperlane warp init`
Adjust incorrect requirement of multiple chain selection in routing ISM builder
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4255
Yes
Manual

fix: require multiple chains in warp init

---

rust/README.md

E2E tests will fail if `hyperlane-registry` repo is not cloned next to the monorepo. This change adds it to the `rust/README.md` file.
Checked how `rust/README.md` looks like in GitHub.

docs: Add hyperlane registry as prerequisite for e2e tests

---

typescript/infra/scripts/secret-rpc-urls/set-rpc-urls-from-registry.ts
typescript/infra/scripts/secret-rpc-urls/set-rpc-urls.ts
typescript/infra/src/utils/rpcUrls.ts

resolves https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4227
- add `set-rpc-urls-from-registry` script to set secrets by reading in contents of registry
- example usage: `yarn tsx scripts/secret-rpc-urls/set-rpc-urls-from-registry.ts -e mainnet3 -c base zircuit arbitrum`
- refactored `set-rpc-urls` to reuse logic across both scripts

feat: add script to set rpc secrets from registry

---

.changeset/pretty-dots-look.md
typescript/cli/src/commands/warp.ts

- Add output of `hyperlane warp read` to ./configs/warp-route-deployment.yaml, similar to `hyperlane core read`
Fixes bug bash issue: "warp read gives you more info than the config/addresses file in .hyperlane"
Yes
Manual

feat(cli): Add output of hyperlane warp read to file 

---

.changeset/warm-zoos-smell.md
typescript/cli/src/commands/core.ts
typescript/cli/src/deploy/utils.ts

Add check & confirm for existing mailbox to core deploy to allow users to decide if they want to deploy a new mailbox
Add skip confirmation to core deploy
Yes
Manual

feat(cli): Add existing mailbox confirmation to core deploy

---

.changeset/breezy-turkeys-march.md
typescript/sdk/src/providers/SmartProvider/SmartProvider.foundry-test.ts
typescript/sdk/src/providers/SmartProvider/SmartProvider.ts

Ethersjs [parses](https://github.com/ethers-io/ethers.js/blob/0bfa7f497dc5793b66df7adfb42c6b846c51d794/packages/providers/src.ts/etherscan-provider.ts#L129-L154) the [jsonrpc](https://www.jsonrpc.org/specification#response_object) responses into their own error codes and Error object. This is an attempt to add handling for blockchain specific errors such as: 
- `Error: execution reverted: MailboxClient: invalid mailbox`
- `Error: insufficient funds for intrinsic transaction cost`
Fixes Bug bash issues:
- "Balance was not sufficient to deploy even though I was told it was"
- “Replace RPC” error shown when mailbox is “invalid”
Yes
Manual

fix(cli): blockchain reason error handling

---

typescript/infra/config/environments/mainnet3/owners.ts
typescript/infra/config/environments/testnet4/helloworld.ts

Successful ICA interactions here: https://www.notion.so/hyperlanexyz/Test-ICA-call-Ethereum-viction-inevm-f7bb4414554248cda038f19489267ec4?pvs=4#66c9651cda2a45b69c49533b24c06500
- Adds the viction ICA as the new owner
- Doesn't yet set the inEVM owner - it's in there but commented out. If it's added now, we'll start to have new contracts be owned by it, but it'll also result in a lot of violations. Happy to uncomment it if that seems better.
- Ideally the ICAs would be generated from the owner address on the ethereum chain, but atm the best way to do this is an eth_call, and we sadly can't do async calls. It's an option to write a non-async version that uses some fancy create2 logic in ts, but this felt like overkill. I can also write a test, but it feels a bit weird to have eth_calls to …

feat: configure ICA owners

---

typescript/infra/config/environments/mainnet3/agent.ts

See thread https://discord.com/channels/935678348330434570/935679524534911007/1271367720797077548 for context.
TLDR:
- upon starting up, validators tend to use more CPU and memory, and this scales a bit with # of messages previously dispatched on that chain
- nothing concerning, but we were exceeding the 75% usage / requests threshold on some of our alerts, so bumping to give some room

chore: bump validator resource requests

---

typescript/sdk/src/ism/metadata/multisig.test.ts

example of test that flakes fairly regularly: https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/10316932362/job/28560341286#step:6:1022

fix: temporarily skip flaky MultisigMetadataBuilder test

---

typescript/infra/config/environments/mainnet3/warp/configGetters/getAncient8EthereumUSDCWarpConfig.ts
typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumInevmUSDCWarpConfig.ts
typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumInevmUSDTWarpConfig.ts
typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionETHWarpConfig.ts
typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionUSDCWarpConfig.ts
typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionUSDTWarpConfig.ts
typescript/infra/config/environments/mainnet3/warp/getAncient8EthereumUSDCWrapConfig.ts
typescript/infra/config/warp.ts
typescript/infra/scripts/agent-utils.ts
typescript/infra/scripts/check-deploy.ts
typescript/infra/scripts/deploy.ts
typescript/infra/scripts/get-warp-route-ids.ts
typescript/infra/src/config/warp.ts
typescript/infra/src/utils/violation.ts
typescript/sdk/src/core/HyperlaneCoreChecker.ts
typescript/sdk/src/router/HyperlaneRouterChecker.ts

- Add in code configs for EVM base warp routes
- Allow checker tooling (check-deploy) to read and run against the config
- Read Warp addresses from registry when run check-deploy for warp modules
- clean up ISM config comparison violation message to handle ISM addressed
Yes
Manual

feat(infra): supporting generating warp configs for EVM routes

---

rust/chains/hyperlane-ethereum/src/rpc_clients/trait_builder.rs

- fix: typo in trait builder log
- noticed while looking at scraper logs

fix: typo in trait builder log

---

.changeset/sour-ladybugs-appear.md
typescript/cli/src/commands/core.ts

This removes the `getUri()` from a specific log because the function throws for MergeRegistry and ends up hiding the real error message.
Yes
Manual

fix(cli): Remove getUri from core read logging

---

typescript/sdk/src/consts/multisigIsm.test.ts
typescript/sdk/src/consts/multisigIsm.ts

- Thresholds must always be a set majority, enforced by a unit test
- Updates thresholds for some chains that should've been updated as the set expanded

fix: require thresholds to always be a set majority

---

codecov.yml
solidity/.vscode/extensions.json
solidity/coverage.sh

- Remove lcov toolchain from coverage script in favor of new native forge features
- Require strictly increasing project coverage
- Add coverage gutters to vscode recommendations for inline view
Yes
See codecov report comment

chore: use new forge feature for filtering coverage

---

.changeset/nine-lamps-boil.md
typescript/sdk/src/token/Token.test.ts
typescript/sdk/src/token/Token.ts
typescript/sdk/src/token/TokenStandard.ts

Adds CollateralFiat to token mapping which will output the correct `standard` to the warp deploy artifact.
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4307
Yes
Manually tested with Beta (collateral) -> Gamma (CollateralFiat)
1. Deploy an ERC20 to represent USDC on beta
```
forge create contracts/test/ERC20Test.sol:ERC20Test \
--constructor-args "Test" "TS" 10000000000000000000000000 6 \
--rpc-url https://beta-op.rpc.caldera.xyz/http \
--private-key $HYP_KEY
```
2. Deploy a CollateralFiat on gamma
```
forge create contracts/test/ERC20Test.sol:FiatTokenTest \
--constructor-args "FiatTest" "FTS" 0 6 \
--rpc-url https://rpc-gamma-2bgo7wnh9d.t.conduit.xyz \
--private-key $HYP_KEY
```
3. warp init and deploy
4. Start up the ts relayer `hyperlane relayer --chains beta,gamma`
5. …

fix(sdk): Add collateralFiat support into Token.ts & TokenStandard.ts

---

.changeset/curly-mangos-buy.md
typescript/infra/scripts/check-deploy.ts
typescript/sdk/src/core/HyperlaneCore.ts
typescript/sdk/src/router/schemas.ts
typescript/sdk/src/token/app.ts
typescript/sdk/src/token/checker.ts

- Extend `HypERC20Checker` with `ProxiedRouterChecker` so we can check for proxyAdmin violations (`checkProxiedContracts` is call in `checkChain`)
- Support passing `proxiedFactories` to `HypERC20App`  
- #4325 
Manual

feat(HypERC20App): Support proxiedFactories in HypERC20App, extend HypERC20Checker with ProxiedRouterChecker

---

typescript/infra/src/infrastructure/monitoring/prometheus.ts

- Labels chosen by looking at https://abacusworks.grafana.net/d/cardinality-management/cardinality-management-1-overview?var-datasource=grafanacloud-prom&from=2024-08-15T11:34:34.928Z&to=2024-08-16T11:34:34.929Z
- Motivating case: a GKE rolling upgrade recently resulting in some issues with the remote write where it complained about too many series https://abacusworks.grafana.net/d/cdn9jukg55bswb/usage-insights-5-metrics-ingestion?var-instance=$__all&viewPanel=panel-9&from=2024-08-16T10:04:52.962Z&to=2024-08-16T11:04:52.962Z (thread https://discord.com/channels/935678348330434570/1273952173037715458)
- Many of these labels would change whenever a pod would be restarted, a new deploy occurred, new nodes set up, etc
- Deployed to testnet4 and mainnet3 and observed the labels were dropped

chore: drop some labels in remote writes to lower cardinality
