- typescript/sdk/src/ism/metadata/arbL2ToL1.ts
warp template UI throws
Yes
Manual
> fix(sdk): Remove console.assert

- .eslintrc
- typescript/cli/.eslintrc
- typescript/sdk/src/ism/metadata/aggregation.test.ts
- typescript/sdk/src/ism/metadata/arbL2ToL1.ts
- typescript/sdk/src/ism/metadata/multisig.test.ts
- typescript/sdk/src/providers/SmartProvider/SmartProvider.ts
- typescript/sdk/src/warp/WarpCore.test.ts
Incorrect imports from node-specific global libs, especially for `assert` are very common. This won't catch all possible mistakes but it will help avoid future problems like https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4327 
Yes
> chore: Enable no-restricted-imports eslint rule

- .changeset/light-poets-teach.md
- solidity/contracts/hooks/OPL2ToL1Hook.sol
- solidity/contracts/interfaces/IInterchainSecurityModule.sol
- solidity/contracts/interfaces/hooks/IPostDispatchHook.sol
- solidity/contracts/interfaces/optimism/ICrossDomainMessenger.sol
- solidity/contracts/interfaces/optimism/IOptimismPortal.sol
- solidity/contracts/isms/hook/OPL2ToL1Ism.sol
- solidity/contracts/libs/OPL2ToL1Metadata.sol
- solidity/contracts/mock/MockOptimism.sol
- solidity/test/isms/ArbL2ToL1Ism.t.sol
- solidity/test/isms/OPL2ToL1Ism.t.sol
Implementing the `OPL2ToL1Hook` and OPL2ToL1Ism` contracts for using the Optimism native bridge for sending messages from the L2 to L1.
- Optimism needs double call encoding for the direct portal call because the portal itself calls the l1Messenger which then directs it to the ism.
None
- fixes https://github.com/hyperlane-xyz/issues/issues/1346
Yes
Unit testing with mocks for OP contracts
> feat: implement `OPL2ToL1Ism` contracts

- .changeset/gentle-chicken-hammer.md
- typescript/sdk/src/token/checker.ts
- When setting up the warp configuration for an `xERC20Lockbox` contract, we pass the lockbox address in the token field for the config and we lookup the underlying ERC20 token in the smart contract constructor https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/1579ca221c2741764207d1d2fa9f8383ac633d55/solidity/contracts/token/extensions/HypXERC20Lockbox.sol#L17 
- This change accounts for this setup when checking for `CollateralTokenMismatch` violations
Manual
> feat(checkToken): Support checking token config for xERC20Lockbox type

- typescript/sdk/src/providers/SmartProvider/SmartProvider.ts
This stops deriving errors such as `hyperlane ism read --address 0xc6608b648111020719d85163017a0dd2c9943d69 --chain fraxtal`
Manual
> fix(sdk): Update smart provider logging to debug

- .changeset/grumpy-taxis-shout.md
- typescript/infra/scripts/check-deploy.ts
- typescript/infra/src/govern/HyperlaneAppGovernor.ts
- typescript/sdk/src/core/HyperlaneCoreChecker.ts
- typescript/sdk/src/deploy/HyperlaneAppChecker.ts
- typescript/sdk/src/deploy/types.ts
- typescript/sdk/src/gas/HyperlaneIgpChecker.ts
- typescript/sdk/src/router/ProxiedRouterChecker.ts
- Support checking proxyAdmin owners for non AW proxy admins
- Stop assuming all proxyAdmins will be owned by AW
- This change was motivated by the need to have our checker tooling check Renzo Wapr routes, where Renzo owns the proxy routers
- Clean up the interface for `ProxyAdminViolation`
Manual
> feat(sdk): Support proxyAdmin checks for admins not owned by AW

- solidity/contracts/mock/MockHyperlaneEnvironment.sol
- solidity/test/InterchainAccountRouter.t.sol
> refactor: Rename InterchainAccountRouter tests for easier reuse

- .github/workflows/monorepo-docker.yml
- typescript/infra/scripts/warp-routes/helm.ts
- typescript/sdk/src/consts/chainMetadata.ts
for warp route monitoring
Note my confidence in the warp route deployment tooling in infra is low on v2 - so I just edited the sts
> chore: update nautilus rpc url

- rust/Cargo.lock
- rust/sealevel/client/Cargo.toml
- rust/sealevel/client/src/core.rs
- rust/sealevel/client/src/main.rs
- rust/sealevel/libraries/test-utils/src/lib.rs
- rust/sealevel/programs/hyperlane-sealevel-token-collateral/tests/functional.rs
- rust/sealevel/programs/hyperlane-sealevel-token-native/tests/functional.rs
- rust/sealevel/programs/hyperlane-sealevel-token/tests/functional.rs
- rust/sealevel/programs/mailbox-test/src/functional.rs
- rust/sealevel/programs/mailbox/Cargo.toml
- rust/sealevel/programs/mailbox/src/accounts.rs
- rust/sealevel/programs/mailbox/src/instruction.rs
- rust/sealevel/programs/mailbox/src/lib.rs
- rust/sealevel/programs/mailbox/src/processor.rs
- rust/sealevel/programs/mailbox/src/protocol_fee.rs
Adds protocol fees to the Sealevel implementation, by embedding the logic / custody into the mailbox program & PDA. The logic is very similar to what already exists in the IGP implementation.
The instructions to interact with the protocol fees implementation are:
- `Init` (now requires specifying the `protocol_fee` and `beneficiary` in addition to the other mailbox params)
- `ClaimProtocolFees` - invokable by anyone, and sending accumulated lamports to the `beneficiary`
- `SetProtocolFeeConfig` - invokable by the owner, sets new values for `protocol_fee` and / or `beneficiary`
- The restriction applied on max message size has been removed to mirror the Solidity V3 implementation
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4356
No - requires redeploying the mailbox …
> feat(sealevel): charge protocol fees

- rust/config/mainnet_config.json
- rust/utils/run-locally/src/ethereum/mod.rs
- typescript/infra/.gitignore
- typescript/infra/config/environments/mainnet3/helloworld.ts
- typescript/infra/config/environments/mainnet3/index.ts
- typescript/infra/config/environments/testnet4/index.ts
- typescript/infra/package.json
- typescript/infra/scripts/agent-utils.ts
- typescript/infra/scripts/agents/update-agent-config.ts
- typescript/infra/scripts/deploy.ts
- typescript/infra/src/config/environment.ts
- typescript/infra/src/deployment/deploy.ts
- typescript/infra/src/utils/utils.ts
- typescript/sdk/src/deploy/HyperlaneDeployer.ts
- typescript/sdk/src/hook/HyperlaneHookDeployer.ts
feat: misc improvements to infra deployments
These are all things that I've done somewhat ad-hoc before, but now upstreaming into the monorepo.
- write the deploy plan to a file instead of stdout
- to avoid cluttering terminal with 1000+ line configs
- `getMultiProviderForRole` should only be populated with the requested set of chains or the supported chains for given environmen
- to avoid fetching 50+ more keys than you need to on any given deploy
- remove the agent config write-back from the post-deploy
- this is already covered by the update-agent-config.ts script which is usually ran manually anyway
- also moved the helper function into the update-agent-config.ts file, as that is the only place it is being used right now
- in `infra/scripts` instead of `infra/src` to avoid a …
> feat: misc improvements to infra deployment

- rust/chains/hyperlane-cosmos/src/providers/grpc.rs
- rust/chains/hyperlane-cosmos/src/providers/grpc/tests.rs
- rust/chains/hyperlane-cosmos/src/providers/mod.rs
Currently, integration into Cosmos make an assumption that the address where a message should be delivered is a contract. This change allows Relayer to actually check if the recipient is a contract.
Yes
* Tested using E2E tests for Cosmos.
* Tested using auxiliary unit test (it is marked as ignored since it connects to real gRPC of Neutron).
> feat: Add check if an address is a contract in Cosmos

- typescript/infra/config/environments/testnet4/agent.ts
- typescript/infra/config/environments/testnet4/core/verification.json
- typescript/sdk/src/deploy/verify/ContractVerifier.ts
- typescript/sdk/src/deploy/verify/PostDeploymentContractVerifier.ts
- adds some missing verification artifacts from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3874
- update tag in config of testnet4 validators from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4316
- driveby: don't throw error if contract already verified
- driveby: gracefully catch errors when running post-deployment verification
> chore: update testnet4 config

- typescript/infra/config/environments/mainnet3/ism/verification.json
- typescript/infra/config/environments/testnet4/ism/verification.json
- Adding staticMerkleRootWeightedMultisigIsmFactory and staticMessageIdWeightedMultisigIsmFactory verification outputs
> feat: weighted ISM factory deployments

- rust/agents/validator/src/settings.rs
- typescript/infra/src/config/agent/validator.ts
- typescript/sdk/src/metadata/agentConfig.ts
Fixing the issue I described [earlier](https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3156#issuecomment-2285659584) where the usage of GCS as an alternative to AWS although supported by Hyperlane Agents, in practice didn't work because the settings still didn't accept "gcs" as a checkpoint syncer type.
Yes
Manual
> feat: Fix GCS support: setting checkpointSyncer.type=gcs

- .changeset/tricky-horses-repair.md
- typescript/cli/examples/submit/strategy/gnosis-ica-strategy.yaml
- typescript/cli/examples/submit/strategy/gnosis-strategy.yaml
- typescript/cli/examples/submit/strategy/impersonated-account-strategy.yaml
- typescript/cli/examples/submit/strategy/json-rpc-strategy.yaml
- typescript/cli/src/commands/submit.ts
- typescript/cli/src/config/submit.ts
- typescript/cli/src/context/context.ts
- typescript/cli/src/context/types.ts
- typescript/sdk/src/index.ts
- typescript/sdk/src/providers/transactions/schemas.ts
- typescript/sdk/src/providers/transactions/submitter/builder/schemas.ts
- typescript/sdk/src/providers/transactions/submitter/builder/types.ts
- This PR is a prerequisite for https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4225
- Adds `ChainSubmissionStrategy` which is a ChainMap of SubmissionStrategy
- Moves the submissionStrategy logic out of the context to allow `--strategy` to be used for both cases (mostly to not having to parse and validate 2 schemas in `getSubmissionStrategy()`)
- Adds logic to assume that all `--transactions` are of the same chainId with explicit validation
Yes
Manual
> feat: Add ChainSubmissionStrategy and update hyperlane submit

- .changeset/red-nails-trade.md
- typescript/sdk/src/token/adapters/CosmWasmTokenAdapter.ts
CosmWasm `ExecuteContract` message require that the attached `funds` attached are sorted by denom ([ref](https://github.com/CosmWasm/wasmd/blob/1d0c66c4cfdf996d12d044638b685b9d09bbd7c1/x/wasm/types/tx.go#L131) and [ref](https://github.com/cosmos/cosmos-sdk/blob/19e0de5e0aab223b8a0dc53a0717ff0120dcb51a/types/coin.go#L270)). 
The current hyperlane-sdk [implementation](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/092ce5fd392eeec2782949062ff084e25ee68e6e/typescript/sdk/src/token/adapters/CosmWasmTokenAdapter.ts#L405-L414) does not have sorting, which causes both the message simulation and submission to fail.  
No
#4384 
Yes
Manual
> fix: sort cosmwasm funds by denom

- rust/utils/run-locally/src/ethereum/mod.rs
- test.yaml workflow already installs yarn dependencies and runs `yarn build` so it's redundant and wasteful to do the same in the main.rs file for run-locally which is dependent on yarn build as it is. So, I made it conditional if E2E_CI_MODE="false".
yarn install ~= 19s
yarn build ~= 1m33s
It should save us 1m52s in the usual longest running CI item.
None
e2e
> fix: remove redundant ``yarn install && yarn build`` from e2e

- .changeset/stale-planets-dance.md
- solidity/contracts/isms/hook/ArbL2ToL1Ism.sol
- solidity/test/isms/ArbL2ToL1Ism.t.sol
- typescript/sdk/src/ism/metadata/arbL2ToL1.ts
- Added support for msg.value by rearranging the `releaseValueToRecipient()` in the verify call
- uncommented out `test_postDispatch_revertWhen_notLastDispatchedMessage` test
Unit tests
> fix: `ArbL2ToL1Ism` will support msg.value

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/scripts/agents/deploy-agents.ts
- typescript/infra/src/agents/aws/key.ts
- deployed to include #4214 
- some drive-bys, e.g. one flaky AWS interaction, and to use a non-zero exit code if there's an error deploying agents
> chore: deploy agents

- rust/chains/hyperlane-cosmos/src/libs/account.rs
- rust/chains/hyperlane-cosmos/src/libs/address.rs
- rust/chains/hyperlane-cosmos/src/libs/mod.rs
- rust/chains/hyperlane-cosmos/src/providers/mod.rs
Populate gas price, nonce and contract as a recipient of a transaction (still naive handling).
Yes
E2E Test for Cosmos (no check in the invariant yet)
> feat: populate more fields in scraper for Cosmos

- rust/Cargo.toml
- rust/sealevel/libraries/access-control/Cargo.toml
- rust/sealevel/libraries/account-utils/Cargo.toml
- rust/sealevel/libraries/ecdsa-signature/Cargo.toml
- rust/sealevel/libraries/hyperlane-sealevel-connection-client/Cargo.toml
- rust/sealevel/libraries/hyperlane-sealevel-token/Cargo.toml
- rust/sealevel/libraries/interchain-security-module-interface/Cargo.toml
- rust/sealevel/libraries/message-recipient-interface/Cargo.toml
- rust/sealevel/libraries/multisig-ism/Cargo.toml
- rust/sealevel/libraries/serializable-account-meta/Cargo.toml
- rust/sealevel/libraries/test-transaction-utils/Cargo.toml
- rust/sealevel/libraries/test-utils/Cargo.toml
- rust/sealevel/programs/hyperlane-sealevel-igp-test/Cargo.toml
- rust/sealevel/programs/hyperlane-sealevel-igp/Cargo.toml
- rust/sealevel/programs/hyperlane-sealevel-token-collateral/Cargo.toml
- rust/sealevel/programs/hyperlane-sealevel-token-native/Cargo.toml
- rust/sealevel/programs/hyperlane-sealevel-token/Cargo.toml
- rust/sealevel/programs/ism/multisig-ism-message-id/Cargo.toml
- rust/sealevel/programs/ism/test-ism/Cargo.toml
- rust/sealevel/programs/mailbox-test/Cargo.toml
- rust/sealevel/programs/mailbox/Cargo.toml
- rust/sealevel/programs/test-send-receiver/Cargo.toml
- rust/sealevel/programs/validator-announce/Cargo.toml
Backport of https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4402
Fixes `cargo build-sbf` warnings by moving all profile overrides to `rust/Cargo.toml`, so they actually take effect.
> fix(v2): set profile overrides in root manifest

- rust/Cargo.toml
- rust/sealevel/libraries/access-control/Cargo.toml
- rust/sealevel/libraries/account-utils/Cargo.toml
- rust/sealevel/libraries/ecdsa-signature/Cargo.toml
- rust/sealevel/libraries/hyperlane-sealevel-connection-client/Cargo.toml
- rust/sealevel/libraries/hyperlane-sealevel-token/Cargo.toml
- rust/sealevel/libraries/interchain-security-module-interface/Cargo.toml
- rust/sealevel/libraries/message-recipient-interface/Cargo.toml
- rust/sealevel/libraries/multisig-ism/Cargo.toml
- rust/sealevel/libraries/serializable-account-meta/Cargo.toml
- rust/sealevel/libraries/test-transaction-utils/Cargo.toml
- rust/sealevel/libraries/test-utils/Cargo.toml
- rust/sealevel/programs/hyperlane-sealevel-igp-test/Cargo.toml
- rust/sealevel/programs/hyperlane-sealevel-igp/Cargo.toml
- rust/sealevel/programs/hyperlane-sealevel-token-collateral/Cargo.toml
- rust/sealevel/programs/hyperlane-sealevel-token-native/Cargo.toml
- rust/sealevel/programs/hyperlane-sealevel-token/Cargo.toml
- rust/sealevel/programs/ism/multisig-ism-message-id/Cargo.toml
- rust/sealevel/programs/ism/test-ism/Cargo.toml
- rust/sealevel/programs/mailbox-test/Cargo.toml
- rust/sealevel/programs/mailbox/Cargo.toml
- rust/sealevel/programs/test-send-receiver/Cargo.toml
- rust/sealevel/programs/validator-announce/Cargo.toml
Fixes `cargo build-sbf` warnings by moving all profile overrides to `rust/Cargo.toml`, so they actually take effect.
- Fixes https://github.com/hyperlane-xyz/issues/issues/1368
Yes
Manually, by initializing `inbox.processed_count` to `u64::MAX - 1`, and then observing logs in e2e:
```
13: Program log: About to increment processed count. Current count: 18446744073709551615
14: Program log: panicked at 'attempt to add with overflow', sealevel/programs/mailbox/src/processor.rs:386:5
```
The panic occurs at `inbox.processed_count += 1;`
> fix: set profile overrides in root manifest

- rust/chains/hyperlane-cosmos/src/libs/account.rs
- rust/chains/hyperlane-cosmos/src/libs/address.rs
- rust/chains/hyperlane-cosmos/src/providers/mod.rs
- rust/hyperlane-core/src/error.rs
* Use correct signer as sender
* Add error handling in getting block by hash
Yes
E2E Test for Cosmos (no implementation in invariant)
> feat: add error handling for blocks and proper sender

- .github/workflows/test.yml
fix: disable fail-fast on e2e-matrix
currently only the non-cosmwasm tests are required to merge, therefore we should not fail the entire matrix if the cosmos job fails. This also means we can test that the issues we're seeing with the `cosmwasm` job do not affect the `non-cosmwasm` one.
> fix: disable fail-fast on e2e-matrix

- .github/workflows/test.yml
- rust/utils/run-locally/src/cosmos/mod.rs
increase time waiting for postgres to be ready, to reduce this sort of flake https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/10665491633/job/29559169324?pr=4410#step:13:2998 
based on the logs it looks like 10s is just on the border, adding an extra 5s to give headroom
currently only the non-cosmwasm tests are required to merge, therefore we should not fail the entire matrix if the cosmos job fails. This also means we can test that the issues we're seeing with the `cosmwasm` job do not affect the `non-cosmwasm` one.
> fix: increase wait time for postgres to be ready in cosmos e2e

- .github/workflows/test.yml
- typescript/infra/fork.sh
- typescript/infra/scripts/run-anvil.ts
- typescript/infra/src/config/chain.ts
- Use Arbitrum and Optimism private RPCs that are set in Github Secrets for env-test
- Increase env-test timeout to 4 mins for viction
- Adapt fork script so that it create anvil instance by calling a script
Manual
> feat(envTests): Support using secret rpcs for CI env tests

- rust/sealevel/client/src/main.rs
Needed to disable relaying to Nautilus on Solana
> feat: add the ability to remove a gas config from the sealevel IGP

- typescript/infra/config/environments/mainnet3/owners.ts
- typescript/infra/scripts/get-owner-ica.ts
feat: support getting owner ICA on multiple chains
- change `chain` -> `chains` 
- print a cool table of chains and the ICAs on each destination chain for a given owner
- add as stronger type to the ICA address map const
getting ICAS:
getting ICAS with `--deploy`:
> feat: support getting owner ICA on multiple chains

- .github/workflows/test.yml
chore: increase env-test timeout to 10 minutes
- to give even more headroom in case some tests take longer
- trying to rule out chance of timeouts affecting the success/failure of a test https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/10704561765/job/29678091884?pr=4395#step:6:1210
> chore: increase env-test timeout to 10 minutes

- typescript/cli/ci-advanced-test.sh
fix: temporarily disable dry-run in cli-advanced-e2e
- until we fix the problem with our call to `resetFork` after a dry-run deployment
- our CI uses the latest nightly foundry releases, and this recent PR https://github.com/foundry-rs/foundry/pull/8768 has broken the fork reset. Ironically, this PR actually is a bugfix for something that was broken that we relied on.
Examples of failures:
- https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/10772795435/job/29873480020?pr=4441#step:12:133
- https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/10751285630/job/29818541086?pr=4448
Note that the `pi_with_core_chain` tests don't fail because they do not do a dry run
> fix: temporarily disable dry-run in cli-advanced-e2e

- rust/agents/relayer/src/msg/pending_message.rs
> chore: revert to using a 10 min relayer `CONFIRM_DELAY`

- typescript/sdk/src/hook/EvmHookModule.hardhat-test.ts
- typescript/sdk/src/ism/EvmIsmModule.hardhat-test.ts
- typescript/sdk/src/ism/HyperlaneIsmFactory.hardhat-test.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.hardhat-test.ts
chore: streamline module test setup
- move reusable setup into `before`
- keep necessary per-test setup in `beforeEach`
- shaves off several minutes from `yarn test:ci` time
- [~15m](https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/10797378870/job/29948649484) -> [~6m](https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/10802337166/job/29964269588?pr=4475)
> chore: streamline evm module/deployer test setup

- .github/actions/yarn-build-with-cache/action.yml
- .github/workflows/monorepo-docker.yml
- .github/workflows/rust-docker.yml
- .github/workflows/test.yml
feat: remove yarn build cache
- saves 600MB of cache space PER COMMIT
- doesn't impact overall per-commit CI time
- better CI time in the general case due to fewer cache evictions on the e2e matrix job
- [with caching](https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/10797745470) vs [no caching](https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/10797213927?pr=4469)
drive-by: disable docker caching for agent build
- currently cache has no impact on build time of the agent image
- rerunning builds for a commit or pushing empty commits should in theory lead to quicker builds with layer caching, but the main problem is that the `RUN` step of building the agents is not cached by the docker action
- only RUNs with bind mounts get a checksum computed …
> feat: remove extraneous caching

- typescript/infra/config/environments/testnet4/agent.ts
- typescript/infra/config/environments/testnet4/aw-validators/hyperlane.json
- Mitosis had previously done some load testing from sepolia to optimismsepolia | arbitrumsepolia, so there were prep queues of 235k+!
- Ignores the offending contracts whose mailboxes are different from the ones we deployed, so these messages are forever unprocessable:
```
$ cast call 0x3da95d8d0b98d7428dc2f864511e2650e34f7087 'mailbox()(address)' --rpc-url $(rpc arbitrumsepolia)
0xBA42Ee5864884C77a683E1dda390c6f6aE144167
$ addy arbitrumsepolia mailbox
0x598facE78a4302f11E3de0bee1894Da0b2Cb71F8
```
- Updates the image as a drive-by
- Stops relaying and validating on solantestnet, which is now old (doesn't include protocol fees) which is incompatible with the agents on `main`. This is because the account storage layout that the agents read has changed. Solantestnet isn't used for anything …
> fix: ignore some testnet4 contracts to reduce prep queues, update testnet4 images, stop relaying solanatestnet

- typescript/infra/config/environments/testnet4/agent.ts
- typescript/infra/config/environments/testnet4/aw-validators/hyperlane.json
- typescript/infra/config/environments/testnet4/funding.ts
- typescript/infra/config/environments/testnet4/gas-oracle.ts
- typescript/infra/config/environments/testnet4/supportedChainNames.ts
- typescript/infra/scripts/funding/deploy-key-funder.ts
- Plumetestnet shut down https://miles.plumenetwork.xyz/ without a specific end date
- Removing it from the list of supported chains for now. Only updating infra workloads and nothing onchain atm
> chore: disable plumetestnet during airplane mode

- rust/main/hyperlane-base/src/metrics/core.rs
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4030
- The general idea of this change is that if the function `set_validator_latest_checkpoints` is called multiple times in a single message's metadata building, the reset of metrics relating to previously set validators now won't always occur. Atm, if two different multisig ISM validator sets are aggregated, they race each other to update the metric. With this change I expect the contention here to not occur anymore, and to still be able to handle changes in validator sets
- This is a bit of a quick fix rather than something super robust tbh - I think in a vacuum I'd prefer something not dependent on time but instead dependent on a context of what message is being processed or something. But at the moment we're seeing …
> feat: support multiple validator sets for a single app context in the relayer's observed validator metrics

- .changeset/gorgeous-owls-kiss.md
- typescript/ccip-server/src/services/HyperlaneService.ts
- typescript/infra/scripts/announce-validators.ts
This PR addresses the restriction on using 'console' from module for follow [eslint rule](https://eslint.org/docs/latest/rules/no-restricted-imports). The changes include:
- Remove all import `console` module, use directly instead Such as: `import {log} from 'console` and `@hyperlane-xyz/utils`
- `services/HyperlaneService.ts`
- `scripts/annouce-validator.ts`
- Everything work well. Just console
- In the future, we should manage log on a unified logger instead of directly console
> fix: replace import console module with direct console

- typescript/cli/examples/submit/strategy/json-rpc-chain-strategy.yaml
- typescript/cli/src/deploy/warp.ts
- typescript/cli/src/tests/commands/helpers.ts
- typescript/cli/src/tests/commands/warp.ts
- typescript/cli/src/tests/warp-apply.e2e-test.ts
- typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5GnosisSafeTxSubmitter.ts
Fix to add conditional for `transactionReceipts` so that the yaml is only parsed when it is not `undefined`. 
E2e tests for warp apply strategy
Yes
> fix: warp apply throws if submitter transactionReceipts is undefined

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/testnet4/agent.ts
- Updates the relayer deployments on mainnet3 (hyperlane & neutron contexts) & testnet4 (hyperlane)
- Includes a couple recent relayer impacting PRs: #4489 and #4495
> chore: deploy relayer to testnet4 and mainnet3

- .github/workflows/rust-skipped.yml
- rust/Dockerfile
Was accidentally removed in #4438. Wonder if there's an easy way to have tests fail if this doesn't work?
> fix: fix VERGEN_GIT_SHA population in Docker image

- .changeset/young-moose-march.md
- typescript/sdk/src/metadata/chainMetadataTypes.ts
- typescript/sdk/src/token/Token.test.ts
- typescript/sdk/src/token/Token.ts
- typescript/sdk/src/token/adapters/SealevelTokenAdapter.ts
- Fix arg validation for Sealevel HypNative adapters
- Increase Token.ts test coverage to Sealevel adapters
- Swallow getBalance errors for non-existent SVM accounts
- Allow extra properties in ChainMetadata objects
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4499
Yes
Tested in Warp UI
> fix: Sealevel hyp token adapter fixes

- rust/main/Cargo.lock
- rust/main/Cargo.toml
Remove pined dependencies on cargo-platform and predicates-core since the pins are not needed.
Yes
Run E2E Tests
> chore: Remove pined dependencies on cargo-platform and predicates-core

- .changeset/mighty-scissors-unite.md
- typescript/infra/src/govern/multisend.ts
- typescript/infra/src/utils/safe.ts
- typescript/sdk/package.json
- typescript/sdk/src/utils/gnosisSafe.js
- yarn.lock
fix: obtain default multisend address correctly
- should help decoding if we're using the expect set of multisend addresses
- also marks our multisend with `onlyCalls: true`
> The reason we can't use `defaultAddress` is because it's fixed to either `canonical` or `eip155` depending on the setting for `ethereum`, regardless of which actually is preferred for each given chain. however, the `networkAddresses` record has items in the correct order.
> See https://github.com/safe-global/safe-deployments/blob/b17349df0eb91cf3683eeae882c07f19188421d9/src/utils.ts#L29 for the implementation.
drive-by:
- bump up to latest safe-deployments patch
| Before | After |
|--------|-------|
| ![Before 1](https://github.com/user-attachments/assets/60b235c1-920b-4c18-b7d8-d50117f3c212) | ![After …
> fix: obtain default multisend address correctly

- typescript/infra/config/environments/mainnet3/funding.ts
- typescript/infra/scripts/funding/fund-keys-from-deployer.ts
- Tested and set up alerts
- We already have the relayer balances from the agents themselves, so just need the ATA payers (which are responsible for paying for the rent of token accounts that don't yet exist when bridging in)
- Putting it here because it's easy and this is what we did in v2 (see #3432, which this is based off)
> feat: monitor sealevel ATA payer balances in the key funder

- solidity/test/isms/ArbL2ToL1Ism.t.sol
- solidity/test/isms/ERC5164ISM.t.sol
- solidity/test/isms/ExternalBridgeTest.sol
- solidity/test/isms/OPL2ToL1Ism.t.sol
- solidity/test/isms/OPStackIsm.t.sol
We currently have 6 different versions of ISMs derived from AbstractMessageIdAuthorizedIsm:
- OPL2ToL1
- ArbL2ToL1
- OPStack (L1->L2)
- ERC5164
- LayerZero
- PolygonPOS
But all of them have their own custom test suite right now, with widely overlapping testing areas. For standardizing the tests, I've created a base test contract `ExternalBridgeTest` that handles the common tests. This has a few benefits:
- harder to miss tests for known pitfalls like msg.value or asynchronicity assumption for verifyMessageId 
- less code duplication with each additional Ism
I have moved OPL2ToL1, ArbL2ToL1, OPStack, and ERC5164 to the new base test, and I'll forgo the rest for now because of the time sensitivity of audit remediations. I've created an issue tracking the remaining work here: …
> chore: refactor MessagIdHook/ISM tests into a common `ExternalBridgeTest` contract

- typescript/infra/scripts/list-validator-checkpoint-indices.ts
Minor addition to make it easy to figure out which validator is behind (from the multisig consts mapping)
> chore: print validator when listing checkpoint indices

- solidity/contracts/token/README.md
While studying the documents, I found that some links are pointing to invalid addresses.
They are updated now with the correct links.
No test is needed as only doc is modified
> docs: fix broken links

- rust/sealevel/client/src/context.rs
- rust/sealevel/environments/mainnet3/warp-routes/eclipseusdc/token-config.json
- Updates the foreignDeployment to be the new one. Just the program-ids.json was updated
- A drive-by with some logging that helps me plug a tx into a script to submit ledger txs (this should eventually be built directly into the sealevel client, at which point we can remove this though)
> chore: update USDC Ethereum router address in token-config

- .vscode/settings.json
`rust-analyzer` only detects workspaces that are 1 directory deep in the source tree, otherwise it has to be configured with the path to workspaces. This PR checks in `.vscode` settings with paths to the rust workspaces. 
This also fixes the issue where someone checks out the monorepo to make TS changes but can't commit because our husky precommit setups assumes that rust workspaces have already been built (which `rust-analyzer` does implicitly).
Noting that the problem is only there if the repo isn't opened using the `mono.code-workspace` setting, which people I talked to don't use (other than @paulbalaji)
> chore: root repo vscode settings for `rust-analyzer`

- solidity/contracts/middleware/README.md
Some of the links in [solidity/contracts/middleware/README.md](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/solidity/contracts/middleware/README.md) were linked to invalid URLs. I updated those links to the correct addresses and replaced them.
> docs: broken links

- .changeset/popular-cars-burn.md
- typescript/sdk/src/ism/metadata/aggregation.ts
Adds useful logs to aggregation ISM metadata builder.
None
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4520
Yes
Manual
> fix: warn on submodule metadata builder failures

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/mainnet3/aw-validators/rc.json
- typescript/infra/config/environments/mainnet3/warp/warpIds.ts
- typescript/infra/config/registry.ts
- typescript/infra/config/warp.ts
- typescript/infra/scripts/agent-utils.ts
- typescript/infra/scripts/check/check-utils.ts
- typescript/infra/scripts/check/check-warp-deploy.ts
- adds a bunch of new app contexts related to the new warp routes
- rearranged some things to avoid circular deps
- deployed from a new image off main (following #4528 being merged too)
- I did an RC deploy, which updated the rc validators for the first time in a while
> chore: add eclipse warp routes to known app contexts

- rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider.rs
- rust/main/chains/hyperlane-cosmos/src/providers/grpc/tests.rs
- rust/main/chains/hyperlane-cosmos/src/trait_builder.rs
- rust/main/hyperlane-base/src/settings/parser/connection_parser.rs
- rust/main/hyperlane-base/src/settings/parser/mod.rs
- rust/main/utils/run-locally/src/cosmos/mod.rs
- rust/main/utils/run-locally/src/cosmos/types.rs
- rust/main/utils/run-locally/src/invariants/termination_invariants.rs
- rust/main/utils/run-locally/src/main.rs
- Add metrics based Scraper invariant into E2E Test for Cosmos
- Report error if transaction contains multiple contract execution messages
- Report error if fee are expressed in unsupported denomination
- Successfully scrape Cosmos chains in e2e test #3355
Yes
E2E Testing
> feat: E2E Test Cosmos Scraper Invariant

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/mainnet3/igp.ts
Following a recent runtime upgrade, they dramatically increased gas costs. It seems like the impact is that some txs may use as much as 4x the normal gas price. But confusingly this is only for some types of txs that affect the "proof of validity".
Some context in the linked discord thread in the comment and in the tg chat with them
> fix: update moonbeam IGP overhead

- typescript/cli/src/context/context.ts
CLI will ask for API keys even if your (local) registry already includes the API key. This PR fixes that. 
Can't say i love the current code setup, it seems to me that it should be more like a pass on the registry and filter chains that don't have api keys, prompt for the api key and then persist that in the registry if its writable. But since i have so little context, kept it mostly this way to accomplish the desired product experience.
> chore: don't ask for api key if it already exists

- rust/main/hyperlane-base/src/settings/checkpoint_syncer.rs
- rust/main/hyperlane-base/tests/chain_config.rs
Previously Checkpoint Syncer wasn't correctly parsing the storage location string. If no folder was provided, it treated the object name as folder, e.g. reading `gs://bucket-name/gcsLatestIndexKey` initialized StorageClient with bucket `bucket-name` and folder `gcsLatestIndexKey`. This was due to incorrect logic for splitting the string by `/` that expected a folder to be present.
In this PR I fixed this logic, treating a location with only one `/` as _bucket/object_ and with two `/`s as _bucket/folder/object_.
Yes
Manual
> fix: GCS correctly splitting storage location into bucket and folder (if present)

- .changeset/bright-rings-jam.md
- typescript/cli/src/send/message.ts
- typescript/cli/src/send/transfer.ts
- Race condition in CLI `send message --relay`
- Related to https://github.com/hyperlane-xyz/v3-docs/issues/174
Yes
Manual
> fix: override default with merkle hook for self relay

- typescript/infra/config/environments/mainnet3/igp.ts
- typescript/infra/config/environments/test/igp.ts
- typescript/infra/config/environments/testnet4/igp.ts
- typescript/infra/src/config/gas-oracle.ts
fix: gas oracle overhead calculation
as spotted by @tkporter  https://canary.discord.com/channels/935678348330434570/1288601439006097498/1288602404950114334
> fix: gas oracle overhead calculation

- rust/main/agents/relayer/src/msg/op_queue.rs
- rust/main/agents/relayer/src/msg/op_submitter.rs
- rust/main/agents/relayer/src/msg/pending_message.rs
- rust/main/hyperlane-core/src/traits/pending_operation.rs
Fixes a bug in the individual submission logic. There is a race condition where a message can become undeliverable between when it was simulated in the `prepare` step and when it's actually submitted.
The bug was discovered as part of batched messages but affects chains without batching too.
- when delivery fails inside batch submission simulation, we fall back to individual submission
- individual submission doesn't simulate the tx outcome, and instead just submits directly
- this is wrong, because the batch may cause messages to become undeliverable for long periods of time (such as when a mint cap is reached)
- I believe simulation used to happen in the individual submission step, but we switched to using the already computed gas estimate from the IGP check in the `prepare` step, to …
> fix(relayer): dry-run before sending txs

- rust/main/Cargo.lock
- rust/main/Cargo.toml
- rust/main/chains/hyperlane-cosmos/Cargo.toml
- rust/main/chains/hyperlane-cosmos/src/error.rs
- rust/main/chains/hyperlane-cosmos/src/libs/account.rs
- rust/main/chains/hyperlane-cosmos/src/libs/account/tests.rs
- rust/main/chains/hyperlane-cosmos/src/libs/address.rs
- rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider.rs
- rust/main/utils/crypto/Cargo.toml
- rust/main/utils/crypto/src/key.rs
- rust/main/utils/crypto/src/lib.rs
Injective uses different logic on generating account addresses from public key. It is implemented in this PR so that sender address is correctly generated from signer info of transaction.
Yes
Added unit tests
Manual testing with Injective blockchain
> feat: Generate cosmos account addresses for Injective

- typescript/sdk/src/warp/WarpCore.ts
Got this log during `warp send`
```
Approval is required for transfer of deUSD
Approval required for transfer of deUSD
Approval is required for transfer of deUSD
Approval required for transfer of deUSD
```
> fix(CLI): do not double info log approval requirement

- rust/main/utils/run-locally/src/cosmos/mod.rs
Dispatch messages before and after start of the agents so that we test both forward and backward looking sequence based indexers.
- Successfully scrape Cosmos chains in e2e test #3355
Yes
- E2E Cosmos Test
- Manual check on E2E Cosmos Test logs
> feat: Dispatch messages before and after start of the agents

- rust/main/agents/relayer/src/msg/op_queue.rs
- rust/main/agents/relayer/src/server/list_messages.rs
The `id` field was missing if the serialized `PendingOperation` was a `PendingMessage`, which made it hard to look up the message in relayer logs or the explorer. This PR takes advantage of `id()` being a required method on `PendingOperation` to derive and display the ID as part of endpoint logic.
Unit Tests
> feat: include `id` field in `list_operations` endpoint

- typescript/sdk/src/core/EvmCoreModule.hardhat-test.ts
- typescript/sdk/src/core/EvmCoreModule.ts
- typescript/sdk/src/core/schemas.ts
original:
there was a series of related problems that people are encountering with cli deploys where the merkleTreeHook is deployed but its address is not included in the artifacts. this PR was intended to bring parity with how infra does it, we can also update for now to only add the merkleTreeHook to the output to unblock the base problem people are having
update:
restricted to just `merkleTreeHook` and `interchainGasPaymaster` to provide MVP fix
https://github.com/hyperlane-xyz/hyperlane-registry/pull/240#discussion_r1784297872
https://github.com/hyperlane-xyz/hyperlane-registry/pull/236#issuecomment-2383922133
https://github.com/hyperlane-xyz/hyperlane-registry/pull/237#discussion_r1782564051
yes
manual
> fix: write merkle & IGP hook addresses if created by core deploy

- Dockerfile
- solidity/bytecodeversion.sh
- solidity/package.json
fix: monorepo docker build, which seems to have been broken from https://github.com/hyperlane-xyz/hyperlane-monorepo/commit/c5c217f8ea1a65c81d54b9118618b284bd370acc#diff-ec261746751beaecd8c9dfe0ad06d2be8e74889eafbe5f7fcbb025726fb2cd90R67
na
na
y
trying
> fix: monorepo docker build

- .changeset/breezy-toys-pay.md
- solidity/contracts/isms/warp-route/RateLimitedIsm.sol
- solidity/test/isms/RateLimitedIsm.t.sol
Add recipient restriction to rate limited ISM. This prevents multiple recipients from sharing the same rate limit ISM and denial of service attacks.
No
Unit Tests
> fix: recipient rate limited ISM

- typescript/sdk/src/providers/ProviderType.ts
- typescript/sdk/src/providers/providerBuilders.ts
- typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5GnosisSafeTxBuilder.ts
- typescript/sdk/src/token/TokenStandard.ts
- typescript/utils/src/types.ts
This rollsback the added ProtocolType for Gnosis safe which was added only for typing. Replace with `any` and will revisit
Yes
None
> fix(cli): rollback gnosis tx builder protocol type

- rust/main/chains/hyperlane-sealevel/src/mailbox.rs
- rust/main/utils/run-locally/src/main.rs
- rust/main/utils/run-locally/src/solana.rs
- rust/sealevel/client/src/cmd_utils.rs
- rust/sealevel/client/src/main.rs
Solana Mainnet is hard forking in 1-2 weeks and one of the RPC methods we were using will be removed.
This PR updates that RPC and runs e2e with an agave `v2.x` network to ensure compatibility. As in the [svm warp route guide](https://docs.hyperlane.xyz/docs/guides/deploy-svm-warp-route), we still use `v1.14.x` to compile programs.
More details:
- `v2.0` migration [guide](https://github.com/anza-xyz/agave/wiki/Agave-v2.0-Transition-Guide)
- `v2.0` release [schedule](https://github.com/anza-xyz/agave/wiki/v2.0-Release-Schedule)
- `solana` to `agave` client transition [guide](https://github.com/anza-xyz/agave/wiki/Agave-Transition)
The solana cli installer logic in e2e is parameterized with `version` and `url`
Yes - no dependency upgrade was needed to switch to the new rpc method
E2E for …
> chore: agave 2.x validator in sealevel e2e

- .changeset/gorgeous-rivers-search.md
- typescript/cli/src/config/submit.ts
- typescript/sdk/src/core/AbstractHyperlaneModule.ts
- typescript/sdk/src/core/EvmCoreModule.ts
- typescript/sdk/src/deploy/EvmModuleDeployer.ts
- typescript/sdk/src/index.ts
- typescript/sdk/src/providers/transactions/schemas.test.ts
- typescript/sdk/src/providers/transactions/schemas.ts
- typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5GnosisSafeTxBuilder.ts
- typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5GnosisSafeTxSubmitter.ts
- typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5ImpersonatedAccountTxSubmitter.ts
- typescript/sdk/src/providers/transactions/submitter/ethersV5/EV5JsonRpcTxSubmitter.ts
- typescript/sdk/src/providers/transactions/transformer/ethersV5/EV5InterchainAccountTxTransformer.ts
- typescript/sdk/src/providers/transactions/types.ts
- typescript/sdk/src/token/EvmERC20WarpModule.ts
Updating the types in the submitters because they were using their own types instead of the existing ones for some reason.
move `createTransferOwnershipTx` from the abstract hyperlane module to the evm module deployer, as it's EVM specific
na
yes
ci
> fix: reuse SDK tx type in submitters

- .changeset/gorgeous-rockets-walk.md
- typescript/sdk/src/metadata/chainMetadataTypes.ts
Adding more technical stack options to the `ChainTechnicalStack` enum, to be used to populate metadata in the registry.
Including `zksync` pre-emptively.
n/a
https://www.notion.so/hyperlanexyz/Adding-more-technical-stacks-to-chain-metadata-11a6d35200d68015a229da552928d4d9?pvs=4
yes
na
> feat: add more options to ChainTechnicalStack enum

- rust/main/agents/scraper/src/chain_scraper/mod.rs
- rust/main/agents/scraper/src/db/message.rs
- rust/main/agents/scraper/src/db/payment.rs
Currently, if Scraper cannot fetch and parse a block or a transaction, it will fail the whole chunk of logs. It means that a transaction which can be fetched and parsed, but happens to be in the same chunk as unparseable transaction, won't be inserted into database. 
This PR fixes it. Scraper will do its best to insert as many as possible blocks and transactions into database from the chunk.
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4632
Yes
Local run of E2E tests.
Local run of Scraper
> feat: Store as much as possible from every range

- .changeset/tender-spiders-deny.md
- typescript/cli/src/deploy/warp.ts
- typescript/cli/src/tests/commands/helpers.ts
- typescript/cli/src/tests/warp-apply.e2e-test.ts
This PR fixes a limitation in `warp apply` such that it can only extend _or_ update an existing warp route. This means that for configs with both changes require `warp apply` to be called multiple times. An example is when Renzo deploys to new chain, and it needs to update the existing ISMs.
- Fixes #4671 
Yes
> fix(cli): Update warp apply to apply changes in single command

- rust/main/chains/hyperlane-cosmos/src/error.rs
- rust/main/chains/hyperlane-cosmos/src/libs/account.rs
- rust/main/chains/hyperlane-cosmos/src/libs/address.rs
- rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider.rs
- rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider/parse.rs
Add support for flow from Celestia
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4646
Yes
Local run of Scraper
Check that transaction and messages can be parsed
> feat: Add support for flow from Celestia

- .changeset/wise-camels-repair.md
- typescript/sdk/src/core/HyperlaneCore.ts
estimates gas + adds gas limit buffer when sending a message through HyperlaneCore
also sets tx overrides
> incremental merkle tree insertions have inconsistent gas usage so if there are multiple dispatch transactions in the mempool the gas estimation can become too low depending on the tx ordering 
bumping up the gas limit helps
[more context](https://discord.com/channels/935678348330434570/1295388159407947859/1295393090181267558)
yes
manual
> fix: add gas buffer when sending message through HyperlaneCore

- .changeset/dirty-clocks-repeat.md
- typescript/cli/src/config/agent.ts
- typescript/infra/scripts/agents/update-agent-config.ts
- typescript/sdk/src/metadata/agentConfig.ts
- typescript/utils/src/objects.test.ts
- typescript/utils/src/objects.ts
Updating the `objMerge` implementation
A bug in the original implementation meant that the `update-agent-config` script did _not_ overwrite the `blocks.reorgPeriod` if there was a change, this new version does.
- gracefully handle missing startBlock data when generating agent config
- fix objMerge calls that had the wrong order
definitely want to fix this bug before attempting to update our agent configs with changes in https://github.com/hyperlane-xyz/hyperlane-registry/pull/276
should be, yes
ci, manual testing when generating agent config files
> fix: update objMerge implementation

- rust/main/hyperlane-core/src/chain.rs
fix: update HyperlaneDomainTechnicalStack with latest stacks
We added new technical stacks, and updated these in registry, but did not update the enum in the agents. this caused a hard failure to load the configs when we tried deploying to prod.
Note: we're omiting `zksync` because that is soon to be moved from a "tech stack" into a "protocol type", and we have no chains in registry with a `zksync` technical stack configured yet anyway.
update existing list of mainnets with "other" technical stack. can't just remove them right now because we have to ensure every value in the enum is mapped
na
yes
todo: fix e2e
> fix: update HyperlaneDomainTechnicalStack with latest stacks

- rust/main/Cargo.lock
- rust/main/agents/relayer/src/msg/op_queue.rs
- rust/main/agents/relayer/src/msg/op_submitter.rs
- rust/main/agents/relayer/src/msg/pending_message.rs
- rust/main/hyperlane-core/Cargo.toml
- rust/main/hyperlane-core/src/traits/pending_operation.rs
- rust/sealevel/Cargo.lock
See https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4068 for the problem description.
In this fix, whenever an operation is moved from one queue to another, its metric count is decremented from the old queue and incremented for the new one.
My initial implementation approach was to update these metrics inside `queue.push(op)`, but the metrics for the operation's previous queue aren't accessible there. #4068 suggests updating them in `op.set_status`, which can't be done for the same reason, even if `op` has a pointer to the current queue's metric internally. 
So the fix I went for does store a pointer to the current queue metric internally in `op`, but also adds a new `op.set_status_and_update_metrics(status, new_queue_metric)` method, which **must** be used if the queue metrics …
> chore: fix queue metric juggedness

- rust/main/agents/relayer/src/msg/op_queue.rs
- rust/main/agents/relayer/src/msg/op_submitter.rs
- rust/main/hyperlane-core/src/traits/pending_operation.rs
Fix for https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4689, where `Dropped` status operations weren't decremented from the metric. I noticed there's still a small difference on a handful of chains, such as celo, where even if Dropped ones are considered, the prep queue metric reports an extra 53 ops compared to the actual queue. Could be that I manually miscounted, I expect releasing this will be a big improvement anyway.
Yes
No, just checked all places where we `.pop_many` but don't `push`
> fix: queue length metric bug

- typescript/infra/config/environments/mainnet3/warp/warpIds.ts
- typescript/infra/config/warp.ts
- typescript/infra/scripts/check/check-warp-deploy.ts
- support Renzo PZETH warp route in checker
- introduce `CheckerWarpRouteIds` enum for warp routes that are supported in the checker, eclipse and sol routes are not currently supported
Manual
> feat(warpChecker): Support Renzo PZETH route

- typescript/sdk/src/deploy/HyperlaneAppChecker.ts
Quick change I encountered when trying to change proxy admin owners -- the contract passed in was the app router, not the proxy admin
> fix: use correct contract for proxyAdmin ownership violation

- rust/main/chains/hyperlane-cosmos/src/providers/rpc/provider.rs
Add logging block hash so that we have both block height and block hash. When Scraper will report that it cannot retrieve block by hash, we'll be able to find its block height.
Yes
Run Scraper locally to see the log message
> feat: Add logging block hash

- .changeset/dry-foxes-battle.md
- typescript/cli/src/commands/warp.ts
- typescript/cli/src/deploy/warp.ts
When using `warp apply`, a user may provide a `strategyUrl`. However, they won't know if 1) it's valid, and 2) if it even exists until much later. This adds the detection & validation early.
Remove yaml print
Yes
Manual
> fix: early strategy detection in warp apply

- .changeset/red-actors-shop.md
- solidity/contracts/mock/MockMailbox.sol
- solidity/contracts/token/extensions/HypERC4626.sol
- solidity/contracts/token/extensions/HypERC4626Collateral.sol
- solidity/test/token/HypERC4626Test.t.sol
- Added a `rateUpdateNonce` in `HypERC4626Collateral` and `previousNonce` in `HypERC4626` to ensure we only update the exchangeRate on the synthetic asset if the update was after the last recorded update. This is to make sure we don't update it to a stale exchange rate which may cause losses to users using the synthetic asset. 
- `processInboundMessage` in MockMailbox` to simulate processing of messages out of order.
- fixes https://github.com/chainlight-io/2024-08-hyperlane/issues/12
Yes
Unit test
> feat(contracts): add nonce for monotonically increasing delivery ordering for `HypERC4626`

- solidity/contracts/isms/TrustedRelayerIsm.sol
- solidity/test/isms/TrustedRelayerIsm.t.sol
- minor fix: add an isContract check for mailbox and non-zero check for relayer when instantiating TrustedRelayerIsm
None
- partly fixes https://github.com/chainlight-io/2024-08-hyperlane/issues/14
Yes
Unit
> fix(contracts): add check for valid mailbox and relayer in `TrustedRelayerIsm`

- solidity/contracts/libs/RateLimited.sol
- solidity/test/lib/RateLimited.t.sol
- Added a check for invalid capacity and event for token level change
None
- fixes https://github.com/chainlight-io/2024-08-hyperlane/issues/14
Yes
Unit tests
> fix(contracts): `RateLimit` minor changes

- .github/workflows/test.yml
- typescript/cli/.mocharc-e2e.json
- typescript/cli/package.json
- typescript/cli/scripts/run-e2e-test.sh
chore: split cli e2e into separate job
before:
after:
na
`yarn-test` step sometimes taking even 15 mins nowadays, half of which is e2e tests
yes
ci
> chore: split cli e2e into separate job

- .changeset/quiet-cooks-join.md
- typescript/cli/src/config/chain.ts
- typescript/sdk/src/index.ts
- typescript/sdk/src/metadata/chainMetadata.test.ts
- typescript/sdk/src/metadata/chainMetadataTypes.ts
- feat: add `EthJsonRpcBlockParameterTag` enum for validating reorgPeriod
- cli will check that reorgPeriod is either a number or one of the appropriate tags, but the underlying schema is still left loose to be forwards-compatible
- exporting the enum will also let us use this in unit tests on the registry side
na
na
ye
ci
> feat: add block tag enum for validating reorgPeriod

- rust/main/hyperlane-core/src/chain.rs
> feat: add zkSync enum variant to HyperlaneDomainTechnicalStack

- rust/main/agents/scraper/src/chain_scraper/mod.rs
- rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider.rs
- rust/main/chains/hyperlane-ethereum/src/rpc_clients/provider.rs
- rust/main/chains/hyperlane-fuel/src/provider.rs
- rust/main/chains/hyperlane-sealevel/src/error.rs
- rust/main/chains/hyperlane-sealevel/src/mailbox.rs
- rust/main/chains/hyperlane-sealevel/src/provider.rs
- rust/main/chains/hyperlane-sealevel/src/rpc/client.rs
- rust/main/hyperlane-core/src/error.rs
- rust/main/hyperlane-core/src/traits/provider.rs
- rust/main/hyperlane-core/src/types/block_id.rs
- rust/main/hyperlane-core/src/types/mod.rs
Make HyperlaneProvider to request block by height, not by hash.
Since it is hard to find a block by hash for Solana, we switch to use block height. We have to do it for all type of chains since we need to change signature of chain-agnostic method
* Small method rename
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4272
Yes
Manual run of Scraper for Ethereum and Neutron chains.
> feat: Make HyperlaneProvider to request block by height, not by hash

- .changeset/quiet-spoons-sleep.md
- typescript/utils/src/objects.test.ts
- typescript/utils/src/objects.ts
When `isObject` pass with param `null/undefined` it returns `null/undefined`
We should strict return boolean value
```diff
export function isObject(item: any): boolean {
- return item && typeof item === 'object' && !Array.isArray(item);
+ return !!item && typeof item === 'object' && !Array.isArray(item);
}
```
Has updated with test `object.test.ts`
> fix: isObject utils fn should return only boolean value

- .changeset/olive-maps-applaud.md
- typescript/sdk/src/token/adapters/SealevelTokenAdapter.ts
- typescript/utils/src/addresses.test.ts
- typescript/utils/src/addresses.ts
- typescript/utils/src/index.ts
Ran into an issue trying to send from Sealevel -> Cosmos where the recipient was 20 bytes. This hasn't been an issue so far because:
- no previous Sealevel -> Cosmos transfers have been done in the UI
- Sealevel -> EVM transfers are successful bc `addressToBytes` actually pads the 20 byte EVM addresses to 32 bytes
- Sealevel -> Sealevel transfers are fine because Sealevel addys are always 32 bytes
> fix: ensure recipients on Sealevel warp transfers are 32 bytes

- .changeset/tidy-meals-add.md
- typescript/utils/src/objects.test.ts
- typescript/utils/src/objects.ts
Add filter `undefined/null` value when use with utils **invertKeysAndValues** function
Add more test at `objects.test.ts`
```diff
return Object.fromEntries(
Object.entries(data)
+      .filter(([_, value]) => value !== undefined && value !== null) // Filter out undefined and null values
.map(([key, value]) => [value, key]),
);
```
None
Currently, nowhere call this **invertKeysAndValues** func
Yes, more tests.
> test: add more object utils test + remove undefined value when use with invertKeysAndValues fnc

- .changeset/sweet-houses-type.md
- typescript/sdk/src/ism/EvmIsmReader.ts
ICA ISM does not implement `module(uint32)` but rather `route(message)`. This modifies ISM derivation with message context to use this function.
Yes
Manual
> fix: use `ism.route(message)` for supporting self relay of ICA ISM

- typescript/infra/config/environments/testnet4/agent.ts
- typescript/infra/config/environments/testnet4/aw-validators/hyperlane.json
- typescript/infra/config/environments/testnet4/funding.ts
- typescript/infra/config/environments/testnet4/supportedChainNames.ts
chore: disable arcadiatestnet until redeployment
- testnet had to be reset
- take down arcadiatestnet validator
- redeploy scraper, relayer, keyfunder without offending chain
> chore: disable arcadiatestnet until redeployment

- typescript/infra/src/agents/index.ts
- typescript/infra/src/config/agent/agent.ts
See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
- In GKE, for the larger relayer node pool, added a taint: `NoSchedule`, label `component=relayer`
- In our relayer workloads, they now have a toleration that matches that taint
- As part of rollout, first did a NoExecute (evicting everything on the big nodes), then moved to NoSchedule (so that some other pods like daemonsets would still get onto these bigger nodes). I made sure the hyperlane and neutron context relayers have these tolerations
- Fixes https://github.com/hyperlane-xyz/issues/issues/1309
> feat: add taint & toleration to mainnet3 relayer node pool

- solidity/test/hooks/ProtocolFee.t.sol
> fix(contracts): assume no zero address for beneficiary address in `ProtocolFee` fuzz test

- rust/sealevel/programs/mailbox-test/src/functional.rs
Applies the same fix from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4655 to a flake that showed up in this PRs CI: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4693#event-15004545304
> fix: another sealevel unit test flake

- rust/main/chains/hyperlane-sealevel/src/account.rs
- rust/main/chains/hyperlane-sealevel/src/error.rs
- rust/main/chains/hyperlane-sealevel/src/interchain_gas.rs
- rust/main/chains/hyperlane-sealevel/src/lib.rs
- rust/main/chains/hyperlane-sealevel/src/mailbox.rs
- rust/main/chains/hyperlane-sealevel/src/provider.rs
- rust/main/chains/hyperlane-sealevel/src/rpc/client.rs
- rust/main/chains/hyperlane-sealevel/src/transaction.rs
- rust/main/chains/hyperlane-sealevel/src/transaction/tests.rs
- rust/main/chains/hyperlane-sealevel/src/utils.rs
Scraper is able to index dispatch messages:
1. Blocks are stored into database
2. Transactions are stored into database (need population of all fields)
3. Dispatched messages are stored into database
Initial indexing of delivered messages (so that Scraper does not crush)
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4272
Yes (Solana-like chains should not be enabled for Scraper)
Manual run of Scraper
E2E Tests
> feat: Scrape Sealevel dispatched messages

- rust/main/hyperlane-base/src/types/gcs_storage.rs
This PR fixes the problem of this issue:
[https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4449](url)
The change was only in the gcs_storage.rs file. Slightly tweaked methods so that you can write files to a specified folder in the terminal.
When trying to run a validator specifying checkpointSyncer settings for GCS:
`--checkpointSyncer.type gcs   --checkpointSyncer.bucket an-s3-signatures-repository   --checkpointSyncer.folder atletaolympia`
```
Building provider without signer
thread 'main' panicked at 'Failed to report agent metadata: error validating bucket name an-s3-signatures-repository/atletaolympia
Caused by:
Character '/' @ 27 is not allowed
Location:
hyperlane-base/src/types/gcs_storage.rs:181:9', agents/validator/src/validator.rs:178:14
```
To solve this problem I …
> fix: GCS folder support

- rust/main/agents/scraper/migration/bin/generate_entities.rs
- rust/main/agents/scraper/migration/src/m20230309_000003_create_table_transaction.rs
- rust/main/agents/scraper/src/db/generated/transaction.rs
- rust/main/agents/scraper/src/db/txn.rs
- rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider.rs
- rust/main/chains/hyperlane-ethereum/src/rpc_clients/provider.rs
- rust/main/chains/hyperlane-fuel/src/provider.rs
- rust/main/chains/hyperlane-sealevel/src/provider.rs
- rust/main/hyperlane-core/src/types/chain_data.rs
Scraper stores input data from Ethereum transactions
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4778
Yes
Manual run of Scraper against 
1. local database
2. database restored from backup of production database
> feat: Scraper stores input data from Ethereum transactions

- rust/sealevel/environments/mainnet3/warp-routes/ORCA-eclipse-solana/program-ids.json
- rust/sealevel/environments/mainnet3/warp-routes/ORCA-eclipse-solana/token-config.json
- rust/sealevel/environments/mainnet3/warp-routes/USDT-eclipse-ethereum-solana/program-ids.json
- rust/sealevel/environments/mainnet3/warp-routes/USDT-eclipse-ethereum-solana/token-config.json
- rust/sealevel/environments/mainnet3/warp-routes/WBTC-eclipse-ethereum-solana/program-ids.json
- rust/sealevel/environments/mainnet3/warp-routes/WBTC-eclipse-ethereum-solana/token-config.json
- typescript/infra/config/environments/mainnet3/funding.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getEclipseEthereumUSDTWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getEclipseEthereumWBTCWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/eclipse-ORCA-deployments.yaml
- typescript/infra/config/environments/mainnet3/warp/eclipse-USDT-deployments.yaml
- typescript/infra/config/environments/mainnet3/warp/eclipse-WBTC-deployments.yaml
- typescript/infra/config/environments/mainnet3/warp/warpIds.ts
- typescript/infra/config/warp.ts
- typescript/infra/scripts/funding/fund-keys-from-deployer.ts
- typescript/infra/scripts/generate-eclipse-usdt-warp-route-config.ts
- typescript/infra/scripts/generate-eclipse-wbtc-warp-route-config.ts
- typescript/infra/src/config/warp.ts
- typescript/infra/src/warp/helm.ts
- ORCA (eclipse <> solana)
- WBTC (ethereum <> eclipse)
- USDT (ethereum <> eclipse <> solana)
> feat: eclipse warp batch #2

- .changeset/clean-dingos-switch.md
- typescript/cli/src/utils/chains.ts
- typescript/cli/src/utils/input.ts
Re-enables space key press for multi-select prompt
- None
- YES
- Manual
> fix(cli): re-enable space key for multiselect prompt

- typescript/infra/scripts/generate-eclipse-usdt-warp-route-config.ts
- typescript/infra/scripts/generate-eclipse-wbtc-warp-route-config.ts
- typescript/infra/scripts/warp-routes/utils.ts
Uncomments generator code to actually instantiate a `routerConfig`, as recommended in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4799#discussion_r1826157666
> chore: instantiate router config in warp generators

- .changeset/six-drinks-eat.md
- solidity/contracts/Mailbox.sol
- solidity/contracts/mock/MockMailbox.sol
processInboundMessage needs to be payable for mocking sending value for ICA router call 
None
None
Yes
None
> chore(contracts): made processInboundMessage payable to mock send value via mailbox.process

- rust/main/Cargo.lock
- rust/main/agents/relayer/src/relayer.rs
- rust/main/hyperlane-base/Cargo.toml
- rust/main/hyperlane-base/src/agent.rs
- rust/main/hyperlane-base/src/metrics/agent_metrics.rs
- we should make sure there are no `unwrap`s outside a `tokio::spawn`, otherwise they'll take down the entire relayer. The offenders have so far been the indexing cursors, so this PR just logs an error and sets a new metric flag instead of panicking: `critical_error`, an `IntGauge` type because prometheus doesn't have boolean gauges. For now this is only used for origin chains, but I envision this as being set when a critical error occurs in the submitter too, in the future
- before setting the flag, cursor instantiation is now retried 10 times (to avoid short lived RPC hiccups)
Removes usage of `Builder` derive macro in metric types, since they're not complex enough to warrant it
Yes
the existing e2e
> feat: alert instead of crashing relayer when building cursors

- solidity/contracts/hooks/warp-route/RateLimitedHook.sol
- solidity/test/hooks/RateLimitedHook.t.sol
- Added onlySender to `RateLimitHook` to only allow a specific sender like a warp route to send messages through the hook.
None
> fix(contracts): access control to prevent DOS on `RateLimitHook`

- .changeset/quick-bags-check.md
- typescript/sdk/src/index.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.ts
- typescript/sdk/src/token/config.ts
- typescript/sdk/src/token/schemas.ts
Fixes "warp read does not return collateralChainName for rebase vault type"  and "warp check fails when checking the config because collateralChainName is missing" of CLI 5.6 Bug Bash
Yes
> fix: add collateralChainName to warp read

- rust/main/agents/scraper/migration/src/m20230309_000001_create_table_domain.rs
- rust/main/agents/scraper/src/db/generated/domain.rs
Remove unique chain id index from db migration script
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4798
Yes
Manual run of DB migration script
> feat: Remove unique chain id index from db migration script

- .changeset/thirty-actors-wonder.md
- typescript/sdk/src/token/IToken.ts
- Ripped out of https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4835, which is necessary so I can merge and release https://github.com/hyperlane-xyz/hyperlane-registry/pull/370 before 4835
> feat: Added coinGeckoId as an optional property of the TokenConfigSchema

- rust/main/chains/hyperlane-sealevel/src/interchain_gas.rs
- rust/main/chains/hyperlane-sealevel/src/mailbox.rs
Remove call to GetBlock for Sealevel for time being
https://discord.com/channels/935678348330434570/935679524534911007/1306588981185740811
Yes
E2E Test for Ethereum and Sealevel
> fix: Remove call to GetBlock for Sealevel for time being

- rust/main/chains/hyperlane-sealevel/src/interchain_gas.rs
- rust/main/chains/hyperlane-sealevel/src/mailbox.rs
- rust/main/chains/hyperlane-sealevel/src/merkle_tree_hook.rs
- rust/main/chains/hyperlane-sealevel/src/rpc/client.rs
Use block slot instead of block height for Sealevel chains
Yes
Manual run of validator against Solana mainnet
> fix: Use block slot instead of block height for Sealevel chains

- .github/workflows/test.yml
- typescript/cli/.mocharc-e2e.json
- typescript/cli/scripts/run-e2e-test.sh
chore: parallelise cli e2e tests
before:
after:
> chore: parallelise cli e2e tests

- rust/main/Cargo.lock
- rust/main/Cargo.toml
- rust/main/chains/hyperlane-sealevel/src/rpc/client.rs
- rust/main/chains/hyperlane-sealevel/src/rpc/client/tests.rs
- rust/main/hyperlane-base/src/settings/signers.rs
- rust/rust-toolchain
- rust/sealevel/Cargo.lock
- rust/sealevel/Cargo.toml
- rust/sealevel/libraries/test-utils/src/igp.rs
- rust/sealevel/rust-toolchain
- Make main and sealevel workspaces compilable with our forked dependencies
- Make Sealevel client be able to parse block with new kind of instruction errors
Yes
E2E Ethereum and Sealevel tests
> fix: Make main and sealevel workspaces compilable with our forked dependencies

- .changeset/empty-dodos-clap.md
- typescript/cli/src/deploy/warp.ts
- typescript/sdk/src/router/schemas.ts
- typescript/sdk/src/token/EvmERC20WarpModule.hardhat-test.ts
- typescript/sdk/src/token/EvmERC20WarpModule.ts
Remove `ismFactoryAddresses`, which was added to the WarpConfig to be used in `WarpModule`, and passed into `IsmModule`. 
This is tech debt that was added before passing in `addresses` via the constructor as done here: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/111e24153250cf702ba8d31970daa855cf7954ec/typescript/sdk/src/ism/EvmIsmModule.ts#L65
Yes
Unit Tests
> chore: Remove ismFactoryAddresses from warpConfig

- typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumFlowCbBTCWarpConfig.ts
- typescript/infra/scripts/check/check-utils.ts
- typescript/infra/scripts/check/check-warp-deploy.ts
- typescript/infra/src/config/environment.ts
- Transfers ownership of the cbBTC warp route between flow and ethereum
- A fix to ensure that proxy admin ownership is set
- a driveby to prevent rebuilding the multiprovider tons of times in the check warp deploy script
> chore: transfer ownership for cbBTC warp deploy on Flow <> Ethereum

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/mainnet3/misc-artifacts/everclear-sender-addresses.json
Tracks messages from the hub/spoke contracts here https://docs.everclear.org/resources/contracts/mainnet (HubGateway (Everclear hub) <> EverclearSpoke (all other spoke chains)). Went with sender tracking to help us flag if there are other new spokes that pop up
> feat: add Everclear relayer app context

- .changeset/polite-beds-begin.md
- typescript/infra/scripts/check/check-validator-version.ts
- typescript/sdk/package.json
- typescript/sdk/src/aws/validator.ts
- typescript/sdk/src/gcp/storage.ts
- typescript/sdk/src/gcp/validator.ts
- typescript/sdk/src/index.ts
- typescript/sdk/src/utils/validator.ts
- yarn.lock
Introduce GcpValidator for retrieving announcements, checkpoints and metadata for a Validator posting to a GCP bucket. Uses GcpStorageWrapper for bucket operations.
update `check-validator-version` to read gcp buckets too
yes
manual
before:
```
Error getting metadata for validator 0x14ADB9e3598c395Fe3290f3ba706C3816Aa78F59 on chain flowmainnet: Error: Unable to parse location gs://ff-hyperlane-validator-1/gcsAnnouncementKey
│ 18      │ 'flowmainnet'  │ '0x14ADB9e3598c395Fe3290f3ba706C3816Aa78F59' │ 'flow foundation' │ 'UNKNOWN'                                  │
```
after:
```
│ 22      │ 'flowmainnet'           │ '0x14ADB9e3598c395Fe3290f3ba706C3816Aa78F59' │ 'flow foundation' │ 'nov-7-batch'              │
```
> feat: add GcpValidator using GcpStorageWrapper

- rust/main/chains/hyperlane-sealevel/src/mailbox.rs
- typescript/infra/config/environments/mainnet3/agent.ts
- Intending to follow up with a more legit way of figuring out fees
> feat: env var to set Jito tip as a stopgap

- rust/main/agents/scraper/migration/src/m20230309_000004_create_table_delivered_message.rs
- rust/main/agents/scraper/src/db/generated/delivered_message.rs
- rust/main/agents/scraper/src/db/message.rs
- rust/main/agents/scraper/src/store/deliveries.rs
- rust/main/agents/scraper/src/store/dispatches.rs
- rust/main/chains/hyperlane-sealevel/src/mailbox.rs
- rust/main/chains/hyperlane-sealevel/src/rpc/client.rs
Support SequenceAware cursors for Deliveries
Yes (need adding column `sequence` to `delivered_message` table before merging
E2E Ethereum and Sealevel tests
> feat: Support SequenceAware cursors for Deliveries

- .changeset/clever-melons-sell.md
- typescript/infra/scripts/warp-routes/monitor/monitor-warp-route-balances.ts
- typescript/sdk/src/token/adapters/CosmWasmTokenAdapter.ts
- typescript/sdk/src/token/adapters/CosmosTokenAdapter.ts
- typescript/sdk/src/token/adapters/EvmTokenAdapter.ts
- typescript/sdk/src/token/adapters/ITokenAdapter.ts
- typescript/sdk/src/token/adapters/SealevelTokenAdapter.ts
- typescript/sdk/src/warp/WarpCore.test.ts
- typescript/sdk/src/warp/WarpCore.ts
- Happened a few times where someone transferred SOL from Eclipse -> SOL on Solana, and the recipient did not yet exist (so had no SOL balance to cover its rent). The amount on these transfers would be insufficient to cover the rent of the recipient, so the transfer could never be delivered. See https://discord.com/channels/935678348330434570/1311371339889639486/1311381212828532858 for context on the first time this happened. There were then a few other instances the day after
- This introduces `ITokenAdapter.getMinimumTransferAmount`, where impls generally return a minimum of 0, but native Sealevel and native Sealevel warp routes have some logic that is aware of required rent exemption balances
- Atm, in WarpCore this only checks getMinimumTransferAmount on the destination side and not …
> feat: require Sealevel native transfers to cover the rent of the recipient

- typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumBscLumiaLUMIAWarpConfig.ts
- typescript/sdk/src/deploy/HyperlaneAppChecker.ts
- Fix LUMIA/bsc-ethereum-lumia warp config, proxyAdmin address was incorrectly set to the AW proxyAdmin in Lumia
- Recent bug fix in checker has surfaced this issue
- Fix bug with ownership check when proxyAdmin is not set in config
Manual
> fix(warpConfig): Fix LUMIA/bsc-ethereum-lumia warp config

- .changeset/yellow-swans-join.md
- typescript/cli/src/status/message.ts
fix: relay message from tx containing multiple dispatches
without this change, it would automatically just assume you wanted to relay the 1st message (event index 0) from the transaction
> fix: relay message from tx containing multiple dispatches

- typescript/infra/config/environments/mainnet3/warp/configGetters/getEclipseEthereumApxETHWarpConfig.ts
Closes out ownership transfer of apxETH to the Dinero team
> chore: transfer ownership of apxETH

- rust/main/agents/scraper/migration/src/m20230309_000001_create_table_domain.rs
- rust/main/agents/scraper/migration/src/m20230309_000004_create_table_gas_payment.rs
- rust/main/agents/scraper/src/agent.rs
- rust/main/agents/scraper/src/conversions.rs
- rust/main/agents/scraper/src/db/generated/gas_payment.rs
- rust/main/agents/scraper/src/db/payment.rs
- rust/main/agents/scraper/src/store/payments.rs
- rust/main/config/test_sealevel_config.json
- rust/main/hyperlane-base/src/settings/base.rs
- rust/main/utils/run-locally/src/config.rs
- rust/main/utils/run-locally/src/invariants/termination_invariants.rs
- rust/main/utils/run-locally/src/main.rs
- rust/sealevel/environments/local-e2e/chain-config.json
- Retrieve gas payment by origin, interchain_gas_paymaster and sequence
- Add Sealevel to Scraper in E2E Ethereum and Sealevel tests
Yes (after backfill of origin, destination, interchain_gas_paymaster)
E2E Ethereum and Sealevel tests (including scraping Sealevel)
> feat: Retrieve gas payments by sequence for scraping Sealevel 

- rust/main/agents/scraper/migration/src/m20230309_000003_create_table_cursor.rs
Add index to cursor table so than Scraper starts quickly
Yes
Manual
> fix: Add index to cursor table

- rust/README.md
- typescript/sdk/CHANGELOG.md
Mostly mentions the new Rust workspace split
None
None
Yes
None
> chore: update the Rust readme

- rust/main/Cargo.lock
- rust/main/Cargo.toml
the escalator doesn't log the hash of the new gas-escalated transaction, so it's hard to find the transaction that actually landed onchain (you have to look by nonce) - example [here](https://cloudlogging.app.goo.gl/cFXYHui4agpxU4AK9). This PR uses a newer version of the escalator, which does log the hash. 
ethers-rs fork PR: https://github.com/hyperlane-xyz/ethers-rs/pull/22
> chore: bump escalator version

- typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionETHWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionUSDCWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionUSDTWarpConfig.ts
- after the recent viction validator set change, just move this over to the default ISM so we always get the latest and greatest
- fixes our warp checker violations
- kinda stylistic, but just explicitly specifying the zero address as the ISM address on the viction side too
> chore: move viction warp routes to default ISMs

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/testnet4/agent.ts
Enable Solana and Eclipse in Scraper.
We don't relay messages in Solana and Eclipse testnets, so, we don't enable these testnets in Scraper.
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4274
Yes
E2E Ethereum and Sealevel test
> feat: Enable Solana and Eclipse in Scraper

- typescript/infra/config/environments/mainnet3/agent.ts
Disable Eclipse in Scraper until we get archival RPC endpoint
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4274
Yes
No testing since it is a config change
> fix: Disable Eclipse in Scraper until we get archival RPC endpoint

- rust/sealevel/programs/hyperlane-sealevel-token-collateral/src/plugin.rs
- This was surfaced a while back but we never made the tweak -- on the collateral warp routes, the account infos exposed to the relayer informing it how to process a message ask for the token mint to be writeable. This isn't necessary - it can be read-only because nothing is changing in the data of the token mint. A consequence of this is that we need to pay higher fees for accounts that have very high contention (like USDC)
- We have strong test coverage here - if this change wasn't possible, our Sealevel tests would fail
> fix: on SVM collateral warp routes, specify the mint when transferring out as readonly

- typescript/infra/config/environments/mainnet3/agent.ts
Re-enable Eclipse in Scraper
Yes
None (config change)
> fix: Re-enable Eclipse in Scraper

- .changeset/long-llamas-fly.md
- typescript/cli/cli.ts
No longer outputs help dialog on any error
> fix: suppress help on CLI failures

- .changeset/hot-spies-share.md
- typescript/cli/src/commands/signCommands.ts
- typescript/cli/src/context/strategies/chain/ChainResolverFactory.ts
- typescript/cli/src/context/strategies/chain/MultiChainResolver.ts
- typescript/cli/src/context/strategies/signer/MultiProtocolSignerManager.ts
Probably fixes an issue due to a recent pr merge that changes how signers are initialized based on the command to be executed
- Updates the key info message log level from info to debug to avoid the following
- Yes
- Manual
> fix(cli): fix signer init strategy

- rust/main/config/mainnet_config.json
- Multicall3 is at a nonstandard address due to it being a zksync chain
> feat: add treasure batch contract address

- .changeset/nine-eyes-smile.md
- solidity/contracts/isms/hook/AbstractMessageIdAuthorizedIsm.sol
- solidity/contracts/isms/hook/ArbL2ToL1Ism.sol
- solidity/contracts/isms/hook/OPL2ToL1Ism.sol
- partially fixes https://github.com/chainlight-io/2024-08-hyperlane/issues/1
> fix(contracts): make `releaseValueToRecipient` internal

- rust/main/chains/hyperlane-ethereum/src/tx.rs
> fix(treasure): gas price estimation

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/mainnet3/warp/warpIds.ts
- typescript/infra/scripts/warp-routes/deploy-warp-monitor.ts
- typescript/infra/src/utils/helm.ts
- typescript/infra/src/warp/helm.ts
- typescript/sdk/src/metadata/matchingList.ts
- Ignores known unprocessable ezETH and pzETH messages from metrics, to avoid alerts there
- Added some logic to remove stale warp route monitors if a warp ID changes such that the previous warp monitor is stale
- Deployed new warp monitors for ezETH and pzETH to include swell
- Pulled in the treasure warp route ID that wasn't put into a PR yet
> feat: ignore unprocessable messages in metrics, add some new warp monitoring

- .changeset/many-clouds-bow.md
- typescript/infra/scripts/check/check-validator-version.ts
- typescript/sdk/package.json
- typescript/sdk/src/gcp/storage.ts
- yarn.lock
- feat: remove GCP storage dependency
- call GCP storage API directly
- little refactor
- add dec 4 batch sha to the validator version checker
test by checking version of flowmainnet validators, because we know the flow foundation validator is on GCP storage https://evm.flowscan.io/tx/0x4ac998b0d35b3d305e792ee608818a398d09ee11851e09e37068f67ce8c6153f?tab=logs
```
yarn --cwd typescript/infra tsx scripts/check/check-validator-version.ts -e mainnet3 -c flowmainnet --show-updated
```
```
✅ 4 Validators with expected git SHA:
┌─────────┬───────────────┬──────────────────────────────────────────────┬───────────────────┬───────────────┐
│ (index) │ chain         │ validator                                    │ alias             │ version       │ …
```
> feat: remove GCP storage dependency from SDK

- rust/main/Cargo.lock
- rust/main/Cargo.toml
Includes the changes from https://github.com/hyperlane-xyz/ethers-rs/pull/24, reviewed by @ameten
> fix: retry zksync errors in escalator

- .changeset/pink-sloths-turn.md
- typescript/widgets/src/components/Button.tsx
- typescript/widgets/src/components/TextInput.tsx
- typescript/widgets/src/icons/Discord.tsx
- Hide ouline in button and text input
- Rename clip path id in discord logo
Yes
> fix: Hide outline in some widget components

- rust/sealevel/client/src/warp_route.rs
Fix E2E tests. New version of dependency was picked up and it broke E2E Ethereum and Sealevel tests.
Yes
E2E Ethereum and Sealevel tests
> fix: update spl-token-cli dependency

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/testnet4/agent.ts
Release Scraper with revert of new SeaORM.
We shall add indexes for searching interchain gas payments and delivered messages by sequence and bring back new version of SeaORM.
Disabled arcadiatestnet2 while their RPC is down to allow Scraper to start
Yes
E2E tests on code change
> fix: Release Scraper with revert of new SeaORM

- rust/main/agents/relayer/src/msg/op_queue.rs
The `new_metric` passed into `set_status_and_update_metrics` was actually using the old `status` of the queue operation, causing prepare queue messages to be reflected in metrics as having the status they had in the submit queue. See https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5001 for more details.
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5001
Yes
Will check on RC before releasing
> fix: operation_status metric inaccuracy

- typescript/infra/config/environments/mainnet3/agent.ts
A temporary measure, seems like Treasure likes to overestimate gas limits. One offending message has been flagged as having insufficient payments, see https://discord.com/channels/935678348330434570/1264883412188135555/1319115367167033399 for details
> chore: looser gas payment enforcement policy on Treasure

- rust/main/chains/hyperlane-ethereum/src/rpc_clients/retrying.rs
60% of validator logs are `Dispatching request`, which really isn't needed at the info/debug level and we can safe quite significantly
> chore(retrying_provider): reduce log verbosity

- .github/workflows/test.yml
- Removing the consistently failing Viction env test, see https://discord.com/channels/935678348330434570/1319783601407262854/1319788686111674418 for context
> chore: rm Viction env-test

- rust/README.md
- rust/build.sh
Fix incorrect instructions in Rust readme for building the docker image. The build does not work as the readme dictates. Being in the rust folder gives a `ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref y1ezs2da6re8bcvxgo9psu1xk::hydxdsbeaxqx3rvjjzako1134: "/rust/main/config": not found` error. Being at the top level causes a successful build.
Also have to edit the build script to target the correct directory dockerfile.
> fix: correct instructions in Rust readme for building docker image

- typescript/sdk/src/token/checker.ts
- reorder checks to so that a token mismatch is caught before decimal checks are done. This will avoid us calling `.decimals` on a contract that is not a token contract i.e if the config has been misconfigured 
Manual
> fix(warpChecker): Check for token mismatch before decimals check

- .changeset/spotty-bees-worry.md
- typescript/sdk/src/index.ts
Export TOKEN_STANDARD_TO_PROVIDER_TYPE, XERC20_STANDARDS, and MINT_LIMITED_STANDARDS maps
Yes
> chore: Export missing token maps from the SDK

- rust/main/hyperlane-core/src/accumulator/incremental.rs
- solidity/contracts/client/MailboxClient.sol
- solidity/contracts/client/Router.sol
- solidity/contracts/isms/hook/AbstractMessageIdAuthorizedIsm.sol
- typescript/cli/src/avs/stakeRegistry.ts
- typescript/infra/scripts/helloworld/utils.ts
- typescript/utils/src/ids.ts
This pull request addresses minor grammatical inconsistencies and corrects typos across multiple files in the repository. Specifically, it replaces incorrect usage of "a" with "an" where appropriate and corrects other minor typographical errors. These changes improve code readability and maintain grammatical accuracy.
- **incremental.rs**: Updated "a incremental" to "an incremental".
- **MailboxClient.sol**: Updated "an Hyperlane" to "a Hyperlane".
- **Router.sol**: Updated "a Application Router" to "an Application Router".
- **AbstractMessageIdAuthorizedIsm.sol**: Updated "a authorized" to "an authorized".
- **stakeRegistry.ts**: Updated "a expiry" to "an expiry".
- **utils.ts**: Updated "an standard" to "a standard".
- **ids.ts**: Updated "an Hyperlane ID" to "a Hyperlane ID".
- No …
> chore: Fix typos in comments

- .changeset/serious-beers-lay.md
- typescript/widgets/src/walletIntegrations/utils.ts
Widgets lib fix: Allow empty data field in ethers5TxToWagmiTx
Yes
> fix: Allow empty data field in ethers5TxToWagmiTx

- typescript/infra/config/environments/mainnet3/agent.ts
- update image in config to the current relayer image tag
- add USDC/ethereum-inevm test tx to blacklist https://explorer.hyperlane.xyz/message/0x998746dc822dc15332b8683fb8a29aec22ed3e2f2fb8245c40f56303c5cb6032 top
> chore: update relayer image

- typescript/infra/config/environments/mainnet3/gasPrices.json
- typescript/infra/config/environments/mainnet3/warp/warpIds.ts
- typescript/infra/src/warp/helm.ts
- Deployed the JitoSOL and kySOL warp route monitors
- Ensured ATA payer balances are sufficient
- Also deployed the relayer with the new app contexts
- Drive-by to lower the ethereum gas price (applied onchain)
> feat: deploy JitoSOL and kySOL warp route monitors

- typescript/infra/config/environments/mainnet3/igp.ts
Context: https://discord.com/channels/935678348330434570/1319115367167033399/1319442102454849639
zkSync chains have non standard EVM gas metering, and their eth_estimateGas RPC returns abnormally high estimates compared to the actual usage. As a semi-temporary workaround, we bump the overhead to result in more gas paid for. The impact of this is actually not meaningful when it comes to cost borne by users - because the zkSync chains are cheap, our min fee logic means that applying this still results in a ~20c cost to users
> feat: bump overhead when sending to zkSync chains

- .changeset/lovely-snakes-cross.md
- typescript/cli/src/commands/send.ts
- typescript/cli/src/commands/warp.ts
- typescript/cli/src/send/transfer.ts
Update `hyperlane warp send` to send a round trip transfer to all chains in WarpCoreConfig, if `--origin` and/or `--destination` is not provided.
Yes
Manual
> feat: hyperlane warp send all chains

- typescript/infra/config/environments/mainnet3/aw-validators/rc.json
- typescript/infra/config/environments/mainnet3/validators.ts
Add Stride validator configuration to RC context
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5113
Yes
On RC
> feat: Add Stride validator configuration to RC context

- typescript/infra/config/environments/mainnet3/owners.ts
- typescript/infra/config/environments/testnet4/owners.ts
- typescript/infra/test/environment.test.ts
fix(infra): ensure all supported chains per env have owners
- add test
- add missing chains
yarn test - tried with + without fix and observed that it correctly fails without the additional chains being added
> fix(infra): ensure all supported chains per env have owners

- .changeset/shaggy-dolphins-wink.md
- typescript/cli/src/utils/files.ts
Fixes 
```
ReferenceError: Excessive alias count indicates a resource exhaustion attack
```
See https://stackoverflow.com/questions/63075256/why-does-the-npm-yaml-library-have-a-max-alias-number
Yes
Manual
> fix: yaml resource exhaustion

- typescript/infra/scripts/check/check-warp-deploy.ts
> There's an annoying issue where if a new chain has been added to mainnet3 in main, then the warp deploy checker cronjob in k8s (which uses the latest image off main) will try to get secret endpoints for that new chain. It'll fail if we haven't done a deploy of the warp deploy checker because the GCP secrets aren't populated into k8s via external secrets, and the deploy checker doesn't have credentials to get secrets directly from GCP secrets
Attempting to remedy this problem by deriving which subset of chains we care about (i.e. have warp config getters for) and only instantiating the multiprovider with these select chains.
[Relevant Thread](https://discord.com/channels/935678348330434570/1242873947293356042/1326854438518001696)
ran locally
```
yarn tsx …
```
> fix: check-warp-deploy only fetches secrets for relevant chains

- rust/main/Cargo.lock
- rust/main/Cargo.toml
applies fix from this ethers PR: https://github.com/hyperlane-xyz/ethers-rs/pull/30
> applies a multiplier of 1.5x to the base fee (or maxFee) and one of 1.1 to the priority fee, since the ones retrieved from the polygon api are too low
> fix: more conservative polygon gas price estimates

- rust/main/Cargo.lock
- rust/main/Cargo.toml
- rust/main/chains/hyperlane-cosmos/Cargo.toml
- rust/main/chains/hyperlane-cosmos/src/interchain_gas.rs
- rust/main/chains/hyperlane-cosmos/src/libs/account.rs
- rust/main/chains/hyperlane-cosmos/src/mailbox/delivery_indexer.rs
- rust/main/chains/hyperlane-cosmos/src/mailbox/dispatch_indexer.rs
- rust/main/chains/hyperlane-cosmos/src/merkle_tree_hook.rs
- rust/main/chains/hyperlane-cosmos/src/payloads/general.rs
- rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider.rs
- rust/main/chains/hyperlane-cosmos/src/providers/grpc.rs
Obsolete version of cosmrs (0.14.0) complains about valid TLS certificates. It makes agents to fail to communicate to Cosmos chains via RPC.
cosmrs 0.16.0 fixes the issue. Some other dependencies also were upgraded.
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5113
Yes
E2E Cosmos tests and E2E Ethereum and Sealevel tests
> fix: Fix certificate issue for Cosmos chains

- .changeset/tall-starfishes-hunt.md
- typescript/cli/src/commands/warp.ts
- typescript/cli/src/tests/warp-deploy.e2e-test.ts
Fix ordering issue where --origin and --destination are sent out of order. For example, when --origin is zircuit, and --destination is ethereum, `warp send` will send from origin ethereum to destination zircuit. 
> fix: hyperlane warp send out of order for --origin --destination 

- rust/main/chains/hyperlane-sealevel/src/rpc/client.rs
- typescript/infra/config/environments/mainnet3/agent.ts
> fix: svm gas price multipliers, relayer image

- typescript/sdk/src/metadata/blockExplorer.test.ts
- Added comprehensive tests for block explorer utilities, covering edge cases such as chains without block explorers and chains without API URLs.
- Implemented tests for handling multiple block explorers, ensuring correct explorer selection by index.
- Included tests for special chain names and proper URL handling, particularly with trailing slashes.
All new tests have been implemented and verified for correctness.
> feat: enhance block explorer utility tests with edge cases and multiple explorers

- typescript/sdk/src/metadata/agentConfig.ts
Fix typo `Seperated` -> `Separated`
No update test
> fix: correct spelling of 'Separated' in agent configuration regex patterns

- typescript/infra/config/environments/mainnet3/agent.ts
- Scrapes SOON
- Temporarily disabling Neutron due to a chain stall and RPC issues there that cause the scraper to panic upon startup
> feat: scrape SOON

- typescript/infra/config/environments/mainnet3/agent.ts
- The chain is back, scraping it again now after its removal in #5165
> chore: re-enable Neutron scraping

- rust/main/Cargo.lock
- rust/main/agents/relayer/Cargo.toml
- rust/main/agents/relayer/src/relayer.rs
- rust/main/agents/relayer/src/settings/mod.rs
- rust/main/hyperlane-base/src/metrics/agent_metrics.rs
- rust/main/hyperlane-base/src/settings/base.rs
- typescript/infra/config/environments/mainnet3/igp.ts
- instead of crashing relayer if any RPC calls fail during `build_mailboxes` and `build_validator_announces`, we just log the error and metric
- relayer will continue running without those chains
Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4887
Are these changes backward compatible? Are there any infrastructure implications, e.g. changes that would prohibit deploying older commits using this infra tooling?
Yes
Added unittests to test ensure functions run correctly and log errors in metrics
> feat: don't crash relayer due to flaky RPCs

- .changeset/three-walls-count.md
- typescript/cli/src/consts.ts
- typescript/cli/src/send/message.ts
- typescript/cli/src/send/transfer.ts
Add link to explorer message for hyperlane CLI `warp send` and `send message` commands
No
Yes
CLI
send message command:
warp send command:
> feat: explorer link in cli logs

- rust/main/chains/hyperlane-ethereum/src/rpc_clients/mod.rs
Retryable errors often indicate that something abnormal is happening (such as we falling back to other providers, which may be causing issues). It's much easier to notice this if the logs are emitted are `warn` level. Non-retryable errors should be logged at `error` level to highlight the relative severity to retryable ones
> chore: retryable errors should still be logged as warnings

- .changeset/green-schools-attack.md
- typescript/cli/src/deploy/utils.ts
fix: print displayName instead of chain name in cli log
> fix: print displayName instead of chain name in cli log

- rust/main/hyperlane-base/src/contract_sync/metrics.rs
- rust/main/hyperlane-base/src/contract_sync/mod.rs
Add contract sync liveness metrics
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5098
Yes
E2E testing in CI
> feat: Add contract sync liveness metrics

- rust/main/Cargo.lock
- rust/main/Cargo.toml
- rust/main/chains/hyperlane-cosmos/Cargo.toml
- rust/main/chains/hyperlane-cosmos/src/error.rs
- rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider/parse.rs
Upgrade Cosmos dependencies
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5098
Yes
Manual testing against Injective, Neutron and Stride
> fix: Upgrade Cosmos dependencies

- rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider.rs
- rust/main/chains/hyperlane-sealevel/src/provider.rs
- rust/main/chains/hyperlane-sealevel/src/rpc/client.rs
- typescript/infra/config/environments/mainnet3/agent.ts
Add chain metrics for cosmos and sealevel chains
Yes
E2E in CI
> feat: Add chain metrics for cosmos and sealevel chains

- .changeset/proud-waves-camp.md
- typescript/cli/package.json
- typescript/cli/src/deploy/warp.ts
- typescript/helloworld/package.json
- typescript/infra/package.json
- typescript/widgets/package.json
- yarn.lock
Fixes #5164 
Fixed an issue where symbols were not taken into account when creating artifacts through warp deploy.
Update registry packages
Related issue: [registry fix](https://github.com/hyperlane-xyz/hyperlane-registry/pull/499)
Yes
CLI
Manual
> fix(cli): artifacts symbol for warp deploy and update registry packages

- rust/main/Cargo.lock
- rust/main/agents/scraper/Cargo.toml
- rust/main/agents/scraper/src/agent.rs
- rust/main/agents/scraper/src/db/block_cursor.rs
- rust/main/agents/scraper/src/db/mod.rs
- rust/main/agents/scraper/src/settings.rs
- handle errors and sets set chain metrics if scraper fails for chain during startup
- implement Clone for `ScraperDb`
- this is because DbConn doesn't implement Clone when `mock` feature is enabled
Fixes https://github.com/hyperlane-xyz/issues/issues/1408
Yes
Added unittest to test function. But don't have tests in place for testing the logic in `Scraper::run()`
> feat: improve scraper startup error handling

- typescript/infra/scripts/safes/combine-txs.ts
feat: script to combine safe txs by chain id
- pass in a directory of safe txs in json form
- combines/groups transactions together by the chainid to submit to
before:
after:
> feat: script to combine safe txs by chain id

- typescript/infra/config/environments/mainnet3/agent.ts
Upgrade scraper to latest version.
Scraper won't crash if a single RPC is unstable. It will report a critical error.
Yes
Deployment
> feat(release): Upgrade scraper to latest version

- typescript/infra/scripts/agent-utils.ts
- typescript/infra/scripts/safes/get-pending-txs.ts
- typescript/infra/scripts/safes/parse-txs.ts
- typescript/infra/src/tx/govern-transaction-reader.ts
- typescript/infra/src/utils/safe.ts
- typescript/sdk/package.json
- typescript/sdk/src/utils/gnosisSafe.js
- yarn.lock
- feat: infra safe tx parser infers txs to parse
- users are no longer required to provide the exact txs to parse
- now supports multiple txs per chain
- still allows someone to provide `--chains`/`-c` arg if they wish to specify exactly which chains to check
- support timelock txs
- write the yaml output to file instead of requiring users to `| tee file.txt`
- add catch-all case for ownership transfers on ownables
- rootLogger instead of console logs (make eslint happy in editor)
- remove `withTxHashes` helper as it's no longer used anywhere
- fix dependency issue by moving getPendingTxs helper to utils
- fixes
no longer need https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5160
> feat: infra safe tx parser auto-infers txs to parse

- typescript/infra/config/environments/mainnet3/agent.ts
Upgrade relayer to 09e1d5b-20250121-214732 version
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5098
Yes
E2E tests in CI
> feat: Upgrade relayer to 09e1d5b-20250121-214732 version

- rust/main/agents/scraper/migration/src/m20230309_000003_create_table_cursor.rs
- rust/main/agents/scraper/migration/src/m20230309_000004_create_table_delivered_message.rs
- rust/main/agents/scraper/migration/src/m20230309_000004_create_table_gas_payment.rs
Add indices to Scraper database so that queries are quicker.
Scraper with SeaORM version 1.1.1 (currently reverted) reported that some queries are running slow. These indices will improve it.
- https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4793
Yes
Tested queries with indices on a separate database where full production database backup was restored
> fix: Add indices to Scraper database so that queries are quicker

- .changeset/nervous-dragons-applaud.md
- typescript/widgets/src/components/Tooltip.tsx
- typescript/widgets/src/icons/Refresh.tsx
- typescript/widgets/src/index.ts
- typescript/widgets/src/stories/Tooltip.stories.tsx
- Export new Refresh Icon
- Add tooltipClassName as a prop to Tooltip and added the default value to be the one used in this [PR](https://github.com/hyperlane-xyz/hyperlane-explorer/pull/147)
No
Refresh button will be used to add refresh functionality to explorer
Yes
Storybook
> feat(widgets): add refresh icon and className to Tooltip component

- solidity/contracts/token/HypERC20.sol
This PR makes the `decimals()` function virtual to allow for further overriding in derived contracts.
None.
N/A.
Yes
N/A
> feat: make `decimals()` virtual

- typescript/infra/config/environments/mainnet3/owners.ts
- typescript/infra/src/tx/govern-transaction-reader.ts
Parse inner transactions on timelocks
Manual
```sh
$ yarn tsx scripts/safes/parse-txs.ts --chains ethereum
```
```yaml
ethereum-0xc096af73952e18fe1201b457a95b598d680d7f185747b28153da2c175532ca8f:
chain: ethereum
to: Timelock Controller (ethereum 0x59cf937Ea9FA9D7398223E3aA33d92F7f5f986A2)
insight: 'Schedule for Sun Jan 26 2025 18:05:17 GMT-0500 (Eastern Standard
Time): {"chain":"ethereum","to":"Timelock Controller (ethereum
0x59cf937Ea9FA9D7398223E3aA33d92F7f5f986A2)","args":{"newDelay":{"type":"BigNumber","hex":"0x00"}}}'
```
> feat: recurse in safe timelock parser

- .changeset/fast-comics-wave.md
- solidity/contracts/token/HypERC20.sol
This PR makes the `initialize` function public and virtual to allow for further overriding in derived contracts.
None.
N/A.
Yes
N/A
> feat: make `initialize` function public virtual

- typescript/infra/config/environments/mainnet3/agent.ts
Upgrade validators in hyperlane context to f6b682c-20250124-144126
Yes
E2E tests in CI
> chore: Upgrade validators in hyperlane context to f6b682c-20250124-144126

- typescript/infra/config/environments/mainnet3/owners.ts
Checkers would expect proxyAdmin/upgrades to be gated by ethereum timelock added in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5278
Yes
Manual/cron
> fix: isolate upgrade and symbiotic timelocks

- rust/main/chains/hyperlane-sealevel/src/mailbox.rs
- rust/main/chains/hyperlane-sealevel/src/tx_submitter.rs
- typescript/infra/config/environments/mainnet3/agent.ts
- context: https://discord.com/channels/935678348330434570/1333035743622336614
- uses the RPC URL used for tx submission (if it's possible) to poll tx status. We use a Helius tx submission URL on solana mainnet so this now uses Helius for polling the status as well
> feat: SVM agents - use the transaction submission URL for polling tx status

- .changeset/selfish-drinks-add.md
- typescript/sdk/src/token/Token.ts
- typescript/sdk/src/token/nativeTokenMetadata.ts
Improve Token.FromChainMetadataNativeToken by having it fallback to default `nativeToken` metadata if it hasn't been set in the `chainMetadata`. This is useful because `nativeToken` is optional and it's relatively safe because pretty much only the `decimals` value is important in cases where this is used.
> feat: Improve usability of Token.FromChainMetadataNativeToken

- typescript/infra/config/environments/mainnet3/warp/configGetters/getRenzoEZETHWarpConfig.ts
Update Renzo to use hardcoded tokenPrices because tokenPrices.json get updated which cause the hook configs to be different.
Yes
> fix: Update Renzo to use hardcoded tokenPrices

- typescript/infra/test/warp-configs.test.ts
This PR optimizes the warp config tests by moving the registry fetching into `before()` and reading it in memory.
Yes
Unit Tests
> chore: optimize warp config tests

- rust/main/Cargo.lock
- rust/main/Cargo.toml
Uses gas escalation fix for Sei from https://github.com/hyperlane-xyz/ethers-rs/pull/32:
> There was a gas spike on Sei overnight in which the escalator wasn't effective at all, because the error message (insufficient fee) is non-standard and txs were just dropped. This meant submissions were stuck until the gas price estimation RPC returned accurate enough values.
> Logs here: https://cloudlogging.app.goo.gl/wCsz7oEuFL6RdaAY7
> fix: handle Sei retryable error

- rust/main/chains/hyperlane-ethereum/src/rpc_clients/trait_builder.rs
- A bit hacky, but we need to satisfy the quick goal of adding headers to Http RPCs
- Doesn't do anything for ws
- Any `custom_rpc_header` query parameter is expected to have the value format: `header_name:header_value`, will be added to the headers, and removed from the URL params.
- Allows you to for example do:
```
HYP_CHAINS_MYCHAIN_CUSTOMRPCURLS=https://foo.bar.com?custom_rpc_header=Authorization%3A%20Bearer%20MySecret
```
> feat: allow headers to be passed in as RPC query params

- typescript/infra/config/environments/mainnet3/warp/configGetters/getRenzoEZETHWarpConfig.ts
This PR addresses an issue mentioned on [discord](https://discord.com/channels/935678348330434570/1321870185984163880/1337085307073597591) where the existing infra checker does not fully support proxyAdmin. The error is introduced because we reused renzo's proxyAdmin. 
This change allows specification of the proxyAdmin, such that if it's not provided, will deploy a new proxyAdmin
Yes
Tested by running `yarn tsx ./scripts/warp-routes/export-warp-configs.ts -e mainnet3` which resulted in:
- no diffs in production ezEth config
- removes the proxyAdmin object from EZETHSTAGE
> feat: Add optional parameter for existingProxyAdmins in getRenzoEZETHWarpConfigGenerator

- typescript/infra/config/environments/mainnet3/agent.ts
we have noticed two more messages with malformed recipients, that are undeliverable. They have been surfaced by adding `SMOL/arbitrum-ethereum-solanamainnet-treasure` to the known app contexts
> chore: blacklist SMOL malformed recipient msgs

- .changeset/new-phones-train.md
- .changeset/stale-seas-travel.md
- typescript/cli/src/context/strategies/chain/MultiChainResolver.ts
- typescript/infra/config/environments/mainnet3/chains.ts
- typescript/infra/config/environments/mainnet3/owners.ts
- typescript/infra/scripts/safes/parse-txs.ts
- typescript/infra/src/tx/govern-transaction-reader.ts
- typescript/sdk/src/consts/multisigIsm.ts
- typescript/sdk/src/utils/gnosisSafe.js
feat: enroll berachain
- add renzo/luganodes validators to default unichain set
- add bera multisend address overrides in SDK
- support reading native token transfers in the GovernTransactionReader
- add deploy-only tx override for matchain
- fix default strategy resolution in `MultiChainResolver`
- encountered issue when attempting `hyperlane status`
> feat: enroll berachain

- .changeset/tender-jokes-wonder.md
- typescript/cli/package.json
fix: move zksync-ethers to regular cli deps
> fix: move zksync-ethers to regular cli deps

- .changeset/purple-geese-study.md
- typescript/sdk/src/hook/EvmHookReader.ts
Right now, because IGP's domains are not an enumerable set, we have to query all known domains on it. That is becoming very expensive. This change at least avoids querying for testnet domains when looking at a mainnet IGP and vice versa.
> fix: don't derive testnet domains in IGP config derivation on mainnet

- .changeset/wicked-bags-enjoy.md
- typescript/infra/src/govern/HyperlaneICAChecker.ts
- typescript/infra/src/govern/ProxiedRouterGovernor.ts
- typescript/sdk/src/router/HyperlaneRouterChecker.ts
- typescript/sdk/src/router/types.ts
- In response to an error thrown when there are actual enrolled routers that are not present in the config, this was encountered running the warp checker against a route not managed by AW. 
Here is the violation output
Manual
> fix(checker): Add MissingRouterViolation when config misses enrolled routers

- rust/main/agents/relayer/src/msg/pending_message.rs
We have so many messages with similar retry counts that now even by spreading them over 1h we still starve new messages. This PR increases the random period to 6h, hoping to more evenly distribute retries of old messages.
A side effect of this is that even newly indexed messages may take 6h to get delivered after a restart
Some data to back this, you can see that after prepare failures start spiking there's also a diff in the prep queue, indicating starvation
> fix: try using a longer randomization period for retrying messages

- rust/main/agents/relayer/src/msg/metadata/aggregation.rs
- rust/main/agents/relayer/src/msg/metadata/base.rs
- rust/main/agents/relayer/src/msg/metadata/ccip_read.rs
- rust/main/agents/relayer/src/msg/metadata/mod.rs
- rust/main/agents/relayer/src/msg/metadata/multisig/base.rs
- rust/main/agents/relayer/src/msg/metadata/null_metadata.rs
- rust/main/agents/relayer/src/msg/metadata/routing.rs
- rust/main/agents/relayer/src/msg/op_queue.rs
- rust/main/agents/relayer/src/msg/pending_message.rs
- rust/main/agents/relayer/src/server/message_retry.rs
- rust/main/agents/validator/src/validator.rs
- rust/main/hyperlane-base/src/settings/checkpoint_syncer.rs
- rust/main/hyperlane-core/src/traits/pending_operation.rs
- rust/main/hyperlane-core/src/types/reorg.rs
- rust/main/utils/run-locally/src/main.rs
- typescript/infra/scripts/send-test-messages.ts
- Only panics in the validator if there is a reorg detected
- Mostly solves https://github.com/hyperlane-xyz/issues/issues/1394 (does not have super clear alert conditions for a reorg occurring, this should come later)
- Whereas before we would use `Result<Option<Vec<u8>>` as a return type for metadata building, where the Result indicates some error occurred (e.g. an RPC issue or something), Ok(Some(_)) meant that metadata building was successful, and Ok(None) meant that no error occurred but simply that fetching metadata wasn't successful -- we now have a new `Metadata` enum:
```
#[derive(Clone, Debug)]
pub enum Metadata {
/// Able to fetch metadata
Ok(Vec<u8>),
/// Unable to fetch metadata, but no error occurred
CouldNotFetch,
/// While building metadata, encountered something that …
```
> feat: graceful and alertable relayer reorg detection

- .github/workflows/test.yml
chore(ci): catch-all e2e job for matrix
- adds `e2e` job at the end of the `e2e-matrix` as the catch-all job to wait for
- just like we do for `cli-e2e-matrix` with the `cli-e2e` step
- this means any future additions to the matrix don't require a change to the github branch protection settings
> chore(ci): catch-all e2e job for matrix

- .changeset/seven-cars-fix.md
- typescript/sdk/src/ccip/consts.ts
- typescript/sdk/src/ccip/utils.ts
- typescript/sdk/src/index.ts
feat: add CCIP utilities
- keep CCIP registry as a const
- add utilities for reading properties from the CCIP registry
> feat: add CCIP utilities

- rust/sealevel/environments/mainnet3/gas-oracle-configs.json
- typescript/infra/src/config/gas-oracle.ts
Solana gas price more than 10xed since the igp quotes were updated. I've updated the gas oracles and merging in the config I got
Quicknode is reporting the medium fee to be 500k ([source](https://www.quicknode.com/gas-tracker/solana)), but in practice helius is quoting us 1M+. Our previous quote was $1, updating to $1.2 to cover some of the increased cost
> chore: update gas oracles for the solana destination

- .husky/pre-commit
chore: fix Release pipeline
- added gitleaks to precommit, but this is not installed by default on github actions
- so skipping gitleaks checks in CI
> chore: fix Release pipeline

- .changeset/mean-cherries-reflect.md
- solidity/contracts/hooks/CCIPHook.sol
- solidity/contracts/isms/hook/CCIPIsm.sol
- solidity/test/isms/CCIPIsm.t.sol
Enable out of order message execution to prevent DoS. 
Set gas limit to benchmark form `forge test --isolate`.
Use 0 instead of msg.value in CCIP ISM.
Yes
Unit/Fork Tests
> fix: CCIP messages should not be DoSable

- typescript/sdk/src/ccip/utils.ts
We write with `_`, but mistakenly read with the old `-`. This fixes that.
Yes
Unit Tests### Description
manual
> fix: reading ccip hook/ism addresses

- rust/main/agents/relayer/src/msg/pending_message.rs
- More frequent retries for the first ~30 mins, meant to accommodate the upcoming CCIP ISM which is known to take ~25 mins on some origins
After this change:
```
Retry #0: cumulative duration from beginning is 0:0:0, since last attempt is 0:0:0
Retry #1: cumulative duration from beginning is 0:0:0, since last attempt is 0:0:10
Retry #2: cumulative duration from beginning is 0:0:10, since last attempt is 0:0:10
Retry #3: cumulative duration from beginning is 0:0:20, since last attempt is 0:0:10
Retry #4: cumulative duration from beginning is 0:0:30, since last attempt is 0:0:10
Retry #5: cumulative duration from beginning is 0:0:40, since last attempt is 0:0:10
Retry #6: cumulative duration from beginning is 0:0:50, since last attempt is 0:0:10
Retry #7: cumulative duration from beginning …
```
> feat: adjust backoff duration to better accommodate CCIP ISM

- solidity/contracts/hooks/libs/AbstractPostDispatchHook.sol
Replace use of `address.transfer` (fixed gaslimit) with `address.sendValue` for refund recipients that may be contracts.
Yes
Unit Tests
> fix: Use sendValue instead of transfer

- solidity/test/isms/ExternalBridgeTest.sol
- solidity/test/isms/MultisigIsm.t.sol
Migrates to 1.0 according to https://book.getfoundry.sh/guides/v1.0-migration#expect-revert-cheatcode-disabled-on-internal-calls-by-default
> fix: repairs broken tests from foundry 1.0 release

- .changeset/fuzzy-pillows-notice.md
- typescript/sdk/src/token/EvmERC20WarpRouteReader.hardhat-test.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.ts
- typescript/sdk/src/token/checker.ts
- typescript/sdk/src/token/deploy.ts
- typescript/sdk/src/token/types.ts
Allow `HypXERC20` and `HypXERC20Lockbox` to be derived in the warp reader, similar to https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5478, just for CLI
Yes
> feat: Support xerc20 token config derivation in warp check

- .changeset/red-cows-warn.md
- typescript/cli/src/check/warp.ts
- typescript/cli/src/commands/warp.ts
- typescript/cli/src/read/warp.ts
- typescript/cli/src/tests/warp/warp-check.e2e-test.ts
- typescript/sdk/src/index.ts
- typescript/sdk/src/token/configUtils.ts
When using `WarpDeployConfig` we often assume certain defaults, however when we compare against `warp read` config, it includes all the "expanded" config. This PR adds "config expansion", so that checking actually can be done. As part of that, it removes the practice of `warp read` after deploy in the warp check e2e tests so that the actual comparison against the intended deploy config can happen (instead of the inferred config from warp read).
This is related to https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5358 and in fact lifts some of the convenience function into `configUtils.ts` fyi @mshojaei-txfusion 
The warp-check e2e test setup changes as mentioned
Yes
Local e2e tests and manual
> feat: Expand warp deploy config in warp check

- .changeset/lazy-otters-boil.md
- typescript/cli/src/tests/warp/warp-check.e2e-test.ts
- typescript/sdk/src/hook/EvmHookModule.hardhat-test.ts
- typescript/sdk/src/hook/EvmHookModule.ts
- typescript/sdk/src/router/types.ts
- typescript/sdk/src/token/EvmERC20WarpModule.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.hardhat-test.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.ts
- typescript/sdk/src/token/configUtils.ts
This PR changes the canonical definition of using the default ism/hooks from `undefined` to `zeroAddress`. This ultimately makes cli checking work. Builds on top of https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5483 and should be based against it once CI tests are passing
Mostly yes (because I don't think this behavior has been leveraged)
Unit tests/e2e tests/ manual tests
> feat: Support ISM/Hook checking when using defaults

- rust/main/agents/relayer/Cargo.toml
- rust/main/agents/relayer/src/msg/pending_message.rs
Due to our lack of unit testing coverage, an overflow bug caused by https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5455 wasn't caught. This bug happened on 7 chains on RC and took down their submitters.
I've noticed it now on RC due to the rising prep queues ([source](https://abacusworks.grafana.net/goto/kbQcXdcNR?orgId=1)), and also confirmed using these logs: https://cloudlogging.app.goo.gl/zJKqhTCTPAxETTg79. 
I'm not sure why but for crashed submitters, the prep queue keeps increasing although the only logic pushing to it lives in the submitter. Maybe's there's a future cancellation issue with `receive_task` and as a result it's still alive ([source](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/ab2917a424534cb034400ad85836b9f833832aaf/rust/main/agents/relayer/src/m …
> fix: overflow in new `next_attempt_after` calculation

- rust/main/config/mainnet_config.json
- typescript/infra/config/environments/mainnet3/chains.ts
- added transactionOverrides for morph based on the recent blocks on their explorer. They have had 0.2-05% full blocks for the past month.
None
- fixes https://discord.com/channels/935678348330434570/1340007394368950372/1340007397183459348
Yes
None
> fix(release): process morph transactions as legacy

- typescript/infra/config/environments/mainnet3/agent.ts
- updated image tag for morph legacy override fix #5489 
none
none
yes
none
> feat(release): release `hyperlane` context relayer for #5489

- typescript/infra/config/environments/mainnet3/agent.ts
deploys the changes from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5434 to the hyperlane context. They've been tested on RC with a bunch of providers to make sure we capture both successful and failed calls.
See the dashboard here: https://abacusworks.grafana.net/goto/R7gtDxcHg?orgId=1
> chore: deploy sealevel provider metrics

- rust/main/agents/relayer/src/msg/metadata/base.rs
We now face ISM trees which are deeper than the configured default
> feat: Increase max-depth tree

- rust/main/config/mainnet_config.json
Specify chunk size for Lumia Prism chain
Yes
Fix for failing RPC calls. Tested with direct change into Relayer RC.
> fix: Specify chunk size for Lumia Prism chain

- rust/main/Cargo.lock
- rust/main/Cargo.toml
- rust/main/agents/relayer/src/relayer.rs
- rust/main/agents/scraper/src/agent.rs
- rust/main/agents/validator/src/validator.rs
- rust/main/hyperlane-base/Cargo.toml
- rust/main/hyperlane-base/src/agent.rs
- rust/main/hyperlane-base/src/metrics/agent_metrics.rs
- rust/main/hyperlane-base/src/metrics/core.rs
- rust/main/hyperlane-base/src/metrics/mod.rs
- rust/main/hyperlane-base/src/metrics/runtime_metrics.rs
- rust/main/utils/run-locally/src/invariants/termination_invariants.rs
We recently had a critical bug on RC where the submitter task crashed due to a panic (https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5487). We've had similar issues in the past, where one tokio task getting dropped wasn't detected by alerts and was only discovered later.
This PR integrates tokio-metrics with our Prometheus setup and exposes one of the metrics available: `dropped_tasks`, which tracked in prometheus as the cumulative count of all tasks ever dropped. In e2e this metric is zero after invariants pass - in prod I think we'll alert if this ever becomes nonzero.
Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5466
No
Yes
Checked in e2e that the new metric exists, otherwise relying on correctness from tokio-metrics
> feat: tokio task metrics

- typescript/infra/scripts/xerc20/xerc20vs-add-bridge.ts
- typescript/infra/scripts/xerc20/xerc20vs-set-limits.ts
- typescript/infra/src/xerc20/utils.ts
- Generally handle Safe or Signer transactions properly
- Throw when safe tx service is not available
- Specifically fallback to Signer tx when the expected owner is a safe in the config but the actual owner is the deployer (Signer), this special case occurs post deployment before ownership transfers are applied 
Manual
> feat(limits): Handle safe transaction scenarios

- typescript/sdk/src/token/checker.ts
Right now we are checking ownables in the infra checker for the collateral token (and its proxy admin). However, we want to be testing the xerc20 owners.
> feat: check the right proxy admin for xerc20 token

- rust/main/chains/hyperlane-ethereum/src/rpc_clients/fallback.rs
Make only one retrying attempt if we get non-retryable error.
At the moment, we are doing 12 RPC calls even if all of them returned a non-retryable error in multicast approach of EthereumFallbackProvider. While we still would like to wait for all providers to return their result when we do multicast, we would like to avoid retrying since it produces a lot of requests with the same failure result. It leads to elevated RPC failure metrics and higher number of alerts.
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5452
Yes
TBD
> fix: Make only one retrying attempt if we get non-retryable error

- typescript/infra/scripts/xerc20/xerc20vs-add-bridge.ts
- typescript/infra/scripts/xerc20/xerc20vs-set-limits.ts
- typescript/infra/src/utils/safe.ts
- typescript/infra/src/xerc20/utils.ts
feat: xerc20 safe tx submission improvements
- use getSafeAndService infra util where possible instead of SDK directly (to have retry logic)
- refactor sendTransaction logic to better leverage MultiSend
- add --chains filter
manual
> feat: xerc20 safe tx submission improvements

- typescript/infra/config/environments/mainnet3/agent.ts
Deploy fix for chuck size for Lumia and Lumia Prism chains.
Yes
> chore: Upgrade Scraper to 84918d2-20250224-172508

- typescript/infra/config/environments/testnet4/funding.ts
Key funder cannot place a claiming transaction on Berachain Berabartio testnet. We are disabling Berabartio testnet at this time.
Yes
Manual run of key-funder
> fix: Prevent key-funder from IGP claiming on berachain berabartio testnet

- .changeset/loud-radios-remember.md
- typescript/sdk/src/token/adapters/SealevelTokenAdapter.ts
Default to `0` for `Sealevel` chains that are not `solanamainnet`
No
Fixes this [issue](https://github.com/hyperlane-xyz/issues/issues/1415)
Yes
Tested in Warp UI:
Solana <> Eclipse https://explorer.eclipse.xyz/tx/2WNYksY9bTbXW8tWZVPRbf5JMQ2MbdiQ7j2j7mMpvq2XpmirNcYDPp3PYKharvidrbfSyy36sVXUgk7EamEQexRC
Solana <> Soon
https://explorer.soo.network/tx/3Sdia7mM3eowhthetDQhNG5FyfU43zNYQYSJNcX8yNXLwg3UjGy9YErXMpuySxHLfaDiFVXr4fCxtEyYYSzjQxMe
> chore: remove sealevel priority fees

- typescript/infra/config/environments/mainnet3/warp/warpIds.ts
- typescript/infra/src/warp/helm.ts
- Add pumpBTC/ethereum-unichain warp route
- Accompanying registry PR https://github.com/hyperlane-xyz/hyperlane-registry/pull/616 
- dashboard: https://abacusworks.grafana.net/d/ddz6ma94rnzswc/warp-routes?orgId=1&var-warp_route_id=pumpBTC.uni%2Fethereum-unichain&from=now-30m&to=now&timezone=browser
Manual
- outbound transfer https://explorer.hyperlane.xyz/message/0xd08c3ce12f0258d4f363e7af416734f2afb9e93e84bb39705d511f90d793b0a3
- inbound transfer https://explorer.hyperlane.xyz/message/0x6ec6c36716fa5d5b8e7e89dd98e10a9405ca14f742e9c655e52ced8042c7e5fb
> feat(warp): Add pumpBTC/ethereum-unichain warp route

- .changeset/thick-suns-confess.md
- typescript/cli/src/config/warp.ts
- typescript/cli/src/tests/warp/warp-init.e2e-test.ts
This implements a fix for this issue https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5513
Yes - proxyAdmin is optional
Unit Tests
> fix: Remove proxyAdmin from warp init

- .changeset/moody-impalas-switch.md
- .changeset/thick-suns-confess.md
- typescript/cli/src/config/warp.ts
- typescript/cli/src/tests/warp/warp-init.e2e-test.ts
This PR changes warp init to output address(0) for ISM by default
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5513
Yes defaultIsm and address(0) are interchangable
> fix: set default ism address zero upon warp init

- .changeset/sweet-ears-sort.md
- .changeset/thick-suns-confess.md
- typescript/cli/src/config/warp.ts
- typescript/cli/src/utils/input.ts
This PR updates warp init to allow user to specify proxyAdmin. It sets it to undefined by default.
Yes
> fix: Update warp init to allow user to specify proxyAdmin 

- typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Scraper with the fix for search for relevant Sealevel transaction
- Deploys https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5558
Yes
CI E2E tests
> chore: Upgrade Scraper to d82d24c-20250225-211517

- rust/sealevel/client/src/warp_route.rs
We have at least 2 PRs whose CIs are failing due to the sealevel e2e: https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5570 and https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5517
TIL that `cargo install`ing from a repo ignores the lockfile. This means that any patch bumps will be automatically applied. This wouldn't be a problem if crates upheld the promise that patches don't break the MSRV, but they do :) and this breaks our sealevel e2e because it is on `1.76.0` (a rust version that doesn't conform to the MSRV after applying the patch updates)
So the fix is to pass a `--locked` flag to `cargo install` to force it to use the lockfile. ~~I've also added the `--force` flag to invalidate any cache so we make sure the lockfile versions are always used.~~
E2E should pass …
> chore: fix broken sealevel e2e build

- typescript/infra/src/xerc20/utils.ts
- typescript/sdk/src/token/adapters/EvmTokenAdapter.ts
Removes a bridge when the buffer cap is set to 0
> feat: remove bridge if bufferCap is set to 0

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/mainnet3/aw-validators/rc.json
- typescript/infra/config/environments/mainnet3/warp/warpIds.ts
- Moves to bigger machines - did this by manually creating a new node pool with the following specs, deploying, and shutting down the old node pool:
```
Custom
32 vCPU
64 GiB
$679.41 / mo
```
- Starts running the `hyperlane` context with the neutron chain, with the ultimate goal of shutting down the neutron context
- Adds the oUSDT app context to the relayers, and blacklists a known message for our monitoring
> feat: bump relayer resources, start using hyperlane context for neutron

- typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Relayer to cc3af7d-20250304-172021
- Contributes into https://github.com/hyperlane-xyz/issues/issues/1420
Yes
Manual check of metrics
> chore: Upgrade Relayer to cc3af7d-20250304-172021

- typescript/sdk/src/token/Token.ts
Fix broken test by adding `EvmHypVSXERC20` and `EvmHypVSXERC20Lockbox` token standards to getHypAdapter
UI test
> chore: add VSXERC20 tokens to getHypAdapter

- .changeset/ten-poems-tan.md
- typescript/cli/src/status/message.ts
Small fixes to status command for filtering on specified message ID.
Yes
Manual
```
Checking status of message 0x96ecd0e3bce5939ad0a16a82cd071bba109b95d0cb73f63fe873ed2fa519480c on superseed
Message 0x96ecd0e3bce5939ad0a16a82cd071bba109b95d0cb73f63fe873ed2fa519480c was delivered in https://explorer.superseed.xyz//tx/0x50a0ed288a1a4e87c6996355fbab4fff18312cb76dd730dfeb76daad2226da03
```
> fix: only relay specified message ID

- rust/main/agents/relayer/src/merkle_tree/processor.rs
Move access to database into a blocking task
The access to rocksdb is synchronous and we discovered that it take about 1 millisecond to make one retrieval of an insertion into a merkle tree from the database when we build internal merkle tree in relayer from scratch. As the result, the worker thread which executes the task, is blocked by access to the database and cannot be used to execute other scheduled tasks.
This change moves the access to the database into a separate thread in the blocking pool. It frees up the worker thread to execute other tasks.
- Contributes into https://github.com/hyperlane-xyz/issues/issues/1420
Yes
Manual run of relayer locally
> fix: Move access to database into a blocking task

- typescript/infra/config/environments/testnet4/agent.ts
Upgrade Relayer Testnet to 8c3e983-20250310-144838
* Add merkle tree processor metrics
* Move retrieval merkle tree into a blocking task
- Contributes into https://github.com/hyperlane-xyz/issues/issues/1420
Yes
Manually
> chore: Upgrade Relayer Testnet to 8c3e983-20250310-144838

- typescript/infra/config/environments/mainnet3/warp/warpIds.ts
- typescript/infra/config/warp.ts
- comment out the oUSDT staging route for now until we decide on a path forward to include it (see https://hyperlaneworkspace.slack.com/archives/C08H0T2FL2V/p1741724924053689) 
- the inclusion of this warpId is leading to the check-warp-deploy job failing as the staging config is not yet merged into registry
- delete duplicated warp route ID for oUSDT 
Manual
> fix: comment out oUSDT staging warp id to fix check warp deploy job

- typescript/infra/scripts/agent-utils.ts
- typescript/infra/scripts/print-warp-routers.ts
Motivating use case: when we see a warp route imbalance, sometimes it's hard to tell exactly why.
Intended to be used with [this metabase dashboard](https://abacus-works.metabaseapp.com/dashboard/793-warp-route-details?routers_comma_separated=4F0654395d621De4d1101c0F98C1Dba73ca0a61f%2CbBa1938ff861c77eA1687225B9C33554379Ef327%2Ca0bD9e96556E27e6FfF0cC0F77496390d9844E1e%2C69158d1A7325Ca547aF66C3bA599F8111f7AB519%2C910FF91a92c9141b8352Ad3e50cF13ef9F3169A1%2C324d0b921C03b1e42eeFD198086A64beC3d736c2%2C7bD2676c85cca9Fa2203ebA324fb8792fbd520b8%2C2dC335bDF489f8e978477Ae53924324697e0f7BB%2C5beADE696E12aBE2839FEfB41c7EE6DA1f074C55%2C4A8149B1b9e0122941A69D01D23EaE6bD1441b4f%2CAf6bEdBA6ab73f0a5941d429807C8B9c24Ea95F3), which will surface using the scraper DB any messages that are not processed. Future …
> feat: add print-warp-routers script

- rust/main/helm/hyperlane-agent/templates/scraper-statefulset.yaml
Make scraper to start on dedicated node. It helps to avoid timeouts on Eclipse RPC with archival node of Luganodes
- Fixes https://github.com/hyperlane-xyz/issues/issues/1431
Yes
In testnet context
> fix: Make scraper to start on dedicated node

- typescript/infra/scripts/warp-routes/deploy-warp-monitor.ts
- typescript/infra/scripts/warp-routes/monitor/monitor-warp-route-balances.ts
- typescript/infra/src/warp/helm.ts
This PR updates deploy-warp-monitor to use withWarpRouteId, which does not require a warpId in warpRouteIds enum
Yes
Manual
> fix: Use withWarpRouteId for deploy-warp-monitor

- rust/main/config/mainnet_config.json
- typescript/infra/config/environments/mainnet3/agent.ts
- To prevent our relayers from wasting their time
- Context https://hyperlaneworkspace.slack.com/archives/C08GHFABJQ6/p1741864497342839
> chore: skip eco messages in relayer

- typescript/sdk/src/consts/testChains.ts
- typescript/sdk/src/token/TokenStandard.ts
- typescript/sdk/src/warp/WarpCore.test.ts
- typescript/sdk/src/warp/WarpCore.ts
- typescript/sdk/src/warp/test-warp-core-config.yaml
- Separate mint limit checking from `isDestinationCollateralSufficient` into its own function: `validateDestinationRateLimit`
- Add new test for XERC20 tokens for checking `isDestinationCollateralSufficient` and `validateTransfer` 
- Add lockbox token standard to `TOKEN_COLLATERALIZED_STANDARDS` 
- Separated `MINT_LIMITED_STANDARDS` from `XERC20_STANDARDS` tokens
- Remove early return in `isDestinationCollateralSufficient` for `MINT_LIMITED_STANDARDS` tokens
Yes
Unit tests
> chore: separate mint limit check and add test

- rust/main/agents/relayer/src/msg/pending_message.rs
It's not clear how often we get batch subcall reverts on the EVM. We know for sure that these occur because the `hyperlane` relayer is racing `rc` to deliver first. For instance, this batch has a revert but there are no occurrences of `Error: Transaction attempting to process message either reverted or was reorged` in logs: https://cloudlogging.app.goo.gl/ZZaLJYbU1SX25NCC8
https://arbiscan.io/tx/0x6196fe0fb19b71a655ee7e9aab98070f210192884b2bcc4263b113b064dfd0f0
Hopefully actually logging will help us more easily identify these cases.
> chore: warning log when msg delivery failed

- .changeset/sour-mirrors-chew.md
…cessful registry build)
Changeset for https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5650
> docs(changeset): Added minimal support for Starknet networks (for registry build)

- typescript/infra/src/warp/helm.ts
This updates the image tag to reflect updates to deploy-warp-monitor in this [PR](https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5666)
Yes - because the update just removes the requirement that warpId is part of the warpRouteIds set
Manual - Tested through redeploying gps monitor
> chore: Update tag to reflect changes to deploy-warp-monitor

- rust/main/chains/hyperlane-cosmos/src/providers/cosmos/provider.rs
- rust/main/chains/hyperlane-cosmos/src/providers/grpc.rs
- rust/main/chains/hyperlane-cosmos/src/providers/rpc/provider.rs
- rust/main/chains/hyperlane-ethereum/src/rpc_clients/trait_builder.rs
- rust/main/chains/hyperlane-sealevel/src/rpc/client_builder.rs
- rust/main/hyperlane-metric/src/prometheus_metric.rs
- rust/main/utils/run-locally/src/cosmos/termination_invariants.rs
- rust/main/utils/run-locally/src/sealevel/termination_invariants.rs
- add a `connection` label to client metrics
- so we can filter based on `rpc/grpc` connection types
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5661
Yes
Updated E2E to filter by connection
> feat: add grpc/rpc separation in rpc metrics

- typescript/sdk/src/consts/testChains.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.ts
- typescript/sdk/src/token/Token.test.ts
- typescript/sdk/src/token/Token.ts
- typescript/sdk/src/token/TokenStandard.ts
- typescript/sdk/src/warp/WarpCore.test.ts
- typescript/sdk/src/warp/WarpCore.ts
- typescript/sdk/src/warp/test-warp-core-config.yaml
- Updates XERC20 collateral warp route adapter for [Super XERC20 variant](https://github.com/hyperlane-xyz/superchain-xerc20).
- Introduces a new token standard to represent this. 
- Adds logic for comparing to buffer cap limits. If the mint limit is decreasing, latency of message delivery can cause the transfer to appear mintable at dispatch time but not at process time. Thus we cap the mint limit at the buffer midpoint (where it will stop decreasing).
Yes
TODO
> fix: constrain max mint limit for super XERC20

- .changeset/slimy-coins-tan.md
- typescript/sdk/src/consts/sealevel.ts
- typescript/sdk/src/gas/adapters/SealevelIgpAdapter.ts
- typescript/sdk/src/gas/adapters/serialization.ts
- typescript/sdk/src/index.ts
- add `populateClaimTx` implementation to the `SealevelIgpAdapter`
- support priority fee config for sealevel chains
- This is a step towards supporting sealevel chains on the key funder
Manual
> feat(sealevel): Support claim tx via SealevelIgpAdapter

- rust/sealevel/environments/mainnet3/chain-config.json
- rust/sealevel/environments/mainnet3/gas-oracle-configs.json
- rust/sealevel/environments/testnet4/chain-config.json
- rust/sealevel/environments/testnet4/gas-oracle-configs.json
- typescript/infra/config/environments/mainnet3/igp.ts
- typescript/infra/config/environments/testnet4/igp.ts
- typescript/infra/scripts/sealevel-helpers/print-gas-oracles.ts
- Updates chain configs
- Mainnets: everclear, infinity, sophon (as https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5630 is not merged yet to track the warp route in question there)
- Testnets: connextsepolia, infinityvmmonza, basesepolia
- Also made sure Solana(testnet) -> infinityvm is free
> feat: update Solana / Solanatestnet IGPs to send to some new chains

- rust/main/helm/hyperlane-agent/templates/relayer-statefulset.yaml
- rust/main/helm/hyperlane-agent/values.yaml
- typescript/infra/config/environments/mainnet3/agent.ts
Set relayer to use premium storage class
This change allows Relayer to use premium storage class which using SSDs instead of HDD. It will allow relayer to start quicker.
- Fixes https://github.com/hyperlane-xyz/issues/issues/1433
Yes
Manual testing in test environment
> feat: Set relayer to use premium storage class

- typescript/cli/package.json
- typescript/cli/src/tests/commands/helpers.ts
- typescript/cli/src/tests/warp/warp-apply-extend.e2e-test.ts
- typescript/cli/src/tests/warp/warp-apply.e2e-test.ts
- typescript/helloworld/package.json
- typescript/infra/config/environments/mainnet3/warp/configGetters/getArbitrumNeutronTiaWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getBaseSolanaTRUMPWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionETHWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionUSDCWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionUSDTWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getMantapacificNeutronTiaWarpConfig.ts
- typescript/infra/package.json
- typescript/sdk/src/token/EvmERC20WarpModule.hardhat-test.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.hardhat-test.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.ts
- typescript/sdk/src/token/adapters/CosmWasmTokenAdapter.ts
- typescript/sdk/src/token/adapters/EvmTokenAdapter.ts
- typescript/sdk/src/token/adapters/SealevelTokenAdapter.ts
- typescript/sdk/src/token/configUtils.test.ts
- typescript/sdk/src/token/configUtils.ts
- typescript/sdk/src/token/deploy.hardhat-test.ts
- typescript/sdk/src/token/deploy.ts
- typescript/sdk/src/token/types.test.ts
- typescript/sdk/src/token/types.ts
- typescript/sdk/src/types.ts
- typescript/widgets/package.json
- yarn.lock
Remove `totalSupply` from `TokenMetadataSchema`. The field is not needed in most cases and could cause misconfiguration issues, on the synthetic token contract `totalSupply` was used, which mints tokens to the message sender.
Instead we now apply a `initialSupply` directly to the synthetic token without the need to use `totalSupply`
- Upgrade registry version
- Fix and remove tests that would depend on `totalSupply`
fixes #5687 
Yes
Unit tests
> chore: remove total supply from token metadata

- .changeset/tender-pandas-bake.md
- typescript/cli/src/status/message.ts
- use `tryGetExplorerTxUrl` instead of `getExplorerTxUrl` to support chains that do not have a block explorer configured e.g. local anvil builds
resolves https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5720
yes
manual
> fix(cli): successfully check status on chains without a block explorer

- .changeset/ten-doors-perform.md
- typescript/sdk/src/warp/WarpCore.test.ts
- typescript/sdk/src/warp/WarpCore.ts
Fixed an issue where `isDestinationCollateralSufficient` would check for the wrong address for lockboxes, it will now instead use [getBridgedSupply](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/cd1d0334411a40950b59efee8b42e341a219cad4/typescript/sdk/src/token/adapters/EvmTokenAdapter.ts#L409) to get collateral balance
Normally the collateral would be held by the destination's `addressOrDenom` but that is not the case for the XERC20 Lockboxes, as you can see [here](https://github.com/hyperlane-xyz/hyperlane-registry/blob/main/deployments/warp_routes/REZ/base-ethereum-config.yaml), this particular route if you dive deeper into the contract you can see that `addressOrDenom` hold no [funds](https://etherscan.io/address/0xc32848c38dd5a5098cd53d33e425c1013a4e06a8) but it is instead …
> fix: WarpCore collateral check for XERC20 lockboxes

- .changeset/violet-fireants-yell.md
- typescript/sdk/src/token/config.ts
This PR fixes reading on chain data on zksync chains by changing the NON_ZERO_SENDER_ADDRESS constant from `0x1` to anvil's `0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266` because only smart accounts can perform read operations on the rpc and 0x1 is a precompile
Before fix:
After fix:
- No
- Yes
- Manual
> fix(sdk): fix read commands on zksync chains

- typescript/sdk/CHANGELOG.md
Update changelog with missing changes from the removal of totalSupply in TokenMetadata
> chore: update SDK changelog with missing changes

- rust/main/agents/relayer/src/msg/metadata/message_builder.rs
- rust/main/agents/relayer/src/test_utils/mock_base_builder.rs
- rust/main/agents/relayer/src/test_utils/mock_ism.rs
- rust/main/chains/hyperlane-sealevel/src/provider/recipient/tests.rs
- rust/main/helm/hyperlane-agent/templates/external-secret.yaml
- rust/main/hyperlane-base/src/settings/parser/connection_parser.rs
- Makes transaction submitter URLs comma separated
- Updates helm to pass in URLs using the correct env var name. Does not try to actually have a fallback here or anything
> feat: Sealevel transaction submitter URLs comma separated, update helm

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/testnet4/agent.ts
Upgrade scraper to latest mainstream image c03278b-20250326-170423. It includes configurable timeout for Sealevel RPC client as well as Sealevel fallback provider
Yes
Testnet environment
> chore: Upgrade Scraper to latest mainstream image

- .github/workflows/test.yml
chore(ci): exit e2e earlier if we detect no rust changes
> chore(ci): exit e2e earlier if we detect no rust changes

- .github/workflows/test.yml
chore(ci): set yarn unit test timeout
- default is 6hours, so we reduce this to 10 mins
- test time is usually 5-7mins
- avoid spinning unnecessarily like https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/14090330834/job/39465209656
> chore(ci): set yarn unit test timeout

- typescript/infra/config/environments/mainnet3/funding.ts
- typescript/infra/config/environments/testnet4/funding.ts
- typescript/infra/scripts/funding/fund-keys-from-deployer.ts
- Essentially undo https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5594/files#diff-eef69ce94f98c3d10324260dd098dc643a30af9ec8df2261c048da71e2a886c0R399-R401
- Now that alfajores is back healthy and berabartio has been fully nuked from our repo, we don't need this. This also had the unintentional adverse impact of skipping some chains we don't actually wanna skip, like zkSync chains!
> fix: don't honor chainsToSkip in key funder

- .changeset/selfish-lizards-play.md
- solidity/package.json
- yarn.lock
New zksync dependencies 
"@matterlabs/hardhat-zksync-solc": "1.3.0",
"@matterlabs/hardhat-zksync-verify": "1.8.0",
introduce a zksync-telemetry package which tries to run husky
This pins them in the solidity package to prevent that
> fix: pin zksync deps from ccip package

- Dockerfile
fix: add cosmos-types to Dockerfile
- to fix this issue https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/14201525450/job/39791444792#step:8:293
> fix: add cosmos-types to Dockerfile

- rust/main/utils/run-locally/src/cosmosnative/cli.rs
Increase chain spin up time for cosmos native E2E tests
> fix(test): e2e increate timeout

- rust/main/chains/hyperlane-cosmos-native/src/providers/grpc.rs
- rust/main/chains/hyperlane-cosmos/src/providers/grpc.rs
Add timeout to Cosmos gRPC requests which we fully control. Some requests are done via a wrapper methods (with BroadcastTxRequest, for example) which do not expose raw Request, so we cannot set timeout on them.
Relayer was hanging indefinitely on request for misbehaving gRPC endpoint. This change is not a remedy, but hopefully we'll get a timeout next time and will be able to switch to a different endpoint.
Yes
None
> fix: Add timeout to some Cosmos gRPC requests

- .changeset/rotten-goats-knock.md
- solidity/contracts/token/HypERC20.sol
- solidity/contracts/token/extensions/4626.md
- solidity/contracts/token/extensions/HypERC4626.sol
- solidity/contracts/token/extensions/HypERC4626Collateral.sol
- solidity/contracts/token/libs/FungibleTokenRouter.sol
- solidity/contracts/token/libs/TokenRouter.sol
- solidity/test/token/HypERC4626Test.t.sol
Inherits more behavior from `FungibleTokenRouter` and `HypERC20`/`HypERC20Collateral` in `HypERC4626` and `HypERC4626Collateral`.
Adjusts docstrings on `TokenRouter` for clarity.
Adds yield route lifecycle diagrams.
No
Existing warp route unit tests
New tests added for approvals
> fix: ensure 4626 warp route variants use `FungibleTokenRouter` scaling

- .changeset/config.json
chore: update cosmos package versions only when there are changes
Noticed that the recent monorepo release bumped up the cosmos-types's first release version as 11.0.0 to be in line with other packages. This PR proposes to only bump up the package versions for the cosmos-sdk + cosmos-types modules when there are changes - similar to how the current solidity "core" package behaves.
See changesets docs for more info on the `fixed` option: https://github.com/changesets/changesets/blob/main/docs/config-file-options.md#fixed-array-of-arrays-of-package-names
> chore: update cosmos package versions only when there are changes

- .github/workflows/monorepo-docker.yml
This PR removes the `cache-to` and `cache-from` from the `depot/build-push-action` inputs - caching is automatically handled by the Depot builder without needing to additionally save / load from GitHub. Removing these options will save that additional time on every build.
cc @paulbalaji
> chore(ci): remove unnecessary cache-to and cache-from

- typescript/infra/test/balance-alerts.test.ts
- Skip balance alert test if grafana api key cannot be read from secrets
- This will allow CI to pass for external PRs
Manual
> fix: skip balance alert test if grafana api key cannot be read from secrets

- rust/main/utils/run-locally/src/main.rs
temporarily copy mantas' fix from https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/4860/commits/6b468c0f3fca1ca1671c51856f43e360ef459510 until https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/5843 is merged
> fix: temp ci patch

- typescript/infra/config/environments/testnet4/agent.ts
Upgrade Relayer in testnet to fe1f33b-20250408-120728
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5748
Yes
Manual
> chore: Upgrade Relayer in testnet to latest image

- typescript/infra/config/environments/mainnet3/agent.ts
Upgrade Relayer in mainnet to fe1f33b-20250408-120728
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5748
Yes
Manual
> chore: Upgrade Relayer in mainnet to latest

- .changeset/calm-humans-do.md
- typescript/sdk/src/token/deploy.hardhat-test.ts
- typescript/sdk/src/token/types.ts
This PR fixes a couple mistakes in token config type definitions. Some of the synthetic token types didn't match to config schemas correctly.
Incompatibilities should be caught by static typing but we can't be sure it doesn't cause breakage in any dependent code.
The existing test suite wasn't extended to expose the bugs.
> fix: corect synthetic token types

- .changeset/wise-parrots-judge.md
- typescript/sdk/src/metadata/chainMetadataTypes.ts
Adds a new optional `public` field for the RpcUrlSchema. This allows the Validators to report more comprehensive stats. 
> [!IMPORTANT]  
> This field should not be set to true in the registry yet.
> feat: add optional public field for RpcUrlSchema

- rust/main/Cargo.lock
- rust/main/agents/relayer/src/relayer.rs
- rust/main/submitter/Cargo.toml
- rust/main/submitter/src/chain_tx_adapter/adapter.rs
- rust/main/submitter/src/chain_tx_adapter/chains/sealevel/adapter.rs
- rust/main/submitter/src/lib.rs
- rust/main/submitter/src/payload_dispatcher.rs
- rust/main/submitter/src/payload_dispatcher/db/loader.rs
- rust/main/submitter/src/payload_dispatcher/db/payload/loader.rs
- rust/main/submitter/src/payload_dispatcher/db/transaction/loader.rs
- rust/main/submitter/src/payload_dispatcher/dispatcher.rs
- rust/main/submitter/src/payload_dispatcher/entrypoint.rs
- rust/main/submitter/src/payload_dispatcher/stages.rs
- rust/main/submitter/src/payload_dispatcher/stages/building_stage.rs
- rust/main/submitter/src/payload_dispatcher/stages/finality_stage.rs
- rust/main/submitter/src/payload_dispatcher/stages/inclusion_stage.rs
- rust/main/submitter/src/payload_dispatcher/stages/state.rs
- rust/main/submitter/src/payload_dispatcher/test_utils.rs
- rust/main/submitter/src/payload_dispatcher/tests.rs
- rust/main/utils/run-locally/src/invariants/termination_invariants.rs
- rust/main/utils/run-locally/src/main.rs
- rust/main/utils/run-locally/src/sealevel/mod.rs
- rust/main/utils/run-locally/src/sealevel/termination_invariants.rs
- rust/sealevel/environments/local-e2e/warp-routes/testwarproute/program-ids.json
- In the SVM adapter, if `submit` is called on a tx that already has a `hash`, the submission is skipped. This is because in solana we shouldn't resubmit unless the hash was dropped, and that would be detected when status is queried within the inclusion stage, causing the tx to be dropped, payloads sent back to the building queue, and a new tx built. This can be optimized but there was no obvious simple way to fix for now. If we do submit again, a new hash would be generated, creating a race condition between the old tx and the new tx. In e2e I noticed that the old tx always lands and the new tx reverts, though the submitter is unaware of it because its `hash` field gets set to the new one, so it keeps the tx stuck in the inclusion stage instead of promoting it to the finality stage.
- …
> feat(submitter): subtask spawner + sealevel e2e

- .github/workflows/agent-release-artifacts.yml
chore(ci): move agent release workflow to depot runners
- now takes ~half the time
- remove usage of legacy `larger-runner`
- use the runners from depot for faster agent release builds
- install clang as part of windows setup
| [Before](https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/12952725397/job/36130719722)         | [After](https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/14379128923)          |
|----------------|----------------|
| ![Before](https://github.com/user-attachments/assets/bb5504de-70b7-4e61-b59c-2604899cb88e) | ![After](https://github.com/user-attachments/assets/af41ee35-e5c3-4988-982b-8a1d1a5700f2) |
> chore(ci): move agent release workflow to depot runners

- rust/main/chains/hyperlane-sealevel/src/provider.rs
- rust/main/submitter/src/chain_tx_adapter/chains/sealevel/adapter.rs
- rust/main/submitter/src/chain_tx_adapter/chains/sealevel/adapter/tests/common.rs
this change had been made as part of the new submitter but introduced an alerting regression in the old submission logic
> fix(sealevel): return an error regardless of how simulation fails

- rust/main/agents/relayer/src/relayer.rs
Remove reset of critical error
Prometheus may miss critical error since it can be reset to false before the metrics are scrapped another time.
- Contributes into https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5748
Yes
None
> fix: Remove reset of critical error

- typescript/infra/config/environments/testnet4/agent.ts
- typescript/infra/config/relayer.json
feat(infra): configure testnet4-neutron-relayer for kessel runner
- kessel runner in progress
- we want to have the 3rd relayer focused purely on this, and blacklist the new testrecipients from the existing relayers to not affect regular testnet activity
> feat(infra): configure testnet4-neutron-relayer for kessel runner

- .changeset/early-cooks-wink.md
- solidity/contracts/token/extensions/HypXERC20Lockbox.sol
Use SafeERC20.safeApprove instead of IERC20.approve to approve expenditure of the wrapped token in HypXERC20Lockbox.approveLockbox(). Useful for cases such as USDT on ethereum whose `approve()` method is non-standard to regular ERC20.
ousdt staging route
> feat(core): use safeApprove in HypXERC20Lockbox.approveLockbox()

- .changeset/blue-chefs-obey.md
- typescript/infra/scripts/check/check-warp-deploy.ts
- typescript/sdk/src/router/HyperlaneRouterChecker.ts
- typescript/sdk/src/router/types.ts
- Update HyperlaneRouterChecker to verify if all remote chain Routers are enrolled in the Router on a specific chain.
- The checker will generate one violation per chain Router listing the expected and existing enrolled chains.
- check-warp-deploys.ts now prints the list of known chains sorted alphabetically
Fixes #5440
Fixes ENG-1061
This change introduces a new warp deployment check without changing other existing checks.
Manually running check-warp-deploy.ts after applying the upcoming LUMIA changes from #5842.
> feat: check for unenrolled routers on new chains

- .github/workflows/test.yml
- typescript/cosmos-sdk/.mocharc-e2e.json
- typescript/cosmos-sdk/Dockerfile
- typescript/cosmos-sdk/compose.yaml
- typescript/cosmos-sdk/eslint.config.mjs
- typescript/cosmos-sdk/package.json
- typescript/cosmos-sdk/scripts/run-e2e-test.sh
- typescript/cosmos-sdk/src/tests/1_interchain_security.e2e-test.ts
- typescript/cosmos-sdk/src/tests/2_core.e2e-test.ts
- typescript/cosmos-sdk/src/tests/3_post_dispatch.e2e-test.ts
- typescript/cosmos-sdk/src/tests/4_warp.e2e-test.ts
- typescript/cosmos-sdk/src/tests/index.e2e-test.ts
- typescript/cosmos-sdk/src/tests/utils.ts
- typescript/utils/src/validator.ts
- yarn.lock
This PR adds e2e tests for the cosmos-sdk. It spawns a local cosmos chain inside a docker container with just the Hyperlane Module installed while transactions are submitted with the cosmos-sdk. It is asserted if the transactions succeed and if there are no errors.
-
-
Yes
e2e testing
> test: add cosmos-sdk e2e tests

- rust/main/Cargo.lock
- rust/main/Cargo.toml
- rust/main/agents/relayer/src/msg/pending_message.rs
- rust/main/agents/scraper/Cargo.toml
- rust/main/agents/validator/Cargo.toml
- rust/main/agents/validator/src/settings.rs
- rust/main/hyperlane-base/Cargo.toml
- rust/main/hyperlane-base/src/settings/checkpoint_syncer.rs
- rust/main/hyperlane-base/src/types/s3_storage.rs
- rust/main/hyperlane-core/src/traits/pending_operation.rs
- rust/main/utils/abigen/src/lib.rs
- Moving to `aws-sdk-s3` instead of rusoto for all S3 operations. We still require rusoto for KMS
- Moved to a static set of S3 clients that are used globally for all anonymous S3 operations. Clients are region specific so there are some ugly types. I preferred the static set to minimize how invasive this change is
- Some context here https://hyperlaneworkspace.slack.com/archives/C08GR6PBPGT/p1744561237142619?thread_ts=1744392583.189179&cid=C08GR6PBPGT
- Web Identity support is still there despite it being deleted, see https://docs.aws.amazon.com/sdk-for-rust/latest/dg/credproviders.html and https://docs.rs/aws-config/latest/aws_config/web_identity_token/index.html#environment-variable-configuration
- sets `resolver = "2"`. This resulted in some slightly different compile warnings / …
> feat: use `aws-sdk-s3` for S3 operations

- rust/main/agents/relayer/src/msg/metadata/routing.rs
- rust/main/hyperlane-base/src/types/s3_storage.rs
adds caching via `message.origin` for routing ISM
- fixes https://linear.app/hyperlane-xyz/issue/ENG-1283/routing-ism-caching-for-the-default-ism-hyper-warp-route
Yes
None
> feat: Routing ISM caching

- rust/main/agents/relayer/src/msg/metadata/base_builder.rs
- rust/main/hyperlane-base/src/types/s3_storage.rs
Build the `checkpoint_syncer` in parallel for each validator in the `BaseMetadataBuilder`
- limits the number of concurrent requests to 10
[Linear](https://linear.app/hyperlane-xyz/issue/BACK-148/make-basemetadatabuilderbuild-checkpoint-syncer-more-concurrent)
Ran E2E tests
> feat: async checkpoint syncer builder

- .changeset/famous-taxis-dream.md
- solidity/generate-artifact-exports.mjs
- solidity/zk-hardhat.config.cts
This PR refactors the ZKsync artifact generation system and updates the Hardhat configuration:
- Refactored artifact generation code for improved maintainability
- Added validation to make sure only zksolc-compiled artifacts are processed
- Updated zksolc compiler version from 1.5.3 to 1.5.12 to speed up compilation
- Improved code organization with configuration object
- Refactored string templates to class-based static methods
- Added better error handling for artifact validation
None
Yes
Manual
> feat: Refactor ZKsync artifact generation and validation logic

- rust/main/Cargo.lock
- rust/main/agents/relayer/src/msg/metadata/aggregation.rs
- rust/main/agents/relayer/src/msg/metadata/base.rs
- rust/main/agents/relayer/src/msg/metadata/message_builder.rs
- rust/main/agents/relayer/src/msg/metadata/multisig/base.rs
- rust/main/agents/relayer/src/msg/metadata/routing.rs
- rust/main/agents/relayer/src/msg/processor.rs
- rust/main/agents/relayer/src/relayer.rs
- rust/main/agents/relayer/src/settings/mod.rs
- rust/main/chains/hyperlane-ethereum/Cargo.toml
- rust/main/chains/hyperlane-ethereum/src/rpc_clients/trait_builder.rs
- rust/main/hyperlane-base/src/cache/moka/dynamic_expiry.rs
- rust/main/hyperlane-base/src/cache/moka/mod.rs
- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/testnet4/agent.ts
- typescript/infra/src/agents/index.ts
- typescript/infra/src/config/agent/relayer.ts
- typescript/sdk/src/index.ts
- typescript/sdk/src/metadata/agentConfig.ts
- Moves away from the default ISM cache config to a vec of ISM cache configs with a selector that can match either default ISM use or a specific app context
- Motivating use case here is the testnet4 load testing doesn't actually use the default ISM. This will also allow us to cache other routes like ezETH etc that don't use the default ISM directly
- Reuses Ethereum HTTP reqwest clients instead of creating a bunch of new ones
> feat: app-context specific ISM cache configs, reuse Ethereum HTTP reqwest clients

- .changeset/dirty-gifts-grin.md
- typescript/sdk/src/metadata/chainMetadataConversion.ts
Include array of RPC urls to `chainMetadataToViemChain` function
No
Storybook
Manual
> chore: add whole RPC array to chainMetadataToViemChain

- typescript/infra/config/environments/mainnet3/igp.ts
chore: increase igp overhead to zeronetwork
- zeronetwork gas usage has changed recently and now requires another 3x multiplier on top of the ZKSync overhead.
- context https://hyperlaneworkspace.slack.com/archives/C08GHFABJQ6/p1744912056132509
> chore: increase igp overhead to zeronetwork

- rust/main/agents/relayer/src/msg/op_batch.rs
- rust/main/chains/hyperlane-ethereum/src/contracts/mailbox.rs
Add simulation back in parallel with refreshing cache so that we can see which calls to Mailbox.process failed in the batch.
Yes
Unit test with real RPC calls
> fix: Add simulation back in parallel with refreshing cache

- rust/main/chains/hyperlane-ethereum/src/contracts/mailbox.rs
- rust/main/chains/hyperlane-ethereum/src/contracts/multicall.rs
- rust/main/chains/hyperlane-ethereum/src/tx.rs
We filter out failed calls from the batch so that the batch is smaller and we don't waist resources.
Yes
Unit tests
> fix: filter out failed calls and estimate only successful calls

- rust/main/agents/relayer/src/msg/op_batch.rs
- rust/main/chains/hyperlane-ethereum/src/contracts/mailbox.rs
- rust/main/chains/hyperlane-ethereum/src/contracts/multicall.rs
- rust/main/chains/hyperlane-ethereum/src/tx.rs
Request latest block and fee history in parallel so that the latency to update cache with block number and fees is reduced. 
We filter out failed calls from the batch so that the batch is smaller and we don't waist resources.
Yes
Unit test with real RPC calls
> fix: request latest block and fee history in parallel and filter out failed calls and estimate only successful calls

- typescript/infra/config/environments/mainnet3/agent.ts
Upgrade mainnet validators to latest image 385b307-20250418-150728
Yes
Testnet
> chore: Upgrade mainnet validators to latest image

- rust/main/chains/hyperlane-ethereum/src/config.rs
- rust/main/chains/hyperlane-ethereum/src/contracts/multicall.rs
- rust/main/chains/hyperlane-ethereum/src/tx.rs
- rust/main/hyperlane-base/src/settings/parser/connection_parser.rs
- adds a gas price cap tx override
- scales down the batch gas limit to 80% of the estimate, since in practice we use no more than 65% of the estimate
e2e
> feat: gas price cap and batch gas limit optimization

- typescript/infra/config/environments/mainnet3/governance/safe/irregular.ts
- typescript/infra/config/environments/mainnet3/governance/signers/irregular.ts
- typescript/infra/config/environments/mainnet3/governance/utils.ts
- typescript/infra/src/governance.ts
- Add irregular GovernanceType and irregulare governance safe address and config for etheruem
- This is only needed for checking
`LOG_FORMAT=pretty LOG_LEVEL=debug yarn tsx ./scripts/safes/governance/check-safe-signers.ts --governanceType irregular`
Manual
> feat: add irregular safes for checking

- rust/main/agents/relayer/src/msg/metadata/aggregation.rs
- rust/main/agents/relayer/src/msg/metadata/base.rs
- rust/main/agents/relayer/src/msg/metadata/message_builder.rs
- rust/main/agents/relayer/src/msg/pending_message.rs
- rust/main/hyperlane-base/src/settings/trace/mod.rs
- typescript/infra/config/environments/test/aggregationIsm.ts
In most aggregation ISM setups, the messageIdMultisigIsm is one of the submodules. This is the fastest one to build, and if the aggregation threshold is 1, there's no need to make network calls to build metadata for the other modules.
This PR adds this "fast path" to the aggregation ISM. If it fails, we fall back to the previous behavior where all submodules are built concurrently.
Fixes the s3 sdk log silencing by matching against the log targets that show up in gcp logs
Yes
e2e with a 1/2 threshold, looking up the log `Built metadata using fast path` (28 occurrences), but it did fail 64 times
> feat: metadata building fast path

- rust/main/agents/relayer/src/msg/op_batch.rs
Restore serial submission for Sealevel and Cosmos chains.
It was removed by mistake during implementation of batch processing for Ethereum chains.
Yes
None
> fix: Restore serial submission for Sealevel and Cosmos chains

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/src/agents/index.ts
- typescript/infra/src/config/agent/relayer.ts
Deployed all the relayers
Deploys all 6 vanguard relayers to c3-standard-44 machines
Updated the other relayers to an image that's after the move to the faster s3 querying, but not anything else - just being conservative to not impact things there
> chore: mainnet vanguards

- typescript/infra/config/environments/mainnet3/agent.ts
Some chat here https://hyperlaneworkspace.slack.com/archives/C08GR6PBPGT/p1745272027027899?thread_ts=1745262374.703859&cid=C08GR6PBPGT
- Vanguards from latest main with #5990
- Other relayers before #5968 which refuses to send txs that aren't batches, which we don't want for low throughput chains
> feat: deploy vanguard relayers with new image, other relayers with older image

- rust/main/chains/hyperlane-ethereum/src/contracts/mailbox.rs
When there is a single successful operation in a batch and decide to fail the batch as a whole, currently, we will reports only failed operations. We should include the successful operation into the failed list.
Yes
None
> fix: Report all operations as failed when we are failing a batch

- rust/main/agents/relayer/src/msg/op_batch.rs
- rust/main/chains/hyperlane-ethereum/src/contracts/mailbox.rs
* Submit failed operations from a batch in a serial manner
* Allow batches to contains a single successful operation
Yes
None
> fix: Submit failed operations from a batch in a serial manner

- rust/main/Cargo.lock
- rust/main/chains/hyperlane-cosmos-native/Cargo.toml
- rust/main/chains/hyperlane-cosmos-native/src/indexers/delivery.rs
- rust/main/chains/hyperlane-cosmos-native/src/indexers/dispatch.rs
- rust/main/chains/hyperlane-cosmos-native/src/indexers/interchain_gas.rs
- rust/main/chains/hyperlane-cosmos-native/src/indexers/merkle_tree_hook.rs
- rust/main/chains/hyperlane-cosmos-native/src/ism.rs
- rust/main/chains/hyperlane-cosmos-native/src/prometheus/metrics_channel.rs
- rust/main/chains/hyperlane-cosmos-native/src/providers/rpc.rs
- rust/main/hyperlane-base/src/settings/chains.rs
- rust/main/utils/run-locally/src/cosmosnative/cli.rs
- rust/main/utils/run-locally/src/cosmosnative/mod.rs
Added new routing ism to the agents.
Decrease provider count for `cosmosnative` by implementing the Drop trait.
[Linear Issue](https://linear.app/hyperlane-xyz/issue/BACK-127/cosmosnative-relayer-routing-ism-support)
Full backwards compatibility.
Added new `RoutingIsm` to the E2E `cosmosnative` tests.
> feat(agents): cosmosnative routing ism

- typescript/infra/scripts/check/check-validator-rpcs.ts
- typescript/sdk/src/aws/s3.ts
- typescript/utils/src/types.ts
Added infra script to check public RPCs on validator sets.
Uses the `metadata_latest.json` for each validator in a given set and matches the entries against the `hyperlane-registry`. We flag every matching RPC to the registry as public.
Yes
Local testing
> feat(infra): check public validator rpc script

- rust/main/agents/relayer/src/msg/metadata/aggregation.rs
- the logic for building aggregation ISM metadata via the fast path has been cleaned up and broken into smaller functions
- previously when the fast path couldn't be used, a misleading warning about a fast path failure was printed. (An example of that is when the threshold was > 1). Since being unable to use the fast path is normal in those cases, now a debug log is printed instead
Fixes https://linear.app/hyperlane-xyz/issue/BACK-171/relayer-metadata-fast-path-change-should-be-cleaned-up-especially-the
Yes
E2E covers this
> chore(metadata): clean up aggregation fast path

- rust/main/hyperlane-base/src/traits/checkpoint_syncer.rs
- rust/main/hyperlane-base/src/types/gcs_storage.rs
- instead of defaulting to 0 when comparing checkpoint indexes, we check if its None.
- if it's None, then we write checkpoint, if not, then we do checkpoint index comparison
- remove GcsStorageClient override of `update_latest_index()`
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4260
Yes/No
None
> feat: don't default to 0 index when comparing checkpoint indexes

- .changeset/twenty-eggs-rescue.md
- typescript/cli/src/deploy/warp.ts
- typescript/infra/test/balance-alerts.test.ts
- typescript/sdk/src/consts/igp.ts
- typescript/sdk/src/contracts/contracts.ts
- typescript/sdk/src/gas/utils.ts
- typescript/sdk/src/metadata/agentConfig.ts
- typescript/sdk/src/metadata/chainMetadataTypes.ts
- typescript/sdk/src/metadata/customZodTypes.ts
feat: cosmosnative fixes
- correctly skip non-EVM chains when doing a warp apply
- adjust the `ZHash` zod regex to support cosmos addresses more explicitly
- required because setting valid cosmos addresses such as `milk1326ley07fm6rpeqgxmxevnqevrsjfew2akzupg` or `neutron1fqf5mprg3f5hytvzp3t7spmsum6rjrw80mq8zgkc0h6rxga0dtzqws3uu7` as an owner in the warp deploy config would break the schema parsing
- bring `CosmosNative` parity in more conditions where `Cosmos` protocol type exists
- don't fail balance thresholds test if an alert threshold is configured in grafana but undefined locally
- this is common when doing new chain deploys, and we should not be breaking CI for everyone else just because 1 PR adds a new chain
manual cli warp apply of the MILK/bsc-milkyway route
> feat: cosmosnative fixes

- rust/main/chains/hyperlane-cosmos-native/src/ism.rs
> fix(cosmos-native): sort sigs in ascending order by validator address

- .github/workflows/rust-docker.yml
- rust/main/chains/hyperlane-cosmos-native/src/ism.rs
- rust/main/hyperlane-base/src/types/multisig.rs
Keep the ordering of metadata signatures the same for MerkleRootMultiSig
> fix: don't change signature order in metadata

- .changeset/lovely-melons-ring.md
- typescript/cli/src/tests/warp/warp-check.e2e-test.ts
- typescript/sdk/src/block-explorer/etherscan.ts
- typescript/sdk/src/token/xerc20.ts
Updates the extra lockboxes logic to only rely on block explorers apis and skip derviation otherwise
- Removes rpc based logic to service lockboxes
- Removes e2e tests for reading on chain lockboxes 
- Manual
> feat: xERC20 extra lockboxes derivation updated logic

- .github/actions/install-cli/action.yml
- .github/workflows/release.yml
feat: rearrange release workflow
- before this change, we'd spend 10-20mins in CI waiting for the cli matrix to run before updating the release PR.
- instead what is more beneficial is only running the full CLI test matrix when we detect that we may want to publish a release.
- passthrough `github` cache-provider to the install/build action so that we use the correct cache on depot runners. currently we are using the wrong cache.
> feat: rearrange release workflow

- typescript/sdk/src/token/checker.ts
This PR adds `this.multiProvider.getChainName(chn)` to convert the each domainId in remoteRouters to a chain name to allow Checker comparison.
Yes
Manual
> fix: update Checker checkChains() to convert remoteRouter domainId to name

- typescript/infra/config/environments/mainnet3/warp/configGetters/getArbitrumBaseEthereumOptimismPolygonZeroNetworkUSDCWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getArbitrumEthereumMantleModePolygonScrollZeroNetworkUSDTWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getArbitrumEthereumSolanaTreasureSMOLWarpConfig.ts
This PR Update remoteRouter names to domainIds in Getters for zero USDC, USDT, and treasure Smol
- Resolves https://linear.app/hyperlane-xyz/issue/ENG-1278/update-configs-that-have-violations
Yes
check warp deploy script
> chore: Update remoteRouter names to domainIds in Getters 

- typescript/infra/test/warp-configs.test.ts
This PR attempts to solve the issue of updated Registry configs causing unrelated PRs config test to fail. This solution attempts to fetch the config on the `main` branch, and then failling back to `main~10` before finally failing.
Yes
> feat: Add getRegistryWithFallback to warp-configs test

- typescript/infra/fork.sh
This PR prevents the exit trap handler in `fork.sh` from failing, which causes the whole test to fail sometimes.
Yes
env-test matrix jobs in CI
> fix: make env-test script more robust

- rust/main/agents/relayer/src/msg/metadata/base.rs
the actual error message is not being printed
> fix: metadata building error message

- typescript/infra/scripts/check/check-warp-deploy.ts
Removing `DEFAULT_GITHUB_REGISTRY` from check-warp-deploy because we will update the cronjob to clone main instead. This reduces github api rate limiting 
Yes
Manual - will test by running `kubectl create job --from=cronjob/check-warp-deploy check-warp-deploy-manual-2025-04-29`
> chore: Remove DEFAULT_GITHUB_REGISTRY from check-warp-deploy

- .changeset/ten-lies-chew.md
- solidity/contracts/token/libs/MovableCollateralRouter.sol
- solidity/contracts/token/libs/ValueTransferBridge.sol
- solidity/coverage.sh
- solidity/test/token/MovableCollateralRouter.t.sol
Add abstract contract that allows a router's collateral to be moved.
N/A
N/A
Yes
Unit
> feat: Add MovableCollateralRouter

- rust/main/submitter/src/payload_dispatcher/metrics.rs
- rust/main/submitter/src/payload_dispatcher/stages/inclusion_stage.rs
- rust/main/submitter/src/payload_dispatcher/tests.rs
- rust/main/utils/run-locally/src/sealevel/termination_invariants.rs
Adds a metric that is incremented each time a transaction is submitted
Unit tests and a new sealevel E2E invariant
> feat(submitter): measure tx submissions

- .github/workflows/monorepo-docker.yml
- docker-entrypoint.sh
- typescript/infra/helm/check-warp-deploy/templates/cron-job.yaml
chore: fetch latest branch in docker-entrypoint
add docker-entrypoint as one of the conditions for running monorepo image builds
```
$ kubectl logs check-warp-deploy-pbio-zq7lk
REGISTRY_COMMIT: main
REGISTRY_URI: /hyperlane-registry
Current commit: 7a0a79942383dac2fca1fa5e5a0e57f5d8b2d3f2
Updating Hyperlane registry to: main
Previous HEAD position was 7a0a799 Update chain metadata and address files
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
HEAD is now at af29ded Update chain metadata and address files
```
> chore: fetch latest branch in docker-entrypoint

- typescript/sdk/src/providers/SmartProvider/SmartProvider.foundry-test.ts
We change the ERC20 errors messages coming back from foundry tests. The difference is caused by foundry@1.1.0 release.
No, as this only works with foundry@1.1.0.
> fix: foundry error messages after foundry@1.1.0 upgrade

- rust/main/submitter/src/error.rs
- lean on higher level retries from the MessageProcessor to avoid getting the submitter blocked on errors that are actually non-retryable
- we can look for increases in the `dropped_transactions` metric to find errors that we can classify as retryable
Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/6101
> chore(submitter): default to considering errors non-retryable

- .changeset/three-schools-happen.md
- typescript/sdk/src/index.ts
- typescript/sdk/src/token/types.ts
Export HypTokenRouterConfigMailboxOptionalSchema and HypTokenRouterConfigMailboxOptional
Yes
> chore: export HypTokenRouterConfigMailboxOptional types

- .github/actions/check-job-status/action.yml
- .github/workflows/test.yml
- rust/main/config/testnet_config.json
feat: skip typescript tests for rust-only PRs
- detect if the PR has _only_ rust changes
- if only rust changes, skip:
- yarn-test
- cli-install-test
- cli-e2e matrix
- cosmos-sdk-e2e
- coverage
- env-test matrix
context:
https://hyperlaneworkspace.slack.com/archives/C08H0T2FL2V/p1746007815024329
A second order benefit is the reduction in `ubuntu-latest` usage, which will hopefully reduce the waiting times for these runners in general
fix the current infra test diffing
https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/14753714224?pr=6084
> feat: skip typescript tests for rust-only PRs

- rust/main/agents/relayer/src/msg/op_submitter.rs
Expose operation ID as separate field on logs so that it is easier to search and the field is indexed by log consolidation tools.
Yes
None
> fix: Expose operation ID as separate field on logs

- solidity/contracts/token/HypERC20Collateral.sol
- solidity/contracts/token/extensions/FastHypERC20Collateral.sol
- solidity/contracts/token/libs/MovableCollateralRouter.sol
- solidity/test/token/HypERC20MovableCollateral.t.sol
- solidity/test/token/MovableCollateralRouter.t.sol
Since HypERC20Collateral is an upgradeable contract, we can't use constructors to set storage. Here we add an initializer function to `MovableCollateralRouter` and call it in the initializer of `HypERC20Collateral`. 
We've also changed the initializer function on `HypERC20Collateral` to have a modifier of `reinitializer(2)` meaning that it can be called two times. This allows us to call `initialize` again on all existing instances of `HypERC20Collateral`.
Yes
Unit
> fix: Add initializer for MovableCollateralRouter

- typescript/infra/src/agents/key-utils.ts
- typescript/infra/test/warp-configs.test.ts
- Starts persisting key addresses in GCP again, fixing key funder infra
- Regression introduced in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3159/files#diff-604c29d425429647a37bc7b46d72cfddb8f5ba0c40d81609234c36bb2a203b35L372 ages ago, just never realized because we didn't add new keys
> fix: persist key addresses in GCP

- .changeset/short-suns-shop.md
- solidity/contracts/middleware/InterchainAccountRouter.sol
- solidity/test/InterchainAccountRouter.t.sol
- typescript/infra/config/environments/mainnet3/owners.ts
- typescript/infra/src/govern/HyperlaneAppGovernor.ts
- typescript/infra/src/govern/HyperlaneICAChecker.ts
- typescript/sdk/src/core/EvmCoreModule.ts
- typescript/sdk/src/core/EvmIcaModule.ts
- typescript/sdk/src/ica/EvmIcaReader.hardhat-test.ts
- typescript/sdk/src/ica/EvmIcaReader.ts
- typescript/sdk/src/ica/types.ts
- typescript/sdk/src/middleware/account/InterchainAccount.ts
- typescript/sdk/src/middleware/account/InterchainAccountChecker.ts
- typescript/sdk/src/middleware/account/InterchainAccountDeployer.ts
- typescript/sdk/src/middleware/account/contracts.ts
- Remove account owners reverse mapping
- Update` InterchainAccountCreated` event for reverse mapping purpose
- Use CREATE2 for constructor implementation deploy
- Do not proxy ICA routers
No
Unit Tests
> feat: optimize `InterchainAccountRouter.handle` proxy deployment

- .changeset/wise-files-listen.md
- typescript/cli/src/tests/commands/helpers.ts
- typescript/cli/src/tests/warp/warp-apply.e2e-test.ts
- typescript/sdk/src/deploy/proxy.ts
Updates the proxy admin ownership management logic to default to the warp route owner if no proxy admin config is specified 
- None
- YES
- Manual
- e2e
> fix(sdk): fix warp apply proxy onwership logic [eng-1399]

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/mainnet3/funding.ts
chore: spin down vanguard0
- update hyperlane image tag to latest `main` build
- remove vanguard blacklisting
- remove vanguard from keyfunder config
- add `ontology` to keyfunder `chainsToSkip`, as we have not received funding for deploying on that chain yet
> chore: spin down vanguard0

- typescript/cli/src/tests/warp/warp-check.e2e-test.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.ts
- typescript/sdk/src/token/configUtils.ts
This PR fixes a bug in the warp reader that assumed that all warp routes are deployed as proxies when it doesn't seem to be the case, which resulted in the on-chain config derivation failing because the `.owner` field was called on the 0 address when deriving the proxy admin config 
- None
- [ENG-1551](https://linear.app/hyperlane-xyz/issue/ENG-1551/fix-warp-checker-reader-trying-to-derive-info-from-the-0-address)
- YES
- Manual
- unit
- e2e
> fix(sdk, cli): fix cli sdk trying to derive configs from 0 address [eng-1551]

- solidity/contracts/mock/MockValueTransferBridge.sol
- typescript/cli/src/tests/commands/helpers.ts
- typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/44
Includes https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/6087
Adds an e2e test that listens to the event emitted by the mocked value transfer bridge and performs an actual transfer to achieve balance
> fix: Add E2E test with mocked bridge

- .github/workflows/static-analysis.yml
Some PRs can't be merged because of Olympix: https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/14795023230/job/41540106815?pr=6097
> fix: Remove Olympix from github actions - Update static-analysis.yml

- rust/sealevel/programs/build-programs.sh
- rust/sealevel/programs/install-solana-1.14.20.sh
Solana CLI releases were migrated from https://release.solana.com to https://release.anza.xyz, but along the way some old versions weren't ported over. This includes 1.14.20, which is the version we require to build the programs.
A couple alternatives were considered (trying to use brew to find an older version, more directly querying github, etc), but in the end I think the best approach is to just try to emulate their old installation script and make sure that it fetches from the right github release.
This PR adds the installation script adapted from https://release.anza.xyz/v1.18.18/install with the following changes:
- The version is hardcoded to 1.14.20
- The URL is hardcoded to read from the old solana-labs repo
- All agave references are replaced with solana
It also moves away from …
> fix: build-programs.sh downloading newer solana CLI releases and the old 1.14.20 version

- rust/main/chains/hyperlane-ethereum/src/rpc_clients/provider.rs
- rust/main/submitter/src/chain_tx_adapter/chains/ethereum/adapter.rs
- rust/main/submitter/src/chain_tx_adapter/chains/ethereum/adapter/gas_limit_estimator.rs
- rust/main/submitter/src/chain_tx_adapter/chains/ethereum/adapter/tx_status_checker.rs
- rust/main/submitter/src/chain_tx_adapter/chains/ethereum/transaction/precursor.rs
Implement `GasLimitEstimator` component, by refactoring logic out of `rust/main/chains/hyperlane-ethereum/src/tx.rs`
- The logic for the `TxStatusChecker` and `GasLimitEstimator` is moved into their own modules. The motivation is to use dependency injection for ease of testing in the future
- The logic for building a `ContractCall` from its subcomponent fields is refactored and reused
- Fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/6134
Yes
Not yet
> feat(submitter): evm GasLimitEstimator

- rust/main/agents/relayer/src/msg/op_batch.rs
- rust/main/agents/relayer/src/msg/pending_message.rs
- rust/main/agents/relayer/src/msg/processor.rs
- rust/main/agents/relayer/src/test_utils/dummy_data.rs
- rust/main/agents/relayer/src/test_utils/mod.rs
Fix message status not being stored correctly.
Turns out, instead of storing the new message status, we store the old message status,
but set it to the new message status in memory.
- fixes: https://linear.app/hyperlane-xyz/issue/ENG-1024/bug-relayer-messages-are-loaded-with-the-wrong-operation-status-from
- move some dummy test code to be public so other tests can also use them
Yes
- added a test with a temp dir rocksdb to make sure `PendingMessage.set_status()` works as expected
> feat: fix message status not being stored correctly

- typescript/cli/src/commands/warp.ts
- typescript/cli/src/tests/commands/warp.ts
- typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
This PR adds tests for the Metrics module in the CLI warp rebalancer command.
Ensures that Metrics are correctly enabled by flag
Fixes https://github.com/BootNodeDev/hyperlane-monorepo/issues/45
Yes
> test(metrics): rebalancer metrics

- .changeset/loose-numbers-tease.md
- typescript/cli/package.json
- typescript/helloworld/package.json
- typescript/infra/package.json
- typescript/infra/scripts/warp-routes/export-warp-configs.ts
- typescript/widgets/package.json
- yarn.lock
Upgraded `@hyperlane-xyz/registry` from v11.1.0 to v14.0.0 across multiple packages and updated warp route config API usage to match the new version requirements.
None
https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/5244
Yes
Manual
> feat: update registry to 14.0.0

- .changeset/little-houses-crash.md
- .changeset/loose-numbers-tease.md
- typescript/cli/package.json
- typescript/cli/src/commands/config.ts
- typescript/cli/src/commands/warp.ts
- typescript/cli/src/config/warp.ts
- typescript/cli/src/context/types.ts
- typescript/cli/src/deploy/warp.ts
- typescript/cli/src/utils/warp.ts
- typescript/helloworld/package.json
- typescript/infra/package.json
- typescript/infra/scripts/warp-routes/export-warp-configs.ts
- typescript/widgets/package.json
- yarn.lock
This PR refactors the warp route configuration functions to use object parameters instead of positional parameters, improving API clarity and flexibility. The main changes include:
- Modified `readWarpRouteDeployConfig` to accept an object parameter with named properties
- Updated `readWarpCoreConfig` with similar parameter style changes
- Added utility functions for handling warp route configuration in various scenarios
- Enhanced context types with warp configuration properties
- Added new `getWarpRouteDeployConfig` utility function
- Added `useProvidedWarpRouteIdOrPrompt` helper function
- Improved error messaging and assertions
Diff with last PR:
https://github.com/hyperlane-xyz/hyperlane-monorepo/compare/upgrade/registry-14.0.0...refactor/warp-config-loading …
> refactor: warp config loading

- solidity/contracts/isms/routing/InterchainAccountIsm.sol
- solidity/contracts/middleware/InterchainAccountRouter.sol
- solidity/contracts/middleware/libs/InterchainAccountMessage.sol
- solidity/test/InterchainAccountRouter.t.sol
You can now make shielded calls using ICAs. We use a [commit/reveal](https://en.wikipedia.org/wiki/Commitment_scheme) scheme where the first message is a commitment, and the second message is a reveal. The commitment message looks like 
```solidity
struct {
address owner;
address ism;
bytes32 salt;
bytes32 commitment;
}
```
The commitment is `hash(bytes32 salt, Call[] calls)`. 
The reveal message looks like 
```solidity
struct {
address offChainLookupIsm;
bytes32 commitment;
}
```
The offChainLookupIsm will contain the urls that a relayer must query to retrieve the calls/salt given the commitment. The relayer will pass the retrieved calls/salt to this ism as **metadata**, and the ism will verify if the salt/calls match the commitment. For more, see #6069 and the [CCIP …
> feat: Support commitments in ICA messages

- rust/main/agents/scraper/src/db/message.rs
- rust/main/helm/hyperlane-agent/templates/relayer-statefulset.yaml
- rust/main/helm/hyperlane-agent/templates/scraper-statefulset.yaml
- rust/main/helm/hyperlane-agent/templates/validator-statefulset.yaml
Instead of inserting all the messages we receive in a single db transaction, we chunk it into smaller sizes.
This prevents us from running into `Too many arguments` errors from Postgres for exceeding their `u16::MAX` parameter count.
- fixes https://linear.app/hyperlane-xyz/issue/ENG-1390/scraper-cannot-insert-too-many-records
Yes
Manual. From Jeff:
Tried it locally with a postgres instance with 100k messages and it failed without chunking 
```
running 1 test
RES: Err(Query Error: encountered unexpected or invalid data: PgConnection::run(): too many arguments for query: 1000000 (sqlx_postgres::connection::executor:215)
Caused by:
0: encountered unexpected or invalid data: PgConnection::run(): too many arguments for query: 1000000 (sqlx_postgres::connection::executor:215)
1: encountered …
```
> feat: chunk message db insertions

- rust/main/chains/hyperlane-ethereum/src/rpc_clients/provider.rs
- rust/main/chains/hyperlane-ethereum/src/rpc_clients/trait_builder.rs
**When reviewing, make double sure the changes in `build_with_signer` make sense, otherwise this can break prod**
Since the new submitter has its own logic for setting tx parameters, so ethers middleware like the gas escalator, nonce manager, etc isn't required. This PR makes the usage of middleware configurable, via an associated const in `BuildableWithProvider` that defaults to `true`. This const is only ever used if `NEEDS_SIGNER` is `true`
Cleans up the provider-building logic in `build_with_signer`
- Fixes: https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/6163
**Yes - but make double sure the changes in `build_with_signer` make sense, otherwise this can break prod**
EVM E2E
> fix(submitter): don't use ethers submission middleware

- typescript/cli/src/rebalancer/executor/Executor.ts
- typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
This allows verifying that all rebalance transactions can be executed before sending them, helping prevent incomplete rebalances caused by a failure in any transaction within the batch.
> fix: Estimate gas before sending rebalance transactions

- docker-entrypoint.sh
Re-add registry commit to `git fetch origin` in docker-entrypoint.sh
> fix: re-add registry commit to docker entry

- typescript/cli/src/commands/warp.ts
- typescript/cli/src/deploy/warp.ts
- typescript/sdk/src/deploy/verify/ContractVerifier.ts
- typescript/sdk/src/deploy/verify/types.ts
- typescript/sdk/src/index.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.ts
- typescript/sdk/src/token/configUtils.ts
- typescript/sdk/src/token/types.ts
- Reworked ContractVerifer.getContractVerificationStatus() to output a status instead of boolean. This allows more granular statuses for statuses such as `Skipped`.
- Update derive contract status to no longer include the actual token contract name and to instead just say `Implementation`. This reduces code complexity and can be featured in later, if needed.
- Add `HypTokenRouterVirtualConfigSchema` to `HypTokenRouterConfigMailboxOptionalSchema`
Manual
> feat(rework): cli warp check should assert that contracts are verified

- typescript/cli/src/commands/warp.ts
- typescript/cli/src/rebalancer/factories/RebalancerContextFactory.ts
- typescript/cli/src/rebalancer/interfaces/IStrategy.ts
- typescript/cli/src/rebalancer/interfaces/ITransformer.ts
- typescript/cli/src/rebalancer/transformers/MonitorToStrategyTransformer.ts
Previous implementation was allowing tokens that could not be rebalanced
> fix: Only rebalance EvmHypCollateralAdapter tokens

- typescript/infra/scripts/warp-routes/monitor/metrics.ts
- typescript/infra/scripts/warp-routes/monitor/monitor-warp-route-balances.ts
Given that these scripts have the warpRouteId already at some point (used to fetch the warpCore), we pass it through each function instead of using createWarpRouteConfigId() with warpCore
Yes - should not change any existing functionality
> feat: Remove createWarpRouteConfigId() from metrics.ts and monitor-warp-route-balances.ts

- rust/main/agents/relayer/src/msg/metadata/ccip_read/mod.rs
- add a 30s timeout on CCIP read requests
- add a regex to prevent localhost, or local IP address requests
- https://linear.app/hyperlane-xyz/issue/ENG-1614/relayer-ccip-read-dos-vector-potential-security-concerns
Yes
Add unit test to ensure regex is correct
> feat: reduce ccip read dos vector

- .changeset/orange-women-show.md
- typescript/cli/src/deploy/warp.ts
- typescript/sdk/src/deploy/warp.ts
- typescript/sdk/src/index.ts
- Move logic from `executeDeploy` that was in the `CLI` to the `SDK`, now this function is named `executeWarpDeploy`
- Instead of using the CLI context, the function will receive the parameters
No
fix #6138 
Yes
Manual local test
> chore: move executeDeploy logic from CLI to SDK

- .changeset/giant-animals-boil.md
- typescript/cli/src/config/warp.ts
- typescript/cli/src/utils/warp.ts
Fixed warp route ID lookup to use deployment configs instead of warp routes when prompting users for selection on warp deployment.
None
N/A
Yes - This change only affects the user selection prompt behavior and doesn't impact infrastructure compatibility.
Manual testing of the warp route ID selection workflow
> fix: warp route id lookup source

- typescript/cli/.mocharc.json
- typescript/cli/src/commands/warp.ts
- typescript/cli/src/rebalancer/executor/Executor.ts
- typescript/cli/src/rebalancer/factories/RebalancerContextFactory.ts
- typescript/cli/src/rebalancer/monitor/Monitor.ts
- typescript/cli/src/rebalancer/strategy/BaseStrategy.ts
- typescript/cli/src/tests/test-setup.ts
- typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
Add logs in different parts of the rebalancing flow
Also prevents from logging in the middle of the `test:ci` tests if the user sets `NODE_ENV=test`
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/51
> chore: add logs to the rebalancer flow

- solidity/package.json
By default we decode internal calls in our foundry tests. This is great for debugging! See these [Foundry v1.0 release notes](https://www.paradigm.xyz/2025/02/announcing-foundry-v1-0) for more.
> feat: Decode internal calls in forge tests

- solidity/contracts/isms/ccip-read/CommitmentReadIsm.sol
- solidity/contracts/middleware/InterchainAccountRouter.sol
- solidity/contracts/middleware/libs/OwnableMulticall.sol
- solidity/test/InterchainAccountRouter.t.sol
The commitment is simply `hash(salt, calls)`. 
- Remove redundant checks on revealed data
- Move check on existing commitment into ICA.
> fix(ICA): Remove ica from commitment 

- typescript/infra/scripts/warp-routes/monitor/monitor-warp-route-balances.ts
- When we extended the oUSDT route, we changed the token standards (`EvmHypXERC20Lockbox` => `EvmHypVSXERC20Lockbox`,  `EvmHypXERC20` => `EvmHypVSXERC20`).
- This was a change that is an accurate representation of the tokens.
- This PR introduces support for these token standards in the monitoring service 
Yes
Manual
> feat: Support VSXERC20 token standard in warp monitor

- typescript/cli/src/rebalancer/config/Config.test.ts
- typescript/cli/src/rebalancer/config/Config.ts
- typescript/cli/src/rebalancer/executor/Executor.ts
- typescript/cli/src/rebalancer/factories/RebalancerContextFactory.ts
- typescript/cli/src/rebalancer/utils/bridgeConfig.test.ts
- typescript/cli/src/rebalancer/utils/bridgeConfig.ts
Adds an `override` key to the chain config where bridge-specific props can be overriden based on the chain.
So, given the following scenario:
```ts
chain1: {
bridge: '0x123',
overrides: {
chain2: {
bridge: '0x222', 
}
}
}
````
When trying to bridge from `chain1` to `chain2`, brdige `0x222` will be used, while in the other cases will be `0x123`
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/61
Yes
> feat: bridge route-based overrides

- .github/workflows/monorepo-docker.yml
- .github/workflows/rust-docker.yml
- README.md
chore: default to only amd64 docker builds
- default agent/monorepo images are only for amd64
- this saves time, cost of each image build
- if required for local runs, devs can manually trigger the workflow and say they want an arm64 build
- allowing manual runs also means that you don't need to have a PR open just to trigger image builds anymore
> chore: default to only amd64 docker builds

- typescript/infra/scripts/validators/print-latest-checkpoints.ts
chore: update print-latest-checkpoints to support all chains
tested with forma, which is not in the core supported chains list but we can read checkpoints for now!
> chore: update print-latest-checkpoints to support all chains

- starknet/package.json
fix: add repository to starknet package.json
- fixes https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/15112270943/job/42478647721#step:5:759
- matches cosmos-sdk/cosmos-types/sdk/utils packages
```
error an error occurred while publishing @hyperlane-xyz/starknet-core: E422 422 Unprocessable Entity - PUT https://registry.npmjs.org/@hyperlane-xyz%2fstarknet-core - Error verifying sigstore provenance bundle: Failed to validate repository information: package.json: "repository.url" is "", expected to match "https://github.com/hyperlane-xyz/hyperlane-monorepo" from provenance 
```
> fix: add repository to starknet package.json

- typescript/cli/src/rebalancer/config/Config.test.ts
- typescript/cli/src/rebalancer/config/Config.ts
- typescript/cli/src/rebalancer/executor/WithSemaphore.test.ts
- typescript/cli/src/rebalancer/executor/WithSemaphore.ts
- typescript/cli/src/rebalancer/strategy/StrategyFactory.test.ts
- typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
A semantic change. That is not backwards compatible.
No
> refactor: rename `bridgeTolerance` to `bridgeLockTime`

- .changeset/beige-falcons-brake.md
- solidity/contracts/client/MailboxClient.sol
- solidity/contracts/isms/ccip-read/AbstractCcipReadIsm.sol
- solidity/contracts/isms/ccip-read/CommitmentReadIsm.sol
- solidity/contracts/isms/ccip-read/TestCccipReadIsm.sol
- solidity/contracts/isms/hook/OPL2ToL1CcipReadIsm.sol
- solidity/contracts/middleware/InterchainAccountRouter.sol
- solidity/contracts/test/TestCcipReadIsm.sol
- solidity/contracts/token/TokenBridgeCctp.sol
- solidity/script/TokenBridgeScript.s.sol
- solidity/test/InterchainAccountRouter.t.sol
- solidity/test/isms/CommitmentReadIsm.t.sol
- solidity/test/isms/OPL2ToL1CcipReadIsm.t.sol
- solidity/test/token/OPL2ToL1TokenBridgeNative.t.sol
- solidity/test/token/TokenBridgeCctp.t.sol
- Enables overriding `MailboxClient.interchainSecurityModule` to avoid unnecessary SLOAD
- Pulls URL config into shared contract
- Shares event revert and mailbox process logic
No
Unit Tests
> refactor: simplify ccip read ISM

- solidity/contracts/isms/ccip-read/CommitmentReadIsm.sol
We need to pass through the whole message, so that we can determine the message ID for the reveal message that we can associated with the calls that were posted, otherwise it is not possible to determine which ICA needs to be passed in the metadata
> feat: Pass the whole message through commitment read ism

- rust/main/submitter/src/chain_tx_adapter/chains/ethereum/adapter.rs
- rust/main/submitter/src/chain_tx_adapter/chains/ethereum/nonce/manager.rs
Avoid holding lock on nonce manager with a remote call.
Now we are using internal mutability to update the number of non finalized transactions in nonce manager
Yes
None
> fix: Avoid holding lock on nonce manager with a remote call

- Dockerfile
- rust/Dockerfile
chore: depot docker recommendations
- update dockerfiles based on the depot recommendations
> chore: depot docker recommendations

- typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
Tests don't fail in some occasions because collateral contracts from different chain might have the same address.
Also interpolating some previously hard-coded expected values.
> fix: Fix e2e destinations

- rust/main/Cargo.lock
- rust/main/Cargo.toml
- rust/sealevel/Cargo.lock
- rust/sealevel/Cargo.toml
Scraper is failing to index some message dispatches due to obsolete Solana SDK we are using. We pinned the dependency version to 1.14.13. Since then enum `TransactionError` added a few enum invariants. New tag of the Solana SDK dependencies brings these invariants from upstream.
Yes
Tested with experimental image
> fix: Scraper: Fix issue with missing enum invariant for Sealevel

- .github/workflows/release.yml
- typescript/infra/src/agents/gcp.ts
chore: reduce release-e2e-matrix frequency
- previously we would run the release cli test matrix if there were no changesets
- no changesets _implied_ that a release is to be done, but in cases where packages are published but no new publishable changes have landed yet - we're still churning through these tests for no good reason
- this PR changes the behaviour such that we always try and do prepare-release so that the Changesets PR is updated, but we also in parallel check if the _current_ package versions are published and only run the tests if we detect that there are packages that need to be published
tested here https://github.com/hyperlane-xyz/hyperlane-monorepo/actions/runs/15161126534
> chore: reduce release-e2e-matrix frequency

- rust/main/submitter/src/chain_tx_adapter/chains/ethereum/adapter/gas_price_estimator.rs
- rust/main/utils/run-locally/src/main.rs
Required fields on EVM transaction are overwritten when we estimate gas price in EVM adapter for Lander. It means that these fields are not set when transaction is submitted into a chain.
This change ensures that all the required fields are copied from old transaction to the new one during gas price estimations.
E2E tests do not pass with fields set, so, we use classical submitter for the time being.
Yes
E2E test
> fix(submitter): Fix transaction fields

- .changeset/crazy-walls-bathe.md
- typescript/cli/src/context/strategies/signer/MultiProtocolSignerManager.ts
This PR only inits Ethereum signers and temporary reverts the changes made in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/6124. This is necessary, since Cosmos Signers are being initialized with an Eth private key in some circumstances which throw an error. The cosmos signers should therefore be disabled until a solution has been found to manage multi-vm signer intializations.
-
-
Yes
Manual Tests
> fix: disable cosmos signers for now

- .changeset/odd-glasses-spend.md
- typescript/cli/src/context/strategies/signer/MultiProtocolSignerManager.ts
chore: reduce logging of extractPrivateKey
> chore: change extractPrivateKey info logs to debug logs

- rust/main/config/testnet_config.json
Make Solana testnet chunk same as for mainnet
Yes
Manual
> fix: Make Solana testnet chunk same as for mainnet

- .github/workflows/rust.yml
- .github/workflows/test.yml
chore: trigger release PR testing automatically
Currently due to the nature of the changesets bot, it requires closing/reopening the release PR to trigger the tests for CI to run. Hoping that enabling this will cause CI to automatically run on the release PR branch
> chore: trigger release PR testing automatically

- .github/workflows/release.yml
feat: publish with github-hosted runner
fixes
```
Error verifying sigstore provenance bundle: Unsupported GitHub Actions runner environment: "self-hosted". Only "github-hosted" runners are supported when publishing with provenance.
```
> feat: publish with github-hosted runner

- typescript/cli/package.json
- yarn.lock
We bring back the missing tsconfig dependency that was lost in an urgent revert.
Part of ENG-1668
Yes
The CLI build works.
> fix: add missing tsconfig dep after revert

- typescript/infra/scripts/check/check-utils.ts
This PR addresses the issue of when there are no warp deploy config by exit(0)
Yes/No
-->
> chore: Add .catch() for cases when there are no warp deploy config

- rust/main/agents/scraper/src/store/storage.rs
- rust/main/chains/hyperlane-cosmos-native/src/indexers/indexer.rs
- rust/main/chains/hyperlane-cosmos-native/src/providers/cosmos.rs
Added block event indexing for cosmos. Block events are special in the sense that they do not have any TX Hash. This will result in the scraper not finding the given events, however, the relayer & validator do.
Local E2E Testing
> feat: cosmos block events

- typescript/infra/scripts/agents/deploy-agents.ts
- typescript/infra/scripts/funding/deploy-key-funder.ts
- typescript/infra/src/utils/gcloud.ts
- typescript/infra/src/utils/helm.ts
feat: check tag exists before deploying agents
- helpers for checking an agent/monorepo image exist
- integrate with agents/keyfunder deploy scripts
> feat: check tag exists before deploying agents

- rust/main/chains/hyperlane-ethereum/src/contracts/multicall.rs
To improve TGE day throughput, we scaled down batch gas limit estimate by 0.8x so we can fit more messages in a block, since hyperchains significantly overestimate gas. Also as part of those changes, we started allowing single-message batches, to simplify the submission flow and keep latency low.
One consequence this has had is a delivery [tx](https://explorer.metall2.com/tx/0x101b4ab2c4598b36471fff88ba5bf0bb98f0292ef5e7e73fcd0a9639632e77b1) that ran out of gas to `metal` chain, where the gas estimate was rather accurate. The tx was a single-message batch - there were supposed to be 2 messages in the batch, but one of them failed simulation: https://cloudlogging.app.goo.gl/J3D6Ga2vyyxTA9q77
We no longer to maximize messages sent per block for now, so I'm setting the batch gas limit back …
> chore: set batch gas limit multiplier back to 1x

- typescript/sdk/src/ism/StarknetIsmReader.ts
This PR fixes the read method for the starknet pausable ISM
-
-
Yes
Manual testing
> fix: pausable owner

- .changeset/tasty-turtles-clap.md
- typescript/cli/package.json
- typescript/helloworld/package.json
- typescript/infra/package.json
- typescript/widgets/package.json
- yarn.lock
This pull request updates the `@hyperlane-xyz/registry` dependency across multiple packages to version `15.10.1` and includes a patch to remove the throw from `addWarpRouteConfig`
Yes, the only impacting update is to removing throw from addWarpRouteConfig(). This function is directly called in  `export-warp-configs.ts` and `warp init`
Manual
> chore: Bump Registry to version 15.10.1

- typescript/cli/src/commands/warp.ts
- typescript/cli/src/rebalancer/utils/getRawBalances.test.ts
- typescript/cli/src/rebalancer/utils/getRawBalances.ts
- typescript/cli/src/tests/commands/warp.ts
- typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
Closes https://github.com/BootNodeDev/hyperlane-monorepo/issues/72
This allows the user to rebalance partially between some of the collaterals of a warp route. For example, if there is no working bridge on a certain chain that supports rebalancing.
> feat: Ignore from rebalancing tokens that are not defined in the config

- typescript/cli/src/commands/warp.ts
- typescript/cli/src/rebalancer/config/Config.test.ts
- typescript/cli/src/rebalancer/config/Config.ts
- typescript/cli/src/rebalancer/executor/Executor.ts
- typescript/cli/src/rebalancer/factories/RebalancerContextFactory.ts
This PR changes the Executor to use `handleTx` instead of ethers' `wait` directly.
Also,
- removed `rebalancerKey` from Config and related components
- removed `registry` and extracted it from context
Fixes https://github.com/BootNodeDev/hyperlane-monorepo/issues/65
Yes
Unit/e2e
> refactor(signer): use handleTx instead of ethers directly

- .changeset/shy-ideas-win.md
- typescript/cli/src/context/context.ts
chore(cli): only prompt for API key for etherscan explorer type
before:
after:
> chore(cli): only prompt for API key for etherscan explorer type

- typescript/infra/scripts/check/check-warp-deploy.ts
fix(infra): filter out testnets for check-warp-deploy
> fix(infra): filter out testnets for check-warp-deploy

- starknet/scripts/fetch-contracts-release.sh
- typescript/sdk/src/core/StarknetCoreModule.ts
- typescript/sdk/src/token/nativeTokenMetadata.ts
- switched protocol fee to be default and merkle to be required for legal reasons. (we should avoid charging non-zero protocol fee payment as advised by the lawyers)
- changed native token from ETH to STRK bc ETH will not be supported after June
- v0.3.8 -> v0.3.9 of starknet contracts (now on main :) )
None
Yes
Live deployment
> feat(sdk): switch starknet hooks config

- .changeset/chubby-apes-travel.md
- solidity/package.json
- typescript/ccip-server/package.json
- typescript/cli/package.json
- typescript/helloworld/package.json
- typescript/infra/package.json
- typescript/sdk/package.json
- typescript/utils/package.json
- yarn.lock
chore: update to ethers v5.8.0
- https://github.com/ethers-io/ethers.js/releases/tag/v5.8.0
> chore: update to ethers v5.8.0

- rust/sealevel/environments/mainnet3/warp-routes/tUSD-eclipsemainnet-ethereum/token-config.json
This PR transfers tUSD warp route to Nucleus owners
Yes
> chore: transfer tUSD warp route ownership

- rust/main/config/testnet_config.json
Reduce chunk size to avoid RPC errors
Yes
Manual
> fix: Reduce chunk size to avoid RPC errors

- rust/main/Cargo.lock
- rust/main/Cargo.toml
- rust/main/hyperlane-base/src/settings/signers.rs
- Updates ethers-rs to https://github.com/hyperlane-xyz/ethers-rs/releases/tag/2025-05-30, which includes setting a timeout on the AwsSigner
- 30s was chosen because we've seemingly only experienced this once, so it's very infrequent, and high enough to not hit false positives on a timeout
> feat: add timeout to AwsSigner

- typescript/sdk/src/core/StarknetCoreModule.ts
- typescript/sdk/src/deploy/StarknetDeployer.ts
- typescript/sdk/src/token/nativeTokenMetadata.ts
- now setting the routes in the domain_routing_ism in one transaction
- add a mapping as a overrides for different starknet chains as paradex and starknet doesn't support the same token as protocol fee
none
none
yes
manual
> feat(sdk): add single tx set route to `StarknetDeployer.deployIsm`

- typescript/cli/src/commands/warp.ts
- typescript/cli/src/rebalancer/factories/RebalancerContextFactory.ts
- typescript/cli/src/rebalancer/metrics/Metrics.ts
- typescript/cli/src/rebalancer/metrics/PriceGetter.ts
- typescript/cli/src/rebalancer/metrics/scripts/metrics.ts
- typescript/cli/src/rebalancer/monitor/Monitor.ts
- typescript/cli/src/rebalancer/rebalancer/Rebalancer.ts
- typescript/cli/src/rebalancer/rebalancer/WithSemaphore.ts
- typescript/cli/src/rebalancer/strategy/BaseStrategy.ts
- typescript/cli/src/rebalancer/strategy/MinAmountStrategy.ts
- typescript/cli/src/rebalancer/strategy/StrategyFactory.ts
- typescript/cli/src/rebalancer/strategy/WeightedStrategy.ts
- typescript/cli/src/rebalancer/utils/getRawBalances.ts
- typescript/cli/src/rebalancer/utils/logger.ts
- typescript/cli/src/rebalancer/utils/tryFn.ts
- typescript/cli/src/tests/commands/warp.ts
- typescript/cli/src/tests/warp/warp-rebalancer.e2e-test.ts
- typescript/infra/helm/rebalancer/templates/_helpers.tpl
- typescript/infra/src/rebalancer/helm.ts
- Expose metrics for ongoing rebalancing
- Use structured logging
- Split start up and on going execution into separate try catch blocks, throw on startup errors and do not throw on execution errors. 
- Set `withMetrics` to default false
Yes
- Unit Tests
- e2e tests
> feat: Collect operational metrics for rebalancer

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/testnet4/agent.ts
- typescript/infra/scripts/agents/utils.ts
- typescript/infra/src/agents/index.ts
- typescript/infra/src/infrastructure/external-secrets/external-secrets.ts
- Updates all testnet4 relayer / validator agents (except for testnet4 neutron relayer)
- Adds concurrency of 10 to external-secrets, so it can update 10 secrets concurrently instead of the default of 1
- Removes unnecessary chains from validator external-secrets templates, cutting down on the work that external-secrets needs to do
- Makes it a bit safer to work with the external-secrets helm chart
> feat: deploy agents, faster external-secrets

- rust/main/hyperlane-base/src/contract_sync/cursors/sequence_aware/backward.rs
- rust/main/hyperlane-base/src/contract_sync/cursors/sequence_aware/mod.rs
It will allow us to set the lowest block height for sequence-aware backward cursor and avoid errors when chain RPC does not provide historical blocks.
- Fixes https://linear.app/hyperlane-xyz/issue/ENG-1727/configurable-lower-block-height-limit-to-index-for-sequence-aware
Yes
Unit tests and manual
> feat: Add configurable lowest block height to sequence-aware backward cursor

- typescript/infra/config/environments/mainnet3/aw-validators/rc.json
- typescript/infra/config/environments/mainnet3/validators.ts
- typescript/infra/scripts/agent-utils.ts
chore: loosen validator consistency check on non-hyperlane contexts
previously when trying to do create keys in the RC context we'd get a validator inconsistency warning. This is due to the fact we check that all chains have a validator configured in a context.
However! We only want to enforce this on `hyperlane`, as RC/Neutron context validators are not mandatory and only spun up for testing.
- make it pretty
- add hyperevm rc validator address
before:
after:
> chore: loosen validator consistency check on non-hyperlane contexts

- rust/main/agents/validator/src/validator.rs
- Observed with Starknet, this is a fix for what we theorize the issue is
> fix: validator count fetching upon startup is retried

- solidity/contracts/isms/hook/OPL2ToL1CcipReadIsm.sol
- solidity/contracts/libs/OPL2ToL1Withdrawal.sol
- solidity/contracts/mock/MockOptimism.sol
- solidity/contracts/token/extensions/OPL2ToL1TokenBridgeNative.sol
- solidity/test/isms/OPL2ToL1CcipReadIsm.t.sol
- Enforces that the prove message is processed IFF the corresponding withdrawal is proven
- Enforces that the finalize message is processed IFF the corresponding withdrawal is finalized
Note that it is still possible for the withdrawal to be proven and finalized by another actor. In this case the messages will verify this status and then be marked as delivered.
Yes
Unit Tests
> fix: check OP withdrawal tx matches hyperlane messages

- typescript/cli/src/check/warp.ts
- typescript/cli/src/tests/warp/warp-check.e2e-test.ts
- typescript/cli/src/tests/warp/warp-deploy.e2e-test.ts
- typescript/sdk/src/index.ts
- typescript/sdk/src/token/TokenMetadataMap.ts
- typescript/sdk/src/token/types.ts
- typescript/sdk/src/utils/decimals.ts
This PR adds a check to `warp check` CLI verifying that decimals are consistent and have the correct scale if not.
#5173
Yes
Two E2E tests checking for missing and incorrect scale, when decimals are not consistent.
> chore: verify decimals & scale

- typescript/infra/config/environments/mainnet3/agent.ts
- To include #6470
- Only deployed Starknet
- Updates some Velo app context addresses
> chore: deploy new starknet validator

- typescript/sdk/hardhat.config.cts
Bump the sdk's solc version. 
Perhaps a shared configuration could be used across the `typescript/` and `solidity/` directories? There's already a `rootHardhatConfig` in `solidity/`.
> refactor(sdk): Use solidity version 0.8.22 in hardhat

- solidity/contracts/token/TokenBridgeCctp.sol
- solidity/test/token/TokenBridgeCctp.t.sol
For safety, we want to make sure that each contract only has one initializer.
> fix: Revert in TokenBridgeCctp if parent initialize is called

- solidity/contracts/isms/hook/OPL2ToL1CcipReadIsm.sol
- solidity/test/isms/OPL2ToL1CcipReadIsm.t.sol
> In PR #6471, the metadata of the OptimismPortal.WithdrawalTransaction was modified to include two Hyperlane message IDs (proveMessageId and finalizeMessageId). However, this patch allows an attacker to create a separate OP to L1 withdrawal transaction with the same pair of message IDs in the metadata, and execute OPL2ToL1CcipReadIsm.verify() using that forged metadata. In other words, it is possible to use the metadata of a different withdrawal transaction instead of the legitimate one. To address this issue, OPL2ToL1CcipReadIsm.verify() should verify that the _tx.sender() from IOptimismPortal.WithdrawalTransaction matches the sender() of the _message
Fixes this issue by enforcing message sender matches tx sender.
No, requires new deployments
Unit Tests
> fix: enforce withdrawal tx sender matches message sender

- solidity/contracts/libs/CctpMessage.sol
- solidity/contracts/token/TokenBridgeCctp.sol
- solidity/contracts/token/libs/TokenMessage.sol
- solidity/test/token/TokenBridgeCctp.t.sol
> In #6386 PR, the patch still allows a 1:N mapping between CCTP messages and Hyperlane messages. For example, verify() does not check whether the length of _hyperlaneMessage.body().metadata() is exactly 8 bytes. If it is longer than 8 bytes, it will automatically be truncated to bytes8, discarding the trailing bytes. This allows malformed metadata values to pass through verify() as if they were valid. Additionally, other parts of _hyperlaneMessage.body() such as amount, recipient, and even _hyperlaneMessage.sender() can be manipulated.
Fixes this issue by checking all fields match.
Requires new CCTP deploy
Unit Tests
> fix: enforce CCTP message matches hyperlane message

- typescript/sdk/src/token/configUtils.test.ts
Description:  
This pull request corrects a typo in the variable name from tranformedObj to transformedObj within the test cases in `typescript/sdk/src/token/configUtils.test.ts`. This change improves code readability and consistency, ensuring the variable name accurately reflects its purpose. No functional changes were made to the test logic.
> fix: typo in variable name in `configUtils.test.ts`

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/mainnet3/customBlacklist.ts
- Ink is enrolled as a remote router on the oUSDT routers, but doesn't have any limits. Sometimes people send messages directly to Ink programmatically, and this causes alert noise. We temporarily remove Ink from the app context to not get high urgency alerted on oUSDT prep queues to Ink
> chore: ignore ink in the oUSDT app context

- rust/main/config/testnet_config.json
- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/mainnet3/customBlacklist.ts
- Deploys #6494 
- Ignore a couple messages destined to a seemingly blocked recipient https://hyperlaneworkspace.slack.com/archives/C08GHFABJQ6/p1750251725429679?thread_ts=1750203987.690569&cid=C08GHFABJQ6
> chore: new relayer image with less logging, ignore some neutron dest msgs

- typescript/infra/config/environments/mainnet3/agent.ts
- typescript/infra/config/environments/mainnet3/customBlacklist.ts
- Now that we should be paying correct gas amounts to starknet chains, we enforce some stricter gas payment enforcement when sending to a starknet chain
- Ignores a message with a bad Neutron recipient (https://hyperlaneworkspace.slack.com/archives/C08HE2R697U/p1751291878494549?thread_ts=1750562486.790529&cid=C08HE2R697U) that seems unable to receive tokens
- Updates the image to include galactica
> chore: deploy relayer, stricter gas enforcement to starknet chains, ignore bad Neutron recipient msg

- typescript/infra/config/environments/mainnet3/agent.ts
chore: update agent images with latest main
updating all image tags, but only deploying new relayers+scraper
> chore: update agent images with latest main

- .changeset/tasty-spoons-live.md
- rust/main/config/mainnet_config.json
- typescript/widgets/src/walletIntegrations/starknet.ts
Some wallets connector like Braavos do not have switch chain logic implemented, which is why this would throw if called instead it will catch this and proceed to attempt to sign.
Also introduced a slight delay when switching network same as ethereum 
Yes
Manual testing
> chore: catch switchChainAsync for starknet

- typescript/infra/scripts/warp-routes/monitor/status.ts
- typescript/infra/src/rebalancer/helm.ts
- typescript/infra/src/utils/consts.ts
- typescript/infra/src/utils/helm.ts
- typescript/infra/src/warp/helm.ts
- add pre flight check to avoid warp monitor and rebalancer being deployed for the same route, as they both expose balance metrics
- small refactor with the helm manager to make it more reusable 
Manual
> chore: add pre flight check to avoid warp monitor and rebalancer being deployed for the same route

- typescript/cli/src/fork/fork.ts
This Pr updates `warp fork` to always use a block confirmation of 1 to fix anvil auto-mine issues
Yes
Manual
> chore: Update fork overrides to always use block.confirmation of 1

- typescript/infra/config/environments/mainnet3/agent.ts
Upgrade agent image to latest in Mainnet
Yes
None
> chore: Upgrade agent image to latest in Mainnet

- .github/workflows/test.yml
- typescript/cli/src/tests/ethereum/warp/warp-apply-1.e2e-test.ts
- typescript/cli/src/tests/ethereum/warp/warp-apply-2.e2e-test.ts
- typescript/cli/src/tests/ethereum/warp/warp-check-1.e2e-test.ts
- typescript/cli/src/tests/ethereum/warp/warp-check-2.e2e-test.ts
- typescript/cli/src/tests/ethereum/warp/warp-check-3.e2e-test.ts
chore: split cli e2e tests in ci
- warp-apply split into 2
- warp-check split into 3
- cli e2e matrix split into 2 matrices (cosm, eth) so we don't extraneously create cli e2e jobs on cosmos
> chore: split cli e2e tests in ci

- .changeset/little-boxes-wink.md
- typescript/cli/src/tests/ethereum/warp/warp-deploy.e2e-test.ts
- typescript/sdk/src/fee/EvmTokenFeeDeployer.hardhat-test.ts
- typescript/sdk/src/fee/EvmTokenFeeDeployer.ts
- typescript/sdk/src/fee/EvmTokenFeeModule.hardhat-test.ts
- typescript/sdk/src/fee/EvmTokenFeeModule.ts
- typescript/sdk/src/fee/EvmTokenFeeReader.hardhat-test.ts
- typescript/sdk/src/fee/EvmTokenFeeReader.ts
- typescript/sdk/src/fee/types.ts
- typescript/sdk/src/index.ts
- typescript/sdk/src/router/EvmRouterReader.ts
- typescript/sdk/src/router/HyperlaneRouterDeployer.ts
- typescript/sdk/src/router/types.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.hardhat-test.ts
- typescript/sdk/src/token/EvmERC20WarpRouteReader.ts
- typescript/sdk/src/token/deploy.ts
- typescript/sdk/src/token/types.ts
This PR adds the Fee deploy logic into token deployer. There are also changes the the Modules to support this deployment with some additional changes to the schema as mentioned in the **Drive-by changes**.
This PR also refactors the schema such that a linear fee can be configured using `bps`.
- Fixes ENG-2070
Yes, these additions should not impact existing warp deployments
Unit Tests
> feat(fees): Deploy and set Fees in Deployer

- typescript/sdk/src/token/adapters/EvmTokenAdapter.ts
- typescript/sdk/src/token/adapters/ITokenAdapter.ts
- typescript/sdk/src/warp/WarpCore.test.ts
- typescript/sdk/src/warp/WarpCore.ts
- Update `validateTokenBalances` to include token fee check
- Max transfer amount now takes into account fees
Restore getWrappedTokenAddress to public as it is used in widgets
Fixes [ENG-2121](https://linear.app/hyperlane-xyz/issue/ENG-2121/validations-should-take-into-account-fees)
No
UI test
> feat(sdk): validate transfer amount and max transfer amount

- .changeset/cool-rivers-tease.md
- typescript/infra/config/environments/mainnet3/warp/configGetters/getBscMilkywayMILKWarpConfig.ts
- typescript/infra/config/environments/mainnet3/warp/configGetters/getEthereumVictionETHWarpConfig.ts
This PR updates some more decimals for in config getters to avoid config-checker violations
Yes, as we are setting actual decimals
Run `check-config.ts`
> chore: set infra decimals in config getters to satisfy updated checker

- typescript/infra/config/environments/mainnet3/warp/configGetters/getMitosisMITOWarpConfig.ts
Update mitosis getter with new timelock owners
> chore(infra): update mitosis getter with new owners

- typescript/infra/config/environments/mainnet3/aw-validators/hyperlane.json
- typescript/infra/config/environments/mainnet3/validators.ts
chore: scale down legacy AW validators
https://linear.app/hyperlane-xyz/issue/ENG-2106/scale-down-to-1-aw-validator-on-all-chains
> chore: scale down to only 1 AW validator per chain
